### ISSUE TITLE
Error: unknown flag: --additional-whitelist

### ISSUE THREAD

**Issue by marekaf** [GoogleContainerTools/kaniko#1006]
**Actual behavior**
`--additional-whitelist` was added and removed short after that from the `gcr.io/kaniko-project/executor:debug-v0.16.0` image

**Expected behavior**
Succesful push

**To Reproduce**
```
 $ /kaniko/executor --verbosity=debug --cache=true --context . --dockerfile Dockerfile-kaniko --additional-whitelist=/var/run --destination SOME_DESTINATION
 Error: unknown flag: --additional-whitelist
```
**To maintainers**
thanks for all the great work on kaniko!
 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [x] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [x] </li></ul>|

**Comment by tejal29** [comment]
@marekaf, The `--additional-whitelist` flag was not supposed to be released in `:debug`.  We have now fixed our release pipeline to not update the `debug` tag on every push to master. 

Please remove it from your command. 
Sorry for the confusion. 

We are going to add this feature in next release `:debug-v0.17.0`.

**Comment by tejal29** [comment]
`--additional-whitelist=/var/run` is now going to be replaced with `--whitelist-var-run`
