### ISSUE TITLE
We need a logo!

### ISSUE THREAD

**Issue by priyawadhwa** [GoogleContainerTools/kaniko#101]

**Comment by priyawadhwa** [comment]
kaniko is a combo of the Greek words for "make" and "image", maybe something that helps get that idea across? any ideas are welcome!

**Comment by ggcarlosr** [comment]
I am on the order I will be developing a proposal I hope you like it

**Comment by ggcarlosr** [comment]
is left alone to close this issues brother.

**Comment by priyawadhwa** [comment]
perfect, thank you! I'll close the issue now.
