### ISSUE TITLE
better logging format

### ISSUE THREAD

**Issue by osela** [GoogleContainerTools/kaniko#1029]
#327 forces logrus to output colored logs, which are very hard to parse using the built-in tools of log collectors like fluentd.

In case you want to keep the existing behaviour, will you be open to accept a PR to allow setting the log formatter using a flag?

**Comment by tejal29** [comment]
@osela  we would not mind that at all. We could definitely add a flag like `--color` and set it true by default. You can set it to `false` to turn off color logging.
