### ISSUE TITLE
USER directive doesn't change home directory

### ISSUE THREAD

**Issue by anton-johansson** [GoogleContainerTools/kaniko#1082]
FYI: I found some related issues/PRs such as #403, however, I can reproduce this with the latest tag of kaniko, so it's maybe not related.

Here is my `Dockerfile`:
```
FROM node:10-slim
USER 1000
RUN whoami \
 && echo $HOME \
 && pwd \
 && ls -la ~ \
 && ls -la .
```

Running `docker build` behaves differently than `kaniko` does.

**Expected behavior**

I expect the following output:
```
node
/home/node
/
total 20
drwxr-xr-x 2 node node 4096 Oct 17 03:09 .
drwxr-xr-x 1 root root 4096 Oct 17 03:09 ..
-rw-r--r-- 1 node node  220 May 15  2017 .bash_logout
-rw-r--r-- 1 node node 3526 May 15  2017 .bashrc
-rw-r--r-- 1 node node  675 May 15  2017 .profile
total 88
drwxr-xr-x   1 root root 4096 Feb 27 14:06 .
drwxr-xr-x   1 root root 4096 Feb 27 14:06 ..
-rwxr-xr-x   1 root root    0 Feb 27 14:06 .dockerenv
drwxr-xr-x   2 root root 4096 Oct 14 00:00 bin
drwxr-xr-x   2 root root 4096 Sep  8 10:51 boot
drwxr-xr-x   5 root root  340 Feb 27 14:06 dev
drwxr-xr-x   1 root root 4096 Feb 27 14:06 etc
drwxr-xr-x   1 root root 4096 Oct 17 03:09 home
drwxr-xr-x   1 root root 4096 Oct 14 00:00 lib
drwxr-xr-x   2 root root 4096 Oct 14 00:00 lib64
drwxr-xr-x   2 root root 4096 Oct 14 00:00 media
drwxr-xr-x   2 root root 4096 Oct 14 00:00 mnt
drwxr-xr-x   1 root root 4096 Oct 17 03:15 opt
dr-xr-xr-x 380 root root    0 Feb 27 14:06 proc
drwx------   1 root root 4096 Oct 17 03:14 root
drwxr-xr-x   3 root root 4096 Oct 14 00:00 run
drwxr-xr-x   2 root root 4096 Oct 14 00:00 sbin
drwxr-xr-x   2 root root 4096 Oct 14 00:00 srv
dr-xr-xr-x  13 root root    0 Feb 19 13:27 sys
drwxrwxrwt   1 root root 4096 Oct 17 03:14 tmp
drwxr-xr-x   1 root root 4096 Oct 14 00:00 usr
drwxr-xr-x   1 root root 4096 Oct 14 00:00 var
```

As you can see, it lists the username `node` and itshome directory. It lists the contents of the home directory and the current directory (`/`).

**Actual behavior**

When building with Kaniko, I get the following output:
```
node
/root
/
ls: cannot open directory '/root': Permission denied
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 2
```

As you can see here, the username `node` is still correct. However, the home directory is not. It's still using the `root` users home directory. Hence, we get a permission error when tried to `ls` in the home directory.

**To Reproduce**

1. Copy to above `Dockerfile` into a directory, say `/home/user/kaniko-test`
2. `$ docker run --rm --mount source=/home/user/kaniko-test,target=/usr/src/app,type=bind gcr.io/kaniko-project/executor:debug-fb0cfd74649f88a942c0a77c85136b791a9c09d1 --context /usr/src/app --no-push --tarPath /dev/null`

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by cvgw** [comment]
I'm not able to repro this bug using tag `a1af057f997316bfb1c4d2d82719d78481a02a79`

Dockerfile
```
FROM node:10-slim
USER 1000
```

Docker command
```
docker run \
  -v $LOCAL_CONTEXT:/workspace
  gcr.io/kaniko-project/executor:a1af057f997316bfb1c4d2d82719d78481a02a79 \
  --context dir:///workspace/ \
  --dockerfile Dockerfile \
  --destination $DESTINATION \
  -v info
```

Test
```
$ docker run --rm $DESTINATION /bin/sh -c 'echo $HOME'
=> /home/node
```

**Comment by cvgw** [comment]
So the issue here is not with the final image, but during the build

during the build $HOME is not updated, but in the final image it is correct.

**Comment by cvgw** [comment]
We need to add an integration test which writes a file to user's HOME directory E.G.

```
FROM alpine
RUN adduser -S -D myuser

USER myuser

RUN echo 'meow' > $HOME/test.txt
```

**Comment by tejal29** [comment]
Integration test ->  https://github.com/GoogleContainerTools/kaniko/pull/1072/files

**Comment by cvgw** [comment]
> Integration test -> https://github.com/GoogleContainerTools/kaniko/pull/1072/files

I'd prefer not to add integration tests which use bash in the docker file to assert the test

**Comment by tejal29** [comment]
@greut already started looking into this. I will work with him to get this fixed.

Thanks @cvgw and @anton-johansson.

**Comment by anton-johansson** [comment]
Thanks yourselves for a great product!
