### ISSUE TITLE
Proposal: Split integration test into multiple travis jobs

### ISSUE THREAD

**Issue by cvgw** [GoogleContainerTools/kaniko#1089]
The integration tests are getting longer
There is a max job time of 50m on travis free tier
We should split some of the integration tests into their own travis jobs
Primarily
TestRun and TestLayers
The other tests can run in the same Travis job

My proposal is to have a job which explicitly passes `-run TestRun` and another which passes `-run TestLayers` and a third which uses `go test ./integration/.. -list=Test` to list all the integration tests and filter out `TestRun` and `TestLayers` from that list using `grep`, then pass that as the regex query to `go test`

IE

`go test ./integration/... -run "TestGitBuildcontext|TestCache|TestRelativePaths"`

cc @samos123 @tejal29

**Comment by samos123** [comment]
+1 I like the way you handled the issue of running all tests except `TestRun` and `TestLayers` by having a script `misc-integration-test.sh` that runs all tests except those 2 programmatically.

**Comment by cvgw** [comment]
> +1 I like the way you handled the issue of running all tests except `TestRun` and `TestLayers` by having a script `misc-integration-test.sh` that runs all tests except those 2 programmatically.

Thanks! I was somewhat surprised that there is no negative match argument for `go test`, but the `-list` option will work. We can also clean up that script at some point to have a list of tests to exclude which should make it easier to maintain.
