### ISSUE TITLE
Pushing same image version into Artifactory gets INVALID_MANIFEST error

### ISSUE THREAD

**Issue by myaesubi** [GoogleContainerTools/kaniko#1095]
Hi,
when using the executor and pushing same image version again into JFrog Artifactory I get error.
this doesn't happen when using docker though.

**Actual behavior**
error pushing image: failed to push to destination artifactory:5001/action_server:1.1.0: MANIFEST_INVALID: manifest invalid; map[description:HTTP 403 Forbidden]

**The error looks like Authorization, but it is not. changing the image version to a new version will go successful.**

**Expected behavior**
the push to the artifactory to be successful. Artifactory allows overriding the same image version, since we're doing the same with docker. 

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [X] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by tejal29** [comment]
@myaesubi we use google/go-containerregistry to push an image to registry and looks like the error is coming from there. 

Given the priorities right now, the team does not have the bandwidth to set up a way to reproduce this issue. If you could help us by providing the steps to set a Jfrog artifactory i will be happy to take a look.

**Comment by myaesubi** [comment]
@tejal29 thanks for getting back to me. I've put here two approaches to install the JFrog:

https://www.jfrog.com/confluence/display/JFROG/Installing+Artifactory

or
https://jfrog.com/screencast/artifactory-5-one-minute-setup-docker-registry-as-container-install/

Thanks,
Mohammad

**Comment by tanguydelignieresaccenture** [comment]
@myaesubi, just to confirm, in your context your registry is setup to allow overwrite on artifactory side (because it works with docker), right?
![repository_rights](https://user-images.githubusercontent.com/11891135/112468589-bc49cb00-8d68-11eb-9734-7a3a930c227f.png)

**Comment by myaesubi** [comment]
@tanguydelignieresaccenture . sorry I forgot to update this item. we were able to push/override to JFrog with proper setting up of permission.
We can close this ticket.

Thanks,
Mohammad
