### ISSUE TITLE
multi-arch manifest lists

### ISSUE THREAD

**Issue by paleozogt** [GoogleContainerTools/kaniko#1102]
**Actual behavior**

I'm building multi-arch containers with kaniko.  I'd like to be able to stitch them together with a manifest list and push to a registry.  Sadly, I have to switch back to Docker in order to do this last step.  Since the whole point of kaniko is to avoid using Docker it seems like it should support manifest lists.

**Expected behavior**

Be able to make manifest lists with kaniko directly.

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [x ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [x ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by tejal29** [comment]
Hi @paleozogt Thank you for opening an issue and identifying an essential gap!

I have added this to our next milestone

**Comment by khassel** [comment]
as long as this is not implemented you can add https://github.com/estesp/manifest-tool to the kaniko-image.

**Comment by azamora-zsc** [comment]
Any news about this feature? I see this thread is almost one year old and I wonder if there is any plan to implement the manifest list creation feature.

**Comment by TBBle** [comment]
To me, this seems somehow out-of-scope for Kaniko, and would be better suited to an dedicated registry-manipulation tool like `manifest-tool` or `skopeo`.

**Comment by imjasonh** [comment]
> To me, this seems somehow out-of-scope for Kaniko, and would be better suited to an dedicated registry-manipulation tool like `manifest-tool` or `skopeo`.

I agree. If you're building multiple single-platform images with Kaniko today, there are plenty of tools to help you stitch them together into a single multi-platform image. `docker manifest` doesn't seem to require a daemon to append and push a manifest list.

If people want this functionality in `kaniko` itself, it might help to discuss what you'd want it to look like. Currently, `executor` only builds and pushes, should there be a separate image for that? At that point, why not use `skopeo`, `manifest-tool`, `docker manifest`? Or should it be a separate command of `executor`?

Maybe this is just a documentation issue, and we can develop/test/document a workflow for using Kaniko + some other tool to produce multi-platform images. wdyt?

**Comment by gsquared94** [comment]
>  we can develop/test/document a workflow for using Kaniko + some other tool to produce multi-platform images. wdyt?

This can work: https://github.com/GoogleContainerTools/kaniko/issues/786#issuecomment-1248838685
