### ISSUE TITLE
Bad handling of trailing slash in WORKDIR

### ISSUE THREAD

**Issue by gilbsgilbs** [GoogleContainerTools/kaniko#1109]
**Actual behavior**

The following Dockerfile:

```Dockerfile
FROM alpine
WORKDIR /home/example/
```

fails to build since v0.18.0 with the following error message:

```
error building image: error building stage: failed to take snapshot: unable to add file /home/example/example to layered map: error creating hash for /home/example/example: lstat /home/example/example: no such file or directory
```

**Expected behavior**

Kaniko should be able to build this Dockerfile.

**To Reproduce**

```bash
echo "FROM alpine\nWORKDIR /home/example/" > Dockerfile
docker run --rm -it -v $(pwd)/Dockerfile:/Dockerfile:ro gcr.io/kaniko-project/executor:debug --dockerfile /Dockerfile --no-push
```

**Additional Information**

- the regression was introduced in `v0.18.0`. `debug-v0.17.1` image does not present the issue.
- if the trailing slash is removed from the workdir, it builds normally:
  ```bash
  echo "FROM alpine\nWORKDIR /home/example" > Dockerfile
  docker run --rm -it -v $(pwd)/Dockerfile:/Dockerfile:ro gcr.io/kaniko-project/executor:debug --dockerfile /Dockerfile --no-push
  ```
- build succeeds in both cases when using `docker build` command. 

 **Triage Notes for the Maintainers**

 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [x] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by gilbsgilbs** [comment]
Note that the regression is easy to reproduce with `WORKDIR`, but I also have similar errors in more complex images with `COPY` (`lstat /xxx: no such file or directory`). It may very well be related.

**Comment by mapopa** [comment]
confirmed , also with ```
FROM node:lts-slim
WORKDIR /var/www/
```

**Comment by gilbsgilbs** [comment]
Closing in favor of #1112 .

**Comment by tejal29** [comment]
Thanks!
