### ISSUE TITLE
Windows Containers Support

### ISSUE THREAD

**Issue by fkorotkov** [GoogleContainerTools/kaniko#111]
With the upcoming GA of Windows in Kubernetes I'm wondering if `kaniko` does/will support building Windows Containers?

I think it's worth a mention in documentation.

**Comment by fkorotkov** [comment]
@priyawadhwa is there a doc outlining challenges for supporting Windows containers? I would like to investigate it.

**Comment by dlorenc** [comment]
I don't think we have a doc on adding Windows support anywhere. It's not something we have a particular use-case for, so we haven't spent much if any time on it. If you do some investigations and write up a proposal, we'd be happy to look it over.
