### ISSUE TITLE
Multistage Dockerfile combined ARG is not expanded

### ISSUE THREAD

**Issue by MAHDTech** [GoogleContainerTools/kaniko#1117]
**Actual behavior**

If you combine multiple ARG at the top of the Dockerfile they are not expanded

**Expected behavior**

The ARG values provided are expanded, and can be passed to later stages. This is the behavior in Docker.

**To Reproduce**

Use the below Dockerfile as an example

**Additional Information**

```
ARG ALPINE_VERSION="3.6"
ARG ARG1="HELLO"
ARG ARG2="WORLD"
ARG COMBINED="${ARG1} ${ARG2}"

FROM alpine:${ALPINE_VERSION} AS builder

ARG COMBINED

RUN echo "$COMBINED"

COPY test.sh /tmp/test.sh

RUN chmod +x /tmp/test.sh \
 && ./tmp/test.sh

ENTRYPOINT [ "/bin/sh" ]
```

Here is Kaniko output

```
INFO[0000] Resolved base name alpine:${ALPINE_VERSION} to alpine: 
INFO[0000] Resolved base name alpine:${ALPINE_VERSION} to alpine: 
INFO[0000] Retrieving image manifest alpine:3.6         
INFO[0004] Retrieving image manifest alpine:3.6         
INFO[0006] Built cross stage deps: map[]                
INFO[0006] Retrieving image manifest alpine:3.6         
INFO[0008] Retrieving image manifest alpine:3.6         
INFO[0010] Unpacking rootfs as cmd RUN echo "$COMBINED" requires it. 
INFO[0011] Taking snapshot of full filesystem...        
INFO[0011] Resolving paths                              
INFO[0011] ARG COMBINED                                 
INFO[0011] RUN echo "Arg = $COMBINED"                   
INFO[0011] cmd: /bin/sh                                 
INFO[0011] args: [-c echo "$COMBINED"]            
${ARG1} ${ARG2}
INFO[0011] Taking snapshot of full filesystem...        
INFO[0011] Resolving paths                              
INFO[0011] No files were changed, appending empty layer to config. No layer added to image. 
INFO[0011] COPY test.sh /tmp/test.sh                    
INFO[0011] Resolving paths                              
INFO[0011] Taking snapshot of files...                  
INFO[0011] RUN chmod +x /tmp/test.sh  && ./tmp/test.sh  
INFO[0011] cmd: /bin/sh                                 
INFO[0011] args: [-c chmod +x /tmp/test.sh  && ./tmp/test.sh] 
${ARG1} ${ARG2}
INFO[0011] Taking snapshot of full filesystem...        
INFO[0011] Resolving paths                              
INFO[0011] No files were changed, appending empty layer to config. No layer added to image. 
INFO[0011] ENTRYPOINT [ "/bin/sh" ] 
```

Here is example Docker output

```
docker image build --tag test:latest .

Sending build context to Docker daemon  3.072kB
Step 1/10 : ARG ALPINE_VERSION="3.6"
Step 2/10 : ARG ARG1="HELLO"
Step 3/10 : ARG ARG2="WORLD"
Step 4/10 : ARG COMBINED="${ARG1} ${ARG2}"
Step 5/10 : FROM alpine:${ALPINE_VERSION} AS builder
 ---> 43773d1dba76
Step 6/10 : ARG COMBINED
 ---> Running in 297804dc64c1
Removing intermediate container 297804dc64c1
 ---> c8a3dd39a0e6
Step 7/10 : RUN echo "$COMBINED"
 ---> Running in 259afbb5aadf
HELLO WORLD
Removing intermediate container 259afbb5aadf
 ---> b84c256a6de3
Step 8/10 : COPY test.sh /tmp/test.sh
 ---> b9c406402c2b
Step 9/10 : RUN chmod +x /tmp/test.sh  && ./tmp/test.sh
 ---> Running in 79d090345d3e
HELLO WORLD
Removing intermediate container 79d090345d3e
 ---> d968fbee09c3
Step 10/10 : ENTRYPOINT [ "/bin/sh" ]
 ---> Running in 4b51729d5e7f
Removing intermediate container 4b51729d5e7f
 ---> 8dd90feb609a
Successfully built 223ac995255d
Successfully tagged test:latest
```

The test.sh

```
#!/bin/sh

echo "$COMBINED"
exit 0
```

I have tested with the following versions with the same result:
- v0.18.0
- v0.17.1
- edge (sha256:d229ff9b49c9c9ea4edab835f3773af09c015152d8ddfeb0ac356787e70df09c)

 
 **Triage Notes for the Maintainers**
 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [X] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [X] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [X] </li></ul>|

**Comment by tejal29** [comment]
Thanks @MAHDTech. 

Looks like there is bug [here](https://github.com/GoogleContainerTools/kaniko/blob/master/pkg/commands/arg.go#L50). Since this function has very little tests, we could add some tests scenarios to test if a previous `arg` value is expanded or not. 

Thanks 
Tejal

**Comment by ljakimczuk** [comment]
Hi @tejal29 

Do you resolve the ARGs against the `config.Env` slice? It seems the slice does not contain any ARGs like ARG1 / ARG2, so the value is `nil` and so it is tried to be expanded against the `ba.GetAllMeta()` map, but the map contains still unexpanded nested/combined ARGs, like `map[ARG1:"Hello" ARG2:"World" COMBINED="$ARG1 $ARG2"]`. I quickly added an additional step of resolving them against the map itself and it gave positive result, but then I don't know if this is the correct approach, I guess it would be better to already provide them in expanded form? Thanks!

https://github.com/GoogleContainerTools/kaniko/compare/master...ljakimczuk:master

**Comment by ljakimczuk** [comment]
I also tested other approach of moving this to the [Parse](https://github.com/GoogleContainerTools/kaniko/blob/9cfb196d028d85bc7a132950eeadb18d8046610f/pkg/dockerfile/dockerfile.go#L108) func (it seems to better fits in there) and trying to expand next ARG's value against all previously defined ARGs:

`
@@ -120,9 +120,34 @@ func Parse(b []byte) ([]instructions.Stage, []instructions.ArgCommand, error) {
                return nil, nil, err
        }
 
+       metaArgs, err = expandNested(metaArgs)
+       if err != nil {
+               return nil, nil, err
+       }
+
        return stages, metaArgs, nil
 }
 
+// expandNestedArgs tries to resolve nested ARG value against the previously defined ARGs
+func expandNested(metaArgs []instructions.ArgCommand) ([]instructions.ArgCommand, error) {
+       prevArgs := make([]string,0)
+       for i := range metaArgs {
+               arg := metaArgs[i]
+               v := arg.Value
+               if v != nil {
+                       val, err := util.ResolveEnvironmentReplacement(*v, prevArgs, false)
+                       if err != nil {
+                               return nil, err
+                       }
+
+                       prevArgs = append(prevArgs, arg.Key + "=" + val)
+                       arg.Value = &val
+                       metaArgs[i] = arg
+               }
+       }
+       return metaArgs, nil
+}
+
`

**Comment by ljakimczuk** [comment]
I eventually added a function that tries to expand all meta ARGs against themselves and build ARGs in [Stages](https://github.com/ljakimczuk/kaniko/blob/3bb6c6bb24a293cc91f50969ebbd4929518f020e/pkg/dockerfile/dockerfile.go#L61). Also extended one test case for checking the correct expansion of meta-args, please check the diff from my previous comment. I can open a PR if it fits you. It seems that currently the `ReplacementEnvs` returns all allowed build ARGs, but I guess these are populated only on stages only ([here](https://github.com/GoogleContainerTools/kaniko/blob/9cfb196d028d85bc7a132950eeadb18d8046610f/pkg/commands/arg.go#L38), not on meta-args "stage" and thus remains empty.

**Comment by tejal29** [comment]
@ljakimczuk would love to see the Pr for this. Sorry for the delay in responding.

**Comment by ljakimczuk** [comment]
@tejal29 no worries! I opened the PR [here](https://github.com/GoogleContainerTools/kaniko/pull/1260), I see the code changed a bit since i forked, but i hope the solution still fits you.
