### ISSUE TITLE
--cache-dir support Google bucket (gs://)

### ISSUE THREAD

**Issue by Sherman-Chata** [GoogleContainerTools/kaniko#1123]
**Actual behavior**

**Expected behavior**

**To Reproduce**
1. ...
2. ...

**Additional Information**
 - Dockerfile 
   Please provide either the Dockerfile you're trying to build or one that can reproduce this error.
 - Build Context
   Please provide or clearly describe any files needed to build the Dockerfile (ADD/COPY commands)
 - Kaniko Image (fully qualified with digest)
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by tejal29** [comment]
@Sherman-Chata Thank you for opening this issue. 
Are you saying we dont support remote GCS cache?

**Comment by Sherman-Chata** [comment]
Yes. Hope the cache base image can support Google bucket, cause we use Kaniko with Google cloud build.

**Comment by tejal29** [comment]
@Sherman-Chata You can absolutely use Kaniko with GCB!
Please see here https://cloud.google.com/cloud-build/docs/speeding-up-builds
