### ISSUE TITLE
can't determine image digest after build

### ISSUE THREAD

**Issue by dlfoo** [GoogleContainerTools/kaniko#1133]
**Actual behavior**

I'm running kaniko executor inside a tekton task run and everything works well however It will never return the image digest in the terminate message. I know that the image is being pushed to the local repository. I don't know where else to get it since its not in the logs. The documentation wasn't clear to me.

**Expected behavior**
I expect to see the sha256 hash in the terminate message, instead of an empty value "".

**To Reproduce**
1. Run executor inside a tekton pipeline and use a local docker registry
2. kubectl describe [taskrunpod] should show the executor container that ran along with the terminate messages.

**Additional Information**
```
step-build-and-push:
    Container ID:  docker://3f90947e0132a95de9810d171eb0ddd5bcc60ee433787428bd03737fa5915042
    Image:         gcr.io/kaniko-project/executor:v0.17.1
    Image ID:      docker-pullable://gcr.io/kaniko-project/executor@sha256:565d31516f9bb91763dcf8e23ee161144fd4e27624b257674136c71559ce4493
    Port:          <none>
    Host Port:     <none>
    Command:
      /tekton/tools/entrypoint
    Args:
      -wait_file
      /tekton/tools/1
      -post_file
      /tekton/tools/2
      -termination_path
      /tekton/termination
      -entrypoint
      /kaniko/executor
      --
      --dockerfile=Dockerfile
      --destination=docker.redacted.net/redacted
      --context=/workspace/docker-source
      --cache
      --cache-dir=/cache
    State:          Terminated
      Reason:       Completed
      Message:      [{"name":"","digest":"","key":"StartedAt","value":"2020-03-13T12:30:08Z","resourceRef":{}}]
      Exit Code:    0
      Started:      Fri, 13 Mar 2020 21:30:00 +0900
      Finished:     Fri, 13 Mar 2020 21:37:24 +0900
    Ready:          False
    Restart Count:  0
```
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by dlfoo** [comment]
Dockerfile

```
FROM golang:1.13 as builder
ENV GO111MODULE=on
WORKDIR /code
ADD go.mod go.sum /code/
RUN go mod download
ADD . .
RUN go build -o /redacted main.go
RUN go test redacted/redacted_test.go
FROM gcr.io/distroless/base
WORKDIR /
COPY --from=builder /redacted /usr/bin/redacted
ENTRYPOINT ["/usr/bin/redacted"]
```

**Comment by dlfoo** [comment]
Tekton Task. Also this was happening before I used the --cache flags

`
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.17.1
      volumeMounts:
        - name: kaniko-cache
          mountPath: /cache
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=$(outputs.resources.builtImage.url)
        - --context=$(inputs.params.pathToContext)
        - --cache
        - --cache-dir=/cache
  volumes:
    - name: kaniko-cache
      persistentVolumeClaim:
            claimName: kaniko-cache-claim
`

**Comment by tejal29** [comment]
@dlfoo Kaniko does not return the digest pushed in output or logs. 
If the flag `--destination` did not have a fully qualified image, you will have to pull the image digest from the registry.

It would be simple to add that to kaniko also here just after a push was done
https://github.com/GoogleContainerTools/kaniko/blob/0522fe2485c25f55d9d96a028058da0b180e0bec/cmd/executor/cmd/root.go#L111

**Comment by dlfoo** [comment]
re reading the docs again, setting digest-file argument should achieve what I want right ?

https://github.com/GoogleContainerTools/kaniko/blob/master/README.md#--digest-file

> Set this flag to specify a file in the container. This file will receive the digest of a built image. This can be used to automatically track the exact image built by Kaniko.
For example, setting the flag to --digest-file=/dev/termination-log will write the digest to that file, which is picked up by Kubernetes automatically as the {{.state.terminated.message}} of the container.
