### ISSUE TITLE
Dangling symlinks cause kaniko to generate layers that cannot be loaded by docker

### ISSUE THREAD

**Issue by tomprince** [GoogleContainerTools/kaniko#1151]
**Actual behavior**
Building an image with a dangling symlink causes kaniko to build an image that `docker load` fails to load. 

It fails with the error
```
ApplyLayer exit status 1 stdout:  stderr: unlinkat .//: device or resource busy
```
Inspecting the layer with `tar tzvP`:
```
drwxr-xr-x 0/0               0 2020-03-20 18:36 .
hrwxr-xr-x 0/0               0 2020-03-20 18:36 / link to .
lrwxrwxrwx 0/0               0 2020-03-20 18:36 link -> nowhere
```

**Expected behavior**
kaniko should generate an image loadable by docker

**Additional Information**
 - Dockerfile 
```
FROM busybox:latest@sha256:b26cd013274a657b86e706210ddd5cc1f82f50155791199d29b9e86e935ce135
RUN ["/bin/ln", "-s", "nowhere", "/link"]
```

 - Kaniko Image: gcr.io/kaniko-project/executor:v0.19.0@sha256:66be3f60f22b571faa82e0aaeb94731217ba0c58ac4a3b062bc84c6d8d545213

Diagnosis:
- If the target of symlink being resolved doesn't exist, gcr.io/kaniko-project/executor:v0.19.0@sha256:66be3f60f22b571faa82e0aaeb94731217ba0c58ac4a3b062bc84c6d8d545213 adds the empty target to the list of files resolve
- https://github.com/GoogleContainerTools/kaniko/blob/v0.19.0/pkg/filesystem/resolve.go#L102 causes the empty file name to be turned into `.`
- Since `/` and `.` are both files being added to the layer tar, https://github.com/GoogleContainerTools/kaniko/blob/v0.19.0/pkg/util/tar_util.go#L92 adds `/` as a hardlink to `.`, which creates a layer that cannot be loaded by docker.
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [X] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by vguaglione** [comment]
We have also experienced this problem.  It may have been introduced somewhere between 0.17.1 and 0.19.0.  We have tested our containers with v0.17.1 and are not seeing this problem.  We have not tested any other intermediate versions of the container.  

Note - same problem whether caching is turned on or off.

When might this fix be available?
