### ISSUE TITLE
error despite official signed certificate

### ISSUE THREAD

**Issue by SIGSEGV911** [GoogleContainerTools/kaniko#1154]
**Actual behavior**
On Kaniko debug build, Kaniko states this error despite skip-tls parameter. Without the parameter the build in my GitLab Pipeline ends much earlier.

```
$ /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination ${CI_REGISTRY_IMAGE} --skip-tls-verify

written to stdout
INFO
[0000] Resolved base name registry:5005/special/alpine:3.9-special to registry:5005/special/alpine:3.9-special
INFO
[0000] Using dockerignore file: /builds/pisa/ecosystem/.dockerignore
INFO
[0000] Resolved base name registry:5005/special/alpine:3.9-special to registry:5005/special/alpine:3.9-special
INFO
[0000] Retrieving image manifest registry:5005/special/alpine:3.9-special
ERRO
[0000] Error while retrieving image from cache: registry:5005/special/alpine:3.9-special Get "https://registry:5005/v2/": x509: certificate signed by unknown authority
INFO
[0000] Retrieving image manifest registry:5005/special/alpine:3.9-special
error building image: Get "https://registry:5005/v2/": x509: certificate signed by unknown authority
```

But my private registry has a well signed certifcate, signed by DigiCert/Thawte. 

**Expected behavior**
Kaniko should push and pull from my registry.

**To Reproduce**
Restarting this jobs....

**Additional Information**
 - Dockerfile 
```
FROM registry:5005/special/alpine:3.11-special 
...
 ````
 - Build Context
   IMHO not relevant
 - Kaniko Image (fully qualified with digest)
   Id: sha256:2ec307dcf7f52dcf700ea0fbc65d448f46365cfac69567e8177bf12b80942f54
   gcr.io/kaniko-project/executor:debug
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by tejal29** [comment]
@schumac2 Thank you reporting this issue. `--skip-tls-verify` is used only when pushing images. 
To skip tls verification for pulling images, please use `--skip-tls-verify-pull`. Can you please try?

**Comment by schumac2** [comment]
Tried this already:
```
$ /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination ${CI_REGISTRY_IMAGE} --skip-tls-verify-pull

written to stdout
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "registry:5005/pisa/ecosystem": creating push check transport for registry:5005 failed: Get "https://registry:5005/v2/": x509: certificate signed by unknown authority
```

**Comment by schumac2** [comment]
Any help on this?

**Comment by SIGSEGV911** [comment]
Still I'm struggling with the SSL behaviour of the kaniko image.
Even against a certificate officially signed by sectigo.

**Comment by SIGSEGV911** [comment]
bump  - my fault, it's working now

**Comment by doctorcolossus** [comment]
@SIGSEGV911, do you remember what the issue was?

**Comment by gtbanfield** [comment]
how was this fixed?

**Comment by Seanland** [comment]
This is an older issue, but, it seems to stop google when searching for the "x509 certificate issue".  So, hopefully, I can help share what solved it for me.

The additional parameter I needed to resolve my issue was `--skip-tls-verify-registry=<registry name>`.  I was using the flag without a value.  It still seemed to execute successfully (as in didn't break the command), however, never resolved the issue.  Be sure to define the registry with that parameter.  Good luck!

**Comment by Setomidor** [comment]
Also looking for a solution on this that does not involve ignoring the cert.

**Comment by srihari11235** [comment]
> bump - my fault, it's working now

@SIGSEGV911 
What was the issue? Im facing this same error.

**Comment by Setomidor** [comment]
@srihari11235 I solved it by looking at the $CI_SERVER_TLS_CA_FILE variable provided by Gitlab for the runner context:

/kaniko/executor --registry-certificate <your.registry.address>=$CI_SERVER_TLS_CA_FILE
