### ISSUE TITLE
Changelog release v0.19.0 content error

### ISSUE THREAD

**Issue by marcaurele** [GoogleContainerTools/kaniko#1159]
**Actual behavior**
The release content for the version 0.19 contains command to pull the version 0.18.

> Thank you all for your patience and supporting us throughout!
>
>    gcr.io/kaniko-project/executor:v0.18.0 and
>    gcr.io/kaniko-project/executor:latest
>
> The debug image is available at:
>
>    gcr.io/kaniko-project/executor:debug-v0.18.0 and
>    gcr.io/kaniko-project/executor:debug

**Expected behavior**

    gcr.io/kaniko-project/executor:v0.19.0 and
    gcr.io/kaniko-project/executor:latest
    
    gcr.io/kaniko-project/executor:debug-v0.19.0 and
    gcr.io/kaniko-project/executor:debug

 **Triage Notes for the Maintainers**
 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by tejal29** [comment]
Thanks @marcaurele !
Fixed!
