### ISSUE TITLE
Override remote cache location/name to avoid invalid image name errors and share cache

### ISSUE THREAD

**Issue by flyte** [GoogleContainerTools/kaniko#1169]
**Actual behavior**
My image registry (GitLab) supports having a slash in the image name but I already use it as part of my image organisation:

```
registry.gitlab.com/team-name/project/feature/foo
                                      ___________
```

Kaniko tries to add another slash:
```
registry.gitlab.com/team-name/project/feature/foo/cache
                                                 ______
```
which makes the push to the registry fail because adding a second slash is unsupported.

**Expected behavior**
Since the images I'm building are essentially the same, but on different branches with minor differences, they should share a cache anyway. I'd like to set the remote cache image name to the following instead, to fix both of these issues:

```
registry.gitlab.com/team-name/project/cache
```

**To Reproduce**
1. Create a GitLab project with container image registry enabled
2. Try to upload an image to the container registry using kaniko that uses the extra 'allowed' slash already.

**Additional Information**
 - Dockerfile n/a
 - Build Context n/a
 - Kaniko Image n/a
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [:heavy_check_mark:] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [:x:] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [:heavy_check_mark:] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [:x:] </li></ul>|

**Comment by flyte** [comment]
I don't know how I missed it, but this is exactly what the `--cache-repo` option does. I swear I read it multiple times without realising :laughing: :man_facepalming: 

For future reference I've set the following command on GitLab CI:

```
--cache-repo $CI_REGISTRY_IMAGE/cache
```

**Comment by tejal29** [comment]
@flyte  have you looked at the flag [`--cache-repo`](https://github.com/GoogleContainerTools/kaniko#--cache-repo)

**Comment by tejal29** [comment]
Great! Thanks!
