### ISSUE TITLE
Report permission issues when kaniko build without FOWNER and DAC_OVERRIDE permission,

### ISSUE THREAD

**Issue by zhangtbj** [GoogleContainerTools/kaniko#1171]
Hi all,

Now I am trying to use kaniko to build container images on a shared kube cluster which enables several security policies.

**1, I found if I don't have the allow capability `DAC_OVERRIDE` in the PSP, the kaniko reports:**
```
...
INFO[0294] cmd: /bin/sh
INFO[0294] args: [-c GIT_COMMIT=$(git rev-list -1 HEAD) && go build -o booktaxi -ldflags "-X main.CommitSHA=$GIT_COMMIT" ./src/cmd/booktaxi]
INFO[0313] Taking snapshot of full filesystem...
INFO[0314] Resolving paths
INFO[0358] Saving file /go/build/booktaxi for later use
error building image: mkdir /kaniko/0/go: permission denied
```

**1, I found if I don't have the allow capability `FOWNER` in the PSP, the kaniko reports:**
```
...
INFO[0008] Retrieving image manifest golang:latest
INFO[0008] Retrieving image manifest golang:latest
INFO[0009] Unpacking rootfs as cmd COPY . /go/build requires it.
error building image: error building stage: failed to get filesystem from image: chmod /var/cache/apt/archives/partial: operation not permitted
```

Can I workaround these two problems without the `DAC_OVERRIDE` and `FOWNER` permission?

Thanks!

**Comment by tejal29** [comment]
@zhangtbj Kaniko does require following capabilities reported in this issue.
https://github.com/GoogleContainerTools/kaniko/issues/778

As per Kaniko's design, we do require root permission to unpack a FS
https://github.com/GoogleContainerTools/kaniko#security

**Comment by tejal29** [comment]
Please let me know if that helps?

**Comment by zhangtbj** [comment]
Hi @tejal29 ,

Yes, we also verified that we need those 5 permissions.

We added in our pod security context.

It is help. Thanks!
