### ISSUE TITLE
Add option to strip timestamps for reproducible image configs

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/kaniko#120]
Expose a (date or bool) flag to allow users to choose to strip timestamps or set a particular one. We should also make sure the rest of the metadata is deterministic. 

https://github.com/moby/moby/pull/30611

**Comment by r2d4** [comment]
cc @sharifelgamal who has much experience in this area

**Comment by sharifelgamal** [comment]
Yeah we have a tool that does exactly this that just needs to ported to Go.

**Comment by sharifelgamal** [comment]
This is waiting for https://github.com/google/go-containerregistry/pull/206
