### ISSUE TITLE
How to simply mirror an image using Kaniko

### ISSUE THREAD

**Issue by Ark-kun** [GoogleContainerTools/kaniko#1208]
Google's Cloud ML Training only allows container images from gcr.io.
I'm seeking a minimal footprint solution for copying a public DockerHub image to gcr.io
Google Cloud Build seems to have [support ](https://cloud.google.com/blog/products/application-development/build-containers-faster-with-cloud-build-with-kaniko)for Kaniko and its build cache, so Kaniko might be a good option.

Ideally I want to do something like this:
```
steps:
- name: gcr.io/kaniko-project/executor
  args:
  - --source=foo/bar
  - --destination=gcr.io/$PROJECT_ID/foo/bar
  - --cache=true
  - --cache-ttl=6h
```
Do I need to upload a dummy Dockerfile with a single `FROM foo/bar` line somewhere or is there an easier solution?
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by tomprince** [comment]
I would probably suggest using a tool other than kaniko for this (such as https://github.com/containers/skopeo perhaps). `skopeo` is designed explicitly for interacting with multiple docker registries, without requiring a local docker daemon.

**Comment by tejal29** [comment]
You can use kaniko to built your entire image in your cluster if you like!
