### ISSUE TITLE
Kaniko doesn't support logs in json format

### ISSUE THREAD

**Issue by mhprowler** [GoogleContainerTools/kaniko#1215]
**Actual behavior**
Kaniko uses logrus but there is no way to specify that the JSONFormatter should be used.

**Expected behavior**
A command line option to turn on json logging.

I can implement it but wanted to check if this is desired behaviour. 

**Additional Information**
 - Kaniko Image (fully qualified with digest) : all versions
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by MichelHollands** [comment]
My mistake, there is a flag to set the log output. It just isn't mentioned in the readme.
