### ISSUE TITLE
Authentication error when pushing to GCR when using kaniko 

### ISSUE THREAD

**Issue by RadoBart** [GoogleContainerTools/kaniko#1237]
**Actual behavior**
Cloud build started failing while pushing into GCR due to an authorization error, reverting to v0.20.0 fixed it.

**Expected behavior**
I expect the latest build of kaniko to successfully build and push a docker image.

**To Reproduce**
1. Use the latest kaniko release in one of the cloud build steps

**Additional Information**
Error log output: 
```
Step #1 - "build": error checking push permissions --
 make sure you entered the correct tag name,
and that you are authenticated correctly, and try again: 
checking push permission for "gcr.io/headless-backoffice-dev/backend:ade32d5b42e8cb4fc6bb8995705a924677f86353": 
creating push check transport for gcr.io failed: 
GET https://gcr.io/v2/token?scope=repository%3Aheadless-backoffice-dev%2Fbackend%3Apush%2Cpull&service=gcr.io: UNAUTHORIZED: 
You don't have the needed permissions to perform this operation, 
and you may have invalid credentials. 
To authenticate your request, follow the steps in: 
https://cloud.google.com/container-registry/docs/advanced-authentication
```

**Comment by treethought** [comment]
Same issue here using gcr.io/kaniko-project/executor:debug in our gitlab CI pipeline. Proper credentials are in place, and was working up until this morning

**Comment by roychri** [comment]
This sounds like a dupe of #1235

**Comment by RadoBart** [comment]
> This sounds like a dupe of #1235
Yeah, it seems identical, closing this as a duplicate.
