### ISSUE TITLE
Document how to provide credentials

### ISSUE THREAD

**Issue by errm** [GoogleContainerTools/kaniko#124]
The README says
> configuring another credential helper should allow pushing to a different registry

It would be great to include an example

**Comment by Boolman** [comment]
this works for me:

sudo docker run -v ${PWD}:${PWD} -v ${HOME}/.docker/config.json:/root/.docker/config.json boolman/kaniko:ubuntu -d gitlab.domain.local:4567/org/containername:tagname -c ${PWD}

cat $HOME/.docker/config.json
{
	"auths": {
		"gitlab.domain.local:4567": {
			"auth": "dXNlcm5hbWU6cGFzc3dvcmQ="
		},
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/18.03.0-ce (linux)"
	}
}

**Comment by carlossg** [comment]
Documented in #129

**Comment by dlorenc** [comment]
Closing as a dup of #109.
