### ISSUE TITLE
Kaniko doesn't cache in Multistage when copying files from a modified stage

### ISSUE THREAD

**Issue by thaituan** [GoogleContainerTools/kaniko#1244]
**Actual behavior**
In multistage, caching when copying file from a stage (which has change, although that change does not effect on copied file) to other stage does not happen.
It seems that this happened after fixing issue https://github.com/GoogleContainerTools/kaniko/issues/589

**Expected behavior**
Layers that haven't changed on the previous stage will still be cached on the next stage.

**To Reproduce**
1. See https://github.com/thaituan/kaniko-cache
2. Build docker image with cache on
3. Update scripts in `package.json` (not change `dependencies` and `devDependencies`)
 Example: `"test": "echo \"Error: no test specified\" && exit 10"` ->  `"test": "echo \"Error: no test specified\" && exit 20"`
4. Re-build docker image with cache on

**Additional Information**
 - Dockerfile: https://github.com/thaituan/kaniko-cache/blob/master/Dockerfile
 ```
FROM node:10-slim AS deps
COPY package.json /tmp
RUN cat /tmp/package.json | xargs -0 -i% node -pe 'o=(%);JSON.stringify({dependencies:o.dependencies,devDependencies:o.devDependencies})' > /tmp/package.deps.json

FROM node:10-slim
WORKDIR /app
COPY --from=deps /tmp/package.deps.json ./package.json
COPY ["yarn.lock", "./"]
RUN yarn install
```
Line 7 is supposed to be cached when only `dependencies` and `devDependencies` are changed.
Using the docker command to build works fine, but kaniko not.
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [x] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [x] </li></ul>|

**Comment by tejal29** [comment]
@thaituan The way kaniko caching works right now, it also adds the cache key for `deps` when calculating the cache key. You can make a change here
https://github.com/GoogleContainerTools/kaniko/blob/03b3391fccd8fed97c7d30ad3ffc59d812171535/pkg/executor/build.go#L186

and that should fix your issue.

**Comment by thaituan** [comment]
@tejal29  thank for your responding.

**Comment by thaituan** [comment]
@tejal29  thank for your responding. I see in line: 
https://github.com/GoogleContainerTools/kaniko/blob/03b3391fccd8fed97c7d30ad3ffc59d812171535/pkg/executor/build.go#L186
and line:
https://github.com/GoogleContainerTools/kaniko/blob/03b3391fccd8fed97c7d30ad3ffc59d812171535/pkg/executor/build.go#L188
are the same with 2 different cases. It looks like the key cache of the `deps` is being generated incorrectly. Is there a way to create a cache key that works the same way as the docker build?

**Comment by tejal29** [comment]
We need to remove it from both cases i.e.
- when a cached command is used
- when a regular command is used.

Please let me know if you need any more pointers.

**Comment by thaituan** [comment]
@tejal29 
Thank you for the help.
I tried removing this block: 
https://github.com/GoogleContainerTools/kaniko/blob/03b3391fccd8fed97c7d30ad3ffc59d812171535/pkg/executor/build.go#L184-L189
and it looks like my problem has been solved. But I don't have enough experience to check if it is bad for other cases.

**Comment by HubertBos** [comment]
Hello 

We have a very similar situation today when a multistage container created a binary on the first stage but use a cached layer on 2nd stage.
