### ISSUE TITLE
Missing or partial support for pattern substition in variable references (e.g. in RUN)

### ISSUE THREAD

**Issue by andraxin** [GoogleContainerTools/kaniko#1246]
Here is a minimal working example that reproduces this issue with across different Kaniko versions, with and without caching. (The script assumes `bash` and a terminal capable of highlighting).
```
cd "$(mktemp -d)"
{
    echo FROM alpine
    echo RUN var=a-b\; echo \${var/-//}
} | tee Dockerfile
e=$'\x1b' w=/workspace k=gcr.io/kaniko-project/executor
for i in {17..21}
do for c in "" "--cache --cache-repo -"
do echo "$e[33;1m$i:${c:2:6}$e[0m"
    docker run --rm -it -v "$PWD":$w $k:v0.$i.0 --no-push $c |
        sed "s/.*missing.*/$e[31;1m&$e[0m/"
    done
done
rm -vfr "$PWD"
cd -
```
The output is omitted for brevity (just run the script). The results are mixed.  The following table provides a summary.

| version | cache | no-cache |
| - | :-: | :-: |
| v0.17.0 | OK | OK |
| v0.18.0 | OK | OK |
| v0.19.0 | **KO** | **KO** |
| v0.20.0 | OK | **KO** |
| v0.21.0 | OK | **KO** |

Essentially, v0.19.0 is broken irrespective of caching, while earlier versions appear to be fine, and later versions only break when caching is turned on. 

The last and likely most relevant part of the compounded error comes from [this line](https://github.com/GoogleContainerTools/kaniko/blob/0bcafd40fc93e4ada0a22deaf2cf29b68932cd3c/vendor/github.com/moby/buildkit/frontend/dockerfile/shell/lex.go#L355)

**Comment by zaventh** [comment]
Still an issue in v1.2.0. For example, the parameter expansion `"${buildArch##*-}"` works in Docker build, but not in Kaniko.

**Comment by pagarwal-tibco** [comment]
I am also facing this issue. Any updates on this issue?

**Comment by nirav-chotai** [comment]
I cannot build the airflow image using kaniko, it works fine with the docker build.

**Error**
```
error building image: error building stage: failed to optimize instructions: failed to process "RUN mkdir -pv /usr/share/man/man1     && mkdir -pv /usr/share/man/man7     && export ${ADDITIONAL_DEV_APT_ENV?}     && bash -o pipefail -e -u -x -c \"${DEV_APT_COMMAND}\"     && bash -o pipefail -e -u -x -c \"${ADDITIONAL_DEV_APT_COMMAND}\"     && apt-get update     && apt-get install -y --no-install-recommends            ${DEV_APT_DEPS}            ${ADDITIONAL_DEV_APT_DEPS}     && apt-get autoremove -yqq --purge     && apt-get clean     && rm -rf /var/lib/apt/lists/*": missing ':' in substitution
```

**Code**
```
...
RUN mkdir -pv /usr/share/man/man1 \
    && mkdir -pv /usr/share/man/man7 \
    && export ${ADDITIONAL_DEV_APT_ENV?} \
    && bash -o pipefail -e -u -x -c "${DEV_APT_COMMAND}" \
    && bash -o pipefail -e -u -x -c "${ADDITIONAL_DEV_APT_COMMAND}" \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
           ${DEV_APT_DEPS} \
           ${ADDITIONAL_DEV_APT_DEPS} \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
...
```

**Comment by abprohorov** [comment]
Same on v1.3.0 with cache

**Comment by trallnag** [comment]
For me this works, where `TEST_VAR`` is passed in via `--build-arg TEST_VAR=$TEST_VAR`

```
FROM alpine:3.13.1
ENV TEST_VAR=${TEST_VAR}
RUN set -u && echo ${TEST_VAR}
```

**Comment by bynare** [comment]
Still seeing this on the latest version..

**Comment by darkdragon-001** [comment]
Same problem in latest version using cache:

```
RUN curl -L https://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION//./_}.tar.bz2 | tar xj
```

**Comment by darkdragon-001** [comment]
Checking [`Dockerfile` documentation](https://docs.docker.com/engine/reference/builder/#environment-replacement), environment variable substitution does only happen for a list of commands **not** including `RUN` since it is executed in a container with environment variables set either using `SHELL` when using _shell form_ (`RUN mycommand`) or directly when using _exec form_ (`RUN ['/bin/bash','-c','mycommand'`).

**Comment by darkdragon-001** [comment]
Checking [`Dockerfile` documentation](https://docs.docker.com/engine/reference/builder/#environment-replacement), environment variable substitution does only happen for a list of commands **not** including `RUN` since it is executed in a container with environment variables set.

**Comment by markus-geiger** [comment]
I also ran int this issue with:
```bash
RUN something --version="release-${APP_VERSION%.*}"
```

IT would be nyce to fix it.

**Comment by marcinz** [comment]
I am seeing the same issue. I am having to move out all complex shell parameter expansions out of the docker file and plug them in through build args. These expansions should be handled by the shell in a shell version of the `RUN` command, but Kaniko cache seems to be unaware of that.

**Comment by guillaume-d** [comment]
> I am seeing the same issue. I am having to move out all complex shell parameter expansions out of the docker file and plug them in through build args. These expansions should be handled by the shell in a shell version of the `RUN` command, but Kaniko cache seems to be unaware of that.

A more local (but still pretty lame...) workaround may be to reformulate the expansions using  command substitution and a pipeline (as in `$(echo "$buildArch" | grep -o '[^-]*$')` instead of `${buildArch##*-}`), which Kaniko at least seems not to choke on.

**Comment by Leletir** [comment]
Still an error in 1.6.0

**Comment by cemoktra** [comment]
This is really annoying. Use sed as a workaround:
`$(echo ${f} | sed -e 's|.txt|.csv|g');`

**Comment by cemoktra** [comment]
Please fix this bug. Its annoying as hell and makes it unusable

**Comment by michaellmonaghan** [comment]
This issue is still present when building with cache on `gcr.io/kaniko-project/executor:latest 1c812ffa8ec1`.

**Comment by tushar-door** [comment]
Is there a workaround for this? Like, not using cache?

**Comment by cemoktra** [comment]
@tushar-door you can work around by moving the problematic lines to a shell script

**Comment by ksa-real** [comment]
Another workaround: `something $(sh -c 'echo ${APP_VERSION%-*}')` instead of `something ${APP_VERSION%-*}`. Pretty annoying...

**Comment by PapaNappa** [comment]
> Another workaround: `something $(sh -c 'echo ${APP_VERSION%-*}')` instead of `something ${APP_VERSION%-*}`. Pretty annoying...

That’s the best workaround for me.
Interestingly, `RUN echo $(sh -c 'echo ${FOO#foo})` works, but `RUN echo "$(sh -c 'echo ${FOO#foo})"` produces the same error message.
It seems when inside `"`, kaniko always tries to substitute the variable, even when it’s actually nested inside `$()`.

**Comment by ksa-real** [comment]
FYI you are missing closing `'` in both cases

**Comment by kt-315** [comment]
Hi all!  
I found the promblem [here](https://github.com/GoogleContainerTools/kaniko/blob/24846d22b11f20edc03dff7ac3b3959019969873/vendor/github.com/moby/buildkit/frontend/dockerfile/shell/lex.go#L312).  
Where cache is use we need get checksum before execute RUN instruction. For that need interpolate all variable of shell (**ARG** or **ENV** in **Dockerfile** can be new and we have to consider this). Lex shell library which used for this case support only syntax: **$var** or **${var}** or **${var:(+|-|?)word}**.  
 Now can use only half **sh** syntax.

**Comment by mcarbonneaux** [comment]
> A more local (but still pretty lame...) workaround may be to reformulate the expansions using command substitution and a pipeline (as in `$(echo "$buildArch" | grep -o '[^-]*$')` instead of `${buildArch##*-}`), which Kaniko at least seems not to choke on.

i used the same type of workaround.... 

ex: "$(echo \"${f}\" | sed \"s/.example$//\")" in place of 'echo ${f%.example}'

**Comment by codethief** [comment]
I'm experiencing a very similar issue: The following line in my Dockerfile

```
RUN VERSION_FROM_PACKAGE_JSON="$(grep --extended-regexp '"playwright": "([0-9].+)"' package-lock.json | cut -d ':' -f 2 | cut -d '"' -f 2)" \
  bash -c 'npm install "playwright@${VERSION_FROM_PACKAGE_JSON}"'
``` 

causes Kaniko to output

```
error building image: error building stage: failed to optimize instructions: failed to process "RUN VERSION_FROM_PACKAGE_JSON=\"$(grep --extended-regexp '\"playwright\": \"([0-9].+)\"' package-lock.json | cut -d ':' -f 2 | cut -d '\"' -f 2)\"   bash -c 'npm install \"playwright@${VERSION_FROM_PACKAGE_JSON}\"'": unexpected end of statement while looking for matching single-quote
```

If I disable the cache, the error no longer shows up.

**Comment by kt-315** [comment]
I have an idea. I'll try to fix it by the end of the week

**Comment by zaventh** [comment]
Good job @kt315 Thanks.

**Comment by domi27** [comment]
I can also confirm using Kaniko version 1.22 helped me out against this bug. Thank you @kt315
