### ISSUE TITLE
how to set cache not expired

### ISSUE THREAD

**Issue by tingshua-yts** [GoogleContainerTools/kaniko#1259]
I use warmer cache base image , but a few days later the cache wile be expired.
How can I set cache not expired?

expired log:
ESC[36mINFOESC[0m[0000] Resolved base name tensorflow/tensorflow:2.1.0-gpu-py3 to tensorflow/tensorflow:2.1.0-gpu-py3
ESC[36mINFOESC[0m[0000] Resolved base name tensorflow/tensorflow:2.1.0-gpu-py3 to tensorflow/tensorflow:2.1.0-gpu-py3
ESC[36mINFOESC[0m[0000] Retrieving image manifest tensorflow/tensorflow:2.1.0-gpu-py3
ESC[37mDEBUESC[0m[0011] Cached image is too old: 2020-04-23 06:58:31.880918355 +0000 UTC
ESC[37mDEBUESC[0m[0011] Image tensorflow/tensorflow:2.1.0-gpu-py3 found in cache but was expired

**Comment by evheny0** [comment]
You can use `--cache-ttl` flag to set expiration time for cache. For example `--cache-ttl=1440h` for two months.
