### ISSUE TITLE
Fetch BusyBox binary from busybox.net instead of Distroless after running "bazel build" 

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/kaniko#1277]
> which is part of `kaniko:debug` image:
> https://github.com/GoogleContainerTools/kaniko/blob/0522fe2485c25f55d9d96a028058da0b180e0bec/deploy/Dockerfile_debug#L36-L41

Unrelated, the way Kaniko fetches BusyBox is inexplicably convoluted. Why getting it from a Distroless image after building it with `bazel build`, while it can simply download the file directly from busybox.net (which is [what Distroless does](https://github.com/GoogleContainerTools/distroless/blob/eddfb5cd7a24d656f77afae595ffe6c232eab847/WORKSPACE#L194))? It's a single binary file. Doesn't make much sense to me.

_Originally posted by @chanseokoh in https://github.com/GoogleContainerTools/distroless/issues/225#issuecomment-631593987_

**Comment by tejal29** [comment]
fixed by #1254
