### ISSUE TITLE
Snapshotting is taking more than 10 mins.

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/kaniko#1282]
**Actual behavior**
Snapshotting FS should for a Node js project  with `npm install` command should be faster than current.

**Expected behavior**
Looks like `TakeSnapshotFS` is a bottleneck for projects with huge number of files.
e.g .for a project with file count 800K, the `TakeSnapshotFS` takes almost 15-20 mins.

After some investigation, i found out we loop over files multiple times. In this PR, we are reducing the number of times we loop over the files.

**Comment by sameersbn** [comment]
I am facing this issue as well. this step takes the most number of cycles in my builds. optimizing this will greatly reduce the build time of ALL my images.
