### ISSUE TITLE
Kaniko cache warmer fails to download said image

### ISSUE THREAD

**Issue by rjdp** [GoogleContainerTools/kaniko#1286]
**Actual behavior**
when running: 
`docker run -v $(pwd):/workspace gcr.io/kaniko-project/warmer:latest --cache-dir=/workspace/cache  --image=python:3.5.9-buster`

I get error: 
`Failed warming cache: Failed to write python:3.5.9-buster to tar buffer: stream error: stream ID 21; PROTOCOL_ERROR`

**Expected behavior**
Should successfully download layers image and populate warmer cache

**To Reproduce**
1. `docker run -v $(pwd):/workspace gcr.io/kaniko-project/warmer:latest --cache-dir=/workspace/cache  --image=python:3.5.9-buster`

**Comment by tejal29** [comment]
@rjdp can you try again. I wasnt able to reproduce this.
```
docker run -v $(pwd):/workspace gcr.io/kaniko-project/warmer:latest --cache-dir=/workspace/cache --image=python:3.5.9-buster
Unable to find image 'gcr.io/kaniko-project/warmer:latest' locally
latest: Pulling from kaniko-project/warmer
c3cb4bc16b13: Pull complete 
7297e31a4a50: Pull complete 
1a44f4735fa9: Pull complete 
4518dc1145a3: Pull complete 
5612d4e53d2c: Pull complete 
dcf1edbeb897: Pull complete 
5dc9f5dc95d8: Pull complete 
45bcf3f59595: Pull complete 
278ba2b90ed2: Pull complete 
Digest: sha256:5569f9723a0ea52be2ad1f2882b6d41f400aa8e00cee12e854b49ec9c9b18937
Status: Downloaded newer image for gcr.io/kaniko-project/warmer:latest
```

**Comment by rjdp** [comment]
this is little strange, was able to reproduce once but not in further attempts. Thanks :) in case I find leads to reproduce I will let you know. closing this.
