### ISSUE TITLE
AWS error reported when building images inside Kubernetes without direct Internet access

### ISSUE THREAD

**Issue by olivier-mauras** [GoogleContainerTools/kaniko#1287]
**Actual behavior**
When running Kaniko inside a Kubernetes cluster that don't have a direct internet access - private registry only - it seems to take an unusual long time - 45 to 60s (timeout?) - before giving the following error:

E0525 12:58:00.462141      15 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors

After the error, the image build proceeds as expected

**Expected behavior**
Not spend time on omthing unused...

**To Reproduce**
Start an image build in a Kubernetes cluster with no direct internet access

**Additional Information**
 - Dockerfile 
   Any 
 - Build Context
    Any
 - Kaniko Image: Last week's debug: sha256:23ad72c3a3133b6745dacc0178100113dc263f422582f4cddf92a3712f5bbb5d
  
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by olivier-mauras** [comment]
#1270

**Comment by olivier-mauras** [comment]
So I can work this around by removing these lines:
https://github.com/GoogleContainerTools/kaniko/blob/master/pkg/creds/creds_linux.go#L38-L51

The AWS issue seems to come from there: https://github.com/vdemeester/k8s-pkg-credentialprovider/blob/master/aws/aws_credentials.go#L68 while it keeps trying to make a new session while there's no AWS option/variable set.

**Comment by will-darkwolf** [comment]
Was this ticket resolved, or just closed?

**Comment by MrAmbiG** [comment]
we still dont have an image which is out of this bug? is anyone working on it?

**Comment by aerfio** [comment]
Anything here?

**Comment by aerfio** [comment]
We're hitting the same issue :/ why does kaniko need access to internet? If I'm pushing to private registry which is also in the cluster (or run as `docker run` alongside) then I should not expose this component to outside world

**Comment by waveywaves** [comment]
I had the same issue recently. Had to switch to a patched kaniko image. Hope this get's fixed soon.

**Comment by leokhachatorians** [comment]
So yeah, is this going to be addressed anytime soon?

**Comment by dectl** [comment]
Still no fix yet?

**Comment by treethought** [comment]
experiencing the same issue

**Comment by guifran001** [comment]
#1270 has been closed has a duplicated, but it is not quite the same behavior. After the AWS message, it just hang forever. 

Seems to be due to the metadata server according on the explanation in #1270:
```
// Enabled implements a special metadata-based check, which verifies the
// storage scope is available on the GCE VM.
// If running on a GCE VM, check if 'default' service account exists.
// If it does not exist, assume that registry is not enabled.
// If default service account exists, check if relevant scopes exist in the default service account.
// The metadata service can become temporarily inaccessible. Hence all requests to the metadata
// service will be retried until the metadata server returns a `200`.
// It is expected that "http://metadata.google.internal./computeMetadata/v1/instance/service-accounts/" will return a `200`
// and "http://metadata.google.internal./computeMetadata/v1/instance/service-accounts/default/scopes" will also return `200`.
// More information on metadata service can be found here - https://cloud.google.com/compute/docs/storing-retrieving-metadata
```
Since, I change my GKE k8s cluster from autopilot to a normal one, it hangs. Does anybody have a workaround or a fix ?

**Comment by u-phoria** [comment]
Running kaniko on a k3s cluster on a GCE VM, I was eventually able to work around this particular issue by adding a host alias to the pod spec:

```
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  hostAliases:
    - ip: "169.254.169.254"
      hostnames:
        - metadata.google.internal
  containers:
    - name: kaniko
...
```

**Comment by rgstephens** [comment]
I'm having this issue and my Pod has external internet access.

**Comment by erSitzt** [comment]
I'm getting this too... i didnt expect to find such an old issue for this...

I tried your runner config, but im still getting the error... @Jasstkn 
Or is this just a fix for when kaniko is hanging ?

For completeness sake, error seems exactly the same as first reported:
```
E0211 21:19:04.844552      45 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

**Comment by imjasonh** [comment]
We've somewhat recently changed how credentials can be provided for GCR/ECR/ACR, so as not to depend on K8s's unsupported cred helpers. If you're interested, this might fix your issues (but then again, it might not!) and in any case, getting recent feedback on whether this is still an issue would be helpful.

You can try out a recent commit-tagged Kaniko image to see if this is fixed:

```
gcr.io/kaniko-project/executor:343f78408c891ef7a85bab1ecbf2dd69367a58bc
gcr.io/kaniko-project/executor:343f78408c891ef7a85bab1ecbf2dd69367a58bc-debug
```

Let me know if that fixes your issue 🤞

**Comment by imjasonh** [comment]
That's correct, the non-debug image doesn't include a shell.

Closing this since it sounds like the issue has been fixed at some point.
