### ISSUE TITLE
Jfrog Container Registry push check failed

### ISSUE THREAD

**Issue by kivio** [GoogleContainerTools/kaniko#1291]
**Actual behavior**

Kaniko raised exception when pushing to Jfrog Container Registry (JCR).
```
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "my-repo.domain/project/project-configuration:testing": creating push check transport for my-repo.domain failed: GET https://my-repo.domain/v2/token?scope=repository%3Aproject%2project-configuration%3Apush%2Cpull&service=my-repo.domain: : Authentication is required
```

**Expected behavior**

It should work - docker configured same way is working correctly.

**To Reproduce**
1. Configure JCR in config.json
2. Try to build

**Additional Information**
- my config file looks like that, it's copied from logged docker that works:
```
{
        "auths": {
                "my-repo.domain": {
                        "auth": "<base-64-here>"
                }
        }
}
```
Sam error when providing all credentials:
```
{
        "auths": {
                "my-repo.domain": {
                   "username": "builder",
                   "password": "pass",
                   "auth": "<base-64-here>",
                   "email": "email@domain"
                }
        }
}
```

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ No ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ Yes ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ Not Applied ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ Not Applied ] </li></ul>|

**Comment by kivio** [comment]
Running in debug or even trace level doesn't give more informations.

**Comment by kumprj** [comment]
I'm able to push to JFrog using Jenkins and shell scripts. I have a step that does
`echo '{"auths": {"jfrog.company.com": {"username":"userhere", "password":"jfrogpw"}}} > /kaniko/.docker/config.json`

**Comment by vivekthangathurai** [comment]
@kivio @tejal29 any solutions for this issue? I am facing the exact same problem.

**Comment by tejal29** [comment]
@vivekthangathurai Can you try the steps mentioned in https://github.com/GoogleContainerTools/kaniko/issues/1291#issuecomment-650812003

**Comment by vivekthangathurai** [comment]
thanks. It worked!!
