### ISSUE TITLE
RUN in shell form works, RUN in exec form breaks, works in Docker

### ISSUE THREAD

**Issue by joe-sonrichard** [GoogleContainerTools/kaniko#1292]
**Overview**
I have an [sbt ](https://www.scala-sbt.org/) generated Dockerfile which builds in docker but not Kaniko. Kaniko fails to find executable when a RUN command is in [exec form](https://docs.docker.com/engine/reference/builder/#run). 

**Actual behavior**
Docker image doesn't build because chown not in `$PATH`.

Error message:
`error building image: error building stage: failed to execute command: starting command: exec: "chown": executable file not found in $PATH`

**Expected behavior**
chown would be found and executed same as with docker legacy build system (haven't tried it with buildkit yet).

**To Reproduce**
1. `mkdir -p opt/docker`
2. Copy one of the Dockerfiles I link below into `./`
3. Try `docker build .`  <- it works
4. Try the command below. It doesn't work for the first Dockerfile in Kaniko, it does for the others.
  ```bash
  docker run --rm -v ${PWD}:/build -w /build gcr.io/kaniko-project/executor:latest \
	--no-push --dockerfile=./Dockerfile --context=./ --oci-layout-path=./image-digest
  ```

**Additional Information**
 - 3 Dockerfiles, the first breaks in Kaniko, the other two work. Behavior is equivalent. (Unfortunately a sbt plugin outputs the first one in a CI/CD pipeline so the workaround isn't as easy as it looks).
```Dockerfile
FROM openjdk:8-jre-alpine
WORKDIR /opt/docker
ADD opt /opt
RUN ["chown", "-R", "daemon:daemon", "."]  # This line
USER daemon
ENTRYPOINT ["/opt/docker/bin/code-gen"]
CMD []
```
```Dockerfile
FROM openjdk:8-jre-alpine
WORKDIR /opt/docker
ADD opt /opt
RUN chown -R daemon:daemon . # This line
USER daemon
ENTRYPOINT ["/opt/docker/bin/code-gen"]
CMD []
```
```Dockerfile
FROM openjdk:8-jre-alpine
WORKDIR /opt/docker
ADD --chown=daemon:daemon opt /opt # This line
USER daemon
ENTRYPOINT ["/opt/docker/bin/code-gen"]
CMD []
```
   
 - Build Context
   `mkdir -p opt/docker` will provide everything you need in your immediate context
 - Kaniko Image:
   This is true for v0.19.0, v0.22.0, and latest. I'm guessing it is common across tags.
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [X] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by tejal29** [comment]
@joe-sonrichard Kaniko debug image  provides `chown` 
```
tejaldesai@tejaldesai-macbookpro2 kaniko (benchmark-snapshot)docker run --entrypoint /busybox/sh -it gcr.io/kaniko-project/executor:debug
/ # ls -al /busybox/chown 
-rwxr-xr-x  398 0        0          1132800 Jun  2 02:37 /busybox/chown
/ # 
```

Or else you will have to use an image which provides the command.
e.g
https://github.com/GoogleContainerTools/kaniko/blob/1bf4421047570790ced358f60118b58709628c15/integration/dockerfiles/Dockerfile_test_parent_dir_perms#L1

**Comment by joe-sonrichard** [comment]
@tejal29 I am not sure you understood the error or I am not understanding your response. My image already provides `chown` as evidenced by the fact the 2nd docker file built just fine. The problem is that, given an image which provides `chown`, Kaniko cannot find `chown` if it is run in the [exec](https://docs.docker.com/engine/reference/builder/#run) form but it can if in shell form.

So, in the same image which has chown installed already, this line works:
```dockerfile
RUN chown -R daemon:daemon .
```
and this one fails:
```dockerfile
RUN ["chown", "-R", "daemon:daemon", "."] 
```

To experiment, I decided to try taking [the dockerfile you referenced](https://github.com/GoogleContainerTools/kaniko/blob/1bf4421047570790ced358f60118b58709628c15/integration/dockerfiles/Dockerfile_test_parent_dir_perms) and modifying the second chown to use `exec form` rather than `shell form` and it broke once again though it works in docker.

Here's the busybox dockerfile as modified:
```dockerfile
FROM busybox

RUN adduser --disabled-password --gecos "" --uid 1000 user
RUN mkdir -p /home/user/foo
RUN chown -R user /home/user
RUN chmod 700 /home/user/foo
ADD https://raw.githubusercontent.com/GoogleContainerTools/kaniko/master/README.md /home/user/foo/README.md
RUN ["chown", "-R", "user", "/home/user"]
```

And here's the command and results where you can see that it fails to run chown in `exec form` though it works in `shell form`.

```bash
->docker run --rm -v ${PWD}:/build -w /build gcr.io/kaniko-project/executor:latest   --no-push --dockerfile=./Dockerfile --context=./ --oci-layout-path=./image-digest
INFO[0000] Retrieving image manifest busybox            
INFO[0001] Retrieving image manifest busybox            
INFO[0001] Built cross stage deps: map[]                
INFO[0001] Retrieving image manifest busybox            
INFO[0002] Retrieving image manifest busybox            
INFO[0002] Executing 0 build triggers                   
INFO[0002] Unpacking rootfs as cmd RUN adduser --disabled-password --gecos "" --uid 1000 user requires it. 
INFO[0003] RUN adduser --disabled-password --gecos "" --uid 1000 user 
INFO[0003] Taking snapshot of full filesystem...        
INFO[0003] Resolving 422 paths                          
INFO[0003] cmd: /bin/sh                                 
INFO[0003] args: [-c adduser --disabled-password --gecos "" --uid 1000 user] 
INFO[0003] Running: [/bin/sh -c adduser --disabled-password --gecos "" --uid 1000 user] 
INFO[0003] Taking snapshot of full filesystem...        
INFO[0003] Resolving 426 paths                          
INFO[0003] RUN mkdir -p /home/user/foo                  
INFO[0003] cmd: /bin/sh                                 
INFO[0003] args: [-c mkdir -p /home/user/foo]           
INFO[0003] Running: [/bin/sh -c mkdir -p /home/user/foo] 
INFO[0003] Taking snapshot of full filesystem...        
INFO[0003] Resolving 427 paths                          
INFO[0003] RUN chown -R user /home/user                 
INFO[0003] cmd: /bin/sh                                 
INFO[0003] args: [-c chown -R user /home/user]          
INFO[0003] Running: [/bin/sh -c chown -R user /home/user] 
INFO[0003] Taking snapshot of full filesystem...        
INFO[0003] Resolving 427 paths                          
INFO[0003] RUN chmod 700 /home/user/foo                 
INFO[0003] cmd: /bin/sh                                 
INFO[0003] args: [-c chmod 700 /home/user/foo]          
INFO[0003] Running: [/bin/sh -c chmod 700 /home/user/foo] 
INFO[0003] Taking snapshot of full filesystem...        
INFO[0003] Resolving 427 paths                          
INFO[0004] Using files from context: []                 
INFO[0004] ADD https://raw.githubusercontent.com/GoogleContainerTools/kaniko/master/README.md /home/user/foo/README.md 
INFO[0004] Adding remote URL https://raw.githubusercontent.com/GoogleContainerTools/kaniko/master/README.md to /home/user/foo/README.md 
INFO[0004] Resolving 1 paths                            
INFO[0004] Taking snapshot of files...                  
INFO[0004] RUN ["chown", "-R", "user", "/home/user"]    
INFO[0004] cmd: chown                                   
INFO[0004] args: [-R user /home/user]                   
INFO[0004] Running: [chown -R user /home/user]          
error building image: error building stage: failed to execute command: starting command: exec: "chown": executable file not found in $PATH
```
