### ISSUE TITLE
Kaniko not preserving ownership on staging building

### ISSUE THREAD

**Issue by kvaps** [GoogleContainerTools/kaniko#1315]
**Actual behavior**
Kaniko does not preserving owner and group for directories and files on staging building.

**Expected behavior**
Same owner and group as in parent stage

**To Reproduce**
1. build Dockerfile bellow
2. Check the permissions:
```
/ # ls /myapp/ -lah
total 0      
drwxr-xr-x    1 root     root          14 Jun 12 16:39 .
drwxr-xr-x    1 root     root         144 Jun 12 16:40 ..
drwxr-xr-x    1 root     root           0 Jun 12 16:39 somedir
```

**Additional Information**
 - Dockerfile
```Dockerfile
FROM alpine:3.11 as builder

RUN mkdir -p /myapp/somedir \
 && chown 123:123 /myapp/somedir

FROM alpine:3.11
COPY --from=builder /myapp /myapp
```
 - Build Context
 - Kaniko Image:
```
gcr.io/kaniko-project/executor:debug-v0.16.0 (sha256:552567f5a8bbc5d8d293d3210619edfe5e9ea0a04fbe3bdae6fc04f5051d5e00)
```
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by michaellmonaghan** [comment]
I have also encountered this exact issue on the lastest release of Kaniko. It is breaking several of my images and is preventing my team from switching from docker build.`gcr.io/kaniko-project/executor:latest 1c812ffa8ec1`
