### ISSUE TITLE
COPY --chown 107:107 fails when /etc/passwd or /etc/group doesn't exist

### ISSUE THREAD

**Issue by dren-dk** [GoogleContainerTools/kaniko#1340]
**Actual behavior**

I have the simplest Dockerfile that looks like this:
FROM scratch
COPY --chown=107:107 disk.qcow2 /disk/disk.qcow2

Kaniko fails on the copy command due to it missing /etc/passwd:

```

error building image: error building stage: failed to execute command: getting user group from chown: open /etc/passwd: no such file or directory
INFO[0041] COPY --chown=107:107 disk.qcow2 /disk/disk.qcow2 
```

**Expected behavior**

I would have liked the file to be added with uid 107 and gid 107 regardless of the existence of /etc/passwd or its contents.

**To Reproduce**

Use this Dockerfile:
```
FROM scratch
ADD --chown=107:107 Dockerfile /Dockerfile
```

I built with this command line:
docker run -v `pwd`:/workspace gcr.io/kaniko-project/executor:latest --dockerfile /workspace/Dockerfile --no-push  --context dir:///workspace/ 

Yields this output:
```
INFO[0000] No base image, nothing to extract            
INFO[0000] Built cross stage deps: map[]                
INFO[0000] No base image, nothing to extract            
INFO[0000] Executing 0 build triggers                   
INFO[0000] Unpacking rootfs as cmd ADD --chown=107:107 Dockerfile /Dockerfile requires it. 
INFO[0000] Using files from context: [/workspace/Dockerfile] 
INFO[0000] ADD --chown=107:107 Dockerfile /Dockerfile   
error building image: error building stage: failed to execute command: getting user group from chown: open /etc/passwd: no such file or directory
```

 - Kaniko Image (fully qualified with digest)

* gcr.io/kaniko-project/executor:debug-v0.23.0
* gcr.io/kaniko-project/executor:latest

 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [X] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by tejal29** [comment]
@dren-dk we do try to get user group and any secondary groups if present by reading the "/etc/passwd" file.

**Comment by tejal29** [comment]
Something we could fix in https://github.com/GoogleContainerTools/kaniko/blob/2609944787c5af903c7fe2a59cd703c58a438e73/pkg/util/command_util.go#L373

**Comment by DarthSlider** [comment]
@dren-dk Hi! Did you find any workaround?

**Comment by DarthSlider** [comment]
@dren-dk 
I just added
 RUN chown 1000:1000 ${HOMEDIR}
 but it isn't usable with
 FROM: scratch

**Comment by HildaHay** [comment]
This is still an issue on the most recent release of Kaniko.

**Comment by aaron-prindle** [comment]
I've verified using the repro above:

`Dockerfile`
```
FROM scratch
ADD --chown=107:107 Dockerfile /Dockerfile
```

kaniko - `v0.23.0`
```
aprindle@aprindle-ssd ~/kaniko  [(HEAD detached at v0.23.0)]./run_in_docker.sh /workspace/Dockerfile /usr/local/google/home/aprindle/kaniko-ctx-dir gcr.io/aprindle-test-cluster/kaniko-test:latest
WARN[0000] kaniko is being run outside of a container. This can have dangerous effects on your system 
WARN[0000] Error detecting container runtime. Using default keychain: container runtime could not be found 
INFO[0000] No base image, nothing to extract            
INFO[0000] Built cross stage deps: map[]                
INFO[0000] No base image, nothing to extract            
INFO[0000] Executing 0 build triggers                   
INFO[0000] Unpacking rootfs as cmd ADD --chown=107:107 Dockerfile /Dockerfile requires it. 
INFO[0000] Using files from context: [/workspace/Dockerfile] 
INFO[0000] ADD --chown=107:107 Dockerfile /Dockerfile   
error building image: error building stage: failed to execute command: getting user group from chown: open /etc/passwd: no such file or directory
```

kaniko `v1.10.0` (likely all versions after #2269)
```
aprindle@aprindle-ssd ~/kaniko  [main]./run_in_docker.sh /workspace/Dockerfile /usr/local/google/home/aprindle/kaniko-ctx-dir gcr.io/aprindle-test-cluster/kaniko-test:latest
INFO[0000] No base image, nothing to extract            
INFO[0000] Built cross stage deps: map[]                
INFO[0000] No base image, nothing to extract            
INFO[0000] Executing 0 build triggers                   
INFO[0000] Building stage 'scratch' [idx: '0', base-idx: '-1'] 
INFO[0000] Unpacking rootfs as cmd ADD --chown=107:107 Dockerfile /Dockerfile requires it. 
INFO[0000] Using files from context: [/workspace/Dockerfile] 
INFO[0000] ADD --chown=107:107 Dockerfile /Dockerfile   
INFO[0000] Taking snapshot of files...                  
INFO[0000] Pushing image to gcr.io/aprindle-test-cluster/kaniko-test:latest 
INFO[0003] Pushed gcr.io/aprindle-test-cluster/kaniko-test@sha256:aacf9935853674958ebfe367f5ae7a955eef6e3cf115f43e78d7d2560303541c 
```

Closing as fixed
