### ISSUE TITLE
Add GCR instruction - Pushing to Different Registries

### ISSUE THREAD

**Issue by renatosuero** [GoogleContainerTools/kaniko#1341]
The documentation has a [section](https://github.com/GoogleContainerTools/kaniko#pushing-to-different-registries) to show how to push in private registries. The doc says it supports GCR, docker, and aws. The examples only show docker and aws. 
[Here](https://github.com/GoogleContainerTools/kaniko#running-kaniko-in-a-kubernetes-cluster) in k8s section, we have the configuration to GCR, we need to define the ENV var.
I was wondering if it would make sense we add the instruction for GCR  in the pushing to different registries, in positive case I could do that.

**Comment by tejal29** [comment]
@renatosuero would love any contributions which help making our docs more user friendly and better!
Please feel free to add it.

**Comment by renatosuero** [comment]
cool, I'll do that this week :)

**Comment by renatosuero** [comment]
merged!
