### ISSUE TITLE
[Question] Force to use existing cache

### ISSUE THREAD

**Issue by matzeeable** [GoogleContainerTools/kaniko#1343]
Hi!

I am using `kaniko` now for a long time on Open Source projects and private repos within a GitLab CI. I've been trying to figure out how to "force a cache usage" within a `Dockerfile` - and just want to ask here, is this possible?

**Context:**

I am using `yarn` inside my `Dockerfile` and want to hot-cache my 3rd party dependencies:

```Dockerfile
// [...]
COPY package.json .
RUN yarn install --frozen-lockfile
```

If the `package.json` changes, the builder throws away the entire cache and Yarn Dependencies installs itself from scratch. I work in a **monorepo**, so the install process can take quite a long time. I do not want the cache to be ignored for this `RUN` command.

Regards,
Matthew 🙂

**Comment by tejal29** [comment]
hmm. @matzeeable not familiar with `yarn install`. From the docs look like yarn installs packages from `package.json`. 
One way, i could think is to split your package.json 
1. 3rd party not changing or rarely changing packages dependencies. 
```
COPY 3rdparty.json . 
RUN yarn install -f 3rdparty.json  --frozen-lockfile.  // Not sure if it is possible to install from another file.
COPY package.json . 
RUN yarn install --frozen-lockfile

```

Or, you could specify a cache directory using "https://classic.yarnpkg.com/en/docs/cli/cache" . 
```
docker run \
    -v "$HOME"/.config/gcloud:/root/.config/gcloud \
    -v /path/to/context:/workspace \
    -v /local-yarn-cache:/yarn-cache
    gcr.io/kaniko-project/executor:latest \
    --dockerfile /workspace/Dockerfile \
    --destination "gcr.io/$PROJECT_ID/$IMAGE_NAME:$TAG" \
    --context dir:///workspace/
```
In your dockerfile
```
COPY package.json .
RUN yarn install --frozen-lockfile --cache-folder /yarn-cache
```

**Comment by matzeeable** [comment]
Hi @tejal29,

Thanks for your detailed message. I forgot to close this issue as I have solved it with `docker commit`. But your idea with a volume seems also good!

Regards,
Matthew :-)
