### ISSUE TITLE
Docker image has wrong kaniko version

### ISSUE THREAD

**Issue by Sineaggi** [GoogleContainerTools/kaniko#1366]
**Actual behavior**
Running kaniko version in docker container produces `Kaniko version :  v0.23.0`

**Expected behavior**
Expected to see `Kaniko version :  v0.24.0`

**To Reproduce**
1. `docker run --rm gcr.io/kaniko-project/executor:v0.24.0 version`
2. `docker run --rm gcr.io/kaniko-project/executor:debug-v0.24.0 version`
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by hashworks** [comment]
Same goes for the latest tag, `Makefile` contains `VERSION_MINOR ?= 23`.

**Comment by tejal29** [comment]
this is fixed now on master
