### ISSUE TITLE
Downloading from docker when "Unpacking rootfs as cmd COPY . . requires it. "

### ISSUE THREAD

**Issue by jeessy2** [GoogleContainerTools/kaniko#1373]
**Actual behavior**
```
FROM golang:alpine3.12 AS builder
WORKDIR /app
COPY . .
```
Downloading from docker when "Unpacking rootfs as cmd COPY . . requires it. "
it's slow

**Expected behavior**
Cache the docker imges

**To Reproduce**
1. ...
2. ...

**Additional Information**
 - Dockerfile 
   Please provide either the Dockerfile you're trying to build or one that can reproduce this error.
 - Build Context
   Please provide or clearly describe any files needed to build the Dockerfile (ADD/COPY commands)
 - Kaniko Image (fully qualified with digest)
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by tejal29** [comment]
@jeessy2 we do have a way to cache base images https://github.com/GoogleContainerTools/kaniko#caching-base-images
Can you try this?

**Comment by jeessy2** [comment]
i don't know the image name, just happen on 'copy . .'

**Comment by dxxd116** [comment]
In my case, the problem seems to be related to network connections. After I add in the proxy settings in the container by:


```
   export http_proxy=<my proxy server: port>
   export https_proxy=<my proxy server: port>
```

Then it works like charms.
