### ISSUE TITLE
error building image: error building stage connection reset by peer

### ISSUE THREAD

**Issue by lbouquinUniv** [GoogleContainerTools/kaniko#1377]
**Actual behavior**
I use it with gitlab-ci. when  kaniko vbuild stage reset connection 
I have the following message:
`error building image: error building stage: failed to get filesystem from image: read tcp 10.233.66.246:35054->IP_B:443: read: connection reset by peer` where IP_B is harbor registry ip address 

**Expected behavior**
We have to build image. 

**To Reproduce**
1. create stage with gitlab-ci like this 
      `Build App:
  stage: build_dev
  tags:
    - cluster.ktest
  image:
    name: gcr.io/kaniko-project/executor:$KANIKO_VERSION
    entrypoint: [""]
  script:
    - mkdir -p /root/.docker
    - echo "{\"auths\":{\"$DOCKER_REGISTRY\":{\"username\":\"$TESTHTTPD_ROBOT_USERNAME\",\"password\":\"$TESTHTTPD_ROBOT_PASSWORD\"}}}"
    - echo "{\"auths\":{\"$DOCKER_REGISTRY\":{\"username\":\"$TESTHTTPD_ROBOT_USERNAME\",\"password\":\"$TESTHTTPD_ROBOT_PASSWORD\"}}}" > /root/.docker/config.json
    - /kaniko/executor --skip-tls-verify-pull  --verbosity debug --skip-tls-verify --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Docker/Dockerfile --destination $DOCKER_REGISTRY/$DOCKER_REGISTRY_PROJET/$DOCKER_REGISTRY_IMAGE:$TAG_IMAGE_DEV --destination $DOCKER_REGISTRY/$DOCKER_REGISTRY_PROJET/$DOCKER_REGISTRY_IMAGE:dev-latest
  only:
    refs:
      - dev
    changes:
      - Docker/**/*
      - Sources/**/*`
2. change one of sources. 
3. push and see the pipeline in gitlab-ci 

**Additional Information**
```
FROM our_registry/cas-clients/phpcas:v1.3.8

USER 0

# Copy des sources
#RUN mkdir /var/www/
COPY Sources/* /var/www/
RUN chown -R www-data:www-data /var/www/

USER 33

CMD ["/usr/sbin/apache2", "-DFOREGROUND"]
```
 ( you can use apache2 server in docker hub ) 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ X] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by lbouquinUniv** [comment]
I found a solution.
I add iptables rules to drop invalid packet harbor registry side. ( iptables -I INPUT -m conntrack --ctstate INVALID -j DROP
 && echo 1 >  /proc/sys/net/netfilter/nf_conntrack_tcp_be_liberal ).

**Comment by dclong** [comment]
@lbouquinUniv Can you explain a little bit more on how you resolved the issue? Did you run the `iptables` command in the Dockerfile or in the Kaniko container?

**Comment by laurent6** [comment]
Hi, 
I run this command in Vm where container is start
