### ISSUE TITLE
Read-only file system when mounting volume

### ISSUE THREAD

**Issue by guyguy333** [GoogleContainerTools/kaniko#1386]
**Actual behavior**

When you mount a volume as RO in Kaniko container, you cannot write to the same volume path from the Dockerfile being built by Kaniko.

**Expected behavior**

Volume mount in Kaniko container has no impact on volumes with same path in Dockerfile being built.

**To Reproduce**
1. Mount a volume as RO in Kaniko container
2. In Dockerfile, try to write file in similar path as mounted volume

**Additional Information**
 - Dockerfile 
```docker
FROM alpine:3

RUN echo "Europe/Paris" > /etc/timezone
```

 - Build Context
Without mounting /etc/timezone:

 ```bash
docker run --rm -v `pwd`:/workspaces gcr.io/kaniko-project/executor:debug-v0.24.0 --context /workspaces --dockerfile /workspaces/Dockerfile --no-push
```

```
INFO[0000] Retrieving image manifest alpine:3           
INFO[0002] Retrieving image manifest alpine:3           
INFO[0004] Built cross stage deps: map[]                
INFO[0004] Retrieving image manifest alpine:3           
INFO[0005] Retrieving image manifest alpine:3           
INFO[0007] Executing 0 build triggers                   
INFO[0007] Unpacking rootfs as cmd RUN echo "Europe/Paris" > /etc/timezone requires it. 
INFO[0007] RUN echo "Europe/Paris" > /etc/timezone      
INFO[0007] Taking snapshot of full filesystem...        
INFO[0008] cmd: /bin/sh                                 
INFO[0008] args: [-c echo "Europe/Paris" > /etc/timezone] 
INFO[0008] Running: [/bin/sh -c echo "Europe/Paris" > /etc/timezone] 
INFO[0008] Taking snapshot of full filesystem...        
INFO[0008] Skipping push to container registry due to --no-push flag 
```

Mounting /etc/timezone:

```bash
docker run --rm -v `pwd`:/workspaces -v /etc/timezone:/etc/timezone:ro gcr.io/kaniko-project/executor:debug-v0.24.0 --context /workspaces --dockerfile /workspaces/Dockerfile --no-push
```

```
INFO[0000] Retrieving image manifest alpine:3           
INFO[0001] Retrieving image manifest alpine:3           
INFO[0003] Built cross stage deps: map[]                
INFO[0003] Retrieving image manifest alpine:3           
INFO[0004] Retrieving image manifest alpine:3           
INFO[0006] Executing 0 build triggers                   
INFO[0006] Unpacking rootfs as cmd RUN echo "Europe/Paris" > /etc/timezone requires it. 
INFO[0006] RUN echo "Europe/Paris" > /etc/timezone      
INFO[0006] Taking snapshot of full filesystem...        
INFO[0006] cmd: /bin/sh                                 
INFO[0006] args: [-c echo "Europe/Paris" > /etc/timezone] 
INFO[0006] Running: [/bin/sh -c echo "Europe/Paris" > /etc/timezone] 
/bin/sh: can't create /etc/timezone: Read-only file system
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
```

 - Kaniko Image (fully qualified with digest)
gcr.io/kaniko-project/executor:debug-v0.24.0
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li> ? </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by tejal29** [comment]
@guyguy333 I am not sure i understand the issue correctly. 
If a docker container inside which kaniko runs, mounts a dir as readonly, kaniko does not have permissions to write in it.

**Comment by guyguy333** [comment]
> @guyguy333 I am not sure i understand the issue correctly. 
> 
> If a docker container inside which kaniko runs, mounts a dir as readonly, kaniko does not have permissions to write in it. 
> 
> It is the expected behavior. 

My bad if it's an expected behavior with Kaniko. I read a bit of code of Kaniko and I think I understood how it works. Indeed, I mustn't mount timezone in Kaniko.

I don't have this issue with Docker and DIND. Docker running DIND has /etc/timezone mounted to get the right timezone. Dockerfile being built in DIND don't care about mounted timezone.
