### ISSUE TITLE
kaniko finishes successfully, but image never shows up in ECR.

### ISSUE THREAD

**Issue by sonofagunn** [GoogleContainerTools/kaniko#1400]
**Actual behavior**
I am using the kaniko:debug container in a gitlab CI job to build an image. If I put the destination as the gitlab repository, everything works fine. If I change it to ECR, the job succeeds but the image isn't in ECR. I am using the ECR Credentials Helper to assume a role that has permissions to the repository. The ecr-login.log that the credentials helper creates shows a successful login to ECR.  If I don't set the credentials helper up correctly the job fails as expected, so I'm confident the login and permissions are ok.

**Expected behavior**
I would expect the image to appear in my ECR repository.

**To Reproduce**
1. Setup ECR credentials helper: 
echo "{\"auths\":{}},\"credHelpers\":{\"$MY_ACCT_NUMBER.dkr.ecr.us-east-1.amazonaws.com\":\"ecr-login\"}}"  > /kaniko/.docker/config.json

Note: I have also tried with the simpler 	{"credsStore": "ecr-login"} config.json. Same behavior.

2. Run kaniko:
/kaniko/executor --context=$CI_PROJECT_DIR --dockerfile=$CI_PROJECT_DIR/Dockerfile --destination=$MY_ACCT_NUMBER.dkr.ecr.us-east-1.amazonaws.com/$MY_REPO:$CI_COMMIT_TAG

**Additional Information**
 **- Dockerfile** 
FROM scratch
COPY hello /
CMD ["/hello"]

 **- Build Context**
   A file called "hello"

 **- Kaniko Image (fully qualified with digest)**
 gcr.io/kaniko-project/executor:debug

**Log info:**

**Kaniko log:**
$ /kaniko/executor --context=$CI_PROJECT_DIR --dockerfile=$CI_PROJECT_DIR/Dockerfile --destination=$MY_ACCT_NUMBER.dkr.ecr.us-east-1.amazonaws.com/$MY_REPO:$CI_COMMIT_TAG
INFO[0003] Using dockerignore file: /redacted/.dockerignore 
INFO[0003] No base image, nothing to extract            
INFO[0003] Built cross stage deps: map[]                
INFO[0003] No base image, nothing to extract            
INFO[0003] Executing 0 build triggers                   
INFO[0003] Unpacking rootfs as cmd COPY hello / requires it. 
INFO[0003] COPY hello /                                 
INFO[0003] Taking snapshot of files...                  
INFO[0003] CMD ["/hello"]       

**/.ecr/log/ecr-login.log:**
time="2020-08-27T21:17:26Z" level=debug msg="Retrieving credentials" region=us-east-1 registry=108383104151 serverURL=108383104151.dkr.ecr.us-east-1.amazonaws.com
time="2020-08-27T21:17:26Z" level=debug msg="Checking file cache" registry=108383104151
time="2020-08-27T21:17:26Z" level=debug msg="Calling ECR.GetAuthorizationToken" registry=108383104151
time="2020-08-27T21:17:26Z" level=debug msg="Saving credentials to file cache" registry=108383104151
time="2020-08-27T21:17:32Z" level=debug msg="Retrieving credentials" region=us-east-1 registry=108383104151 serverURL=108383104151.dkr.ecr.us-east-1.amazonaws.com
time="2020-08-27T21:17:32Z" level=debug msg="Checking file cache" registry=108383104151
time="2020-08-27T21:17:32Z" level=debug msg="Calling ECR.GetAuthorizationToken" registry=108383104151
time="2020-08-27T21:17:32Z" level=debug msg="Saving credentials to file cache" registry=108383104151

**~/.aws/config**
[default]
region = us-east-1
role_arn = arn:aws:iam::redacted:role/redacted
credential_source = Ec2InstanceMetadata

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>No</li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>Yes</li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>Yes</li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>No</li></ul>|

**Comment by rcollette** [comment]
Is that the actual echo statement you are using?  If so you have not escaped the quotes and you have an extra brace after the auths property.

It should be
```bash
```

**Comment by sonofagunn** [comment]
Thanks for the reply. The actual echo statement is escaped, I'm not sure how I cut and paste something without them. I know the login is working correctly because I see the successful login messages. Also, I can change the account number (or remove the echo statement completely) and then the run will fail with an error message.

$ cat /kaniko/.docker/config.json
{"auths":{"registry.gitlab.com":{"username":"gitlab-ci-token","password":"[MASKED]"}},"credHelpers":{"MY_ACCT_NUMBER.dkr.ecr.us-east-1.amazonaws.com":"ecr-login"}}

**Comment by sonofagunn** [comment]
Closing this issue since I figured it out. In case someone in the future has the same problem:

It wasn't an issue with kaniko (woohoo!), but rather the AWS ECR web console silently failing to display images due to permissions. The web console just showed an empty repository rather than saying I didn't have permissions to view the images.
