### ISSUE TITLE
Specify an alternative path to .docker/config.json  e.g .dockercfg

### ISSUE THREAD

**Issue by akram** [GoogleContainerTools/kaniko#1407]
Hi kaniko team,

I am trying to use kaniko to push to openshift internal registry. By default, on OpenShift, push and pull secrets are automatically created but they are using the old .dockercfg filename.

Is there any way (I didn't find flag) to specify an alternate path to the default .docker/config.json ?

**Comment by akram** [comment]
partially answering myself: it seems that https://github.com/GoogleContainerTools/kaniko/pull/1238/files introduced a kind of a change. If one reads comments before the PR, we can see:
```
// DockerConfLocation returns the file system location of the Docker configuration	
// from the DOCKER_CONFIG environment variable.  If that variable is not set, it	
// returns "/kaniko/.docker/config.json".	

```

and then
```
// DockerConfLocation returns the file system location of the Docker
// configuration file under the directory set in the DOCKER_CONFIG environment
// variable.  If that variable is not set, it returns the OS-equivalent of
```

@ddgenome what do you think? would it more robust to allow the 2 behavior:
if DOCKER_CONFIG is not a directory, then consider its content as a filename
else if it is a directory, append config.json 

I will propose a PR for that.

**Comment by elatt** [comment]
Has this worked for folks (especially in the OpenShift environment)? I've been playing around with setting `DOCKER_CONFIG` to point to the `.dockercfg` secret that OpenShift creates by default but `kaniko` always seems to think that my setting for `DOCKER_CONFIG` is a director and thus appends `/config.json` to it.
