### ISSUE TITLE
multistage build error: failed to execute command: starting command: fork/exec /bin/sh: no such file or directory

### ISSUE THREAD

**Issue by Reme3180** [GoogleContainerTools/kaniko#1421]
**Actual behavior**
This is the Dockerfile for the debug image builder:(v0.22.0)

FROM reme3180/debian-arm64:9.12.0 AS build
WORKDIR /
RUN touch test.txt
FROM reme3180/debian-arm64:9.12.0
COPY --from=build /test.txt /root/
WORKDIR /
USER root
RUN ls

This Executor is a binary of my own ARM schema type
The build log is as follows：
[Build] [36mINFO[0m[0000] Resolved base name reme3180/debian-arm64:9.12.0 to build 
[Build] [36mINFO[0m[0000] Retrieving image manifest reme3180/debian-arm64:9.12.0 
[Build] [36mINFO[0m[0004] Retrieving image manifest reme3180/debian-arm64:9.12.0 
[Build] [36mINFO[0m[0011] Retrieving image manifest reme3180/debian-arm64:9.12.0 
[Build] [36mINFO[0m[0014] Retrieving image manifest reme3180/debian-arm64:9.12.0 
[Build] [36mINFO[0m[0019] Built cross stage deps: map[0:[/test.txt]]   
[Build] [36mINFO[0m[0019] Retrieving image manifest reme3180/debian-arm64:9.12.0 
[Build] [36mINFO[0m[0022] Retrieving image manifest reme3180/debian-arm64:9.12.0 
[Build] [36mINFO[0m[0028] Executing 0 build triggers                   
[Build] [36mINFO[0m[0028] Unpacking rootfs as cmd RUN touch test.txt requires it. 
[Build] [36mINFO[0m[0041] WORKDIR /                                    
[Build] [36mINFO[0m[0041] cmd: workdir                                 
[Build] [36mINFO[0m[0041] Changed working directory to /               
[Build] [36mINFO[0m[0041] RUN touch test.txt                           
[Build] [36mINFO[0m[0041] Taking snapshot of full filesystem...        
[Build] [36mINFO[0m[0042] Resolving 5773 paths                         
[Build] [36mINFO[0m[0042] cmd: /bin/sh                                 
[Build] [36mINFO[0m[0042] args: [-c touch test.txt]                    
[Build] [36mINFO[0m[0042] Running: [/bin/sh -c touch test.txt]         
[Build] [36mINFO[0m[0042] Taking snapshot of full filesystem...        
[Build] [36mINFO[0m[0043] Resolving 5774 paths                         
[Build] [36mINFO[0m[0043] Saving file test.txt for later use           
[Build] [36mINFO[0m[0043] Deleting filesystem...                       
[Build] [36mINFO[0m[0043] Retrieving image manifest reme3180/debian-arm64:9.12.0 
[Build] [36mINFO[0m[0046] Retrieving image manifest reme3180/debian-arm64:9.12.0 
[Build] [36mINFO[0m[0051] Executing 0 build triggers                   
[Build] [36mINFO[0m[0051] Unpacking rootfs as cmd COPY --from=build /test.txt /root/ requires it. 
[Build] [36mINFO[0m[0067] COPY --from=build /test.txt /root/           
[Build] [36mINFO[0m[0067] Resolving 1 paths                            
[Build] [36mINFO[0m[0067] Taking snapshot of files...                  
[Build] [36mINFO[0m[0067] WORKDIR /                                    
[Build] [36mINFO[0m[0067] cmd: workdir                                 
[Build] [36mINFO[0m[0067] Changed working directory to /               
[Build] [36mINFO[0m[0067] USER root                                    
[Build] [36mINFO[0m[0067] cmd: USER                                    
[Build] [36mINFO[0m[0067] RUN ls                                       
[Build] [36mINFO[0m[0067] Taking snapshot of full filesystem...        
[Build] [36mINFO[0m[0068] Resolving 5771 paths                         
[Build] [36mINFO[0m[0068] cmd: /bin/sh                                 
[Build] [36mINFO[0m[0068] args: [-c ls]                                
[Build] [36mINFO[0m[0068] util.Lookup returned: &{Uid:0 Gid:0 Username:root Name:root HomeDir:/root} 
[Build] [36mINFO[0m[0068] performing slow lookup of group ids for root 
[Build] [36mINFO[0m[0068] Running: [/bin/sh -c ls]                     
[Build] error building image: error building stage: failed to execute command: starting command: fork/exec /bin/sh: no such file or directory

I get the following error:
[Build] error building image: error building stage: failed to execute command: starting command: fork/exec /bin/sh: no such file or directory

But the docker build was successful，the log is:
Step 1/8 : FROM reme3180/debian-arm64:9.12.0 AS build
9.12.0: Pulling from reme3180/debian-arm64
Digest: sha256:06ffa6bb1bb972a500f9861ac7ed995e0e1c3d032babf1752d566f39582d30b4
Status: Downloaded newer image for reme3180/debian-arm64:9.12.0
 ---> 6be6a2ab621d
Step 2/8 : WORKDIR /
 ---> Running in e2b695269b1d
Removing intermediate container e2b695269b1d
 ---> 5598a7c99ab7
Step 3/8 : RUN touch test.txt
 ---> Running in 476032ecff9a
Removing intermediate container 476032ecff9a
 ---> 2d21e35c53da
Step 4/8 : FROM reme3180/debian-arm64:9.12.0
 ---> 6be6a2ab621d
Step 5/8 : COPY --from=build /test.txt /root/
 ---> 6f0616ee477d
Step 6/8 : WORKDIR /
 ---> Running in f33237e4f669
Removing intermediate container f33237e4f669
 ---> 28e520732877
Step 7/8 : USER root
 ---> Running in 83aac873a9e5
Removing intermediate container 83aac873a9e5
 ---> 7a4bc4c1404b
Step 8/8 : RUN ls
 ---> Running in 7aa98a3caf8a
bin
boot
dev
etc
home
lib
media
mnt
opt
proc
root
run
sbin
srv
sys
tmp
usr
var
Removing intermediate container 7aa98a3caf8a
 ---> e1d48a27f767
Successfully built e1d48a27f767
Successfully tagged test:latest

**Expected behavior**

**To Reproduce**
1. ...
2. ...

**Additional Information**
 - Dockerfile 
   Please provide either the Dockerfile you're trying to build or one that can reproduce this error.
 - Build Context
   Please provide or clearly describe any files needed to build the Dockerfile (ADD/COPY commands)
 - Kaniko Image (fully qualified with digest)
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ no] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [no ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [no ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ yes] </li></ul>|

**Comment by Reme3180** [comment]
I found not only /bin/sh not found, but also other programs

**Comment by Reme3180** [comment]
i found that the multistage dockerfile build  would delete the system after the execution of the first FROM, affecting the RUN instruction under the second FROM

**Comment by Reme3180** [comment]
I have solved the problem.
It's not Kaniko's problem.

**Comment by tal-zvon** [comment]
How did you solve this problem?

**Comment by cmoulliard** [comment]
I also run a multi-stages build and that fails for me
```time="2022-01-21T12:07:49Z" level=info msg="Running: [/bin/sh -c echo ${some_arg} > /opt/arg.txt]"
panic: error building stage: failed to execute command: starting command: fork/exec /bin/sh: no such file or directory
```
Questions:
- Is a multi-stages build supported by kaniko ?
- If the answer is yes, what should we do to configure kaniko and avoid the error `fork/exec /bin/sh: no such file or directory` ?

**Comment by elisw93** [comment]
I ran into this error when trying to build a Dockerfile inside kaniko with this sort of recipe: (paraphrased)
```dockerfile
# erroneously assuming /foo is a directory
COPY Makefile /foo
# now /foo is a normal file that contains a copy of the local Makefile

WORKDIR /foo
RUN make all
```

I hope this information may be useful to someone in the future, since this is currently the first Google result for this specific error message.
