### ISSUE TITLE
Building Dockerfile from debian:stretch fails

### ISSUE THREAD

**Issue by louiscpalma** [GoogleContainerTools/kaniko#1422]
**Actual behavior**
When running an `apt-get update && apt-get install` inside a Dockerfile using `debian:stretch` or `ubnutu:18.04`, kaniko fails with the following error: 

```
E: Problem executing scripts DPkg::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 100
```
Using same Dockerfile with `FROM debian:buster` or `FROM ubuntu:20.04` builds successfully.

**Expected behavior**
Kaniko should be able to build Debian 9 / Ubuntu 18.04 images without having `dpkg` errors on `apt-get install`

**To Reproduce**
1. Write basic dockerfile
2. Run kaniko to build image

**Additional Information**
Using `gcr.io/kaniko-project/executor:debug` image

```Dockerfile
FROM debian:stretch
RUN apt-get update \
  && apt-get install --no-install-recommends -y \
    curl \
    wget \
  && rm -rf /var/lib/apt/lists/*
```
This issue has come up before, but was resolved in very early kaniko versions. Did not expect there to be a difference between building Debian 9 vs Debian 10.

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [X] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by hamsterready** [comment]
I've seen this issue while working with gitlab-ci and running multiple `/kaniko/executor` commands one after another. Adding `--cleanup` as mentioned [here](https://gitlab.com/gitlab-org/gitlab/-/issues/216348#note_335197187) solved the problem.
