### ISSUE TITLE
[Question]: Why is the "not including whiteout files" step slow?

### ISSUE THREAD

**Issue by eysi09** [GoogleContainerTools/kaniko#1430]
Hi all!

First of all, thanks for a great project!

I noticed that my builds where taking more time then expected with Kaniko and as I was debugging this, I saw that after the `not including whiteout files` step, Kaniko "hangs" for about 35 seconds. Here's a bit more context:

```console
[2020-09-22T14:11:28Z] Not adding /dev because it is ignored
DEBU[2020-09-22T14:11:28Z] Not adding /etc/hostname because it is ignored
DEBU[2020-09-22T14:11:28Z] Not adding /etc/hosts because it is ignored
DEBU[2020-09-22T14:11:28Z] Not adding /etc/mtab because it is ignored
DEBU[2020-09-22T14:11:28Z] Not adding /proc because it is ignored
DEBU[2020-09-22T14:11:28Z] Not adding /sys because it is ignored
DEBU[2020-09-22T14:11:28Z] Not adding /var/run because it is ignored
DEBU[2020-09-22T14:11:31Z] Whiting out /etc/ssl/.wh.certs
DEBU[2020-09-22T14:11:31Z] not including whiteout files  <---- Here's where Kaniko "hangs" for 35 seconds
INFO[2020-09-22T14:12:06Z] ENV PORT=8080
INFO[2020-09-22T14:12:06Z] No files changed in this command, skipping snapshotting.
DEBU[2020-09-22T14:12:06Z] build: composite key for command ENV PORT=8080 &{[sha256:*** ENV PORT=8080]}
DEBU[2020-09-22T14:12:06Z] build: cache key for command ENV PORT=8080 ***
```

Any idea why this is the case? 

This is a large portion of the total time it takes Kaniko to fetch the cached layers, which is usually around 60 sec. In these cases, the number of cached layers are roughly 8 and half of them don't need snapshotting. 

This is roughly what my setup looks like:

* Running Kaniko on GCP and using GCR
* Fairly standard Dockerfile for a Node.js project with no multi-stage builds

And this is how I run Kaniko:

```
sh -c /kaniko/executor "--context" "dir:///***" "--dockerfile" "Dockerfile" "--destination" "eu.gcr.io/***" "--cache=true" "--log-timestamp" "--verbosity=debug" "--build-arg" "***";
```

Please let me know if you need any more details.

Thanks!

**Comment by tejal29** [comment]
thanks @eysi09 for the logs. 
Can you give is what is the size of your cache?
Looks like the line is coming from here, https://github.com/GoogleContainerTools/kaniko/blob/f20f495051627b988c7449e9b163a4f9f30cc044/pkg/util/fs_util.go#L156

Is it possible the cached layer is a huge layer and kaniko is spending time extracting it at L185?

Also, is this layer for run command or copy command?
In v1.2.0 we got rid of caching copy layers which should reduce the number of cached layers for an image.

**Comment by eysi09** [comment]
Hi @tejal29 and thank you for your reply!

Turns out I was on a dated version of Kaniko by accident and I'm not seeing this issue anymore. Apologies for the trouble.
