### ISSUE TITLE
Kaniko - The Environment is empty when set up it from --build-arg

### ISSUE THREAD

**Issue by 1ricardo** [GoogleContainerTools/kaniko#1434]
**Actual behavior**
When I start POD with the following setup:

```   
    Image:         gcr.io/kaniko-project/executor:latest
    Args:
      --verbosity=info
      --reproducible
      --dockerfile=/kaniko/Dockerfile
      --destination=my.ecr.com/test-repo:3.11.6
      --build-arg=VERSION=3.11.6
```

Kaniko will execute the following Dockerfile

```
    FROM alpine:$VERSION

    ENV VER $VERSION

    WORKDIR /src

    RUN echo $VERSION > log.test

    COPY . ./
```

This docker file is very trivial but it's enough for the explanation of the issue.
The problem is that the `--build-arg=VERSION=3.11.6` working fine only for the first line

so it will change it to the expected behavior, from
```
FROM alpine:$VERSION 
```
to 

```
 FROM alpine:3.11.6
```
but `ENV` and `RUN` show only empty string, like the `$VERSION` was not set before

```
$env
...
HOME=/root
VER=
PWD=/src
...
```
```
/src # cat log.test 

/src #
```

I tried many different way to find solutions, for example: setup `ARG` from `--build-arg` and then ENV, or use different way of arg definition `${VERSION}, "$VERSION" , "${VERSION}"`, but it never worked.

**Expected behavior**
I would like to setup ENV variable from `--build-arg`, so at the end the ENV looks like this `VER=3.11.6`

**To Reproduce**
Please use my dockerfile, which is enough to make a test
1. Dockerfile
```

    FROM alpine:$VERSION

    ENV VER $VERSION

    WORKDIR /src

    RUN echo $VERSION > log.test

    COPY . ./
```
2. also you need to add build-arg to your configuration
```
--build-arg=VERSION=3.11.6
```

Thank you in advance for any TIP, if I'm doing something wrong

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by 1ricardo** [comment]
That was my mistake, I should read carefully the Docker Documentation

**Comment by trallnag** [comment]
For me this works on debug 1.3.0, where `TEST_VAR`` is passed in via `--build-arg TEST_VAR=$TEST_VAR`

```
FROM alpine:3.13.1
ENV TEST_VAR=${TEST_VAR}
RUN set -u && echo ${TEST_VAR}
```
