### ISSUE TITLE
Allow building without pushing

### ISSUE THREAD

**Issue by mikebryant** [GoogleContainerTools/kaniko#144]
# Context
When using tooling like Gitlab-CI, we want to be able to run the build process pre-merge, in order to validate changes

# Problem
kaniko doesn't appear to allow you to run just the build without also needing credentials to push to a registry. 

# Solution
Allow for just the build process to run, without specifying a destination to push to.

**Comment by mikebryant** [comment]
```
m@hotppc17686:~/tmp/kaniko$ cat Dockerfile 
FROM library/busybox:latest
m@hotppc17686:~/tmp/kaniko$ docker run -it --rm -v ${PWD}:/workspace gcr.io/kaniko-project/executor:latest
INFO[0000] Unpacking filesystem of library/busybox:latest... 
INFO[0000] Whitelisted directories are [/kaniko /proc /dev /dev/pts /sys /sys/fs/cgroup /sys/fs/cgroup/systemd /sys/fs/cgroup/rdma /sys/fs/cgroup/net_cls,net_prio /sys/fs/cgroup/freezer /sys/fs/cgroup/memory /sys/fs/cgroup/cpu,cpuacct /sys/fs/cgroup/devices /sys/fs/cgroup/cpuset /sys/fs/cgroup/perf_event /sys/fs/cgroup/blkio /sys/fs/cgroup/hugetlb /sys/fs/cgroup/pids /dev/mqueue /workspace /etc/resolv.conf /etc/hostname /etc/hosts /dev/shm /dev/console /proc/asound /proc/bus /proc/fs /proc/irq /proc/sys /proc/sysrq-trigger /proc/kcore /proc/timer_list /proc/sched_debug /sys/firmware] 
INFO[0004] Initializing source image library/busybox:latest 
ERRO[0010] invalid reference format                     
m@hotppc17686:~/tmp/kaniko$ docker build .
Sending build context to Docker daemon 2.048 kB
Step 1/1 : FROM library/busybox:latest
 ---> 5b0d59026729
Successfully built 5b0d59026729
m@hotppc17686:~/tmp/kaniko$ 
```

**Comment by dlorenc** [comment]
This basically just drops the image after it's been built, as a way to validate the build "succeeds"?

**Comment by mikebryant** [comment]
@dlorenc yup. It validates that the Dockerfile syntax is correct and so on, prior to merge.

**Comment by mikebryant** [comment]
Alternatively if the build and push steps were separate that would be great too

**Comment by dlorenc** [comment]
We'll tackle this by adding a flag to output a tarball on disk, which is useful for other cases as well.

**Comment by dlorenc** [comment]
This should be fixed now. You can run with a --tar-path=/dev/null and it will skip the push.

**Comment by abdennour** [comment]
thank you @smrutimandal ! you saved my month

**Comment by DavidAntliff** [comment]
Unfortunately the `--no-push` option also disables caching, causing kaniko to rebuild the entire image from scratch.

On the other hand, with the `--tar-path` option (which is now `--tarPath`), kaniko still makes use of the cache, so that may be more useful in some cases.
