### ISSUE TITLE
Debug image of `v1.1.0` does not exist

### ISSUE THREAD

**Issue by aytekinar** [GoogleContainerTools/kaniko#1443]
**Actual behavior**

`debug-v1.1.0` does not seem to exist.

**Expected behavior**

It should exist as per the [release notes](https://github.com/GoogleContainerTools/kaniko/releases/tag/v1.1.0).

**To Reproduce**

```fish
~> docker run --rm -it gcr.io/kaniko-project/executor:debug-v1.1.0
Unable to find image 'gcr.io/kaniko-project/executor:debug-v1.1.0' locally
docker: Error response from daemon: manifest for gcr.io/kaniko-project/executor:debug-v1.1.0 not found: manifest unknown: Failed to fetch "debug-v1.1.0" from request "/v2/kaniko-project/executor/manifests/debug-v1.1.0".
See 'docker run --help'.
```

**Additional Information**
 
N/A.
 
 **Triage Notes for the Maintainers**

N/A.

**Comment by tejal29** [comment]
Sorry about that. I will publish it.

**Comment by tejal29** [comment]
The debug image
```
gcr.io/kaniko-project/executor:debug-v1.1.0
gcr.io/kaniko-project/warmer:v1.1.0
```

**Comment by aytekinar** [comment]
Thank you. Now, I can pull it. Closing the issue...
