### ISSUE TITLE
debug-* tags don't follow semantic version

### ISSUE THREAD

**Issue by dmaciel** [GoogleContainerTools/kaniko#1448]
I'm working on a tool to check for update on containers and for parsing versions I'm using this library https://github.com/hashicorp/go-version 

The debug-* images don't follow semver and the library is not able to process them, will it be possible to switch the "debug" string at the end? so instead of debug-v1.2.0 we can have v1.2.0-debug (or v1.2.0+debug if we use it as [metadata](https://semver.org/#spec-item-10)). Technically the 'v' in the front is not semver compliant neither, but at least the library is able to handle that case.

There is not need to delete the "debug-*" tag, but having "*-debug" or "*+debug" will be helpful for scripting

**Comment by tejal29** [comment]
sure. we can provide that. 
You could easily do that by making a change to this cloudbuild.yaml to create another tag
https://github.com/GoogleContainerTools/kaniko/blob/master/deploy/cloudbuild-release.yaml#L24

**Comment by sladyn98** [comment]
@tejal29 @dmaciel Would love to send in a PR for this.

```
 name: "gcr.io/cloud-builders/docker"
    args: ["tag", "gcr.io/kaniko-project/warmer:$TAG_NAME", 
           "gcr.io/kaniko-project/warmer:latest"]
```

What new tags would I need to add here ?

**Comment by tejal29** [comment]
The warmer image is fine i guess. 
you will have to do the following for the debug image.
you will have to make this change in 2 files. `couldbuild-release.yaml` and `cloudbuild.yaml`
```
  - name: "gcr.io/cloud-builders/docker"
    args: ["tag", "gcr.io/kaniko-project/executor:debug-$TAG_NAME", 
           "gcr.io/kaniko-project/executor:$TAG_NAME-debug"]

```

**Comment by tejal29** [comment]
Oh and in the images 
```
images: ["gcr.io/kaniko-project/executor:$TAG_NAME",
         "gcr.io/kaniko-project/executor:latest",
         "gcr.io/kaniko-project/executor:debug-$TAG_NAME",
         "gcr.io/kaniko-project/executor:debug",
         "gcr.io/kaniko-project/warmer:$TAG_NAME",
         "gcr.io/kaniko-project/warmer:latest"]
```
Add the newly tagged  `gcr.io/kaniko-project/executor:$TAG_NAME-debug`

**Comment by sladyn98** [comment]
Sounds good :+1:

**Comment by sladyn98** [comment]
I created a PR for this @tejal29 . Thanks for the help
