### ISSUE TITLE
Logo Proposal Kaniko

### ISSUE THREAD

**Issue by ggcarlosr** [GoogleContainerTools/kaniko#146]
**# I hope you like my logo proposal for this interesting tool**

![kaniko](https://user-images.githubusercontent.com/37964430/39259759-4d2607a0-4885-11e8-82b4-a45e1a8ee3b4.png)

**Comment by priyawadhwa** [comment]
Thank you, this looks great! Would you be able to submit this as a pull request? You could create a `logo` directory and put it in there :)

**Comment by ggcarlosr** [comment]
ok I will try to do it, although I have not done it for the first time.

**Comment by priyawadhwa** [comment]
Great, let me know if you have any questions!

**Comment by ggcarlosr** [comment]
it would be easier for me to pass a link in google drive with the editable logo files and you would add my proposal to your project

**Comment by priyawadhwa** [comment]
so unfortunately you'll need to sign a CLA for us to be able to use your awesome logo, which means you need to submit a pull request

where are you having difficulty?

**Comment by ggcarlosr** [comment]
in carrying out each step of the extraction request.

**Comment by priyawadhwa** [comment]
This [guide](https://gist.github.com/Chaser324/ce0505fbed06b947d962) may be helpful. It looks like you've already created a [fork](https://github.com/ggcarlosr/kaniko) of the project, so you just need to follow the steps in the guide. After you complete the `Create a Branch` step, you can create a logo folder in the project, put the same image above in it, and submit it as a pull request (as described in later steps in the guide)

**Comment by ggcarlosr** [comment]
Already make the extraction request that resolutions will need the logo for the project.

**Comment by ggcarlosr** [comment]
list the pull request please confirm that it has been done correctly

**Comment by ggcarlosr** [comment]
hey men I get my Pull request? was done correctly? missing something you need?

**Comment by priyawadhwa** [comment]
It looks great, we just merged the pull request so I'll close this issue. Thank you so much!
