### ISSUE TITLE
Build context via HTTP(S)

### ISSUE THREAD

**Issue by thannaske** [GoogleContainerTools/kaniko#1464]
Currently it's possible to provide the build context via a HTTP(S) link to an Azure Blob Storage URL. However it seems to check whether the provided URL matches a specific format that is suitable for Azure, only. Is there a reason why kaniko doesn't support the download of the build context .tar.gz via HTTP(s) no matter where it comes from?

Before I start working on a pull request that implements this behavior I wanted to ask if there is any particular reason for this restriction.

**Comment by jfrabaute** [comment]
Hi,

I had the same problem and I just send a PR to allow getting the tar.gz from any https repo: https://github.com/GoogleContainerTools/kaniko/pull/1519

Would that help?

Thanks.
