### ISSUE TITLE
error checking push permissions

### ISSUE THREAD

**Issue by lyj8330328** [GoogleContainerTools/kaniko#1467]
**Actual behavior**

error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "xxxxxxxxxx/xxxxxx/new-test-2:v1.2": creating push check transport for xxxxxxx.com failed: Get "https://xxxxxxxxxxxxxxx/v2/": dial tcp 10.82.128.17:443: connect: no route to host

**Expected behavior**

**To Reproduce**
1. ...
2. ...

**Additional Information**
 - Dockerfile 
   Please provide either the Dockerfile you're trying to build or one that can reproduce this error.
 - Build Context
   Please provide or clearly describe any files needed to build the Dockerfile (ADD/COPY commands)
 - Kaniko Image (fully qualified with digest)
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by kumprj** [comment]
What are you trying to authenticate and how are you trying to authenticate? in #1291 you can see how I authenticate with JFrog.

**Comment by aaron-prindle** [comment]
Closing this for now as the description doesn't have enough info on how auth was attempted, feel free to add more context and we can re-open here.  Thanks
