### ISSUE TITLE
error building image: error building stage: failed to get filesystem from image: mkdir /usr/share/file/magic: not a directory

### ISSUE THREAD

**Issue by Anugushashank** [GoogleContainerTools/kaniko#1469]
**Actual behavior**
When kaniko executor is run as a binary from another image, it fails with error
`error building image: error building stage: failed to get filesystem from image: mkdir /usr/share/file/magic: not a directory`

This issue occurs only when there is a difference in filesystem of container image and the base image of the dockerfile. Ex: /usr/share/file/magic is a directory in the base image whereas it a file in container filesystem.

Why is this happening:
While building a stage, FS is extracted in each layer from tar and gets created on the container except for the mounted directories. While extracting the FS, if there is a dir(/usr/share/file/magic) which needs to be created on the container, and there is already a file(/usr/share/file/magic) with same path on the container then an error(`not a directory`) is thrown

**Expected behavior**
Kaniko executor should not fail while creating a dir if there is already a file with the same path. 

There should be a check [here](https://github.com/GoogleContainerTools/kaniko/blob/master/pkg/util/fs_util.go#L752), if there exists a file with the dir path then it should be deleted before proceeding with the dir creation

**To Reproduce**
1. Build this dockerfile using docker and tag it as container_image, `docker build -t container_image .`
```
FROM gcr.io/kaniko-project/executor:debug as kanikoImage

FROM amazoncorretto:11

COPY --from=kanikoImage /kaniko/executor /kaniko/executor
```
2. Build below docker file using kaniko executor from above created image, `docker run -v {dockerfile_location}:/workspace container_image /kaniko/executor --dockerfile /workspace/Dockerfile --no-push --verbosity=trace`

```
FROM python:3.7.6

RUN apt-get update && \
    apt-get install -y virtualenv git default-mysql-client
```
3. Above build fails with error `error building image: error building stage: failed to get filesystem from image: mkdir /usr/share/file/magic: not a directory`

**Additional Information**
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by defaultcute12** [comment]
Hi, is this issue fixed?

**Comment by anugu-chegg** [comment]
@defaultcute12 Yes. This is released as part of https://github.com/GoogleContainerTools/kaniko/releases/tag/v1.5.0

**Comment by vl-shopback** [comment]
we got the same issue on Kaniko version :  v1.8.1 + amazoncorretto:17

**Comment by gulldan** [comment]
we got the same issue on Kaniko version : v1.9.2 + nvcr.io/nvidia/deepstream:6.2-devel

**Comment by sherman-yang** [comment]
get the same issue with Kaniko:v1.9.1

**Comment by Aishwarya-Lad** [comment]
Has this been fixed? I am getting the same issue with Kaniko:v1.8.0.
