### ISSUE TITLE
if registry mirror does not have it, can you default it to index.docker.io

### ISSUE THREAD

**Issue by darewreck54** [GoogleContainerTools/kaniko#1473]
This is more of a question.  Right now Kaniko allows you to specify a registry mirror --registry-mirror.  Is it possible to have it look at the registry mirror first and if it's not there than pull from the default `index.docker.io`.  In other words, support multiple registry mirrors.

The main desire for this is that dockerhub is limiting API calls to 100 per 6 hours.  We wanted to utilize google's mirror container registry.  However, if it does not contain the image kaniko will fail.  Google doesn't copy the image to the mirror right away and it will remove unused mirrors if it's not referenced

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by sean-ersw** [comment]
Yes Kaniko has what (I would consider) breaking behaviour compared to Docker!!

- Docker daemon will try the mirror first and then revert to docker hub if its not cached in the mirror.
- Kaniko will just fail to pull from mirror.gcr.io and fail

With this odd re-interpretation of `registry-mirror` then we have many builds that fail after switching to Kaniko and instead I need start scripting efforts to get around it.

Given the increased usage of mirrors (and in all other tools I am aware of it, registry mirror is a pull through like Docker daemon) I would like to see this as the top priority for a fix!

**Comment by angelsantillana94** [comment]
I have the same problem. I need multiples registry mirrors or at least, when my private registry is not available, the execution of kaniko can continue and does not fail.

**Comment by vbehar** [comment]
there is a PR ready at #1498 which is just waiting for review... if you really need it, you can build it locally and push it to your own registry. We've been using it for all our builds and it works nicely.

**Comment by angelsantillana94** [comment]
I really appreciate your PR. Although the option you are telling me helps me, I prefer to wait for it to be reviewed and officially implemented.
