### ISSUE TITLE
Provide debug images for arm64

### ISSUE THREAD

**Issue by effitient** [GoogleContainerTools/kaniko#1488]
Currently you are providing debug images for amd64 and non-debug images for arm64 and other architectures. The arm64 images are not suitable for Gitlab pipelines utilizing the gitlab-runner as the [Gitlab Documentation](https://docs.gitlab.com/13.5/ee/ci/docker/using_kaniko.html) states:

> The kaniko debug image is recommended (gcr.io/kaniko-project/executor:debug) because it has a shell, and a shell is required for an image to be used with GitLab CI/CD.

My workaround is creating a suitable image myself based on the official executor:arm64 image by adding the busybox binaries and updating the PATH:

```
FROM gcr.io/kaniko-project/executor:arm64-v1.3.0

COPY --from=arm64v8/busybox:1.32.0 /bin /busybox
# Declare /busybox as a volume to get it automatically in the path to ignore
VOLUME /busybox
ENV PATH /usr/local/bin:/kaniko:/busybox
```

**Acceptance Criteria:**
- Provide the debug image also for other architectures than amd64

**Comment by morganchristiansson** [comment]
I just tried it and both 1.6.0 and 1.5.2 debug images run on arm64

**Comment by sharon-codefresh** [comment]
@effitient Looks like v1.6.0 supports arm64 out-of-box, can we mark this item as closed?

**Comment by effitient** [comment]
@sharon-codefresh Can be closed, yes.
