### ISSUE TITLE
How can I pass the secret to Image with Kaniko?

### ISSUE THREAD

**Issue by Zlob** [GoogleContainerTools/kaniko#1505]
Hi all!

I'm trying to build an image inside the Gitlab CI process with Kaniko.
The problem is that during the building process I need an access to the private Gitlab repository.
With `docker:stable-dind` I could easily pass the secret 
```yaml
   - docker build
      ...
      --secret id=gitconfig,src=$HOME/.gitconfig
      ...
```
and then just mount it inside the Dockerfile
```
RUN --mount=type=secret,id=gitconfig,dst=/root/.gitconfig --mount=type=ssh composer install
```

How can I achieve the same behavior with Kaniko?

**Comment by LaurentTrk** [comment]
Hi @Zlob 
I am looking for a similar feature.
As explained in the #489, the `/kaniko` folder is accessible during the image build. We should be able to use it to store and use secrets...

**Comment by Zlob** [comment]
Thanks @LaurentTrk 
But I still don't get it.
For instance, I put my gitlab token into the file and put it into the  `/kaniko` folder. How can I use it without leaving a trace in docker image?

**Comment by LaurentTrk** [comment]
Well, you need to find a way to use the token in `/kaniko/my_secret_gitlab.token` in your image build without copying it outside the `/kaniko` folder.
I don't know `composer`, but let's say you have an option to set gitlab token to use when using the command, you could do :
```bash
composer --gitlab-token=/kaniko/my_secret_gitlab.token install

# Or maybe an environment variable should do the trick
GITLAB_TOKEN_PATH=/kaniko/my_secret_gitlab.token composer install

# Or maybe a symbolic link
ln -sf  /kaniko/my_secret_gitlab.token ~/.gitlab.token && composer install
```

I didn't check the last option, maybe the link is kept during the image built...
But I used the 2nd option with success when trying to install private python packages with pip.

The  `/kaniko` folder is not added to the image, but is accessible when building.

**Comment by Zlob** [comment]
@LaurentTrk thanks a lot, you've really saved my day.

At the end, I just put my git config into `/kaniko/git/config` file in gitlab CI and than used it in docker file with 
`ARG XDG_CONFIG_HOME="/kaniko"`

Hope it will help others too.

**Comment by rajendar38** [comment]
> @LaurentTrk thanks a lot, you've really saved my day.
> 
> At the end, I just put my git config into `/kaniko/git/config` file in gitlab CI and than used it in docker file with `ARG XDG_CONFIG_HOME="/kaniko"`
> 
> Hope it will help others too.
Any reference to docker file and kaniko-pod.yaml is very helpfull
https://github.com/GoogleContainerTools/kaniko/issues/1850
Actually I am unable mount secrets
