### ISSUE TITLE
How can I disable the Amazon ECR plugin?

### ISSUE THREAD

**Issue by JackGzj** [GoogleContainerTools/kaniko#1512]
When I am using kaniko with tekton to build my image, I find kaniko trying to communicate with Amazon ECR（When I don't set the AWS_S3_USE_ARN_REGION env value）：
```
2020-12-02 16:17:23 ~/test k logs test-ph96g-pod-scjvf step-build-and-push
E1202 08:16:34.449739      22 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
    For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```
Now I am setting an non-exist value "no" for env-value AWS_S3_USE_ARN_REGION to avoid kaniko visiting Amazon ECR.
And part of my ClusterTask yaml is:
```
  - name: build-and-push
    workingDir: $(workspaces.source.path)
    image: $(params.BUILDER_IMAGE)
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    - name: AWS_S3_USE_ARN_REGION
      value: "no"
    command:
        ......
```
I wound like to know if it's any graceful way to do that. Thank you.

**Comment by ChuckNoxis** [comment]
I'm also interested in this.
I'm using Kaniko in Gitlab K8s runners, when I do my build with kaniko, it displays this error but the build an upload to gitlab's registry seems to work fine :
`E1105 15:42:29.623597      82 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.`
As I don't use AWS, I would like to disable this error/warning.

**Comment by xkfen** [comment]
Spec: batchv1.JobSpec{
	Template: coreV1.PodTemplateSpec{
		Spec: coreV1.PodSpec{
			Containers: []coreV1.Container{
				{
					Name:  name,
					Image: image,
					Args:  args,
					Ports: nil,
					Env: []coreV1.EnvVar{ 
						/**
						ignore logs:while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
							For verbose messaging see aws.Config.CredentialsChainVerboseErrors
						https://github.com/GoogleContainerTools/kaniko/issues/1512#issuecomment-972840975
						*/
						{
							Name:  "AWS_S3_USE_ARN_REGION",
							Value: "false",
						},
						{
							Name:  "AWS_ACCESS_KEY_ID",
							Value: "none",
						},
						{
							Name:  "AWS_SECRET_ACCESS_KEY",
							Value: "none",
						},
						{
							Name:  "AWS_ACCAWS_SESSION_TOKENESS_KEY_ID",
							Value: "none",
						},
					},
					VolumeMounts: volumeMounts,
				},
			},
			RestartPolicy: restartPolicy,
			Volumes:       nil,
		},
