### ISSUE TITLE
[Feature Request] Add Support for Public ECR Gallery

### ISSUE THREAD

**Issue by PatrickXYS** [GoogleContainerTools/kaniko#1515]
Given we have launched [Public ECR registry](https://aws.amazon.com/blogs/aws/new-amazon-ec2-g4ad-instances-featuring-amd-gpus-for-graphics-workloads/?nc1=b_nrp) last week, we should expect feature-requests fron ECR users for using Kaniko with Public ECR Authentication.

So the whole story will be:

Add support in amazon-ecr-credential-helper -> amazon-ecr-credential-helper cut new release -> Send PR to kaniko and make sure we build latest image of amazon-ecr-credential-helper into our executor image.

Related issue: https://github.com/awslabs/amazon-ecr-credential-helper/issues/248

/cc @tejal29 @priyawadhwa 

Any insights will be appreciated!

**Comment by andreyvelich** [comment]
We would highly appreciate if we push this forward once `amazon-ecr-credential-helper` changes are done.
I assume that `Dockerfile` is using [the latest package](https://github.com/GoogleContainerTools/kaniko/blob/master/deploy/Dockerfile#L24) for the `docker-credential-ecr-login`, so we don't need to modify Kaniko codebase after new release for the `amazon-ecr-credential-helper`.

Just to be aware, do we have any approximate timelines when Kaniko folks are planning to make the new release ?

/cc @gaocegege @johnugeorge

**Comment by PatrickXYS** [comment]
We have PR for fixing awslabs/amazon-ecr-credential-helper#248

https://github.com/awslabs/amazon-ecr-credential-helper/pull/253

So next step should be collaborating with Kaniko folks for embedding latest ECR Credential Helper and cut new release.

**Comment by andreyvelich** [comment]
Thank you @PatrickXYS!
Should we wait until this PR: https://github.com/awslabs/amazon-ecr-credential-helper/pull/253 will be merged ?

**Comment by PatrickXYS** [comment]
> Thank you @PatrickXYS!
> Should we wait until this PR: [awslabs/amazon-ecr-credential-helper#253](https://github.com/awslabs/amazon-ecr-credential-helper/pull/253) will be merged ?

Right, as long as the PR merged, we issue another PR in kaniko repo, and get it shipped.

**Comment by theofpa** [comment]
awslabs/amazon-ecr-credential-helper#253 has been merged and included in the latest [0.50](https://github.com/awslabs/amazon-ecr-credential-helper/releases/tag/v0.5.0) release. The next kaniko release will include it as it will be fetched during the [docker build](https://github.com/GoogleContainerTools/kaniko/blob/09cac63b7b811dff3e0422e6c50cd0cc59e210df/deploy/Dockerfile#L39), I don't think we need a PR for that.
```
% go get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login
go: downloading github.com/awslabs/amazon-ecr-credential-helper/ecr-login v0.0.0-20210211190242-b19192b6522b
go: downloading github.com/awslabs/amazon-ecr-credential-helper v0.5.0
...
```

**Comment by PatrickXYS** [comment]
@theofpa Thanks for confirmation! How is it going with Kaniko folk's release cadence?

**Comment by snooyen** [comment]
Has this been included in kaniko v1.5.0-debug or is this slated for the next release?

**Comment by theofpa** [comment]
> Has this been included in kaniko v1.5.0-debug or is this slated for the next release?

yes!

```
% docker run -it --entrypoint=/kaniko/docker-credential-ecr-login gcr.io/kaniko-project/executor:debug version
0.6.3
```

@PatrickXYS this issue can be closed as @tejal29 silently pushed v1.5.0 last week!

**Comment by PatrickXYS** [comment]
Yeah very nice, we can close the issue as of now

/close

**Comment by snooyen** [comment]
Seems I'm still unable to use a public.ecr.aws/<registry_alias>/<image>:<tag> as a build destination when running Kaniko on an EKS worker node.

The kaniko container gets this docker-config mounted at runtime 
```yaml
  docker-config.yml: |
    {
        "credHelpers": {
            "public.ecr.aws": "ecr-login",
            "287908807331.dkr.ecr.us-east-2.amazonaws.com": "ecr-login"
        }
    }
```
The worker node has the `AmazonElasticContainerRegistryPublicPowerUser` policy attached to its instance role.
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ecr-public:GetAuthorizationToken",
                "sts:GetServiceBearerToken",
                "ecr-public:BatchCheckLayerAvailability",
                "ecr-public:GetRepositoryPolicy",
                "ecr-public:DescribeRepositories",
                "ecr-public:DescribeRegistries",
                "ecr-public:DescribeImages",
                "ecr-public:DescribeImageTags",
                "ecr-public:GetRepositoryCatalogData",
                "ecr-public:GetRegistryCatalogData",
                "ecr-public:InitiateLayerUpload",
                "ecr-public:UploadLayerPart",
                "ecr-public:CompleteLayerUpload",
                "ecr-public:PutImage"
            ],
            "Resource": "*"
        }
    ]
}
```
