### ISSUE TITLE
When --tarPath option is used, image is not uploaded to the registry

### ISSUE THREAD

**Issue by polasekr** [GoogleContainerTools/kaniko#1544]
**Actual behavior**
I want to create a tar of the containeras the part of the build pipeline as well as upload the image to the docker registry. I want this to happen within a single step of build pipeline, where a single kaniko command creates both. Kaniko documentation suggests that unless --no-push switch is specified, this should work. I am using following command line switches:
```
/kaniko/executor --cache=false --cache-dir=/workspace --context=/workspace/source --dockerfile=Dockerfile-php \
   --destination=${DOCKER_REGISTRY}/${DOCKER_REGISTRY_ORG}/${APP_NAME}-php:$VERSION --verbosity=info \
   --tarPath /workspace/php.tar
```
The actual behaviour is that only tar image is created, but image is not uploaded to the registry If the switch --tarPath is removed, image is uploaded to the registry.
 
**Expected behavior**
I expect that tar archive of the image to be created as well as the image is uploaded to the registry

**To Reproduce**
1) run kaniko with switch --tarPath specified usinf any Dockerfile specification
```
/kaniko/executor --cache=false --cache-dir=/workspace --context=/workspace/source --dockerfile=Dockerfile-php \
   --destination=${DOCKER_REGISTRY}/${DOCKER_REGISTRY_ORG}/${APP_NAME}-php:$VERSION --verbosity=info \
   --tarPath /workspace/php.tar
```
2) verify that tar file is created 
3) check whether image has been uploaded to the specified registry

**Additional Information**
 - Dockerfile 
   Please provide either the Dockerfile you're trying to build or one that can reproduce this error.
 - Build Context
   Please provide or clearly describe any files needed to build the Dockerfile (ADD/COPY commands)
 - Kaniko Image (fully qualified with digest)
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by stevehipwell** [comment]
Any news on this issue as it's just caught us out?

**Comment by stevehipwell** [comment]
@tejal29 is this something which could be looked into?

**Comment by stevehipwell** [comment]
>We ran into the same issue when we tested kaniko on our Gitlab Runner. We wanted to export the image as a tarball to scan it later for vulnerabilities - but also upload it to our registry. 

@larsgroeber same here.
