### ISSUE TITLE
k8s_test.go:39: getwd: no such file or directory

### ISSUE THREAD

**Issue by Bean900** [GoogleContainerTools/kaniko#1545]
Hey :)
I'm trying to run Kaniko's integration tests to actively support this project in developing new features. Unfortunately, I cannot pass the k8s_test when running the integration tests locally. I tried running it on Arch 5.4 and another machine with a newly installed Ubuntu 20.04. In both cases the following error appears:
```
=== RUN   TestK8s
    k8s_test.go:39: getwd: no such file or directory
--- FAIL: TestK8s (0.00s)
FAIL
FAIL    github.com/GoogleContainerTools/kaniko/integration      1201.511s
FAIL
make: *** [Makefile:70: integration-test] Fehler 1
```
[log-snipped.log](https://github.com/GoogleContainerTools/kaniko/files/5797694/log-snipped.log)
Maybe someone knows a solution. Otherwise I can publish more information about my setup.

Thanks in advance for your help :)

**Comment by aaron-prindle** [comment]
@Bean900 were you able to resolve this issue?  Happy to try to help here, from the logs it seems it is failing here:
https://github.com/GoogleContainerTools/kaniko/blob/main/integration/k8s_test.go#L37-L39

Not sure exactly what error path it was hitting, my naive guess is that the path at PWD did not exist in the filesystem

**Comment by Bean900** [comment]
hey @aaron-prindle,
thanks for your response :) unfortunately i couldn't resolve this issue . In addition, I no longer have the test setup described to reproduce the error again. However, if you give me some time, I can try to set up the environment again. It might even work then.

**Comment by aaron-prindle** [comment]
@Bean900 that would be great if you would be willing to setup the test environment again and report back.  Thanks!

**Comment by Bean900** [comment]
I don't know what I did differently, but now it seems to work :) thank you in any case and maybe until the next pull request
