### ISSUE TITLE
Would it be possible to tag a new release soon?

### ISSUE THREAD

**Issue by MrMage** [GoogleContainerTools/kaniko#1554]
I am using kaniko on Google Cloud Build and would be interested in using functionality such as `--cache-copy-layers`. However, that flag is not available in one of the public releases yet.

Would it be possible to tag a new release with the latest changes soon and update the corresponding Cloud Build Builder?

**Comment by MrMage** [comment]
Also see #1481.

**Comment by erzz** [comment]
We all hate me too's - but really need a 1.4 debug image for better the better mirror handling

**Comment by MrMage** [comment]
Looks like the tags are available now.
