### ISSUE TITLE
gcr.io/kaniko-project/executor:debug-v1.4.0 not uploaded yet?

### ISSUE THREAD

**Issue by hochreitercorpuls** [GoogleContainerTools/kaniko#1563]
**Actual behavior**
I'd expect after last night's release that a pull of the new debug image would work.
`gcr.io/kaniko-project/executor:debug-v1.4.0` is unavailable though.

**Expected behavior**
The image being available.

**To Reproduce**
```bash
docker pull gcr.io/kaniko-project/executor:debug-v1.4.0
```

**Comment by khassel** [comment]
the images are still missing in the [google registry](https://console.cloud.google.com/gcr/images/kaniko-project/GLOBAL/executor?gcrImageListsize=30&gcrImageListquery=%255B%257B_22k_22_3A_22_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22v1.3_5C_22_22%257D_2C%257B_22k_22_3A_22_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22v1.4_5C_22_22%257D%255D&gcrImageListsort=-created%252C-uploaded)

**Comment by martint17r** [comment]
The 1.4.0 drop was not a github release but a git tag and the tag was not signed FWIW.

**Comment by NULLx76** [comment]
It _was_ a release initally as my e-mail notification shows:
![image](https://user-images.githubusercontent.com/1809198/106384469-4742c080-63cb-11eb-8424-4d3605cc55bc.png)

but it seems to have been removed.

**Comment by MrMage** [comment]
Still missing, it seems: https://console.cloud.google.com/gcr/images/kaniko-project/GLOBAL/executor?gcrImageListsize=30

**Comment by tejal29** [comment]
Sorry the release was busted

**Comment by MrMage** [comment]
@tejal29 what do you mean with busted? Will there be another release soon?

**Comment by tarvitz** [comment]
Noticed it too, once I've tried to use debug image both for amd64 and arm64 architectures :).

**Comment by bmarick** [comment]
The slim version in particular is the one I am interested in

**Comment by aytekinar** [comment]
So, neither `gcr.io/kaniko-project/executor:debug-v1.4.0` nor `gcr.io/kaniko-project/executor:debug-v1.5.0` is `docker pull`-able.

**Comment by hochreitercorpuls** [comment]
> 
> 
> So, neither `gcr.io/kaniko-project/executor:debug-v1.4.0` nor `gcr.io/kaniko-project/executor:debug-v1.5.0` is `docker pull`-able.

seems they changed their naming scheme. Try `gcr.io/kaniko-project/executor:v1.5.0-debug`
