### ISSUE TITLE
kaniko release v1.5.0 reports as v1.3.0

### ISSUE THREAD

**Issue by hochreitercorpuls** [GoogleContainerTools/kaniko#1583]
**Actual behavior**
Using the command `/kaniko/executor version` in a freshly pulled docker image (e.g. `gcr.io/kaniko-project/executor:v1.5.0-debug`) outputs 1.3.0

**Expected behavior**
I'd expect that the new release 1.5.0 will report as 1.5.0.

**To Reproduce**
- pull image
- run `/kaniko/executor version`

**Comment by aytekinar** [comment]
Is `gcr.io/kaniko-project/executor:debug-v1.5.0` or `gcr.io/kaniko-project/executor:v1.5.0-debug` even pullable?

**Comment by hochreitercorpuls** [comment]
> gcr.io/kaniko-project/executor:v1.5.0-debug

@aytekinar - yes the latter one [is available](https://console.cloud.google.com/gcr/images/kaniko-project/GLOBAL/executor@sha256:a0f4fc8cbd93a94ad5ab2148b44b80d26eb42611330b598d77f3f591f606379a/details?tab=info)

**Comment by aytekinar** [comment]
Apparently, there has been a (breaking) name change recently, like you mentioned in https://github.com/GoogleContainerTools/kaniko/issues/1563#issuecomment-781318500

**Comment by tejal29** [comment]
Sorry folks. i was testing the github flow and ended up not upgrading the version number.

**Comment by tejal29** [comment]
This is now fixed with v1.5.1.

**Comment by aytekinar** [comment]
@tejal29, your [release notes](gcr.io/kaniko-project/executor:debug-v1.5.1) do _not_ contain the correct address for the pushed image. It says `gcr.io/kaniko-project/executor:debug-v1.5.1` for the debug image, but it should have been `gcr.io/kaniko-project/executor:v1.5.1-debug`, perhaps?

Moving forward, which one is the correct naming?

**Comment by roock** [comment]
@priyawadhwa FYI the release notes for 1.5.2 also show the incorrect container tags for slim and debug.
Incorrect:
- gcr.io/kaniko-project/executor:debug-v1.5.2
- gcr.io/kaniko-project/executor:slim-v1.5.2

correct:
- gcr.io/kaniko-project/executor:v1.5.2-debug
- gcr.io/kaniko-project/executor:v1.5.2-slim

**Comment by priyawadhwa** [comment]
@roock thank you! I've updated the release notes :)
