### ISSUE TITLE
ADD with https in URL treated as file

### ISSUE THREAD

**Issue by balonik** [GoogleContainerTools/kaniko#1590]
**Actual behavior**

using `ADD` with `https` in URL is treated like file in context instead of URL.

```
error building image: error building stage: failed to get files used from context: failed to get fileinfo for /builds/images/alpine/https:/example.com/file.tar.gz: lstat /builds/images/alpine/https:/example.com/file.tar.gz: no such file or directory
```

**Expected behavior**

Using `http` in URL is working, `https` in URL should work the same way.

**To Reproduce**
1. Create Dockerfile

```
FROM alpine:latest

ADD https://example.com/file.tar.gz
```

2. try to build with kaniko

**Additional Information**
 - Kaniko Image (fully qualified with digest)

```
gcr.io/kaniko-project/executor@sha256:e00dfdd4a44097867c8ef671e5a7f3e31d94bd09406dbdfba8a13a63fc6b8060
```
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by michbeck100** [comment]
Any updates on this?

**Comment by michbeck100** [comment]
Would be great if anyone of the project owners could comment on this. I think this a major issue.

**Comment by jmhbnz** [comment]
Ran into the same problem while trying to migrate a codebase to kaniko today so this is definitely still an issue.

**Comment by anguswilliams** [comment]
I had a similar issue where adding a file from URL did not work for me. This is actually supported by kaniko, but the URL must be valid and accessible from where kaniko is running. Took me a while to find, but in my case the function below was burying an SSL validation error on the URL I was trying to add. Fixed by appending my custom CA to `/kaniko/ssl/certs/ca-certificates.crt` in the kaniko container.

https://github.com/GoogleContainerTools/kaniko/blob/cf9a334cb027e6bc6a35c94a3b120b34880750a9/pkg/util/command_util.go#L285

**Comment by aaron-prindle** [comment]
Thanks for flagging this, can anyone in the thread here clarify if the workaround/fix @anguswilliams mentioned worked for them as well?  Currently not clear if this is a kaniko bug requiring code change/fix or something that requires additional documentation.

**Comment by anguswilliams** [comment]
@aaron-prindle it's a valid error, but it could be logged better. I think it could do with some UX improvement as it's hard to tell what's actually going on if you hit the specific scenario. Two options I can think of:

1. Check the error return from [here](https://github.com/GoogleContainerTools/kaniko/blob/main/pkg/util/command_util.go#L298), and log the error
2. Get rid of that `http.Get` entirely as I'm not sure it's necessary, in that case any get errors would get surfaced [here](https://github.com/GoogleContainerTools/kaniko/blob/main/pkg/util/fs_util.go#LL607C25-L607C25) 

In my mind the second option is best, as it looks like that function is just trying to validate the source file is a URL or not. It's basically double handling that file. Happy to submit a PR to fix.

**Comment by aaron-prindle** [comment]
Ah I see, thank you for the additional context there @anguswilliams.  +1, I think the second option - that would be great if you could submit a PR with the fix!
