### ISSUE TITLE
then debug image naming issue

### ISSUE THREAD

**Issue by sherman-yang** [GoogleContainerTools/kaniko#1593]
**Actual behavior**
we use the Kaniko version as a parameter in our CI/DI, with every new Kaniko version, we just pass the v1.5.1 as a parameter. but don't know why suddenly changed the debug image name. so 
it should be gcr.io/kaniko-project/executor:**debug-v1.5.1**
but actually, the name is gcr.io/kaniko-project/executor:**v1.5.1-debug**.
this cause all our projects cannot find the image. we have about three hundred projects. it is painful to change all those names, and don't know when the name will change again in future.

**Expected behavior**
the new debug image should naming 
gcr.io/kaniko-project/executor:**debug-v1.5.1**

**To Reproduce**

**Additional Information**
 
 **Triage Notes for the Maintainers**

**Comment by sherman-yang** [comment]
it just a name, it can be anything. but since it changed, will need a lot of other code changes.

**Comment by stevehipwell** [comment]
Is this a permanent change or a bug/regression?

**Comment by aaron-prindle** [comment]
Sorry for the tag name change and the inconvenience there.  This is a permanent change and we currently have no plan on changing the name to the old syntax.  I am not aware of the initial reasons for the change but at this point I don't think it makes sense to switch the tag naming back.  Feel free to comment and I can re-open this if there is a strong desire for both tag names still
