### ISSUE TITLE
Can we put `context.ExcludesFile` before `os.Lstat` when copyDir?

### ISSUE THREAD

**Issue by keshin** [GoogleContainerTools/kaniko#1598]
Hi team,

We have a Jenkins job which runs two stages in parallel, 
1. stage A might delete some files under the folder defined in `.dockerignore`
2. stage B runs kaniko executor to build/push docker images with the `.dockerignore`

If a file under the ignore folder is deleted after 

https://github.com/GoogleContainerTools/kaniko/blob/eda57e5400e4cdecccb2a3d9db445e57e81a9c4f/pkg/util/fs_util.go#L591-L594

Then an error would be raise when calling `os.Lstat`, even the file is meant to be ignored.

https://github.com/GoogleContainerTools/kaniko/blob/eda57e5400e4cdecccb2a3d9db445e57e81a9c4f/pkg/util/fs_util.go#L597-L606

Questions:
1. May I know why we need to put `os.Lstat` before `context.ExcludesFile?`?
2. Is there a way that we can prevent such issue happens?

**Comment by jimmy-guzman** [comment]
Just sharing that we're seeing this behavior as well in our pipelines and we also came to the same conclusion.
