### ISSUE TITLE
When using "--no-push" and "--tarPath" error is thrown expecting "--destination" to be set.

### ISSUE THREAD

**Issue by GarrettGeorge** [GoogleContainerTools/kaniko#1613]
**Actual behavior**
Command run 
```
/kaniko/executor --dockerfile=Dockerfile --no-push --tarPath=image.tar \
  --context=dir:///workspace "${opt_args}" --verbosity=debug \
  >/workspace/builder.log 2>&1
```

Returns error in log:
```
error pushing image: must provide at least one destination when tarPath is specified
```

**Expected behavior**
Expect no push to attempt to be executed and `image.tar` to appear in `/workspace`.

**To Reproduce**
1. Run command with both `--tarPath` and `--no-push`

**Additional Information**
 - The issue is with the order of the `opts` checks for `opts.tarPath` and `opts.noPush`. Because it checks for `opts.tarPath` first it throws an error expecting `--destination` to be set, but I specifically don't want to push which is why I'm using `--no-push`. 
Presumably the `opts.noPush` conditional should be at the very top because why run any part of `DoPush` if `--no-push` is set. https://github.com/GoogleContainerTools/kaniko/blob/0477900febfacb98b88abdbfaf8bbaeb05f51060/pkg/executor/push.go#L229-L248
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/Np** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by TalZiv** [comment]
I am having the exact same issue, 👍🏻

**Comment by guyguy333** [comment]
Agree, having the same issue

**Comment by mitar** [comment]
I think it has to be set to `--destination=image`. See documentation here: https://github.com/GoogleContainerTools/kaniko#--tarpath

**Comment by HontoNoRoger** [comment]
This one is still an issue. While adding `--destination=image` actually helped, it is a bit confusing one has to use it.

**Comment by ChauhanKrunal** [comment]
> **Actual behavior** Command run
> 
> ```
> /kaniko/executor --dockerfile=Dockerfile --no-push --tarPath=image.tar \
>   --context=dir:///workspace "${opt_args}" --verbosity=debug \
>   >/workspace/builder.log 2>&1
> ```
> 
> Returns error in log:
> 
> ```
> error pushing image: must provide at least one destination when tarPath is specified
> ```
> 
> **Expected behavior** Expect no push to attempt to be executed and `image.tar` to appear in `/workspace`.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Run command with both `--tarPath` and `--no-push`
> 
> **Additional Information**
> 
> * The issue is with the order of the `opts` checks for `opts.tarPath` and `opts.noPush`. Because it checks for `opts.tarPath` first it throws an error expecting `--destination` to be set, but I specifically don't want to push which is why I'm using `--no-push`.
>   Presumably the `opts.noPush` conditional should be at the very top because why run any part of `DoPush` if `--no-push` is set. https://github.com/GoogleContainerTools/kaniko/blob/0477900febfacb98b88abdbfaf8bbaeb05f51060/pkg/executor/push.go#L229-L248
> 
> **Triage Notes for the Maintainers**
> 
> **Description**	**Yes/Np**
> Please check if this a new feature you are proposing	
> * [ ]
> 
> Please check if the build works in docker but not in kaniko	
> * [x]
> 
> Please check if this error is seen when you use `--cache` flag	
> * [ ]
> 
> Please check if your dockerfile is a multistage dockerfile	
> * [ ]

That is a strange behaviour, but even if I use `--tar-path /some-dir/my-img.tar`, I still need to use the `--destination=image` and `--no-push` flags to create a tar of the image. This clearly seems to be a bug, because `--destination` and `--no-push` are not required if there is already a flag to create tar of the images, as stated in the help section.

By adding `kind/bug` label will be help to draw attention.

**Comment by aaron-prindle** [comment]
Related:
https://github.com/GoogleContainerTools/kaniko/issues/2185
https://github.com/GoogleContainerTools/kaniko/issues/1860

**Comment by JeromeJu** [comment]
From https://github.com/GoogleContainerTools/kaniko/pull/549, it seems that we have changed the noPush check after opts.TarPath != "" condition because we would still want layer caching and tarball files to be created even with noPush according to:
```
When an image is built with just the tarPath and noPush is true, we should still create the tarBall (which wasn't happening).
```

Looks like the way forward for this issue is change the dependencies of the current DoPush behavior on `dependencies` at https://github.com/GoogleContainerTools/kaniko/blob/73b711816e07054f3fe5d9016a30f2c25110c56e/pkg/executor/push.go#L188. And also add some test cases with different combinations of opts 🤔

**Comment by vikramrajawat** [comment]
It works without --destination=image also for me but i have tried only with --tar-path as --targPath is deprecated now. Have also noticed the error when the path of image is not valid for --tar-path but in this case that should not be the case.
