### ISSUE TITLE
Kaniko debug image is not arm64 compatible

### ISSUE THREAD

**Issue by ajaykmis** [GoogleContainerTools/kaniko#1616]
**Actual behavior**
The kaniko 1.5.0 + images are multi-architecture, so the following image for example works on arm64: 

```yaml
6 spec:
  7   containers:
  8   - name: kaniko
  9     image: gcr.io/kaniko-project/executor:v1.5.2
 10     args:
 11     - "--dockerfile=Dockerfile"
 12     - "--context=/source/workspace"
 13     - "--destination=gcr.io/does/not.matter:test"
 14     volumeMounts:
 15     - mountPath: /var/secrets/kaniko-secret
 16       name: kaniko-secret
 17     - name: source
 18       mountPath: /source
 19     env:
 20     - name: GOOGLE_APPLICATION_CREDENTIALS
 21       value: /var/secrets/kaniko-secret/credentials
```

just changing the image to v1.5.2-debug, I get the following error: 

```
$ kubectl logs -f kaniko-working -n build
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: error while configuring docker-credential-gcr helper: /kaniko/docker-credential-gcr configure-docker --registries=gcr.io : : fork/exec /kaniko/docker-credential-gcr: exec format error
```

**Expected behavior**
debug image of kaniko should be arm64 compatible as well.

**To Reproduce**
1. use v1.5.2-debug on arm64

 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [No ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ Yes] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ NA] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ Yes] </li></ul>|

**Comment by radicand** [comment]
For what it's worth, `gcr.io/kaniko-project/executor:debug` executes fine on arm64 for me as-is.

**Comment by ajaykmis** [comment]
@radicand the kaniko executor is fine, but I think the docker-credential-gcr is not packaged correctly. 

```
err: fork/exec /kaniko/docker-credential-gcr: exec format error, out: ``
```

**Comment by aaron-prindle** [comment]
@ajaykmis were you able to get things working here?  In later releases of Kaniko (current latest: v1.11.0) the docker-credential-gcr package is packaged per arch so should work now:
https://github.com/GoogleContainerTools/kaniko/blob/main/deploy/Dockerfile#L37

**Comment by aaron-prindle** [comment]
I believe this is resolved now (see info in comment above).  Closing
