### ISSUE TITLE
Cannot use --registry-mirror with a mirror that requires a prefix

### ISSUE THREAD

**Issue by insertjokehere** [GoogleContainerTools/kaniko#1618]
**Actual behavior**
When trying to use `--registry-mirror` with a cache that requires a prefix, Kaniko will refuse to build. For example, I am using Harbor (goharbor/harbor), and in order to pull an image, I have to prefix the image name with the name of the cache project - eg, to pull `python:3.9` from my cache, I have to pull `harbor.example.com/cache/python:3.9`.

* Running Kaniko with `--registry-mirror harbor.example.com/cache` and a Dockerfile that has `FROM python:3.9` fails with "error building image: registries must be valid RFC 3986 URI authorities"
* Running Kaniko with `--registry-mirror harbor.example.com` and a Dockerfile that has `FROM cache/python:3.9` works

**Expected behavior**
* Running Kaniko with `--registry-mirror harbor.example.com/cache` and a Dockerfile that has `FROM python:3.9` should build an image
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [x] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by AndreKR** [comment]
This also affects the registry provided by GitLab.

**Comment by warmfusion** [comment]
Hi,
We made a nginx proxy that solves this problem on our on-prem installation, which may be viable in your situations;

Requirements;
1. nginx container/node
2. a read-only robot account to enable listing of /v2/

The nginx config we used to proxy on dockerhub-mirror.harbor.yourdomain.com to a harbor hosted project named 'docker.io'

This works with --registry-mirror=dockerhub-mirror.harbor.yourdomain.com for Kaniko, and also for Docker clients natively.

```
server {
    listen 80 default_server;
    server_name _;

    error_log stderr debug;

    resolver kube-dns.kube-system.svc.cluster.local valid=5s ipv6=off;

    location ~ ^/v2/+(?<path>.*)$ {
        # if the path is empty, just send it on as Kaniko needs to do an API version check
        # if the path isn't empty, prefix it with docker.io/ which is the mirror cache vault in Harbor itself

        if ($path !~* "^(docker\.io.*)?$" ) {
            # inject project and source domain into uri
            set $path "docker.io/$path";
        }

        proxy_pass            https://harbor.yourdomain.com/v2/$path;
        proxy_cache           off;
        proxy_set_header      Host                            "harbor.yourdomain.com";   # required for docker client's sake
        proxy_set_header      X-Real-IP                       $remote_addr; # pass on real client's IP
        proxy_set_header      X-Forwarded-For                 $proxy_add_x_forwarded_for;
        proxy_set_header      X-Forwarded-Proto               "https";
        # To ensure that Kaniko/etc can get a version check when pulling assets, provide a basic auth token
        # which in this case is hard-coded to a robot set up on the cache with RO access exclusivly.
        # Usefully, this should also prevent any odd attempts to push resources via the proxy mirror as auth headers will get nixed by this line
        proxy_set_header      Authorization                   "Basic BASE_64_HTPASSWORDSTRING_HERE";
        proxy_read_timeout    900;
        # prepare delegate auth
        proxy_hide_header     Www-Authenticate;
    }
    location ~ ^/service/ {
        if ($args ~* "^(.*)(scope=repository%3A)(.*)$") {
            # inject project and source domain into the auth scope
            set $args "$1$2docker.io%2F$3";
        }
        proxy_pass            https://harbor.yourdomain.com$uri$is_args$args;
        proxy_cache           off;
        proxy_set_header      Host                            "harbor.yourdomain.com";   # required for docker client's sake
        proxy_set_header      X-Real-IP                       $remote_addr; # pass on real client's IP
        proxy_set_header      X-Forwarded-For                 $proxy_add_x_forwarded_for;
        proxy_set_header      X-Forwarded-Proto               "https";
        proxy_read_timeout    900;
    }

}
```

**Comment by davidc** [comment]
This is still an issue since #1707 was reverted.

**Comment by barthanssens** [comment]
Probably needs to be re-opened ...
