### ISSUE TITLE
Reproducible build has History without CreatedBy (e.g. the command)

### ISSUE THREAD

**Issue by hermanbanken** [GoogleContainerTools/kaniko#1620]
**Actual behavior**
When using `--reproducible` the config file is modified and both the Created and CreatedBy are missing.

**Expected behavior**
The docs say that `--reproducible` **only strips the time (Created)**, so I expect it to keep CreatedBy correctly.

**To Reproduce**
1. Build using `--reproducible`
2. Run `docker history <image>`

**Additional Information**
Any Kaniko version.
 
 **Triage Notes for the Maintainers**
I've found what is causing this and created a PR in the library https://github.com/google/go-containerregistry/pull/978. However, there is a chance that this is a breaking change for this library, and that it won't be fixed. In that case, I think we must **at the very least fix the documentation** in Kaniko. Alternatively we can workaround the bug.
 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by aaron-prindle** [comment]
@hermanbanken your upstream PR to https://github.com/google/go-containerregistry/pull/978 and kaniko uses a version of go-containerregistry that has your PR.  Just want to confirm that it is likely ok to close this issue now, thanks!

**Comment by hermanbanken** [comment]
```bash
$ echo -e 'FROM alpine \nRUN echo "created from standard input"' > Dockerfile | tar -cf - Dockerfile | gzip -9 | docker run \
  --interactive  \
  -v "$HOME"/.config/gcloud:/root/.config/gcloud \
  -v $(pwd):/workspace gcr.io/kaniko-project/executor:latest \
  --context tar://stdin \
  --destination=gcr.io/myproject/myimage:test --force

$ docker history gcr.io/myproject/myimage:test --no-trunc

IMAGE                                                                     CREATED        CREATED BY                                                                                          SIZE      COMMENT
sha256:9c5258d48770ac483f04739e17f2fa17547d98eba391d23bd16ac854a6fe7d32   12 hours ago   /bin/sh -c #(nop)  CMD ["/bin/sh"]                                                                  0B        
<missing>                                                                 12 hours ago   /bin/sh -c #(nop) ADD file:1da756d12551a0e3e793e02ef87432d69d4968937bd11bed0af215db19dd94cd in /    7.33MB 
```
