### ISSUE TITLE
[Question] Possible to disable the cache for some  specific command (layer)?

### ISSUE THREAD

**Issue by huxuan** [GoogleContainerTools/kaniko#1635]
For example, when we `pip install [some-package]` and always want to use the latest version. Kaniko will treat this as the same layer since the command is always the same, but the upstream might already change. So here we want to disable the cache temporarily. Will it be possible?

**Comment by tejal29** [comment]
@huxuan, we do have a time set on cache. `--cache-ttl`. Would reducing the  time to cache help?

**Comment by huxuan** [comment]
Actually, I mean to disable cache for specific commands. I suppose it would be something like 

```
pip install XXX # kaniko: no-cache
```

**Comment by huxuan** [comment]
Close as this might not be supported, cache ttl is accepted as a workaround. Thanks @tejal29 .
