### ISSUE TITLE
[Suggestion] Exit Code Propagation for failing RUN commands

### ISSUE THREAD

**Issue by fridayy** [GoogleContainerTools/kaniko#1649]
Hey guys, 

first and foremost thank you for great work on kaniko, it already served us pretty well in production. 
I have a small suggestion though and I would love to hear your feedback on this.

## Description

If a RUN command fails during the build kaniko currently always exits with exit code 1 no matter what exit code the original command produced.

**Example:**

Dockerfile:
```
FROM python:3.7

RUN exit 123

CMD ["python", "--version"]
``` 

If you try to build this with Docker:

```fish
❯ docker build . -t=exit-code:1
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM python:3.7
 ---> 4890a41b5e72
Step 2/3 : RUN exit 123
 ---> Running in e2d5fa66d9ed
The command '/bin/sh -c exit 123' returned a non-zero code: 123

❯ echo $status
123
```

When building with kaniko resulting exit code will be always 1:
```sh
❯ docker run -v /tmp/exit-code-test:/ctx gcr.io/kaniko-project/executor:latest --context=/ctx --dockerfile=./Dockerfile --no-push
INFO[0000] Retrieving image manifest python:3.7
INFO[0000] Retrieving image python:3.7 from registry index.docker.io
INFO[0001] Built cross stage deps: map[]
INFO[0001] Retrieving image manifest python:3.7
INFO[0001] Returning cached image manifest
INFO[0001] Executing 0 build triggers
INFO[0001] Unpacking rootfs as cmd RUN exit 123 requires it.
INFO[0038] RUN exit 123
INFO[0038] Taking snapshot of full filesystem...
INFO[0041] cmd: /bin/sh
INFO[0041] args: [-c exit 123]
INFO[0041] Running: [/bin/sh -c exit 123]
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 123

/tmp/exit-code-test on ☁️  (eu-central-1) took 42s
❯ echo $status
1
```

Of course this is not the biggest of deals. Especially since the information about the original exit code is still there (in the logs).
When using kaniko in k8s jobs (CI) for example it might be useful to propagate the exit code back to the caller to find out fast what failed and why. 

## Gains

If implemented this would potentially allow kaniko users to leverage existing error code definitions and help them to faster find out what failed and why.

```
FROM python:3.7

RUN execute_unit_tests.py #fails with exit code 5 if tests failed
RUN build_something.py # fails with 6 on general error, 7 if some file is missing, and so on
#...
```

## Drawbacks

Apart from being an edge case and probably not required by lots of folks: 
If a failing RUN command produced the same exit code as a some well-defined exit code kaniko itself uses the whole thing might be a little confusing.

## Implementation

Exit code propagation should not be the standard behavior but must be enabled using a flag (avoids this being a breaking change as well). For example: `--propagate-exit-code`

An quick and dirty implementation can be found here: https://github.com/fridayy/kaniko/commit/a6ca7e0c142c3f80d9933d8998828e89563ca4f2

(Sorry I rarely ever write something in go - please be kind)

```sh
/tmp/exit-code-test on ☁️  (eu-central-1)
❯ docker run -v /tmp/exit-code-test:/ctx lso/kaniko/executor:latest --context=/ctx --dockerfile=./Dockerfile --no-push --propagate-exit-code
INFO[0000] Retrieving image manifest python:3.7
INFO[0000] Retrieving image python:3.7 from registry index.docker.io
INFO[0001] Built cross stage deps: map[]
INFO[0001] Retrieving image manifest python:3.7
INFO[0001] Returning cached image manifest
INFO[0001] Executing 0 build triggers
INFO[0001] Unpacking rootfs as cmd RUN exit 123 #asdasd requires it.
INFO[0040] RUN exit 123 #asdasd
INFO[0040] Taking snapshot of full filesystem...
INFO[0043] cmd: /bin/sh
INFO[0043] args: [-c exit 123 #asdasd]
INFO[0043] Running: [/bin/sh -c exit 123 #asdasd]
error building image: exit status 123

/tmp/exit-code-test on ☁️  (eu-central-1) took 44s
❯ echo $status
123
```

I hope I could explain everything in a understandable manner.
Thank again for your time, efforts and kaniko itself and I am looking forward to your feedback on this.

With best regards!

**Comment by tejal29** [comment]
@fridayy Thank you for the issue and the code to fix. it. 
Please open a PR and get this in. I would say, we should always propagate the exit code and get rid of the flag `--propogate-exit-code`

Looking forward to see this PR.

**Comment by fridayy** [comment]
Hi @tejal29 ! Thanks for your feedback! Great to hear that the flag can be dropped and this should be the standard behaviour. I will open a PR as soon as possible.

Best regards!
