### ISSUE TITLE
Add dependabot integration

### ISSUE THREAD

**Issue by CrAzE124** [GoogleContainerTools/kaniko#1661]
Is it possible to add dependabot integration to kaniko's GitHub repository? As part of our organizational requirements, automated dependency checking is a "must-have". I think having this enabled for Kaniko would also bring some enhancements. 

Issues like #1656 could be automatically detected and a PR opened for it.

**Comment by aaron-prindle** [comment]
Thanks for flagging this, dependabot has been added to kaniko's Github repository since this issue was created.  Closing
