### ISSUE TITLE
Push image to private registry should use https

### ISSUE THREAD

**Issue by triThirty** [GoogleContainerTools/kaniko#1664]
**Actual behavior**
It seems like that when pushing image to my private registry, kaniko dosen't use https instead of http.

I use command `docker run --rm -v ~/.docker/config.json:/kaniko/.docker/config.json -v /root/appname:/workspace gcr.io/kaniko-project/executor:v1.6.0 --context /workspace --dockerfile /workspace/Dockerfile --destination my-private-registry/appname:test1`, and the output is this :
```Shell
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "my-private-registry/appname:test1": POST https://my-private-registry/v2/appname/blobs/uploads/: unexpected status code 403 Forbidden: 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
This distribution is not configured to allow the HTTP request method that was used for this request. The distribution supports only cachable requests.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: ==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```
But acctually my docker credential use https, like this:
```JSON
{
  "auths": {
    "https://my-private-registry": {
      "auth": "<token>"
    }
  }
}
```
Acctually, I tried to run `curl http://my-private-registry`, I got the same 403 output, but if I run `curl https://my-private-registry/v2`, it can correctly return the basic auth window.

And for docker credential, I am sure that this credential works well locally.

**Expected behavior**
I woulde expect the kaniko should use https when I push image to private registry.

**To Reproduce**
1. ...
2. ...

**Additional Information**
 - Dockerfile 
   ```TEXT
    FROM python:3.8
    
    WORKDIR /app
    
    COPY . ./
    
    RUN pip3 install -r requirements.txt 
    CMD python app.py
   ```
 - Build Context
   Please provide or clearly describe any files needed to build the Dockerfile (ADD/COPY commands)
 - Kaniko Image (fully qualified with digest)
 `gcr.io/kaniko-project/executor:v1.6.0 `
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by aaron-prindle** [comment]
@triThirty I believe this is likely a dupe of https://github.com/GoogleContainerTools/kaniko/issues/1882.  Can you confirm if you were specifying a  docker registry with a custom port when you encountered this issue (as mentioned in that issue)?

**Comment by triThirty** [comment]
hi @aaron-prindle , I don't know the root cause, but after I use latest kaniko, I can push my image to my private registry. But I also notice that my registry team uses CDN to pull image, and another endpoint to push image, I am not sure if latest kaniko fix the issue or my registry team fix it from their side. Anyway, thanks for your care. I will close the issue
