### ISSUE TITLE
cache-ttl does not default to hours like documented

### ISSUE THREAD

**Issue by Nothing4You** [GoogleContainerTools/kaniko#1694]
**Actual behavior**
Unable to set 6 hour cache TTL by passing `6`.
```
Error: invalid argument "6" for "--cache-ttl" flag: time: missing unit in duration 6
```

**Expected behavior**
Argument should follow the documentation:
> Cache timeout in hours. Defaults to two weeks.

**To Reproduce**
1. build a container with `--cache-ttl 6` or any other number

**Additional Information**
 - Kaniko Image (fully qualified with digest)
> Using docker image sha256:7053f62a27a84985c6ac886fcb5f9fa74090edb46536486f69364e3360f7c9ad for gcr.io/kaniko-project/executor:debug with digest gcr.io/kaniko-project/executor@sha256:fcccd2ab9f3892e33fc7f2e950c8e4fc665e7a4c66f6a9d70b300d7a2103592f ...
 
 **Triage Notes for the Maintainers**
 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [x] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by junzebao** [comment]
We ran into the same issue yesterday, only to find out we needed to add a `h` after the number...
