### ISSUE TITLE
Build of Images fails with unclear message

### ISSUE THREAD

**Issue by nbyl** [GoogleContainerTools/kaniko#170]
I tried to build the attached Dockerfile using kaniko, but the build failed with the following error.

```
time="2018-05-07T13:41:41Z" level=error msg="could not parse reference"
```

Attached you'll find the [build.log](https://github.com/GoogleContainerTools/kaniko/files/1980062/build.log) and the [Dockerfile](https://github.com/GoogleContainerTools/kaniko/files/1980065/Dockerfile.txt).

**Comment by priyawadhwa** [comment]
I was able to build the image successfully, so I suspect it's an issue with the location you're trying to push the final image to. What are you passing in to the --destination flag?

**Comment by nbyl** [comment]
Yes, this the problem. I omitted the --destination flag which results in this error. I submitted a PR which will prevent this in the future.
