### ISSUE TITLE
/bin/sh not available via kaniko build

### ISSUE THREAD

**Issue by airkewld** [GoogleContainerTools/kaniko#1716]
I have a use case to include /bin/sh in a scratch image due to an external project, however /bin/sh is not available if built using kaniko.

Dockerfile
FROM alpine:3.12 as builder

FROM scratch
WORKDIR /go/src/app
COPY --from=builder /bin/sh /bin/sh
COPY --from=builder /lib/ld-musl-x86_64.so.1 /lib/ld-musl-x86_64.so.1
USER 65532

CMD /go/src/app/migrate.linux-amd64 -path /go/src/app/migrations -database "$DB_CONN" -verbose up

Kaniko build command (running locally and mounting cwd)

docker run --rm -it -v $(pwd):/tmp kaniko/executor:debug2(local latest image)  --use-new-run --snapshotMode=redo --context /tmp --dockerfile /tmp/build/Dockerfile.migrations --destination docker.io/library/kaniko:local-kaniko --no-push --tarPath=/tmp/migrate.tar

docker load -i migrate.tar
docker run --rm -it kaniko:local-kaniko /bin/sh
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown.

docker build -t kaniko:docker-build -f build/Dockerfile.migrations .

docker run --rm -it kaniko:docker-build /bin/sh
/go/src/app $ %   

Any insight into this behavior is greatly appreciated.

**Comment by dgilmanTORQATA** [comment]
The readme encourages you to use the debug image if you need a shell. https://github.com/GoogleContainerTools/kaniko#debug-image
