### ISSUE TITLE
Kaniko cannot download image via mirror

### ISSUE THREAD

**Issue by Phylu** [GoogleContainerTools/kaniko#1721]
**Actual behavior**

Kaniko cannot download the image via registry mirror and aborts with the following error:

```
$ /kaniko/executor --registry-mirror [REDACTED] --cache=true --cache-dir=/cache --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" $BUILD_ARGS
INFO[0001] Using dockerignore file: /builds/zSBJNYyW/0/applications/pentaho/.dockerignore 
INFO[0001] Retrieving image manifest openjdk:8-jre-slim-buster 
ERRO[0001] Error while retrieving image from cache: openjdk:8-jre-slim-buster strict validation requires the registry to be explicitly defined 
INFO[0001] Retrieving image manifest openjdk:8-jre-slim-buster 
```

**Expected behavior**

The build succeeds

**To Reproduce**
1. Start the build
2. See how the build fails

**Additional Information**
 - Dockerfile 

```
FROM openjdk:8-jre-slim-buster
```

 - Build Context: N/A
 - Kaniko Image (fully qualified with digest): Current master state (https://github.com/GoogleContainerTools/kaniko/commit/7e3954ac734534ce5ce68ad6300a2d3143d82f40). The issue is not present in the stable version v1.6.0
- This bug seems to be a regresison of: https://github.com/GoogleContainerTools/kaniko/issues/1172
- This bug was introduced with commit https://github.com/GoogleContainerTools/kaniko/commit/4e218f21623d89ef4161461c1f3c73baf2d7c119. The build works fine with the commit(s) before.

 **Triage Notes for the Maintainers**
 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [x] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by tbnguyen1407** [comment]
Hello, ran into this issue just now with 1.7.0 release. Any update on this?

**Comment by jbub** [comment]
@tbnguyen1407 probably related #1787

**Comment by sylvaindd** [comment]
Same problem here, could really use a minor version here.

**Comment by Phylu** [comment]
@tejal29 @dlorenc @sharifelgamal Is it possible to create a hotfix release from the current master branch? This should resolve this issue, which currently renders kaniko unusable for all our builds :(

**Comment by dlorenc** [comment]
I'm no longer a maintainer here, sorry. Tejal/Sharif might be able to help.

**Comment by freehck** [comment]
I have just checked that the problem does not exist in the release v1.0.8 anymore.
