### ISSUE TITLE
Kaniko in jenkins-inbound-agent running in Fargate, and issues pushing to AWS ECR

### ISSUE THREAD

**Issue by vladaurosh** [GoogleContainerTools/kaniko#1742]
I have built docker image based on jenkins inbound agent (alpine), with kaniko inside. I am trying to run it in AWS Fargate. 
So far I had success running kaniko executor, it successfully created docker image. But I am having issues with authentication to AWS ECR repo.

This works:
I have config.json in /kaniko/.docker ({"credsStore": "ecr-login"}) and I have /root/.docker/.aws/config and /root/.docker/.aws/credentials file with aws_access_key_id, aws_secret_access_key and aws_session_token from user that has privileges to push to ECR. With this setup, docker image is built and pushed to ECR.

This doesn't work:
I have config.json in /kaniko/.docker ({"credsStore": "ecr-login"}) and I have IAM role with permissions to push to ECR attached to ECS task. Here I get this error message:
GET KEYCHAIN                                 
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "12345678.dkr.ecr.eu-west-1.amazonaws.com/jenkins-inbound-agent:test": POST https://12345678.dkr.ecr.eu-west-1.amazonaws.com/v2/jenkins-inbound-agent/blobs/uploads/: unexpected status code 401 Unauthorized: Not Authorized

I did some troubleshooting and inside container it is possible to run (when IAM role is attached to task):
curl http://169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
This will return string with RoleArn, AccessKeyId, SecretAccessKey and Token.
I used these in .aws/credentials and with those, it successfully pushed image to ECR, so I am sure that IAM role is attached and has correct privileges.

So any idea what's wrong here? Or how can I troubleshoot this further?
I know that running kaniko outside of official image is not supported, but this looks to be only way to run with jenkins inbound agent.

**Comment by vladaurosh** [comment]
This was my bad, issue with DOCKER_CONFIG variable. 
Closing ticket.

**Comment by vladaurosh** [comment]
This was my bad, issue with DOCKER_CONFIG variable.
Closing ticket.

**Comment by cristian98149** [comment]
Hi, how have you include kaniko executor in alpine image?

Thank you
