### ISSUE TITLE
Three Test_GetFSFromLayers tests fail with kaniko 1.7.0

### ISSUE THREAD

**Issue by hashworks** [GoogleContainerTools/kaniko#1779]
**Actual behavior**
I'm providing an [AUR package](https://aur.archlinux.org/packages/kaniko/) of kaniko for [Arch Linux Docker Images](https://hub.docker.com/_/archlinux). Building the new 1.7.0 version works fine, but tests using `go test -short ./{cmd,pkg}/...` seem to fail:

```
--- FAIL: Test_GetFSFromLayers_with_whiteouts_include_whiteout_enabled (0.00s)
    fs_util_test.go:1124: expected [/tmp/layers-test340080850/foobar] to equal [/tmp/layers-test340080850/foobar /tmp/layers-test340080850/.wh.foobar]
--- FAIL: Test_GetFSFromLayers_with_whiteouts_include_whiteout_disabled (0.00s)
    fs_util_test.go:1238: expected whiteout foobar file to be deleted. However found it.
--- FAIL: Test_GetFSFromLayers_ignorelist (0.00s)
    fs_util_test.go:1319: expected [/tmp/layers-test146054141/testdir/file /tmp/layers-test146054141/other-file] to equal [/tmp/layers-test146054141/.wh.testdir /tmp/layers-test146054141/testdir/file /tmp/layers-test146054141/other-file]
time="2021-10-19T17:02:51+02:00" level=warning msg="Retrying operation after 10ms due to Failing with i=0"
time="2021-10-19T17:02:51+02:00" level=warning msg="Retrying operation after 10ms due to Failing with i=0"
time="2021-10-19T17:02:51+02:00" level=warning msg="Retrying operation after 20ms due to Failing with i=1"
FAIL
FAIL	github.com/GoogleContainerTools/kaniko/pkg/util	1.375s
?   	github.com/GoogleContainerTools/kaniko/pkg/version	[no test files]
FAIL
```

**Expected behavior**
No tests fail for released versions.

**To Reproduce**
1. git clone https://aur.archlinux.org/kaniko.git
2. cd kaniko
3. Adjust version to `1.7.0` and sha256sums to `a2a51b55d393357b3e9859371f16687b202a4325a22a7bf0740cc40ed778fb7a`
4. Run `extra-x86_64-build`

But simply `go test -short ./pkg/...` should work as well.

**Additional Information**
 - Used PKGBUILD: https://fb.hash.works/t801oi/ 
 - Build log: https://fb.hash.works/84eKSCRR/

**Comment by KingCrunch** [comment]
The issues are still there. For now I don't know how to fix them ....

**Comment by andreasf** [comment]
I am getting the same errors in a colima VM (Alpine kernel, I think?) as well as on an old Fedora 34 installation.

However, I was able to run tests successfully in a Debian 12 VM.
