### ISSUE TITLE
Push Permission Error on latest

### ISSUE THREAD

**Issue by zkanda** [GoogleContainerTools/kaniko#1786]
**Actual behavior**
Permission error on pushing to google container registry.

```txt
Step #0: error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "eu.gcr.io/<project-id>/services/svc:master-xxxx": creating push check transport for eu.gcr.io failed: GET https://eu.gcr.io/v2/token?scope=repository%3A<project-id>%2Fservices%2Fsvc%3Apush%2Cpull&service=eu.gcr.io: UNAUTHORIZED: Not Authorized.
Finished Step #0
ERROR
ERROR: build step 0 "gcr.io/kaniko-project/executor:latest" failed: step exited with non-zero status: 1
```

**Expected behavior**
It should successfully push, I reverted to 1.6.0 and it works great.

**To Reproduce**
Make a google build with this yaml:

```
steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=eu.gcr.io/$PROJECT_ID/services/svc:$BRANCH_NAME-$SHORT_SHA
  - --dockerfile=svc/Dockerfile
  - --cache=true
  - --cache-ttl=168h
  - --cache-repo=eu.gcr.io/$PROJECT_ID/cache
  - --snapshotMode=redo
  - --use-new-run
```

**Additional Information**
 - Dockerfile 
Any dockerfile will reproduce the error.
 - Kaniko Image (fully qualified with digest)
 gcr.io/kaniko-project/executor:latest
digest: 8504bde9a9a8c9c4e9a4fe659703d265697a36ff13607b7669a4caa4407baa52

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [x] </li></ul>|

**Comment by mkushakov** [comment]
Same here with GCR as container repository and GitLab with kaniko job on `gcr.io/kaniko-project/executor:debug`

Look like this PR has fixed this issue #1780 
We just need new v1.7.1 release from `master` to have it working back.

**Comment by slahs3r** [comment]
Same here.

My environment is:

- Google Cloud Build
- Google Container Registry

This workaround works for me:
```
gcloud config set builds/kaniko_image gcr.io/kaniko-project/executor:v1.6.0
```

**Comment by Retsuki** [comment]
Could this fix be the cause?
#1471

**Comment by plechi** [comment]
> My environment is also:
> 
> * Google Cloud Build
> * Google Container Registry
> 
> If I specify gcr.io/kaniko-project/executor:edge, it also works.

Keep in mind that this image is from May 7, 2020. I think it's better to use the `v1.6.0` tag until this is fixed.

**Comment by robertlindner** [comment]
Same:
* Push to GCR check fails
* gitlab.com runner (on gke)
* GOOGLE_APPLICATION_CREDENTIALS pointing to service account key file for gcr auth
* I have additional credentials for the gitlab registry in /kaniko/.docker/config.json

**Comment by dogomedia-github** [comment]
+1 Same as everyone else

My environment is:

Google Cloud Build
Google Container Registry

Downgrading to 1.6.0 fixes the error, but this is not a viable work around. Updating hundreds of projects to use 1.6.0 is hardly a solution. Why was this change made without proper QA testing to make sure it doesn't break anything?

**Comment by zkanda** [comment]
The latest version now works for me for a few days. Closing this.

**Comment by gsabbih6** [comment]
It does not work, was this resolved. ! have same issue, tried every build of kaniko

**Comment by inimaz** [comment]
Same issue here, we are using the `debug` tag.
