### ISSUE TITLE
Deprecation of whitelist-var-run in 1.7.0 does not work

### ISSUE THREAD

**Issue by hashworks** [GoogleContainerTools/kaniko#1795]
**Actual behavior**
Using `--whitelist-var-run` in 1.7.0 results in `Error: unknown flag: --whitelist-var-run`, crashing the build.
Using the replacement `--ignore-var-run` results in `Flag --ignore-var-run has been deprecated, please use ignore-var-run instead.`

**Expected behavior**
Using `--whitelist-var-run` in 1.7.0 results in a deprecation warning and automatically assumes `--ignore-var-run`, not breaking the build.
Using the replacement `--ignore-var-run` does not produce a deprecation warning.

**To Reproduce**
```
$ docker run gcr.io/kaniko-project/executor:v1.7.0-slim --whitelist-var-run
Error: unknown flag: --whitelist-var-run
Usage:
  executor [flags]
  executor [command]
[...]
$ docker run gcr.io/kaniko-project/executor:v1.7.0-slim --ignore-var-run
Flag --ignore-var-run has been deprecated, please use ignore-var-run instead.
Error: You must provide --destination, or use --no-push
Usage:
  executor [flags]
  executor [command]
[...]
```

**Additional Information**
 - [Broken build](https://gitlab.archlinux.org/archlinux/archlinux-docker/-/jobs/37157#L32)
 - [Fixed build with wrong deprecation message](https://gitlab.archlinux.org/archlinux/archlinux-docker/-/jobs/37278#L34)

**Comment by olivergregorius** [comment]
Any news or fix on this? I see exactly the same output as @hashworks.

**Comment by imjasonh** [comment]
Does the fix in https://github.com/GoogleContainerTools/kaniko/pull/1339 address the issue? Perhaps we should just fix that up and merge it before v1.8.0.

**Comment by olivergregorius** [comment]
#1339 has been started in July 2020 and was never merged whereas #1668 has been created and merged in June 2021. I think #1339 can be closed and another PR must be opened to fix the issues introduced with #1668.

**Comment by imjasonh** [comment]
> #1339 has been started in July 2020 and was never merged whereas #1668 has been created and merged in June 2021. I think #1339 can be closed and another PR must be opened to fix the issues introduced with #1668.

Sounds great. Would you be interested in doing that? I can review.

**Comment by olivergregorius** [comment]
> Sounds great. Would you be interested in doing that? I can review.

I'm not that familiar with Golang and especially the codebase of this project, yet, but I could try to fix this.

**Comment by olivergregorius** [comment]
@imjasonh Well I figured it out and provided a fix.
