### ISSUE TITLE
Pulling executor:debug image is the old version 1.6.0?

### ISSUE THREAD

**Issue by Crapshit** [GoogleContainerTools/kaniko#1812]
Pulling executor:debug image seems to be the old Kaniko version 1.6.0:
user@host ~# docker pull gcr.io/kaniko-project/executor:debug
debug: Pulling from kaniko-project/executor
981fc7edb8fd: Pull complete 
d044254b2a54: Pull complete 
8f137c16aecd: Pull complete 
6566d8138b04: Pull complete 
3d8068545002: Pull complete 
fe2d5f51c3f2: Pull complete 
ee2c784f1c11: Pull complete 
13e1a61a0623: Pull complete 
ddd1314b2f82: Pull complete 
1e1b51c21c3c: Pull complete 
Digest: sha256:fcccd2ab9f3892e33fc7f2e950c8e4fc665e7a4c66f6a9d70b300d7a2103592f
Status: Downloaded newer image for gcr.io/kaniko-project/executor:debug
gcr.io/kaniko-project/executor:debug

user@host ~# docker run -it --entrypoint=/busybox/sh gcr.io/kaniko-project/executor:debug
/workspace # cd /kaniko/
/kaniko # ./executor version
Kaniko version :  v1.6.0

I would expect that this executor:debug image is the same new version as below:
user@host ~# docker pull gcr.io/kaniko-project/executor:v1.7.0-debug
v1.7.0-debug: Pulling from kaniko-project/executor
b9f241f9d2e8: Pull complete 
1de4761794ba: Pull complete 
585edf44cc3b: Pull complete 
dd687676e859: Pull complete 
5629f641d093: Pull complete 
8c9c08846cad: Pull complete 
f77ae48936b0: Pull complete 
9fa64f572b2c: Pull complete 
84fdf0b3d632: Pull complete 
45c12e3304a9: Pull complete 
97702ca62d42: Pull complete 
Digest: sha256:88dacc7ea3f5c04709eae96776693c717869405364b19d6e78850fe54c63c6a2
Status: Downloaded newer image for gcr.io/kaniko-project/executor:v1.7.0-debug
gcr.io/kaniko-project/executor:v1.7.0-debug

user@host ~# docker run -it --entrypoint=/busybox/sh gcr.io/kaniko-project/executor:v1.7.0-debug
/workspace # cd /kaniko/
/kaniko # ./executor version
Kaniko version :  v1.7.0

**Comment by baby-gnu** [comment]
This is a problem since 1.6.0 has #1592 issue.

**Comment by TonyNoble** [comment]
Seconded.  In our case, it's an issue because 1.7.0 introduced the --compressed-caching flag, which we require to get large image builds working under kubernetes.  Additionally, there appears to be no 1.8.0 debug build.

**Comment by imjasonh** [comment]
There's no v1.8.0 build at all. See #1871 

In the meantime, you can get commit-tagged images that likely include lots of improvements over `:latest`/`:v1.6.0`. The latest commit-tagged image is `:f067edae9f077393398ad52abf2fcca5e5a37a75` with the debug variant at `:f067edae9f077393398ad52abf2fcca5e5a37a75-debug`.

**Comment by TonyNoble** [comment]
@imjasonh - fair enough re. 1.8.0, but I'd at least expect the 'debug' tag to point to 1.7.0-debug rather than 1.6.0-debug.  We require debug builds in order to run under gitlab-ci and 1.7.0 contains some fairly critical fixes - we can hard-code the specific debug release, but it'd be nicer to be able to just rely on the debug tag pointing to the latest one.

**Comment by imjasonh** [comment]
There was an issue in the 1.7.0 release and the solution to it was to revert latest to point to 1.6.0 (including debug, slim, warmer).

When 1.8.0 is released I expect future releases not to revert the tag this way, but instead to roll forward fixes. Or at least to document this better.

Sorry for the inconvenience in the meantime.

**Comment by Crapshit** [comment]
Hi @imjasonh, what issue we are talking about?
Thanks in advance :)

**Comment by imjasonh** [comment]
> Hi @imjasonh, what issue we are talking about?
> Thanks in advance :)

See comments in https://github.com/GoogleContainerTools/kaniko/issues/1871

**Comment by TonyNoble** [comment]
@imjasonh - that makes sense.  Thanks for the clarification - I'll keep an eye out for 1.8.0 👍
