### ISSUE TITLE
Pulling kaniko with tag :latest is not version 1.7.0

### ISSUE THREAD

**Issue by kirrmann** [GoogleContainerTools/kaniko#1822]
**Actual behavior**
pulling `gcr.io/kaniko-project/executor:latest` actually pulls version `:v1.6.0` instead of `:v1.7.0`

**Expected behavior**
I expect that version 1.7.0 is pulled. Either the release notes are extremely misleading, wrong or the images are tagged incorrect.

https://github.com/GoogleContainerTools/kaniko/releases/tag/v1.7.0

**Comment by woz5999** [comment]
this is true for the `debug` tag as well

**Comment by Mistic92** [comment]
This is because of bugs in version 1.7.

**Comment by aaron-prindle** [comment]
Seems there is some additional context as to why this was done - https://github.com/GoogleContainerTools/kaniko/issues/1893#issuecomment-1021491198
