### ISSUE TITLE
executor:debug doesn't expose /bin/sh

### ISSUE THREAD

**Issue by rvillane** [GoogleContainerTools/kaniko#1828]
**Actual behavior**
executor:debug image doesn't expose /bin/sh but executor:v1.7.0-debug does and they are supposed to be the same image per [v1.7.0](https://github.com/GoogleContainerTools/kaniko/releases/tag/v1.7.0) release notes.

Ticket #1748 added a symlink to /bin/sh and the actual change is reflected [here](https://github.com/GoogleContainerTools/kaniko/blob/master/deploy/Dockerfile_debug#L89-L90).

**Expected behavior**
executor:debug image should expose /bin/sh.

**To Reproduce**
1. Run this command: `docker run -it --entrypoint=/bin/sh gcr.io/kaniko-project/executor:debug`, it will produce the following error:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown.
```

2. Now run this command: `docker run -it --entrypoint=/bin/sh gcr.io/kaniko-project/executor:v1.7.0-debug`, it works fine:

```
/workspace # ls -ls /bin/sh
     0 lrwxrwxrwx    1 0        0               11 Oct 20 02:35 /bin/sh -> /busybox/sh
```

 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>No</li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>No</li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>No</li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>No</li></ul>| 
 

I suspect `gcr.io/kaniko-project/executor` image tags are assigned incorrectly.

**Comment by dallmair** [comment]
At the moment, `debug` is the same as `v1.6.0-debug` as per @imjasonh 1.7.0 has a few regressions (https://github.com/GoogleContainerTools/kaniko/issues/1788#issuecomment-1027308325).

**Comment by imjasonh** [comment]
It's true. Please try the latest commit-tagged image to see if this is resolved at head.

```
gcr.io/kaniko-project/executor:d0fe83024cac52fdcf77ea6e634cefd90abc7f6e-debug
```

**Comment by aaron-prindle** [comment]
Going to close this this seems to have been resolved in future kaniko releases.  As of today (6/13/23), the latest release of kaniko `v1.11.0` has `debug` and `v1.11.1-debug` tags pointing to the correct image:
![image](https://github.com/GoogleContainerTools/kaniko/assets/1951658/9380e504-5425-49d8-bb1a-237e41bd6c9e)
