### ISSUE TITLE
COPY directory and --cache-copy-layers

### ISSUE THREAD

**Issue by RoSk0** [GoogleContainerTools/kaniko#1877]
I have a multistage Dockerfile which has `COPY` commands in multiple stages copying contents of directories. In one instance the directory contains files as a direct children. In another, it's a mix with files and many directories which also have files and directories.

When files changed in the first directory Kaniko notices it and runs COPY command, but when files change in the seconds, couple levels down from the directory root, Kaniko uses cached layer.

The questions I have are: 
1. Do I use it correctly or not ? 
2. Are my expectations reasonable and this is a bug ?

**Comment by dradetsky** [comment]
Kaniko doesn't properly support `--cache-copy-layers` in multistage builds. I've made a PR to fail fast in this case https://github.com/GoogleContainerTools/kaniko/pull/2227
