### ISSUE TITLE
Can't Build jenkinsci/docker-slave

### ISSUE THREAD

**Issue by kmadel** [GoogleContainerTools/kaniko#190]
From https://github.com/jenkinsci/docker-slave/blob/master/Dockerfile

Issue seems related to concatenating RUN commands and may also be due to ARGS being present is said command.

Building with latest:
```
latest: Pulling from kaniko-project/executor
Digest: sha256:501056bf52f3a96f151ccbeb028715330d5d5aa6647e7572ce6c6c55f91ab374
Status: Image is up to date for gcr.io/kaniko-project/executor:latest
```

Results in this error:
```
time="2018-05-19T12:58:07Z" level=info msg="args: [-c mkdir /home/${user}/.jenkins && mkdir -p ${AGENT_WORKDIR}]"
time="2018-05-19T12:58:07Z" level=error msg="exit status 1"
command terminated with exit code 1
```

This is the relevant line in the [Dockerfile](https://github.com/jenkinsci/docker-slave/blob/master/Dockerfile#L45):
```
RUN mkdir /home/${user}/.jenkins && mkdir -p ${AGENT_WORKDIR}
```

**Comment by kmadel** [comment]
Similar issue with https://github.com/beedemo/jnlp-agent with this [line](https://github.com/beedemo/jnlp-agent/blob/c865a7193f52ab3c2c9a671941fc5a67abd6cc00/Dockerfile#L17)

```
time="2018-05-19T13:08:03Z" level=info msg="args: [-c mkdir /home/jenkins/.jenkins && mkdir -p ${AGENT_WORKDIR}]"
time="2018-05-19T13:08:03Z" level=error msg="exit status 1"
command terminated with exit code 1
```
Updated to:
```
RUN mkdir /home/jenkins/.jenkins
RUN mkdir -p ${AGENT_WORKDIR}
```
Still fails with:
```
time="2018-05-19T13:15:23Z" level=info msg="args: [-c mkdir /home/jenkins/.jenkins]"
time="2018-05-19T13:15:23Z" level=error msg="exit status 1"
command terminated with exit code 1
```

**Comment by kmadel** [comment]
`RUN mkdir /.jenkins` seems fine but and `RUN mkdir /home/.jenkins` works, but `RUN mkdir /home/jenkins/.jenkins` does not.

**Comment by kmadel** [comment]
Yet another update - `RUN mkdir /home/jenkins/.test` works fine, so it seems this is an issue with having a hidden directory in a directory with the same name.

**Comment by priyawadhwa** [comment]
Looks like the bug is happening because we aren't handling environment replacement for ARG, I'll open a PR to fix this.

**Comment by priyawadhwa** [comment]
This should be fixed now, let me know if you have any issues.
