### ISSUE TITLE
Push to docker registry from tar file

### ISSUE THREAD

**Issue by Rez0k** [GoogleContainerTools/kaniko#1916]
Hi,

I want to use kaniko to push tar files to docker registry.
I dont want to build the image, only to push ready tar files.

Does kaniko support this functionality?

**Comment by imjasonh** [comment]
No, but [`crane`](https://github.com/google/go-containerregistry/tree/main/cmd/crane) does. Specifically, [`crane push`](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane_push.md), e.g.:

```
crane push some.tar registry.io/my/image:latest
```

**Comment by Rez0k** [comment]
Thank you very much, I will check it out
