### ISSUE TITLE
Kaniko image won't let me run binaries

### ISSUE THREAD

**Issue by tal-zvon** [GoogleContainerTools/kaniko#1920]
I'm using a Raspberry Pi 4. I just built the latest version of Kaniko from the master branch on it. Everything appears to have worked fine.

My python project requires the `cryptography` library, which [requires the Rust programming language](https://cryptography.io/en/latest/faq/#why-does-cryptography-require-rust).

Normally, installing rust is as simple as running:

`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

My dockerfile looks like this:

```
FROM python:3.7
...
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
...
```

If I manually start the `python:3.7` container and run the command, rust installs without any issues. Having kaniko run the Dockerfile, this fails.

I did some digging with the failed Kaniko image, and this appears to be what's happening:

- The command downloads a bash script, and makes bash run it with the `-y` arg to accept the defaults (to enable non-interactive mode)
- The script then downloads an arm binary ([this one](https://static.rust-lang.org/rustup/dist/armv7-unknown-linux-gnueabihf/rustup-init), since it's a Raspberry Pi)
- It tries to execute the binary, but gets the error that the file can't be found

I would have thought that Kaniko would have executed this binary in the context of a `python:3.7` container, but it appears to try to run it within its own container, that's based on `scratch`.

If I'm using bash within the Kaniko container, I can use curl to download that binary, and it has the execute bit set, but I can't execute it - it says the file can't be found.

I suspect that one of the dynamically linked libraries the binary requires is missing in the kaniko container. Unfortunately, the container is missing `ldd`, so I can't confirm this. Copying `ldd` from the host raspberry pi into the container, and running it against the binary, it just says that the binary isn't dynamically linked, which is wrong. It definitely is, because copying the binary to the host and running `ldd` against it there shows the required libraries it's looking for.

Copying the required libraries from the host into the container didn't help either.

My Questions:

- Am I correct in assuming that Kaniko is designed to run the binary within its own container, which is built based on `scratch`, as opposed to running it in the `python:3.7` image that's specified in my Dockerfile? Why is it doing that?
-  Is this likely an issue with missing dynamic libraries?
- Is there anything I can do about this? Perhaps build Kaniko to be based on another linux image, like `ubuntu`, instead of `scratch`? Would that break things? Would that likely help?

**Comment by imjasonh** [comment]
> I would have thought that Kaniko would have executed this binary in the context of a `python:3.7` container, but it appears to try to run it within its own container, that's based on `scratch`.
> 

> * Am I correct in assuming that Kaniko is designed to run the binary within its own container, which is built based on `scratch`, as opposed to running it in the `python:3.7` image that's specified in my Dockerfile? Why is it doing that?

It's based on `scratch`, but prior to executing that `RUN` instruction, kaniko fetches the contents of `python:3.7` and puts all those files in the correct location inside its own container.

It does this because the kaniko image doesn't know what base image your Dockerfile will request until it requests it at runtime. So kaniko is built `FROM scratch`, but should account for this already. I suspect there's something it's not doing during that process that's the root of this bug.

> * Is this likely an issue with missing dynamic libraries?

Maybe? [`container-diff`](https://github.com/GoogleContainerTools/container-diff) might be helpful here.

> * Is there anything I can do about this? Perhaps build Kaniko to be based on another linux image, like `ubuntu`, instead of `scratch`? Would that break things? Would that likely help?

Basing kaniko on another image _might_ help, but it might also break everything, since at the time of the `RUN` instruction execution, the filesystem contents would be a combination of `ubuntu`'s filesystem and `python:3.7`'s.

If you build a Kaniko image `FROM python:3.7` (by editing `deploy/Dockerfile` and `docker build`ing it) does it fix your issue? That might be a useful diagnosis step.

**Comment by tal-zvon** [comment]
Basing the kaniko image on `python:3.7` instead of `scratch` made the image 10x as big (from 28MB to 312MB), but worked. The same dockerfile, with the same command that installs Rust ran with no issues.

Is there anything else I can do do help debug this?
What would I compare using `container-diff`?

**Comment by tal-zvon** [comment]
I just tried another test.
Instead of basing the kaniko image on `python:3.7`, I just used ldd to see which libraries were required by the rust binary:

```
# ldd rustup-init
    linux-vdso.so.1 (0xbeb67000)
    libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb6726000)
    librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0xb6710000)
    libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb66ea000)
    libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xb6682000)
    libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xb666f000)
    libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6570000)
    /lib/ld-linux-armhf.so.3 (0xb6f67000)
```

And added these lines to `deploy/Dockerfile_debug`:

```
COPY --from=python:3.7 /lib/arm-linux-gnueabihf/libgcc_s.so.1 /lib/arm-linux-gnueabihf/libgcc_s.so.1
COPY --from=python:3.7 /lib/arm-linux-gnueabihf/librt.so.1 /lib/arm-linux-gnueabihf/librt.so.1
COPY --from=python:3.7 /lib/arm-linux-gnueabihf/libpthread.so.0 /lib/arm-linux-gnueabihf/libpthread.so.0
COPY --from=python:3.7 /lib/arm-linux-gnueabihf/libm.so.6 /lib/arm-linux-gnueabihf/libm.so.6
COPY --from=python:3.7 /lib/arm-linux-gnueabihf/libdl.so.2 /lib/arm-linux-gnueabihf/libdl.so.2
COPY --from=python:3.7 /lib/arm-linux-gnueabihf/libc.so.6 /lib/arm-linux-gnueabihf/libc.so.6
COPY --from=python:3.7 /lib/ld-linux-armhf.so.3 /lib/ld-linux-armhf.so.3
```

The resulting kaniko image is much smaller, since it's still based on `scratch`, but seems to have worked. It can now run the [rust install binary](https://static.rust-lang.org/rustup/dist/armv7-unknown-linux-gnueabihf/rustup-init).

Are these libraries being ignored by kaniko for some reason? Shouldn't they be copied over from the `python3.7` image automatically, without me specifying them explicitly, since my Dockerfile says that it's based on `python:3.7`, and those libraries are in `python:3.7`?

**Comment by imjasonh** [comment]
Yeah that would be my expectation too. Is there anything interesting in the build logs that indicates kaniko is skipping those paths for some reason?

**Comment by tal-zvon** [comment]
Doesn't look like it.
With a simple dockerfile like this:

```
FROM python:3.7
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
CMD /bin/sh
```

running this command:

```
docker container run \
    --rm \
    -v $PWD:/app \
    --entrypoint="" \
    --privileged \
    OUR_COMPANY_CONTAINER_REGISTRY_SERVER/tal/kaniko/executor:debug \
    /kaniko/executor \
        --context /app \
        --dockerfile /app/dockerfile \
        --destination=test:latest \
        --tarPath=/app/out.tar \
        --no-push
```

results in these logs:

```
INFO[0000] Retrieving image manifest python:3.7
INFO[0000] Retrieving image python:3.7 from registry index.docker.io
ERRO[0000] Error parsing the serverURL                   error="docker-credential-ecr-login can only be used with Amazon Elastic Container Registry." serverURL=index.docker.io/library/python
INFO[0001] Built cross stage deps: map[]
INFO[0001] Retrieving image manifest python:3.7
INFO[0001] Returning cached image manifest
INFO[0001] Executing 0 build triggers
INFO[0001] Unpacking rootfs as cmd RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y requires it.
INFO[0228] RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
INFO[0228] Taking snapshot of full filesystem...
INFO[0267] cmd: /bin/sh
INFO[0267] args: [-c curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y]
INFO[0267] Running: [/bin/sh -c curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y]
info: downloading installer
main: line 449: /tmp/tmp.XZfQgvP6mq/rustup-init: No such file or directory
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
```

This is all running on a raspberry pi.
The `executor:debug` image here was built using `make images` on the kaniko main branch, for the raspberry pi architecture. I don't have the exact commit of kaniko I used, but it was the latest one a few days ago.

**Comment by imjasonh** [comment]
Can you try with `-v=debug` or `-v=trace`? This might give us more logs about why those paths are being excluded.

**Comment by tal-zvon** [comment]
[Debug logs](https://pastebin.com/jJUv7ZVd)
[Trace logs](https://drive.google.com/file/d/1CAACUa6uB0i7OZt-2zdPDQPaGrJmDsB5/view?usp=sharing)

The trace level logs were actually too big for pastebin :)

The majority of the libraries that I had to copy over manually from `python:3.7` were in `/lib/arm-linux-gnueabihf`.
Neither the Debug, nor the Trace logs have any mention of `arm-linux-gnueabihf`.

**Comment by imjasonh** [comment]
So I think I figured it out.

`python:3.7` is a multi-platform image, with support for both `linux/arm/v5` and `linux/arm/v7` CPU variants.

If you don't pass a custom platform, Kaniko will attempt to guess your current runtime platform, but only takes into account the OS and architecture, and not the CPU variants:

https://github.com/GoogleContainerTools/kaniko/blob/76624697df879f7c3e3348f22b8c986071af4835/pkg/executor/build.go#L629

The result is, it's using the `arm/v5` image, and you want the `arm/v7` image. The `arm/v5` image has `/lib/arm-linux-gnueabi/libdl.so.2`, the `v7` image has `/lib/arm-linux-gnueabihf/libdl.so.2` which you're looking for.

Try adding `--customPlatform=linux/arm/v7`, and see if that works. If it does, I can make Kaniko's runtime platform detection smarter about selecting the right CPU variant, so you don't need the flag.

**Comment by tal-zvon** [comment]
Confirmed - adding `--customPlatform=linux/arm/v7` fixes the issue. No more need for `COPY --from=python:3.7` lines. Everything works great.

Thank you - I really appreciate it.

Do you want me to keep this issue open so it can be auto-closed when the pull request is accepted and merged?

**Comment by imjasonh** [comment]
Yeah, let's keep this open until merging the fix fixes it.

I'm glad that worked, I had no idea what the problem would be if it wasn't that! 😅

**Comment by tal-zvon** [comment]
Awesome.

Thanks again
