### ISSUE TITLE
Docker images without "v" prefix

### ISSUE THREAD

**Issue by iFrozenPhoenix** [GoogleContainerTools/kaniko#1931]
Currently the docker images are published with a v prefix which is not semver conform.

Would it be possible to publish the images without the "v" prefix, so that they are semver conform?
This would enable automation tools to parse the version in a standard way so that they can e.g. load the latest image by the version no instead of the latest tag.

**Comment by imjasonh** [comment]
I'm not sure this is worth the additional complexity in automating both versions of the tag, and making sure they stay synced.

What system are you using that has difficulty with the `v` prefix? It seems like that's a fairly common practice, even if it might not be exactly semver.

**Comment by imjasonh** [comment]
That seems like a reasonable workflow, I don't know of anything better off the top of my head. Having to account for the `v` prefix is annoying, but I can at least pretty reliably promise that it'll only ever be the form we have now, `v1.2.3`, and not anything more complex than that. The logic to detect and strip the `v` prefix should be straightforward in Go or Bash at least.

Sorry this isn't a very helpful response, I'm just not sure it's worth the ongoing operational complexity to push `:1.2.3` in addition to `:v1.2.3` for existing users, and sync the two.
