### ISSUE TITLE
[bug] `getContainerRuntime` reports error with `gcr.io/kaniko-project/executor:debug`

### ISSUE THREAD

**Issue by gabyx** [GoogleContainerTools/kaniko#1936]
**Actual behavior**

I get a wrong detection of "kaniko not running inside container" when `gcr.io/kaniko-project/executor:debug` is used.

**Expected behavior**
It is running inside a container, and the warning should not be seen.

**To Reproduce**

1. When I build the image with `make image` myself on `main`.
and 
2. `docker run -it -v $(pwd):/workspace gcr.io/kaniko-project/executor:debug --dockerfile /workspace/Dockerfile`
3. I get a wrong detection of "kaniko not running inside container".

**Additional Information**
 - Dockerfile 
  ```
  FROM alpine:latest
  ```

-  Host: macOS

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by imjasonh** [comment]
I've seen this before during testing, but I'm not able to reproduce with the latest pushed image: `:ef97636546f21ecacd714f3c486b0593dd071314-debug`:

```
docker run -it -v $(pwd):/workspace gcr.io/kaniko-project/executor:ef97636546f21ecacd714f3c486b0593dd071314-debug --dockerfile /workspace/Dockerfile --no-push
```

**Comment by agargiulo** [comment]
I seem to have a related issue but I'm not sure if it's the same thing or not.
Previously I was able to use the executor:debug image to run a shell and in that shell run `/kaniko/executor ...` but now I'm only able to use the above method to build images. 
If I try to run kaniko exeuctor from inside a shell in the `gcr.io/kaniko-project/executor:debug` images I get the `kaniko should only be run inside of a container, run with the --force flag if you are sure you want to continue` message
