### ISSUE TITLE
[bug] Kaniko silently crashs

### ISSUE THREAD

**Issue by gabyx** [GoogleContainerTools/kaniko#1954]
**Actual behavior**

Exactly c6623cd1e350b6f99a889b8a19eec10161a946ac or docker build of kaniko:
explicitly `gcr.io/kaniko-project/executor:c6623cd1e350b6f99a889b8a19eec10161a946ac-debug`
contains weird behavior (probably segfaulting with no output). 

```shell
docker run --rm  -it \
  -v "$(pwd)":/workspace \
  --entrypoint=/busybox/sh \
  gcr.io/kaniko-project/executor:c6623cd1e350b6f99a889b8a19eec10161a946ac-debug \
  script.sh
```

where `script.sh` is something like

```shell
/kaniko/executor \
    --context "dir:///workspace" \
    --ignore-path "/run" \
    --cleanup  .......
```

The `executor` crashes directly after a `RUN` command is finished and a `INFO[0122] Taking snapshot of full filesystem...` should be issued (its not). No stacktrace, nothing, the whole docker run just exits with 0
With the commit on `main` before that, there is no problem.

**Expected behavior**
Log line `INFO[0122] Taking snapshot of full filesystem...` is issued and kaniko runs through successfully.

**To Reproduce**
Hard to say, what the problem is. There is just no problem with `c6623cd1e350b6f99a889b8a19eec10161a946ac^`

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by imjasonh** [comment]
Hey, could you try `:f067edae9f077393398ad52abf2fcca5e5a37a75` (it's still being built, hot off the presses!), and see if you see different behavior? There was a bug where all logs were being dropped.

**Comment by gabyx** [comment]
Thanks for mentioning that. I test this.

**Comment by crucialfelix** [comment]
This most recent commit works for me!

```yaml
    name: "gcr.io/kaniko-project/executor:f067edae9f077393398ad52abf2fcca5e5a37a75"
```

The current docker :latest tag is not working at all. It times out, posts no logs. I tried with both cache on and off.

#1959 fixed that. 

```
ID                                    CREATE_TIME                DURATION  SOURCE  IMAGES  STATUS
ba99c8c6-5025-4649-98dc-00f70a310a5f  2022-03-01T16:55:33+00:00  10M5S     -       -       SUCCESS  cache on
60bdbd4a-a1bd-4ef8-9955-6421c3f299b2  2022-03-01T16:38:29+00:00  14M26S    -       -       SUCCESS  cache off
554e57d3-739e-44d2-9f9a-d1e3e7510555  2022-03-01T16:12:53+00:00  11M51S    -       -       FAILURE
dcae2d97-bc0b-484b-a448-8139686c9f60  2022-03-01T15:58:43+00:00  6M42S     -       -       FAILURE
1e5c4f4e-4550-41e2-96ad-b57d936f969e  2022-03-01T14:47:48+00:00            -       -       FAILURE
2323f5dd-fe98-460a-929c-b634bf7cb1c2  2022-03-01T14:25:38+00:00  10M1S     -       -       TIMEOUT
61d33db1-2117-47ff-a0b1-38c94e6d96cc  2022-03-01T12:42:41+00:00  8M38S     -       -       FAILURE
eb9bba4e-71ce-4ed4-9c24-6ffb43792b86  2022-02-17T13:35:51+00:00  10M23S    -       -       TIMEOUT
50f45e19-ada2-4fe9-8fca-12ec53f602b4  2022-02-15T13:12:31+00:00  10M1S     -       -       TIMEOUT
```

I expect build times will return to about 4 minutes now that cache is back on.

**Comment by gabyx** [comment]
I guess: #1959 fixed this issue. "executor:f067edae9f077393398ad52abf2fcca5e5a37a75" works for me too

**Comment by Mistic92** [comment]
It's happening for me with python dockerfile especially when installing torch even smaller cpu only version
```
RUN pip install -vvv -r ${APP_ROOT}/requirements.txt -f https://download.pytorch.org/whl/torch_stable.html
```
Kaniko on minikube is running with below arguments
```
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:ceb2bdf4c829f1923a2bd4ae5b0f82e4e3e68ace-debug
    args: ["--dockerfile=Dockerfile",
            "--context=./",
            "--snapshotMode=redo",
            "--verbosity=debug",
            "--use-new-run",
            "--no-push"] 
```

```
...
Skipping link: not a file: https://pypi.org/simple/torch/
Given no hashes to check 1 links for project 'torch': discarding no candidates
Collecting torch==1.9.0+cpu
  Created temporary directory: /tmp/pip-unpack-uiev3y2e
  Looking up "https://download.pytorch.org/whl/cpu/torch-1.9.0%2Bcpu-cp38-cp38-linux_x86_64.whl" in the cache
  No cache entry available
  https://download.pytorch.org:443 "GET /whl/cpu/torch-1.9.0%2Bcpu-cp38-cp38-linux_x86_64.whl HTTP/1.1" 200 175478746
  Downloading https://download.pytorch.org/whl/cpu/torch-1.9.0%2Bcpu-cp38-cp38-linux_x86_64.whl (175.5 MB)
  Updating cache with response from "https://download.pytorch.org/whl/cpu/torch-1.9.0%2Bcpu-cp38-cp38-linux_x86_64.whl"
  Caching due to etag
Killed
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 137
```
I was trying to run this on Gitlab and local minikube with the same result. 

This output is from `gcr.io/kaniko-project/executor:f067edae9f077393398ad52abf2fcca5e5a37a75-debug`

**Comment by imjasonh** [comment]
@Mistic92 this sounds like a different issue than the one described in the issue.

It may even be a bug with `download.pytorch.org`, or with `pip install`. If you see the same errors using `docker build` this may not be a bug in Kaniko at all.

**Comment by gabyx** [comment]
Check that urls which it is accessing, might be due to missing certificates on the POD.

**Comment by Mistic92** [comment]
In second run it passed but now tensorflow crashed. In minikube I found OOM but it's crashing even on k8s pod with 10GB memory limit :/ 
But from below log I see that `pip` is throwing oom not kaniko itself. 

```
al_pcp:260kB free_cma:0kB
[  +0.000000] lowmem_reserve[]: 0 0 0 0 0
[  +0.000003] DMA: 1*4kB (U) 0*8kB 0*16kB 1*32kB (U) 2*64kB (U) 1*128kB (U) 1*256kB (U) 0*512kB 0*1024kB 1*2048kB (M) 3*4096kB (M) = 14884kB
[  +0.000008] DMA32: 1911*4kB (UE) 888*8kB (UE) 645*16kB (UE) 233*32kB (UME) 116*64kB (UME) 56*128kB (UME) 16*256kB (ME) 2*512kB (M) 0*1024kB 0*2048kB 0*4096kB = 52236kB
[  +0.000008] Normal: 1250*4kB (UME) 586*8kB (UME) 280*16kB (UE) 84*32kB (UE) 51*64kB (UME) 19*128kB (ME) 2*256kB (M) 0*512kB 0*1024kB 0*2048kB 0*4096kB = 23064kB
[  +0.000010] 94259 total pagecache pages
[  +0.000001] 21880 pages in swap cache
[  +0.000001] Swap cache stats: add 869077, delete 847197, find 97345/187652
[  +0.000001] Free swap  = 0kB
[  +0.000000] Total swap = 2097152kB
[  +0.000001] 1572511 pages RAM
[  +0.000000] 0 pages HighMem/MovableOnly
[  +0.000001] 52692 pages reserved
[  +0.000304] Out of memory: Killed process 67044 (pip) total-vm:862324kB, anon-rss:612040kB, file-rss:4kB, shmem-rss:0kB, UID:0 pgtables:1276kB oom_score_adj:1000
```
