### ISSUE TITLE
[CRITICAL BUG] Build log missing since #1946

### ISSUE THREAD

**Issue by zzh8829** [GoogleContainerTools/kaniko#1955]
**Actual behavior**

All logging output from kaniko's log.Info/Warn/Debug are missing 

**Expected behavior**

log.Info should output log

**To Reproduce**
1. Use docker image built after #1946 for example `gcr.io/kaniko-project/executor:9969c747034aee243a630412c0d74e788eca0d2a`

2. run a basic build with `no-push`

```
docker run --rm gcr.io/kaniko-project/executor:9969c747034aee243a630412c0d74e788eca0d2a --dockerfile Dockerfile --context /workspace --no-push
```

everything works fine

3. run a basic build with any destination 

```
docker run --rm gcr.io/kaniko-project/executor:9969c747034aee243a630412c0d74e788eca0d2a --dockerfile Dockerfile --context /workspace --destination $DOCKER_REPO
```

there is no log output from kaniko

**Additional Information**
Reason why this happens 
In https://github.com/GoogleContainerTools/kaniko/pull/1946
https://github.com/GoogleContainerTools/kaniko/pull/1946/files#diff-b0cd856098c47c7aa75c3c9299bb998d62e14e567bced865808d76576a360336R33
Set EcrHelper's logging out put to ioutil.Discard presumably it stops aws from printing things like `no valid credential found`

But EcrHelper uses logrus.StandardLogger() which is shared by Kaniko's logger. When setting ecr.log to discard this will actually unexpected set kaniko's log to discard as well.

I didn't make a pull request because im not too sure how we want to fix this
removing ecr junk log is pretty nice but we can't have it remove all kaniko logs 😓 
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by zzh8829** [comment]
I believe this is also the root cause for https://github.com/GoogleContainerTools/kaniko/issues/1954

**Comment by imjasonh** [comment]
Ugh, that is unfortunate. And entirely my own oversight, since I was too focused on disabling logrus for users who don't want it, and didn't even think about those who would want it. 😞 

Let me think on it a bit and see if we can come up with something. It might require changes to ecr-login to make them use a dedicated logger (set to stderr by default), so that it can be selectively disabled without disabling the shared global logger.

**Comment by imjasonh** [comment]
In the meantime, I've patched the ecr-login PR above and built:

```
gcr.io/imjasonh/executor@sha256:4e322efeee7de6b1cb963263e366f2c83f29726f6b2e3da93eeb1a4fc6444100
```

...which seems to fix the issue. Please let me know if you see other behavior.

**Comment by imjasonh** [comment]
This is also why integration tests are failing. Tests check for some log output, and don't find it.

If the ecr-login change isn't merged soon I may revert the breaking commit, or patch it.

Sorry for missing this.
