### ISSUE TITLE
Unrecognized challenge: BASIC

### ISSUE THREAD

**Issue by ErikWegner** [GoogleContainerTools/kaniko#196]
I am trying to build a container image inside kubernetes. The command `docker run -v ~/.docker:/root/.docker -v ~/workspace:/workspace gcr.io/kaniko-project/executor:latest -f Dockerfile -d privateregistry.example.com/org1/hello:v1 -c /workspace` builds the image and tries to upload it to my private registry. The output is:

    time="2018-06-01T11:40:00Z" level=info msg="Unpacking filesystem of hello-world:linux..."
    2018/06/01 11:40:00 No matching credentials found for index.docker.io, falling back on anonymous
    time="2018-06-01T11:40:01Z" level=info msg="Mounted directories: [/kaniko /var/run /proc /dev /dev/pts /sys /sys/fs/cgroup /sys/fs/cgroup/systemd /sys/fs/cgroup/cpuset /sys/fs/cgroup/memory /sys/fs/cgroup/net_cls /sys/fs/cgroup/hugetlb /sys/fs/cgroup/cpu,cpuacct /sys/fs/cgroup/devices /sys/fs/cgroup/blkio /sys/fs/cgroup/perf_event /sys/fs/cgroup/freezer /sys/fs/cgroup/pids /dev/mqueue /workspace /root/.docker /etc/resolv.conf /etc/hostname /etc/hosts /dev/shm /proc/asound /proc/bus /proc/fs /proc/irq /proc/sys /proc/sysrq-trigger /proc/kcore /proc/timer_list /proc/timer_stats /sys/firmware]"
    time="2018-06-01T11:40:01Z" level=info msg="Unpacking layer: 0"
    time="2018-06-01T11:40:02Z" level=info msg="Taking snapshot of full filesystem..."
    time="2018-06-01T11:40:04Z" level=error msg="Unrecognized challenge: BASIC"

Credentials for the private registry are inside the .docker/config.json file:

    {
      "auths": {
        "privateregistry.example.com": {
          "auth": "base64 encoded username:password"
        }
      }
    }

What does the error message mean? Which steps may help?

**Comment by priyawadhwa** [comment]
Initially I thought the error might be coming from [here](https://github.com/google/go-containerregistry/blob/0ff1db03aaaabc9820e8a13353f61d8474814abd/v1/remote/transport/transport.go#L82) while trying to get the config file, but I was able to build an image based off `hello-world:linux` and push it to GCR and Docker registry.

Could you provide the Dockerfile you're trying to build?

**Comment by ErikWegner** [comment]
This is my Dockerfile:

    FROM hello-world:linux
    
    

How do I know which auth path is required?

**Comment by jonjohnsonjr** [comment]
This is fixed upstream 👍

**Comment by ErikWegner** [comment]
Works now, thank you.
