### ISSUE TITLE
GCR cred helper with workload-id not working in 1.8.0

### ISSUE THREAD

**Issue by bizrad** [GoogleContainerTools/kaniko#1980]
**Actual behavior**
When trying to build an image that uses a base image from marketplace.gcr.io the build fails with the following error in both 1.7.0 and 1.8.0.

This can be reproduced in Google Kubernetes Engine or in a GCP VM.

```
INFO[0000] Retrieving image manifest marketplace.gcr.io/google/debian10
INFO[0000] Retrieving image marketplace.gcr.io/google/debian10 from registry marketplace.gcr.io
error building image: GET https://marketplace.gcr.io/v2/token?scope=repository%3Agoogle%2Fdebian10%3Apull&service=marketplace.gcr.io: UNAUTHORIZED: Not Authorized.
```

/kaniko/.docker/config.json
```
{
  "auths": {},
  "credHelpers": {
    "asia.gcr.io": "gcr",
    "eu.gcr.io": "gcr",
    "gcr.io": "gcr",
    "marketplace.gcr.io": "gcr",
    "staging-k8s.gcr.io": "gcr",
    "us.gcr.io": "gcr"
  }
}
```

**Expected behavior**
Build passes

**To Reproduce**
1. Spin up a Debian 10 VM on GCP
2. Enable Container Registry API on the GCP project (not sure if needed)
3. SSH to VM instance
4. [Install docker engine](https://docs.docker.com/engine/install/debian/) on VM
5. Switch to root user `sudo su -`
6. Run kaniko container 
`docker run -it --rm --entrypoint="sh" gcr.io/kaniko-project/executor:v1.8.0-debug`
8. Echo in docker config
```
echo -e '{"auths": {},"credHelpers": {"asia.gcr.io": "gcr","eu.gcr.io": "gcr","gcr.io": "gcr","marketplace.gcr.io": "gcr","staging-k8s.gcr.io": "gcr","us.gcr.io": "gcr"}}'>/kaniko/.docker/config.json
```
10. Echo in Dockerfile
```
echo -e 'FROM marketplace.gcr.io/google/debian10\nRUN echo "true"\n'>Dockerfile
```
12. Run build command  
```
/kaniko/executor --single-snapshot --dockerfile Dockerfile --no-push
```      

**Additional Information**
 - Dockerfile 
```
FROM marketplace.gcr.io/google/debian10
RUN echo "true"
```

 - Kaniko Image (fully qualified with digest)
 
1.8.0-debug image tried and fails: 
`image: gcr.io/kaniko-project/executor@sha256:0d8408715c7bcc2dc747405936c0e72665cafb2357fb78e23eb71f90bc39624f`

1.7.0-debug image tried and fails:
`gcr.io/kaniko-project/executor@sha256:88dacc7ea3f5c04709eae96776693c717869405364b19d6e78850fe54c63c6a2`

1.6.0-debug image works:
`gcr.io/kaniko-project/executor:v1.6.0-debug`
`gcr.io/kaniko-project/executor@sha256:fcccd2ab9f3892e33fc7f2e950c8e4fc665e7a4c66f6a9d70b300d7a2103592f`
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by imjasonh** [comment]
Out of curiosity, are you able to see the same failure if you _don't_ add the Docker config at `/kaniko/.docker/config.json`?

**Comment by imjasonh** [comment]
Also: what error message / logs do you see when it fails with 1.8.0?

**Comment by bizrad** [comment]
@imjasonh interesting, it appears that if I leave out the docker config.json file copy then it works

```
# docker run -it --rm --entrypoint="sh" gcr.io/kaniko-project/executor:v1.8.0-debug
/workspace # echo -e 'FROM marketplace.gcr.io/google/debian10\nRUN echo "true"\n'>Dockerfile
/workspace # /kaniko/executor --single-snapshot --dockerfile Dockerfile --no-push
INFO[0000] Retrieving image manifest marketplace.gcr.io/google/debian10
INFO[0000] Retrieving image marketplace.gcr.io/google/debian10 from registry marketplace.gcr.io
INFO[0000] Built cross stage deps: map[]
INFO[0000] Retrieving image manifest marketplace.gcr.io/google/debian10
INFO[0000] Returning cached image manifest
INFO[0000] Executing 0 build triggers
INFO[0000] Unpacking rootfs as cmd RUN echo "true" requires it.
INFO[0004] Taking snapshot of full filesystem...
INFO[0006] RUN echo "true"
INFO[0006] cmd: /bin/sh
INFO[0006] args: [-c echo "true"]
INFO[0006] Running: [/bin/sh -c echo "true"]
true
INFO[0006] Taking snapshot of full filesystem...
INFO[0007] No files were changed, appending empty layer to config. No layer added to image.
INFO[0007] Skipping push to container registry due to --no-push flag
/workspace # ls -la /kaniko/.docker/
total 8
drwxr-xr-x    2 root     root          4096 Mar  9 01:57 .
drwxr-xr-x    1 root     root          4096 Mar 10 21:36 ..
/workspace # echo -e '{"auths": {},"credHelpers": {"asia.gcr.io": "gcr","eu.gcr.io": "gcr","gcr.io": "gcr","marketplace.gcr.io": "gcr","staging-k8s.gcr.io": "gcr","us.gcr.io": "gcr"}}'>/kaniko/.docker/config.json
/workspace # /kaniko/executor --single-snapshot --dockerfile Dockerfile --no-push
INFO[0000] Retrieving image manifest marketplace.gcr.io/google/debian10
INFO[0000] Retrieving image marketplace.gcr.io/google/debian10 from registry marketplace.gcr.io
error building image: GET https://marketplace.gcr.io/v2/token?scope=repository%3Agoogle%2Fdebian10%3Apull&service=marketplace.gcr.io: UNAUTHORIZED: Not Authorized.
```

However, I'm actually trying to pull from GCR for the base image then also work with private GitLab and dockerhub images.

So my full config looks more like this:
```
{
  "auths": {
    "https://index.docker.io/v1/": {
      "username": "mydockeruser",
      "password": "token"
    },
    "registry.gitlab.com": {
      "username": "gitlab-ci-token",
      "password": "GITLAB_CI_TOKEN"
    }
  },
  "credHelpers": {
    "asia.gcr.io": "gcr",
    "eu.gcr.io": "gcr",
    "gcr.io": "gcr",
    "marketplace.gcr.io": "gcr",
    "staging-k8s.gcr.io": "gcr",
    "us.gcr.io": "gcr"
  }
}
```

**Comment by imjasonh** [comment]
> @imjasonh interesting, it appears that if I leave out the docker config.json file copy then it works

Great!

That means you don't need the `"credHelpers"` section of your config. You can change it to:

```
{
  "auths": {
    "https://index.docker.io/v1/": {
      "username": "mydockeruser",
      "password": "token"
    },
    "registry.gitlab.com": {
      "username": "gitlab-ci-token",
      "password": "GITLAB_CI_TOKEN"
    }
  }
}
```

**Comment by bizrad** [comment]
Nice, that appears to have done the trick! Now everything works. I thought I needed that in there to get things working back with 1.6.0.
Thanks for the help!
