### ISSUE TITLE
I use insecure-skip-tls-verify flag, but also get connection refused error

### ISSUE THREAD

**Issue by StephenLiuYa** [GoogleContainerTools/kaniko#200]
time="2018-06-06T09:59:29Z" level=error msg="Get https://XXX/v2/: dial tcp XXX:443: connect: connection refused"

**Comment by priyawadhwa** [comment]
Hey @StephenLiuYa , this is being worked on in #169

**Comment by priyawadhwa** [comment]
Closing as dupe of #168
