### ISSUE TITLE
`cache-copy-layers` disabled but not during multi-stage images ?

### ISSUE THREAD

**Issue by thomas-tacquet** [GoogleContainerTools/kaniko#2003]
**Actual behavior**
When building my images and multi stages images with --cache-copy-layer at false (or not definied) I was surprised to find that in multi stages images only, kaniko pushes cache layers to target registry. 

I always get the following log entry in my multi stages images : `INFO[0033] Pushing layer REDACTED/REDACTED/REDACTED/cache:REDACTED to cache now`

I think that command arguments are not correctly propagated through build workflow on multi-stage docker images ?

The function pushing cache layers : https://github.com/GoogleContainerTools/kaniko/blob/main/pkg/executor/push.go#L291 if you check call stack it should be called only when CopyCacheLayers is enabled.

**Expected behavior**
I expect that `--copy-cache-layers=false` work with single stage images and multi stages images, but it only works partialy in mutli-stage images

**To Reproduce**
1. Write a multi stage image, for example something found here : https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds 
2. ensure you have cache enabled but copy-cache-layers set at false
3. build the image with kaniko and check that kaniko push sub image cache layers but no first layer
4. try with a single stage image and ensure it does not any push layer

**Additional Information**
 - Dockerfile 
 https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds 
 - Build Context
   Please provide or clearly describe any files needed to build the Dockerfile (ADD/COPY commands)
 - Kaniko Image: tag v1.7.0
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [X] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [X] </li></ul>|

**Comment by thomas-tacquet** [comment]
Thanks to @RamyChaabane for helping me to figure out the problem.

I was testing the flag `--use-new-run`by asserting it would not interfer with other flag, but it does ( https://github.com/GoogleContainerTools/kaniko#--use-new-run ) : 

1. By reading the readme (https://github.com/GoogleContainerTools/kaniko/blob/main/README.md#caching-layers) : `kaniko can cache layers created by RUN and COPY (configured by flag --cache-copy-layers) ` made me think that the flag enable/disabl for COPY and RUN commands but it does not
2. It just changes for COPY commands : [commands.go](https://github.com/GoogleContainerTools/kaniko/blob/1b59a296a8e2f1e1bdc6d248b7cb8038d0cc5a70/pkg/commands/commands.go#L71) 
3. For run [run](https://github.com/GoogleContainerTools/kaniko/blob/1b59a296a8e2f1e1bdc6d248b7cb8038d0cc5a70/pkg/commands/run.go#L195) and [new-run](https://github.com/GoogleContainerTools/kaniko/blob/1b59a296a8e2f1e1bdc6d248b7cb8038d0cc5a70/pkg/commands/run_marker.go#L79) it's at true by default

We will raise a PR to add a flag `--copy-run-layers` to enable or disable copying run layers.

I was wondering if it makes sens to have two flags :  `--cache-copy-layers` &`--cache-run-layers` Instead of having just one `--copy-layers` flag ?

**Comment by imjasonh** [comment]
I'd probably bias toward fewer flags in general, unless there's some strong reason you'd expect folks to only want to cache one type and not the other.

Thanks for looking into this, and thanks for sending a PR!
