### ISSUE TITLE
Help: Does kaniko support looping and concurrent execution

### ISSUE THREAD

**Issue by zhixiongdu027** [GoogleContainerTools/kaniko#2019]
I have an idea, which is add an HttpServer to receive client requests， and then we can execute the following pseudo code:

httpServer:
```
while(true){
    receiver_request --> go { create_opts, executor.DoBuild, executor.DoPush)
}
```

Demo program is complete and seems to work.

I would like to ask the experts, is there any potential risk in this approach?

**Comment by zhixiongdu027** [comment]
thanks for answer
Maybe I can modify it to the following pattern:

```
HttpServer:

while(true){
    receiver_request --> create pod { create_opts, executor.DoBuild, executor.DoPush)
}

```

**Comment by imjasonh** [comment]
Yeah that sounds doable. That's more or less how https://kaniko.kontain.me works, with each request routed to a container that only serves one request at a time.

**Comment by zhixiongdu027** [comment]
Many TKS
