### ISSUE TITLE
using mvn spring-boot:build-image to build images, is there a way to retag the image using kaniko

### ISSUE THREAD

**Issue by Gmanweb** [GoogleContainerTools/kaniko#2026]
Hi all

One of our teams doesn't use docker files in their spring-boot applications, they run the following commands from Jenkins.

```
sh "mvn spring-boot:build-image -pl ${MODULE_NAME}"
sh "docker tag ${APP_NAME}:${POM_VERSION} ${OUR_PRIVATE_REGISTRY}/${APP_NAME}:${APP_TAG_VERSION}"
```

For other project we use kanika
```
container(name: 'kaniko', shell: '/busybox/sh') {
     sh """#!/busybox/sh
         /kaniko/executor --context `pwd` --destination ${OUR_PRIVATE_REGISTRY}/${APP_NAME}:${APP_TAG_VERSION}
     """
}
```

Is there a way we can remove the docker tag and use kaniko to do the tagging?

Or does kaniko integrate with the spring-boot application easily?

Any example you can recommend so I can suggest to them to migrate.

**Comment by imjasonh** [comment]
Kaniko doesn't have any functionality to move or retag images, but other tools like [`crane`](https://github.com/google/go-containerregistry/blob/main/cmd/crane) or Skopeo do, e.g.:

```
crane cp ${APP_NAME}:${POM_VERSION} ${OUR_PRIVATE_REGISTRY}/${APP_NAME}:${APP_TAG_VERSION}
```

**Comment by kumprj** [comment]
We use Crane to copy images around JFrog.

**Comment by Gmanweb** [comment]
Hey, thanks for the suggestion on Crane, and I will look into.

With Kaniko I don't need docker is this the same and does Crane integrate easily with Jenkins. 

Any working example I can look at for using with spring boot and running on a Jenkins pipeline (running in Kubernetes)

**Comment by kumprj** [comment]
We use Jenkins in k8s and use Kaniko to build images. We push them to JFrog Artifactory, then we copy images from JFrog to ECR with crane so they maintain the sha. 

You just have to echo the auth (ecr helper and jfrog user + token in our case) to /kaniko/.docker/config.json
