### ISSUE TITLE
Run Kaniko container without executing 

### ISSUE THREAD

**Issue by romanzdk** [GoogleContainerTools/kaniko#2058]
I need to use Kaniko in my existing docker container, however I am unable to use Kaniko image without executing it on run.

Is it possible to somehow just include executables of Kaniko in my container so I can run it on-demand?

**Comment by imjasonh** [comment]
I'm not entirely sure I understand what you're asking, but just in case it's helpful anyway, sure, you can include Kaniko's executable in your image, by adding this line to your Dockerfile:

```
FROM whatever-base-image
...
COPY --from gcr.io/kaniko-project/executor /kaniko/executor /kaniko/executor
```

Then the Kaniko executor image will be present in your image, and you can run it any way you want.

**Comment by romanzdk** [comment]
Yes that's it (except the missing "=" :)). Thank you.
