### ISSUE TITLE
can build dockerfile with --pull and --rm args

### ISSUE THREAD

**Issue by StephenLiuYa** [GoogleContainerTools/kaniko#207]

**Comment by priyawadhwa** [comment]
Currently there is no caching in kaniko so it always pulls the latest version of an image. We also don't build any intermediate containers, so neither of these flags apply to kaniko as of now!

**Comment by StephenLiuYa** [comment]
@priyawadhwa  I just want to change the entrypoint  to reuse the pod to build image.
