### ISSUE TITLE
Issue with authentication

### ISSUE THREAD

**Issue by palnabarun** [GoogleContainerTools/kaniko#212]
I am trying to build an image locally and pushing it to AWS ECR.

```
$ sudo docker run -v ${PWD}:${PWD} -v ${HOME}/.docker:/root/.docker -v ${HOME}/.aws:/root/.aws -e DOCKER_CONFIG=/root/.docker gcr.io/kaniko-project/executor:latest -d $ECR/firefly-fib:latest -c ${PWD}
time="2018-06-21T06:54:38Z" level=info msg="appending to multi args XXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/firefly-fib:latest"
time="2018-06-21T06:54:38Z" level=info msg="Unpacking filesystem of firefly..."
2018/06/21 06:54:38 No matching credentials found for index.docker.io, falling back on anonymous
time="2018-06-21T06:54:41Z" level=info msg="Mounted directories: [/kaniko /var/run /proc /dev /dev/pts /sys /sys/fs/cgroup /sys/fs/cgroup/systemd /sys/fs/cgroup/memory /sys/fs/cgroup/blkio /sys/fs/cgroup/net_cls,net_prio /sys/fs/cgroup/devices /sys/fs/cgroup/pids /sys/fs/cgroup/cpuset /sys/fs/cgroup/freezer /sys/fs/cgroup/hugetlb /sys/fs/cgroup/cpu,cpuacct /sys/fs/cgroup/rdma /sys/fs/cgroup/perf_event /dev/mqueue /root/.docker /root/.aws /etc/resolv.conf /etc/hostname /etc/hosts /dev/shm /mnt/Data_SSD/codes/rorodata/kubernetes-sandbox/firefly-sq /proc/asound /proc/bus /proc/fs /proc/irq /proc/sys /proc/sysrq-trigger /proc/kcore /proc/timer_list /proc/sched_debug /sys/firmware]"
time="2018-06-21T06:54:42Z" level=error msg="UNAUTHORIZED: \"authentication required\""
```

I am logged in to Docker with the ECR credentials. I browsed through the issues  but couldn't find any relevant information. I am not able to figure out what I am doing wrong. Any insights on this would be helpful.

Edit: The command that I am using.

**Comment by Boolman** [comment]
If you look at the dockerfile, it uses /kaniko/.docker/ instead of $HOME/.docker

ENV DOCKER_CONFIG /kaniko/.docker/

so you should probably add an -e DOCKER_CONFIG=/root/.docker/

**Comment by priyawadhwa** [comment]
It looks like you're trying to pull a private image from the Docker registry as the base image of your Dockerfile, is that correct? If so, are those credentials included in your docker config?

**Comment by palnabarun** [comment]
No. The image that I am basing my Dockerfile from is from a public repository.

In any case, my docker hub is present in the config.json that I am passing in to kaniko.

**Comment by priyawadhwa** [comment]
Ah, could you tell me what base image you're trying to use?

**Comment by palnabarun** [comment]
Sure. Here it is: https://hub.docker.com/r/palnabarun/firefly/

**Comment by priyawadhwa** [comment]
From this line in the logs:
`time="2018-06-21T06:54:38Z" level=info msg="Unpacking filesystem of firefly..."`
it looks like you may have specified the base image as `firefly` instead of `palnabarun/firefly`, which I was able to build and push with successfully.

**Comment by palnabarun** [comment]
Ah. Okay. I got the mistake now.

I will try and update the issue accordingly.

**Comment by palnabarun** [comment]
Thanks. This worked.
