### ISSUE TITLE
Error: error resolving dockerfile path: copying dockerfile: open /kaniko/Dockerfile: permission denied  "chown /kaniko/Dockerfile:operation not permitted"

### ISSUE THREAD

**Issue by BobbyNie** [GoogleContainerTools/kaniko#2122]
**Actual behavior**

when run in openshift it can't run as root.  

get error:
Error: error resolving dockerfile path: copying dockerfile: open /kaniko/Dockerfile: permission denied

after fix by make a new image chmod 777 to /kaniko, got   "Error: error resolving dockerfile path: copying dockerfile: chown /kaniko/Dockerfile:operation not permitted"

Dockerfile like this:

FROM gcr.io/kaniko-project/executor as kaniko
FROM bash:latest
COPY --from=kaniko / /
RUN chmod -R 777 /kaniko
ENTRYPOINT ["/kaniko/executor"]
WORKDIR /workspace
ENV DOCKER_CREDENTIAL_GCR_CONFIG=/kaniko/.config/gcloud/docker_credential_gcr_config.json
ENV DOCKER_CONFIG=/kaniko/.docker/
ENV SSL_CERT_DIR=/kaniko/ssl/certs
ENV PATH=/usr/locdal/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/kaniko
ENV HOME=/kaniko

 
**Additional Information**

maybe do not chown in fs_util.CopyFile  will work

https://github.com/GoogleContainerTools/kaniko/blob/e14ad85eadb0885639fc06176ecb87b28c0a7e1f/pkg/util/fs_util.go#L805

func CopyFile(src, dest string, context FileContext, uid, gid int64) (bool, error)

**Comment by hown3d** [comment]
Can you provide a bit more background on this? With which securityContext (user, group etc.) are you building inside the openshift cluster?

**Comment by BobbyNie** [comment]
> 
Thanks for replay.

Yes , Run kaniko in openshift cluster.
actually this attempt not work  when the Dockerfile contained any copy or run  cmd.

finally I  created a service account  and give it anyuid permission. then runAsUser 0.

**Comment by karthiravich** [comment]
Hello. Same issue for me. I need to create container images using /kaniko on our OKD cluster as part of the CI process . The workload runs as Jenkins agent pod in the OKD cluster and currently there is a requirement to run the container as non-root user .  Is there a way we can get the kaniko container running **without runAsUser 0** in the securityContext?
