### ISSUE TITLE
HOWTO: Using Skaffold with Kaniko and ECR

### ISSUE THREAD

**Issue by jicowan** [GoogleContainerTools/kaniko#213]
How would you configure Skaffold to use Kaniko to build images in a k8s pod and then push the resulting image to an ECR registry?

**Comment by priyawadhwa** [comment]
Hey @jicowan, to push to ECR with kaniko you need to be able to mount in your own config.json and aws credentials file (which I think you can already do in skaffold as a secret). I'd open an issue in skaffold to add support for this, and then it should work.
