### ISSUE TITLE
Executor issue when doing multiple /kaniko/executor runs a pipeline

### ISSUE THREAD

**Issue by E-N-G-XOR** [GoogleContainerTools/kaniko#2143]
Hey all, so I am attempting to push an image to quay.io. I have a little script that sets the login info to the config.json, but, ass soon as the executor pod launche it crashes with the error ( )

13:09:40  Warning: A secret was passed to "sh" using Groovy String interpolation, which is insecure.
13:09:40  		 Affected argument(s) used the following variable(s): [TOKEN]
13:09:40  		 See https://jenkins.io/redirect/groovy-string-interpolation for details.
13:09:40  ERROR: Process exited immediately after creation. See output below
13:09:40  Executing sh script inside container kaniko of pod bag-service-pr-55-7-lbpvk
13:09:40  OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: chdir to cwd ("/workspace") set in config.json failed: no such file or directory: unknown 

It happens on v1.81-debug though to all the old versions except v1.3.0. Is this a bug?  

The jenkins stage I am running is pretty simple... 

stage('Kaniko: Publish') {
    dir(image.folder) {
      sh """
        /kaniko/executor \
        --dockerfile=Dockerfile --context `pwd` \
        --destination ${registryUrl}/${image.name}:${tag} \
        --image-name-with-digest-file image-name-with-digest-file
      """
      String imageNameWithDigest = readFile file: 'image-name-with-digest-file'
      env.IMAGE_DIGEST = imageNameWithDigest.split(':')[1]
      currentBuild.description = "Published with tag: $tag ,digest : $env.IMAGE_DIGEST"
    }
  }

Yet it craps out as soon as the container launches....

**Comment by mkyc** [comment]
do you have multiple `/kaniko/executor` runs in your pipeline?

**Comment by E-N-G-XOR** [comment]
Yes, the kaniko containers spin up on different nodes I  the cluster. But,
it runs ASAP self-contained container. It runs once in a pipeline and it
using the official image...

**Comment by mkyc** [comment]
Have a look at this issue: https://github.com/GoogleContainerTools/kaniko/issues/1586 

I just had exactly the same problem as mentioned there and between each `/kaniko/executor` command I did additional `mkdir /workspace` and it solved problem for me.
