### ISSUE TITLE
Support relative Dockerfile paths

### ISSUE THREAD

**Issue by ImJasonH** [GoogleContainerTools/kaniko#216]
Currently the path to Dockerfile needs to be absolute. It would be useful to accept a relative path as well.

**Comment by priyawadhwa** [comment]
Hey @ImJasonH, an absolute path or a path relative to the build context should work.

**Comment by dlorenc** [comment]
@ImJasonH did you test this out? As far as I can tell it should work.

**Comment by ImJasonH** [comment]
I see failures when I specify `--dockerfile=./Dockerfile`

```
time="2018-06-26T15:21:44Z" level=error msg="open ./Dockerfile: no such file or directory"
```

Same with `--dockerfile=Dockerfile`

```
time="2018-06-26T15:26:08Z" level=error msg="open Dockerfile: no such file or directory"
```

This works when I change it to an absolute path `/workspace/Dockerfile`.

In this case the build context is a local workspace directory containing only the `Dockerfile` ([this gist](https://gist.github.com/ImJasonH/4940f3f2a0358a178b28e2a1afbaf587), cloned)

**Comment by dlorenc** [comment]
So I think this might be due to the fact that we don't set the CWD to be /workspace inside the container. I'll try changing the Dockerfile to add a WORKDIR.
