### ISSUE TITLE
Support for different base OS like UBI8

### ISSUE THREAD

**Issue by jauyzed** [GoogleContainerTools/kaniko#2186]
Hello,

Being at financial org, usage of alpine image or other OS images like ubuntu/debian is not certainly recommended.  It would be great if there is an option to use RH UBI8 based image. 

Info: https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image

**Comment by lieryan** [comment]
Not quite sure that this really makes sense. IUUC, the kaniko image doesn't use alpine or ubuntu/debian. From my understanding, it is just a statically build go binary.

You can use kaniko to build containers from any base images, and I don't see any reasons why it wouldn't work with RH UBIs.
