### ISSUE TITLE
ECR with S3 context getting error

### ISSUE THREAD

**Issue by suvendu123** [GoogleContainerTools/kaniko#2212]
Error: error resolving source context: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, GetObjectInput.Bucket.

Usage:
  executor [flags]
  executor [command]

----
pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: kaniko-s3
spec:
  containers:
    - name: kaniko-s3
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=Dockerfile"
        - "--context=s3://kanikotest/context.tar.gz"
        - "--destination=<account-id>dkr.ecr.us-west-2.amazonaws.com/kanikorepo/spring-demo"
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
        # when not using instance role
        - name: aws-secret
          mountPath: /root/.aws/
      env:
        - name: AWS_REGION
          value: us-west-2
  restartPolicy: Never
  volumes:
    - name: docker-config
      configMap:
        name: docker-config
    # when not using instance role
    - name: aws-secret
      secret:
        secretName: aws-secret

**Comment by lfarrel6** [comment]
Seeing the same error. It appears to be a regression present in v1.9.0:

Running with: `--context=s3://<S3_BUCKET>/<S3_KEY> --destination=<PATH_IN_REPOSITORY> --force` works for v1.8.1, but returns the error in the original issue on v1.9.0

**Comment by suvendu123** [comment]
Thanks , its working with v1.8.1

**Comment by lfarrel6** [comment]
@suvendu123 I think this issue should be kept open as it's a regression in Kaniko
