### ISSUE TITLE
pushing to registries signed by unknown authority

### ISSUE THREAD

**Issue by efiguti** [GoogleContainerTools/kaniko#224]
it seems that the flag **--insecure-skip-tls-verify**  is not implemented
and when i try to push a image 
error message received

```
2018/07/04 07:02:51 No matching credentials found for XXX:5000, falling back on anonymous
ERRO[0001] Get https://XXX:5000/v2/: x509: certificate signed by unknown authority
```

**Comment by r2d4** [comment]
Dupe of https://github.com/GoogleContainerTools/kaniko/issues/168
