### ISSUE TITLE
using git build context from Azure Devops (ADO) fails

### ISSUE THREAD

**Issue by artbegolli** [GoogleContainerTools/kaniko#2305]
**Actual behavior**

Unable to use context from ADO - receiving status code: 400

Error: error resolving source context: unexpected client error: unexpected requesting "https://org@dev.azure.com/org/project/_git/myrepo/git-upload-pack" status code: 400

Seems as though kaniko is using go-git to clone repositories https://github.com/GoogleContainerTools/kaniko/blob/main/pkg/buildcontext/git.go - go-git doesn't support ADO for reasons outlined in this issue https://github.com/go-git/go-git/issues/64

**Expected behavior**

The repo to be cloned successfully

**To Reproduce**
1. specify --context as any ADO repository

**Additional Information**
 - Dockerfile N/A
   Please provide either the Dockerfile you're trying to build or one that can reproduce this error.
 - Build Context N/A
   Please provide or clearly describe any files needed to build the Dockerfile (ADD/COPY commands)
 - Kaniko Image (fully qualified with digest): kaniko-project/executor:v1.9.1
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ No ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ Yes ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ Yes ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ No ] </li></ul>| 
 
Also - the purpose of this issue is mainly as a reference point for other users of ADO who are trying out kaniko. There doesn't seem to be a fix for ADO cloning provided by go-git and the issue has been outstanding for a number of years.

Internally we're planning on cloning through an init container instead to make the build context available for kaniko to use.

**Comment by aaron-prindle** [comment]
This  was fixed upstream in https://github.com/go-git/go-git/issues/64, see:
https://github.com/go-git/go-git/issues/64#issuecomment-1331764847

and kaniko uses a version of go-git where this patch is merged.  I believe this is fixed now, would appreciate if you can confirm.  Closing this now as I believe it is resolved, feel free to comment and I can re-open.  Thanks
