### ISSUE TITLE
tag v1.9.1 has executor v1.9.0

### ISSUE THREAD

**Issue by flyingsaucerer** [GoogleContainerTools/kaniko#2344]
The image tagged as v1.9.1 actually has executor v1.9.0.
I used the following image `gcr.io/kaniko-project/executor:v1.9.1-slim` but all 1.9.1 tagged images show that the version of the executor is v.1.9.0.

```
podman run --rm <image_id> version
Kaniko version :  v1.9.0
```

**Comment by aaron-prindle** [comment]
As @TobiX mentioned, this was only a display issue. Currently the latest releases have the correct version displayed:

```
aprindle@aprindle-ssd ~/kaniko  [main]docker run gcr.io/kaniko-project/executor:v1.9.1 version
Kaniko version :  v1.9.0
aprindle@aprindle-ssd ~/kaniko  [main]docker run gcr.io/kaniko-project/executor:v1.10.0 version
Kaniko version :  v1.10.0
aprindle@aprindle-ssd ~/kaniko  [main]docker run gcr.io/kaniko-project/executor:v1.9.2 version
Unable to find image 'gcr.io/kaniko-project/executor:v1.9.2' locally
v1.9.2: Pulling from kaniko-project/executor
Digest: sha256:034f15e6fe235490e64a4173d02d0a41f61382450c314fffed9b8ca96dff66b2
Status: Downloaded newer 
```

Closing as versions are displayed correctly for v1.9.2+ versions and there are no plans to re-release old images/bins (typically fix forward)
