### ISSUE TITLE
How can I configure the docker-registry of Aliyun through config.json?

### ISSUE THREAD

**Issue by KawhiWei** [GoogleContainerTools/kaniko#2358]
sh "[ -d $SGR_REGISTRY_CONFIG ] || mkdir -pv $SGR_REGISTRY_CONFIG"
   						sh """#!/busybox/sh -e
                    		echo '{"auths": {"'$SGR_REGISTRY_ADDR'": {"auth": "'$SGR_REGISTRY_AUTH'"}}}' > $SGR_REGISTRY_CONFIG/config.json
						"""
						sh '''#!/busybox/sh
							/kaniko/executor -f $SGR_DOCKER_FILE -c . --destination=$SGR_REPOSITORY_NAME:v$BUILD_NUMBER  --insecure --skip-tls-verify -v=debug
						'''

**Comment by aaron-prindle** [comment]
@KawhiWei were you able to configure authentication w/ Aliyun?  I'm happy to help investigate this, can you provide some additional information on the file(s) or config.json you are attempting to use, what version of kaniko, you are using, the kaniko commands being run and their output (or the error you are seeing)?  Thanks!

**Comment by KawhiWei** [comment]
@aaron-prindle I have solved the problem and thank you very much for your answer.
