### ISSUE TITLE
Broken image produced (one layer cannot be extracted)

### ISSUE THREAD

**Issue by tjohnston-cd** [GoogleContainerTools/kaniko#2398]
**Actual behavior**
I build an image which is based on [the upstream voidlinux image](https://hub.docker.com/layers/voidlinux/voidlinux/latest/images/sha256-26ba972f0c06beadcec4796ec3037e0bec32af4d255edb68a528bd98304c74f4?context=explore).

My build completes successfully with kaniko 1.9.1

However, the produced image cannot be extracted during a `docker pull`. It always fails on one particular layer like this:

```
cf1b8be9c016: Already exists 
928931f0b814: Already exists 
b086025ce20a: Pull complete 
2411607247bd: Extracting  70.78MB/70.78MB
failed to register layer: Error processing tar file(exit status 1): failed to mknod("/usr/share/zoneinfo/p
osix/Africa/Abidjan", S_IFCHR, 0): no such file or directory
```

I will post my minimal reproduction `Dockerfile` below. Images built by `docker build` from this same `Dockerfile` are able to be pulled/extracted.

**Expected behavior**
The image built should be extracted by `docker pull` so that it can be used.

**To Reproduce**

Build from this `Dockerfile`:

```
FROM voidlinux/voidlinux
RUN xbps-install -S
RUN xbps-install -yu xbps && xbps-install -Syu
```

The final line in this `Dockerfile` creates the layer which cannot be extracted (shown above).

Build with something like this command:
`docker run -v $(pwd):/workspace gcr.io/kaniko-project/executor:latest --context =/workspace --dockerfile=./Dockerfile --destination=...`

When I pull the resulting image from my registry, I receive the error shown above.

**Additional Information**
- The upstream base container image was last rebuilt 2 years ago
  - void linux is a rolling release distribution: the packages installed by the 3rd line in my Dockerfile are the latest available versions
  - several months ago, previous builds of this same image (also using kaniko 1.9.1) did not experience this issue
  - they would have been installing older versions of "the latest void linux packages" in the final Dockerfile line
  - this leads me to believe the problem is being exposed by newer versions of the `tzdata` package
    - I have not gone further to test this yet (e.g. by pinning to an older version)
- The `void-packages` issue tracker has [similar issues](https://github.com/void-linux/void-packages/issues/38363) about the `tzdata` package
   - I decided to post this to the kaniko tracker, since the image built by docker (from the same package versions) is working correctly
   - But the issue may be partially the fault of the `tzdata` package as well - not sure! 
- kaniko's `--cache` and `--cleanup` flags do not seem to affect the outcome
  - I did see several similar issues related to caching e.g. #1162, #1217
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by tjohnston-cd** [comment]
Let me know if there is anything you would like me to try - not deeply familiar with kaniko, so I'm trying to digest the related issues and pick out some good debug commands/things to look at in more detail..

**Comment by TobiX** [comment]
Is this the same as #2308?

**Comment by tjohnston-cd** [comment]
> 

Maybe? It certainly seems similar.

I guess I could try a kaniko build from before [the commit you found by bisecting](https://github.com/GoogleContainerTools/kaniko/issues/2308#issuecomment-1448264643) to find out..?

**Comment by aaron-prindle** [comment]
@tjohnston-cd were you able to try kaniko at a previous version to see if that was a workaround?  The version prior to the commit found via bisect is `v1.8.0` - https://github.com/GoogleContainerTools/kaniko/releases/tag/v1.8.0

Additionally a fix PR is currently in progress here - https://github.com/GoogleContainerTools/kaniko/pull/2590 (assuming it's the same issue)

**Comment by TobiX** [comment]
@tjohnston-cd You can try the image `docker.io/andreasfleig/kaniko-executor:debug`, which contains a similar fix (see https://github.com/GoogleContainerTools/kaniko/issues/2308#issuecomment-1597471521)

**Comment by tjohnston-cd** [comment]
Good news!
Builds from `docker.io/andreasfleig/kaniko-executor:debug` are also able to be extracted.

**Comment by tjohnston-cd** [comment]
So.. I guess this can probably be closed. I'll watch for a new release containing the fix(es) and probably be well on my way.

Thanks for the help, especially @andreasf with your changes!

**Comment by tjohnston-cd** [comment]
Just one more thing - happily building images with no trouble on the 1.12.0 release container image.

Thanks again!
