### ISSUE TITLE
cannot create directories via RUN

### ISSUE THREAD

**Issue by sebgoa** [GoogleContainerTools/kaniko#240]
Hi, I am doing a build with kaniko.
My Dockerfile contains a `RUN mkdir foobar` directives.

kaniko errors out (permissions issues I suppose):

```
...
time="2018-07-18T15:00:20Z" level=info msg="Taking snapshot of full filesystem..."
time="2018-07-18T15:00:35Z" level=info msg="Executing 0 build triggers"
time="2018-07-18T15:00:35Z" level=info msg="cmd: /bin/sh"
time="2018-07-18T15:00:35Z" level=info msg="args: [-c mkdir foobar]"
time="2018-07-18T15:00:35Z" level=error msg="exit status 1"
```

**Comment by dlorenc** [comment]
Can you share the full Dockerfile and pod.yaml (assuming you ran in k8s)?

**Comment by sebgoa** [comment]
I am actually running in pain Docker.

```
FROM kubeless/python:3.6
RUN mkdir kubeless
```

I tried:

```
FROM kubeless/python:3.6
RUN mkdir -p /workspace/kubeless
```

which succeeds but the `/kubeless` directory is not present at the root of the resulting image.

**Comment by sebgoa** [comment]
well, it is my base image :)

works fine with `debian:stable-slim`

**Comment by sebgoa** [comment]
correct, currently it is a runtime volumeMount, I was trying to create it and forgot the user privileges.

my bad, thanks for checking.
