### ISSUE TITLE
level=warning msg="Flag --snapshotMode is deprecated. Use: --snapshot-mode"

### ISSUE THREAD

**Issue by sherman-yang** [GoogleContainerTools/kaniko#2408]
**Actual behavior**
when use the v1.9.1 with --snapshotMode=redo,  the log shows "level=warning msg="Flag --snapshotMode is deprecated. Use: --snapshot-mode"

**Expected behavior**
should accept "--snapshotMode=redo"

**To Reproduce**
add the flag --snapshotMode=redo

it is painful for changing the config for hundred projects. for a respected tool, one should try to always keep the names. this has happened before, there is no reason just changed executor:debug-xxx to executor:xxx-debug. why do people treat the name like a game

**Comment by aaron-prindle** [comment]
@sherman-yang sorry for the issue you encountered here.  I was not maintaining the project when this decision was made but I agree that this is something to much more care with in the future and understand your frustration.  At this point think it makes sense to keep the deprecation as this has already rolled for months now out but the project will be sure to keep flag compatibility and naming/cli changes that would cause users friction like you mentioned top of  mind going forward.  Sorry for the issues here and thanks for flagging this.  Going to close this as there isn't anything actionable here, feel free to comment and I can re-open if you disagree.  Thanks
