### ISSUE TITLE
UNAUTHORIZED: Pushing Docker images with manifest v2 schema 1 to this repository is blocked

### ISSUE THREAD

**Issue by swethagannapu** [GoogleContainerTools/kaniko#2454]
**Actual behavior**
Pushing image to Jfrog artifactory is blocked using kaniko, the same works fine when i push from my local using same credentials.

**Expected behavior**
Image Should be pushed to Jfrog with out any errors.

**To Reproduce**
1. use image: gcr.io/kaniko-project/executor:debug
2. /kaniko/executor --context `pwd` --cache=true --destination=xxxx:443/image:xxxx

**Additional Information**
 - Dockerfile 
                containers:
                  - name: docker
                    image: gcr.io/kaniko-project/executor:debug
                    imagePullPolicy: IfNotPresent
                    tty: true
                    command:
                        - /busybox/cat
                    volumeMounts:
                      - name: jenkins-docker
                        mountPath: /kaniko/.docker
                      - mountPath: /home/jenkins/
                        name: workspace-volume
                      - mountPath: /tmp
                        name: tmp
                      - mountPath: /cache
                        name: docker-cache
                    workingDir: /home/jenkins/agent

 - Kaniko Image (fully qualified with digest)
     gcr.io/kaniko-project/executor:debug

**Comment by zigelboim-misha** [comment]
We had the same issue a couple of years ago, [this article](https://stackoverflow.com/a/61356179) saved my mates time.

**Comment by aaron-prindle** [comment]
@swethagannapu were you able to look at the information @zigelboim-misha linked?  Just curious if this issue is still ongoing or if you were able to resolve this, thanks
