### ISSUE TITLE
Issue with `--registry-mirror` Path Support in Kaniko and Harbor Registry Proxy

### ISSUE THREAD

**Issue by allen0099** [GoogleContainerTools/kaniko#2471]
Hi Developers,

I am writing to bring to your attention an issue with `--registry-mirror` in Kaniko that seems to be related to path support. According to PR #1707, this feature should be supported, but it was subsequently reverted in PR #1794.

When using [Harbor](https://github.com/goharbor/harbor) as a registry proxy, it is necessary to include a prefix to access the proxy cache. However, as seen in the discussions on issue https://github.com/GoogleContainerTools/kaniko/pull/1794#issuecomment-996081822 and issue https://github.com/GoogleContainerTools/kaniko/issues/1618#issuecomment-1498749167, this appears to create a problem for Kaniko with `--registry-mirror`.

I am curious to know whether the support for `--registry-mirror` path support will be reinstated in the future or if it has been discontinued altogether.

Edit:
The error is
`error building image: registries must be valid RFC 3986 URI authorities: harbor.example.com/dockerhub`
where `dockerhub` is a proxy cache in harbor

Thanks

**Comment by patsevanton** [comment]
Any news ?

**Comment by mschneider82** [comment]
also need this feature, sadly that the feature PR got revered and not fixed :-(

**Comment by mschneider82** [comment]
please also add label registry/jfrog i have this issue using artifactory with /path

**Comment by gawsoftpl** [comment]
Still dependency proxy for harbor and gitlab doesnt work. 

https://example.gitlab.myendpoint.com/dependencyproxy
https://example.harbor.myendpoint.com/dockerhub-proxy

**Comment by prima101112** [comment]
add this issue also and created PR https://github.com/GoogleContainerTools/kaniko/issues/3046 hopefully it will help us cause i have the same problem
