### ISSUE TITLE
Build fails due to UNAUTHORIZED on docker.io

### ISSUE THREAD

**Issue by remko** [GoogleContainerTools/kaniko#2486]
**Actual behavior**

Running a build with kaniko fails due to unauthenticated docker.io registry call.

I'm triggering a kaniko build from Google Cloud Build. In the first step, the build fails:

```
Step #0: gcr.io/kaniko-project/executor:latest
Step #0: INFO[0001] Resolved base name golang:1.18-buster to build 
Step #0: INFO[0001] Using dockerignore file: /workspace/.dockerignore 
Step #0: INFO[0001] Retrieving image manifest builder            
Step #0: INFO[0001] Retrieving image builder from registry index.docker.io 
Step #0: error building image: GET https://index.docker.io/v2/library/builder/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/builder Type:repository]]
```

The build runs fine in docker.

**Expected behavior**

Running a build succeeds.

**To Reproduce**

Trigger a kaniko build from Cloud  Build

**Additional Information**

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [x] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [x] </li></ul>|

**Comment by remko** [comment]
Sorry for the noise, my mistake.

**Comment by remko-bw** [comment]
@justrdk I forgot :( Maybe an IAM problem?

**Comment by agiv** [comment]
For further google search hits. I got that problem with typo error something like
```
FROM golang:1.18-buster as build
...
FROM scratch as publish
COPY --from=builder ...
```
