### ISSUE TITLE
Ability to save save/upload stage or built targets.

### ISSUE THREAD

**Issue by henrique-nascent** [GoogleContainerTools/kaniko#252]
Hello,

Just thinking if it makes sense to expose then, as some times we want to build an specific stage.
https://docs.docker.com/engine/reference/commandline/build/#specifying-target-build-stage---target

So it maybe nice to be able to save/upload those images as well.
I think the stage builds are already saved so it would be just an way to expose that.

If `tarPath` is set, save all stages with names maybe saved there.

**Comment by priyawadhwa** [comment]
Hey @henrique-nascent, I think it should be pretty straightforward to add this feature. Let me know if you're interested in contributing it!

**Comment by sfrique** [comment]
@priyawadhwa I've opened the issue with the right account. Sorry for the mistake!

**Comment by priyawadhwa** [comment]
haha yah I saw that right after I commented, thanks!
