### ISSUE TITLE
Kaniko cannot use Alibaba Cloud ACR for authentication

### ISSUE THREAD

**Issue by zijiwork** [GoogleContainerTools/kaniko#2530]
**Actual behavior**
When using the Warmer cache basic image, it seems that authentication is not possible. Attempting to use Harbor to cache normally, does it not support ACR?

```
docker run -v `pwd`:/workspace -v config.json:/kaniko/.docker/config.json:ro gcriokaniko/warmer --cache-dir=/workspace/cache --image=dnsjia-registry-vpc.cn-hangzhou.cr.aliyuncs.com/base/golang:1.19.2
INFO[0000] Retrieving image manifest dnsjia-registry-vpc.cn-hangzhou.cr.aliyuncs.com/base/golang:1.19.2
INFO[0000] Retrieving image dnsjia-registry-vpc.cn-hangzhou.cr.aliyuncs.com/base/golang:1.19.2 from registry dnsjia-registry-vpc.cn-hangzhou.cr.aliyuncs.com 
Failed warming cache: Failed to warm any of the given images
WARN[0000] Error while trying to warm image: dnsjia-registry-vpc.cn-hangzhou.cr.aliyuncs.com/base/golang:1.19.2 Failed to retrieve image: dnsjia-registry-vpc.cn-hangzhou.cr.aliyuncs.com/base/golang:1.19.2: GET https://dnsjia-registry-vpc.cn-hangzhou.cr.aliyuncs.com/v2/base/golang/manifests/1.19.2: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:base/golang Type:repository]] 
```

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by yoon7t** [comment]
Hello, how to solve the problem of private library?
