### ISSUE TITLE
time="2018-07-27T10:17:27Z" level=info msg="Unpacking filesystem of mirror.jd.com/jupyter/ubuntu-base:latest..." 2018/07/27 10:17:27 No matching credentials found for mirror.jd.com, falling back on anonymous time="2018-07-27T10:17:27Z" level=error msg="Get https://mirror.jd.com/v2/: dial tcp 172.28.217.53:443: connect: connection refused"

### ISSUE THREAD

**Issue by ALiBaBa-Jimmy** [GoogleContainerTools/kaniko#259]
When I pull one image from my private repo “http://mirror.jd.com ” ，there is one err : 
 __msg="Get https://mirror.jd.com/v2/: dial tcp 172.28.217.53:443: connect: connection refused__

 my cluster couldn't connect to the internet!

the kaniko support the feather which can pull image from private image repo or not.. ?
Anyone else has the same problem ?..

**Comment by priyawadhwa** [comment]
Hey @ALiBaBa-Jimmy, kaniko does support pulling from and pushing to private registries, but you'll have to provide the necessary authentication yourself.

We specifically provide helpers for GCR and ECR, but if you need anything else for your private repo you'd have to mount it in yourself!

**Comment by dlorenc** [comment]
@ALiBaBa-Jimmy the full documentation for registry credentials is here: https://github.com/GoogleContainerTools/kaniko#pushing-to-different-registries

**Comment by priyawadhwa** [comment]
Hey @ALiBaBa-Jimmy I'm going to go ahead and close this issue since it seems like an auth issue rather than a bug in kaniko, but feel free to open another one if you have any more issues.
