### ISSUE TITLE
Create a github buildcontext

### ISSUE THREAD

**Issue by priyawadhwa** [GoogleContainerTools/kaniko#269]
In a lot of bugs people have opened I noticed they're using init containers to clone a github repo into a shared volume, and then mounting that volume into a separate kaniko container and using it as the kaniko build context.

It could be cool to add a `git://<repo url>` [build context](https://github.com/GoogleContainerTools/kaniko/blob/master/pkg/buildcontext/buildcontext.go#L33) option to kaniko. `docker build` also supports this, so would allow for greater feature parity.

**Comment by vkartik97** [comment]
Please assign this to me.
