### ISSUE TITLE
refactor: remove `fallbackToUID` bool option from Kaniko code as it is only ever `true`

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/kaniko#2718]
This issue tracks removing the `fallbackToUID` field from getUIDAndGIDFromString as it is only ever `true` in actual usage.  `fallbackToUID` bool option is not actually toggled in kaniko's code path's, it  is always `true`.  It is only in tests where it is actually `false`:

```
getUIDAndGIDFromString only called with fallbackToUID true in actual kaniko code paths (excluding tests)

aprindle@aprindle-ssd ~/kaniko  [fix-2327]ack getUIDAndGIDFromString
pkg/util/syscall_credentials.go
29:	uid, gid, err := getUIDAndGIDFromString(userStr, true) # <--- true

pkg/util/command_util_test.go
770:		uid, gid, err := getUIDAndGIDFromString(tt.args.userGroupStr, tt.args.fallbackToUID) # <--- false only in tests

pkg/util/command_util.go
358:	uid32, gid32, err := getUIDAndGIDFromString(chown, true) # <--- true
370:func getUIDAndGIDFromString(userGroupString string, fallbackToUID bool) (uint32, uint32, error) {
```

**Comment by vishal-khot** [comment]
Hi, I would like to take this up

**Comment by aaron-prindle** [comment]
@vishal-khot that's great!  I'm happy to review if you can  submit a PR w/ the fix here.  Lmk if you would like any additional help/information as you start the fix here.  Thanks!

**Comment by aaron-prindle** [comment]
I've assigned this issue to you for now 🙌

**Comment by vishal-khot** [comment]
Thanks @aaron-prindle! I should also be removing tests where `fallbackToUID` field is set to `false` right? For example, 
<pre>
testname: "only uid and fallback is false",
args: args{
    userGroupStr:  fmt.Sprintf("%d", currentUserUID),
    fallbackToUID: false,
},
expected: expected{
    userID:  expectedCurrentUser.userID,
    groupID: 0,
},
</pre>
In the above test, the expected value of 0 for `groupID` would never be returned after removing `fallbackToUID` from getUIDAndGIDFromString. Setting the expected value of `groupID` to `expectedCurrentUser.userID` would make the test redundant.

**Comment by aaron-prindle** [comment]
+1 - Yes, removing the value from the tests and the tests that rely on this behavior definitely makes sense here

**Comment by vishal-khot** [comment]
Thanks for the clarity! I've submitted a PR, please do let me know if any changes are required :)
