### ISSUE TITLE
archive/tar: sockets not supported

### ISSUE THREAD

**Issue by MnrGreg** [GoogleContainerTools/kaniko#272]
Experiencing the following error during 3rd stage of multistage build (FROM build AS publish):

> INFO[0129] args: [-c dotnet build XXXXX.API.Core.csproj -c Release -o /app]
> Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
> Copyright (C) Microsoft Corporation. All rights reserved.
> Restoring packages
> [redacted]
> Time Elapsed 00:00:06.90
> INFO[0136] Taking snapshot of full filesystem...
> **ERRO[0152] archive/tar: sockets not supported**

Dockerfile:
```
FROM microsoft/aspnetcore:2.0 AS base
WORKDIR /app
EXPOSE 18080
RUN adduser --system appuser

FROM microsoft/aspnetcore-build:2.0 AS build
WORKDIR /src
COPY XX.API.Core/XX.API.Core.csproj XX.API.Core/
COPY XX.API.Data/XX.API.Data.csproj XX.API.Data/
ENV NUGET_PACKAGES=/root/.nuget/packages
ENV HOME=/root
RUN dotnet restore XX.API.Core/XX.API.Core.csproj
COPY . .
WORKDIR /src/XX.API.Core
RUN dotnet build XX.API.Core.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish XX.API.Core.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
RUN chown -R appuser /app
ENV ASPNETCORE_URLS="http://*:18080"
USER appuser
ENTRYPOINT ["dotnet", "XX.API.Core.dll"]
```

**Comment by dlorenc** [comment]
Is there a github repo somewhere we can try to repro this against? I see some COPY lines in the Dockerfile and I'm not sure what type of files would go there.

**Comment by MnrGreg** [comment]
Here is a sample GitHub repo where the error 'archive/tar: sockets not supported' is experienced.

https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/Dockerfile

Just add `ENV HOME=/root` to the 3rd line of the Dockerfile which `dotnet restore` requires

**Comment by priyawadhwa** [comment]
Hey @MnrGreg , this should work now, please open another issue if it doesn't!

**Comment by MnrGreg** [comment]
Yup, sockets are now skipped and build completes.

**Comment by antonyjohnpaul23us** [comment]
Th issue seems to have re-surfaced in version 1.9

ERRO[0061] Can't add file /data/var/lib/containers/storage/overlay/dbecfc96d215e991ac3c5a84e1c7c31c4ab45cb801ee9c8a160f8f9336ce3758/diff/tmp/CoreFxPipe_MSBuild106 to tar: archive/tar: sockets not supported
ERRO[0061] Can't add file /data/var/lib/containers/storage/overlay/dbecfc96d215e991ac3c5a84e1c7c31c4ab45cb801ee9c8a160f8f9336ce3758/diff/tmp/CoreFxPipe_MSBuild74 to tar: archive/tar: sockets not supported
ERRO[0061] Can't add file /data/var/lib/containers/storage/overlay/dbecfc96d215e991ac3c5a84e1c7c31c4ab45cb801ee9c8a160f8f9336ce3758/diff/tmp/CoreFxPipe_MSBuild91 to tar: archive/tar: sockets not supported
ERRO[0061] Can't add file /data/var/lib/containers/storage/overlay/dbecfc96d215e991ac3c5a84e1c7c31c4ab45cb801ee9c8a160f8f9336ce3758/diff/tmp/xgicJLh614PpucyV4Nn9s_uL0EDEHYOnMe1l7fuQkb8 to tar: archive/tar: sockets not supported
