### ISSUE TITLE
Build Kaniko with Kaniko

### ISSUE THREAD

**Issue by fkorotkov** [GoogleContainerTools/kaniko#274]
I was wondering if it's possible to build Kaniko with Kaniko and ran this command:

```bash
./run_in_docker.sh deploy/Dockerfile $PWD build:local
```

which failed on downloading a tarball with:

```
level=info msg="Taking snapshot of full filesystem..."
level=info msg="cmd: Add [https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v1.4.3-static/docker-credential-gcr_linux_amd64-1.4.3.tar.gz]"
level=info msg="dest: /usr/local/bin/"
level=error msg="lstat /workspace/https:/github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v1.4.3-static/docker-credential-gcr_linux_amd64-1.4.3.tar.gz: no such file or directory"
```

So the question is "Is it possible to build Kaniko with Kaniko"? And why it fails on adding a remote archive if there is an [integration test](https://github.com/GoogleContainerTools/kaniko/blob/master/integration/dockerfiles/Dockerfile_test_add#L22) for that?

**Comment by dlorenc** [comment]
kaniko can build itself, I'm not sure why it's failing in this case.

**Comment by fkorotkov** [comment]
I also expected it! But I can reproduce this issues locally and in a k8s. 😢

**Comment by priyawadhwa** [comment]
Hey @fkorotkov , looks like there was a bug when trying to add a remote URL without any other sources.

I opened a PR to fix this, and kaniko should be able to build itself once that gets merged!

**Comment by fkorotkov** [comment]
@priyawadhwa great! thank you!
