### ISSUE TITLE
Specify ECR Registry with VPC Endpoint

### ISSUE THREAD

**Issue by chriscannon** [GoogleContainerTools/kaniko#2753]
**Actual behavior**
When pushing a kaniko image build to ECR using a VPC endpoint destination the request fails with a 401 error because the registry ID is not specified in the request. The error looks like this:

```
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "<REDACTED>": POST <REDACTED>: unexpected status code 401 Unauthorized: Not Authorized
```

**Expected behavior**
Allow a way to set the registry ID so that it can be included in the request to ECR.

**To Reproduce**
Use a VPC endpoint (vpce-XXX.dkr.ecr.us-east-1.vpce.amazonaws.com) instead of the public endpoint (e.g., XXX.dkr.ecr.us-east-1.amazonaws.com). 

**Additional Information**
 - Dockerfile 
   Please provide either the Dockerfile you're trying to build or one that can reproduce this error.
 - Build Context
   Please provide or clearly describe any files needed to build the Dockerfile (ADD/COPY commands)
 - Kaniko Image (fully qualified with digest)
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ Yes ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ N/A ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ N/A ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ Yes ] </li></ul>|

**Comment by aaron-prindle** [comment]
@chriscannon thanks for flagging this issue, is this something that you would like to take up as far as adding the functionality?  Additionally do you have some idea of what this would look like or the changes necessary to kaniko to pass to VPC endpoint to ECR?  Currently I am not quite sure where to pass this info.  Thanks

**Comment by chriscannon** [comment]
I actually discovered that so long as the Docker VPC endpoint is setup you can use the same public endpoint (e.g., XXX.dkr.ecr.us-east-1.amazonaws.com) and it will somehow translate it (I assume some DNS magic) to the correct VPC endpoint.
