### ISSUE TITLE
Splitting build + deploy for testing purposes

### ISSUE THREAD

**Issue by ekimia** [GoogleContainerTools/kaniko#276]
Problem: Kaniko at least what i can determine doesnt have an option to build in 1 stage and deploy in another. In CI,it would be beneficial to build the image, run tests, then deploy. Is there something im overlooking?

**Comment by priyawadhwa** [comment]
Hey @ekimia , right now kaniko can build your image and save it to a tarball instead of deploying it (by setting the `--tarPath` flag). Would you be able to use that in your CI system?

**Comment by AndreaGiardini** [comment]
What about saving the tar.gz to /dev/null ? Is it possibile?

It's a bit hacky but it should work

**Comment by priyawadhwa** [comment]
Hey @ekimia , #292 will add a `--no-push` flag which could be useful here.

**Comment by bobcatfish** [comment]
Currently assuming `--no-push` handles this, plz re-open or open a new issue if not.
