### ISSUE TITLE
Image size difference in multistage builds by kaniko and docker 

### ISSUE THREAD

**Issue by jaskeerat789** [GoogleContainerTools/kaniko#2768]
**Actual behavior**
The image size of a multistage image build by docker is very large as compared to docker. Kaniko might not be discarding builder stage image. This is an initial hunch. I am using kaniko with Gitlab CI running on EKS cluster. 

**Expected behavior**
The image size build by kaniko should be similar to that of image built by docker

**To Reproduce**
1. Build the following Dockefile locally
2. Build the same Dockerfile using kaniko
3. compare the size of images pushed to repo 

**Additional Information**
 - Dockerfile 
```
FROM <private centos image with java 8> AS builder
WORKDIR /builds

COPY . /builds/
RUN ./gradlew clean build

#################### Runner Image ######################## 
FROM amazoncorretto:8-alpine3.17
WORKDIR /home/app

COPY --from=builder /builds/build/libs/app.jar ./app.jar
COPY ./startApp.sh .

USER app-user
EXPOSE 8080
ENV CADANCE_WORKER=true

ENTRYPOINT ["/bin/ash"]
CMD ["startApp.sh"]
```
 - Build Context: Building a java application using gradle in first stage and using jar file built in the second stage
 - Kaniko Image: gcr.io/kaniko-project/executor:v1.15.0-debug
 - Difference in sizes. First one is built and pushed by kaniko whereas the second image was built and pushed by docker running locally on an intel macbook .
 
![image](https://github.com/GoogleContainerTools/kaniko/assets/38110126/3f7889e4-985a-4757-a320-3e9a3c46a384)

 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [x] </li></ul>|

**Comment by aaron-prindle** [comment]
Thank you for flagging this @jaskeerat789. This issue has been reported previously here:
https://github.com/GoogleContainerTools/kaniko/issues/2261

Feel free to continue the conversation there, going to close this as a dupe
