### ISSUE TITLE
Release Automation: Update release.sh to generate proper CHANGELOG.md and Makefile updates

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/kaniko#2785]
Currently cutting a new kaniko release requires manually transferring some information from the hack/release.sh script to CHANGELOG.md and Makefile.  This should be automated to reduce the amount of work required for a release.

**Comment by JeromeJu** [comment]
Looks like this has been fixed by https://github.com/GoogleContainerTools/kaniko/pull/2786. Closing this. Thanks @aaron-prindle !
