### ISSUE TITLE
Umbrella Tracking Issue: Investigate and Resolve Kaniko OOM w/ multi-stage builds

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/kaniko#2788]
Umbrella tracking issue for investigating and resolving Kaniko OOM w/ multi-stage builds.  Steps include:

- [x] Research root cause and develop repro case w/ github  repo
- [x] Implement fix for identified root cause (eg: memory leak, symlink cycles, etc.)

**Comment by aaron-prindle** [comment]
Related: #2033

**Comment by JeromeJu** [comment]
Thanks to the pointers Aaron. I've tried screening on the following issues:
- https://github.com/GoogleContainerTools/kaniko/issues/2249

**Comment by aaron-prindle** [comment]
This should be ok to close out now with the merge of https://github.com/GoogleContainerTools/kaniko/pull/2863.  Closing
