### ISSUE TITLE
refactor: remove refs to deprecated io/ioutil

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/kaniko#2806]
Currently kaniko has some references to the deprecated io/ioutil library.  These should be replaced w/ `io` references (eg: s/ `io/ioutil` /`io`)

This abandoned PR attempted the fix but had some compilation issues:
https://github.com/GoogleContainerTools/kaniko/pull/2716

**Comment by Manish-Giri** [comment]
Hi, can I take this up?

**Comment by Manish-Giri** [comment]
Thank you, I'm working on it now.

**Comment by Manish-Giri** [comment]
Status update - changes are underway, and are being done in this [branch ](https://github.com/Manish-Giri/kaniko/tree/fix/remove-deprecated-references)in my fork.

@aaron-prindle I got an IDE warning while I was in this file in the `vendor` folder, about this file being auto-generated and should not be modified -
https://github.com/GoogleContainerTools/kaniko/blob/caedb087497dd3b7fe468a6a942804bb34043b09/vendor/github.com/aws/aws-sdk-go-v2/service/s3/deserializers.go#L25

Wanted to confirm that no changes should be made to the `vendor` folder, then? Are there any other folders where changes should also not be made?

**Comment by Manish-Giri** [comment]
@aaron-prindle Any thoughts on this?
