### ISSUE TITLE
rpc error: code = Unknown desc = Error writing blob: blob size mismatch

### ISSUE THREAD

**Issue by 1-z** [GoogleContainerTools/kaniko#283]
Some images made by Kaniko appear to be confusing to CRI-O based kubelet (1.10.4).

I believe the issue is similar to [this](https://github.com/projectatomic/libpod/issues/655)

Not all images seem to have this problem. Registry is the latest image and CRI-O is built from master.

**Comment by dlorenc** [comment]
Can you provide any more info on how to reproduce this?

**Comment by 1-z** [comment]
I can hopefully provide a reproduction later today.

I also tried executor:v0.3 instead of executor:latest, as "latest" is from June. So far the same images with the single snapshot flag are working, but I haven't yet determined if it's the version bump or the flag, or a coincidence.

**Comment by 1-z** [comment]
I believe this was fixed by using the v0.3 image instead of latest, which was not the latest. I haven't been able to reproduce this issue anymore on latest CRI-O.
