### ISSUE TITLE
v1.18.0 docker image reports Kaniko version v1.17.0

### ISSUE THREAD

**Issue by manics** [GoogleContainerTools/kaniko#2839]
**Actual behavior**
`/kaniko/executor` in `gcr.io/kaniko-project/executor:v1.18.0` reports version `v1.17.0`

**Expected behavior**
It should report `v1.18.0`

**To Reproduce**
```
$ podman pull --platform linux/amd64 gcr.io/kaniko-project/executor:v1.18.0
Trying to pull gcr.io/kaniko-project/executor:v1.18.0...
Getting image source signatures
Copying blob 39bc67626d92 skipped: already exists  
Copying blob a13620305055 skipped: already exists  
Copying blob 630c95e41184 skipped: already exists  
Copying blob bf567119a2fe skipped: already exists  
Copying blob 0d0cf3a75faa skipped: already exists  
Copying blob d4d6338ae33d skipped: already exists  
Copying blob d1961195bcf7 skipped: already exists  
Copying blob b0f1fde9f5f4 skipped: already exists  
Copying blob 24b9c0f43324 skipped: already exists  
Copying config 5ae5c6bdd2 done   | 
Writing manifest to image destination
5ae5c6bdd294d3e32644369cffaabf2b2b6ea341e0f5103290296a30730d63c6

$ podman run -it --rm --platform linux/amd64 gcr.io/kaniko-project/executor:v1.18.0 version
Kaniko version :  v1.17.0
```

**Additional Information**
Digest: `gcr.io/kaniko-project/executor@sha256:e935bfe222bc3ba84797e90a95fcfb1a63e61bcf81275c2cac5edfb0343b2e85`

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by RoSk0** [comment]
Same goes for `debug` tag as well:

```
$ docker pull gcr.io/kaniko-project/executor:debug
...
Digest: sha256:b6a520e10252cfbb1898cac88d05f4c7c838cf615d1a588ec63a0d415db6c4c0
Status: Downloaded newer image for gcr.io/kaniko-project/executor:debug
$ docker run gcr.io/kaniko-project/executor:debug version
Kaniko version :  v1.17.0
```

**Comment by aaron-prindle** [comment]
Thanks for flagging this - there was an error during this release where the release branch was tagged one commit before the value was changed in the release cut commit.  This is resolved for later releases, closing
