### ISSUE TITLE
Unable to warm twice

### ISSUE THREAD

**Issue by mxbossard** [GoogleContainerTools/kaniko#2892]
Hi, I am using the new warmer 1.19.0.

**Actual behavior**
When I try to warm an image twice, the warmer exit with a failure the second time.

**Expected behavior**
I expect the warmer tell me the image is already in cache and do not fail.

**To Reproduce**
/kaniko/warmer -i alpine:latest -v trace
/kaniko/warmer -i alpine:latest -v trace

**Additional Information**
Logs :
DEBU[0000] /cache                                       
DEBU[0000] [xxx/yyy/alpine:3.14.2] 
INFO[0000] Retrieving image manifest xxx/yyy/alpine:3.14.2 
INFO[0000] Retrieving image xxx/yyy/alpine:3.14.2 from registry xxx 
INFO[0000] Found sha256:69704ef328d05a9f806b6b8502915e6a0a4faa4d72018dc42343f511490daf8a in local cache 
INFO[0000] Found manifest at /cache/sha256:69704ef328d05a9f806b6b8502915e6a0a4faa4d72018dc42343f511490daf8a.json 
WARN[0000] Error while trying to warm image: xxx/yyy/alpine:3.14.2 
 
The error do not indicate the root cause.
I suspect the problem is the new way the image is not anymore stored in RAM but in a temp file.
- The log line "Found sha256:..." indicate that the cache key was found in local cache by LocalSource func (cache.go line 196)
- The log line "Found manifest at ..." indicate that the manifest was found in local cache by cachedImageFromPath func (cache.go line 247)
- So AlreadyCachedErr{} should be raised in warmer.go line 163 and swallowed line 99 to stop the process cleanly. But this case is badly managed and the error AlreadyCachedErr{} is returned.

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by aaron-prindle** [comment]
Issue related to recent PR here: https://github.com/GoogleContainerTools/kaniko/pull/2763

**Comment by aaron-prindle** [comment]
Fixed with #2893, closing
