### ISSUE TITLE
401 when pushing image to ECR - docker config location

### ISSUE THREAD

**Issue by brendanhatton** [GoogleContainerTools/kaniko#290]
When I follow the instructions on the Kaniko page Pushing to Amazon ECR (using the gcr.io/kaniko-project/executor:debug image), I get an error

```
ERRO[0022] Failed to push to destination ....amazonaws.com/... 
ERRO[0022] unsupported status code 401; body: Not Authorized
```

The instructions currently say to mount the docker configmap to `/root/.docker`. I noticed that one of the environment variables in the image is `DOCKER_CONFIG=/kaniko/.docker/` so when I mount the configmap to `/kaniko/.docker`, the credentials are detected and the push succeeds.

Is this just a documentation update?

**Comment by priyawadhwa** [comment]
Hey @brendanhatton , thanks for pointing this out! I think you're right and this is a documentation issue.

**Comment by priyawadhwa** [comment]
Made the documentation change in #306 , so I'll go ahead and close this issue. @brendanhatton please comment if you see this error again!
