### ISSUE TITLE
Multistage build failing - works with Docker - including Repro

### ISSUE THREAD

**Issue by RufusJWB** [GoogleContainerTools/kaniko#2944]
**Actual behavior**
Building a multistage DOCKERFILE inside a container with Kaniko is failing. Building the same DOCKERFILE directly with Docker is working.

**Expected behavior**
Successfully building the multistage DOCKERFILE with Kaniko

**To Reproduce**
Full reproducible example https://github.com/RufusJWB/KanikoMultistageFailRepro

***Working example***
1. Navigate to PROXY Protocol Tester directory
1. Build image docker build -t dockerbuild:working . . Logs are at https://gist.github.com/RufusJWB/ebf95c6ff7aa85e487a55167fa3048df
1. Run container docker run -t dockerbuild:working . Logs are at https://gist.github.com/RufusJWB/364b87c02e06c6940a750530954828b4

***Failing example***
1. Stay in root directory
1. Build image docker build -t kanikobuild:fail . . Logs are at https://gist.github.com/RufusJWB/caa2371f5f1cdbdf46b6af593ca08913
1. Run container docker run -t kanikobuild:fail . Logs are at https://gist.github.com/RufusJWB/369d8428103dda76b47b5735de0994d7

**Additional Information**
See https://github.com/RufusJWB/KanikoMultistageFailRepro for full example
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [No] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [Yes] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [Yes] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [Yes] </li></ul>|

**Comment by atorrembo** [comment]
#2576

**Comment by hypery2k** [comment]
sounds like this issue #909 

we run into similiar issues. You give these arguments a try: 
```
  KANIKO_BUILD_ARGS: >-
    --cache=true --cache-run-layers=true --cache-copy-layers=true --cache-dir=${KANIKO_DIR}/cache --cache-repo="${CI_REGISTRY_IMAGE}/build" --compressed-caching=false
    --single-snapshot --cleanup 
```

**Comment by RufusJWB** [comment]
Adding `"--insecure-registry=host.docker.internal:5000"` did the trick. Now it is executing but again running into an error:

> DEBU[0024] Optimize: cache key for command WORKDIR /src c6d80849db561efcca36dc423cac859a094193a4f3e501809e75a74316a695c6
>
> DEBU[0024] Resolved PROXY Protocol Tester.csproj to PROXY Protocol Tester.csproj
> DEBU[0024] Resolved . to .
> error building image: error building stage: failed to optimize instructions: failed to get files used from context: failed to get fileinfo for /workspace/PROXY Protocol Tester.csproj: lstat /workspace/PROXY Protocol Tester.csproj: no such file or directory

**Comment by RufusJWB** [comment]
Would someone be able to have a deeper look into this issue?

**Comment by hypery2k** [comment]
Try with setting correct context: ```--context "$CI_PROJECT_DIR/PROXY Protocol Tester"``` 

Regarding memory tweaks you can also check this issue: see #2444

**Comment by RufusJWB** [comment]
> Try with setting correct context: `--context "$CI_PROJECT_DIR/PROXY Protocol Tester"`

Not working:

> DEBU[0024] Resolved . to .
> error building image: error building stage: failed to optimize instructions: failed to get files used from context: failed to get fileinfo for /buildDir/SRC/PROXY Protocol Tester/PROXY Protocol Tester.csproj: lstat /buildDir/SRC/PROXY Protocol Tester/PROXY Protocol Tester.csproj: no such file or directory

Full gist here: https://gist.github.com/RufusJWB/cf748809d9968abfeeb7f260a7b4eaf2

**Comment by hypery2k** [comment]
Actually I don't know why it's not working. Tried your sample in Gitlab and it's working
![image](https://github.com/GoogleContainerTools/kaniko/assets/979121/42605e4b-efa9-4e8c-8aa1-9fad3fd4b5b8)


Applied this in Gitlab:

```
....
mainBuild:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - export DOCKER_CONFIG=/kaniko/.docker/
    - export
    - pwd
    - ls -lah
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --verbosity=trace
      --ignore-path=$CI_PROJECT_DIR
      --context "$CI_PROJECT_DIR/PROXY Protocol Tester"
      --single-snapshot
      --cache=true --compressed-caching=false
      --cleanup
      --dockerfile "$CI_PROJECT_DIR/PROXY Protocol Tester/Dockerfile"
      --build-arg http_proxy
      --build-arg https_proxy
      --build-arg no_proxy
      --build-arg HTTP_PROXY
      --build-arg HTTPS_PROXY
      --build-arg NO_PROXY 
      --build-arg EAGLE_HTTP_PROXY
      --build-arg EAGLE_HTTPS_PROXY
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG


....
````

**Comment by RufusJWB** [comment]
Whatever the reason was, but I can confirm it is working with a GitLab runner and this configuration:

```
mainBuild:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json    
    - /kaniko/executor
      --ignore-path=$CI_PROJECT_DIR
      --context "$CI_PROJECT_DIR/PROXY Protocol Tester"
      --single-snapshot
      --cache=true
      --cleanup
      --dockerfile "$CI_PROJECT_DIR/PROXY Protocol Tester/Dockerfile"
      --build-arg http_proxy
      --build-arg https_proxy
      --build-arg no_proxy
      --build-arg HTTP_PROXY
      --build-arg HTTPS_PROXY
      --build-arg NO_PROXY 
      --build-arg EAGLE_HTTP_PROXY
      --build-arg EAGLE_HTTPS_PROXY
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
```

I will investigate further why it is still not working with local Docker.

**Comment by RufusJWB** [comment]
> I will investigate further why it is still not working with local Docker.

Also local build is working now. I updated the example at https://github.com/RufusJWB/KanikoMultistageFailRepro and will close this issue. Thank you for your support!
