### ISSUE TITLE
COPY fails when multiple files are copied to path specified in ENV

### ISSUE THREAD

**Issue by softmetz** [GoogleContainerTools/kaniko#2946]
**Actual behavior**
When I RUN
```
ENV TARGET_PATH=/target/path/

COPY /source/* $TARGET_PATH
```

Kaniko fails with

`error building image: error building stage: failed to get files used from context: when specifying multiple sources in a COPY command, destination must be a directory and end in '/'`

**Expected behavior**

COPY copies the files to the target directory

**To Reproduce**

See actual behaviour

**Additional Information**
 - Dockerfile 
```
ENV TARGET_PATH=/target/path/

RUN mkdir -p $TARGET_PATH

COPY /source/* $TARGET_PATH
```

 - Build Context
```
.
└── source
    ├── bar
    └── foo
```

 - Kaniko Image (fully qualified with digest): gcr.io/kaniko-project/executor@sha256:899886a2db1c127ff1565d5c7b1e574af1810bbdad048e9850e4f40b5848d79c
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by yossicohn** [comment]
Just got the same error on the same COPY issue
```
COPY /source/* target/
```
