### ISSUE TITLE
failed with /bin/bash", "-c", "/kaniko/executor 

### ISSUE THREAD

**Issue by barryzhoutrojai** [GoogleContainerTools/kaniko#3008]
**Actual behavior**

I am using python programming to create a kaniko, so in the pod spec, I specify command like "/bin/bash -c /kaniko/executor"

        job_command = [
            "/bin/bash", "-c", "/kaniko/executor --dockerfile=/workspace/Dockerfile --context=/workspace --destination=trojai/troj-engine-base-tabular:kaniko4 --image-fs-extract-retry=5"
        ]

the pod ends up "startError", check pod's state as following, seem it could not run command.

```
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  32s   default-scheduler  Successfully assigned abc/image-build-14022024-163346-376405-m9ns4 to kind-worker
  Normal   Pulling    32s   kubelet            Pulling image "gcr.io/kaniko-project/executor:latest"
  Normal   Pulled     29s   kubelet            Successfully pulled image "gcr.io/kaniko-project/executor:latest" in 2.691330585s (2.691353876s including waiting)
  Normal   Created    29s   kubelet            Created container image-build-14022024-163346-376405
  Warning  Failed     29s   kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown
```

**Expected behavior**

```
my pod should be started and run correctly
```

**To Reproduce**

Since I am programming to run kaniko, no test environments here, so I could not share how to reproduce it here.

**Additional Information**
 - Dockerfile 
   Please provide either the Dockerfile you're trying to build or one that can reproduce this error.
 - Build Context
   Please provide or clearly describe any files needed to build the Dockerfile (ADD/COPY commands)
 - Kaniko Image (fully qualified with digest)
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by JeromeJu** [comment]
Hi @barryzhoutrojai , it looks like the error is complaining that it cannot find the entrypoint for kaniko executor, which is the image. Could you provide more context what you are trying to achieve through this? You may find more instructions here also: https://github.com/GoogleContainerTools/kaniko/blob/main/README.md#running-kaniko-in-docker
