### ISSUE TITLE
better retry logic for downloading ?

### ISSUE THREAD

**Issue by cppforlife** [GoogleContainerTools/kaniko#301]
following error occurred:

```
...
time="2018-08-22T08:56:03Z" level=info msg="Taking snapshot of full filesystem..."
time="2018-08-22T08:56:09Z" level=error msg="Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/1a/1af690c440281a524947b15bb44fa4394eca3032c3c96f9a4efb03350dd7a1af/data?verify=...: read tcp 10.16.2.169:37268->104.18.125.25:443: read: connection reset by peer"
```

looks like it's trying to download something from the registry, but fails (failed once out of 100 or so CI builds). i didnt have a chance to look at the code if it's already retrying, so filing this just in case.

**Comment by priyawadhwa** [comment]
Hey @cppforlife , which version of the kaniko image are you using? In older versions we used to download image configs and layers for multistage builds after snapshotting, but in the latest version this shouldn't be the case anymore.

**Comment by bobcatfish** [comment]
Closing - assuming fixed in latest version, please re-open if not!

**Comment by f0o** [comment]
Please re-open, We're hitting this issue as well.

`error building image: error building stage: failed to get filesystem from image: read tcp 10.244.2.157:58634->104.18.124.25:443: read: connection reset by peer`

filling up out CI pipelines... I can curl production.cloudflare.docker.com fine from the same box so something must be different between curl and kaniko doing the requests...

**Comment by jinchihe** [comment]
/reopen

I can hit the problem now, any solution to work around? Thanks.
```
error building image: error building stage: read tcp 10.128.0.67:47742->104.18.125.25:443: read: connection reset by peer
```
