### ISSUE TITLE
ADD using an url with GET parameters and a directory destination includes the GET parameters in the file name

### ISSUE THREAD

**Issue by elan-slovelock** [GoogleContainerTools/kaniko#3032]
**Actual behavior**
The GET parameters of the url are included in the filename when the destination is a directory.

**Expected behavior**
The filename should have the GET parameters removed.

**To Reproduce**
1. Create a Dockerfile with the following contents
```
FROM ubuntu:jammy
ADD https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf?ext=.txt test-dir/
RUN ls -l test-dir
```
3. Build using docker to observe the output from line 3 is 
```
total 16
-rw------- 1 root root 13264 Aug 27  2007 dummy.pdf
```
4. Build using kaniko to observe the output from line 3 is
```
total 16
-rw------- 1 root root 13264 Aug 27  2007 dummy.pdf?ext=.txt
```

**Additional Information**
 - Kaniko Image (fully qualified with digest)
`gcr.io/kaniko-project/executor@sha256:ac169723b2076f9d5804f4bc05c98397e286da6fdcdd5a09fdc179f06ccb3be1`
 - Location of issue: https://github.com/GoogleContainerTools/kaniko/blob/main/pkg/util/command_util.go#L218
 - Caused by: [filepath.Base()](https://pkg.go.dev/path/filepath#Base) returns the last element of path and does not account for urls with GET parameters
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by prima101112** [comment]
hi @JeromeJu already rebased the PR. please review anytime
