### ISSUE TITLE
Auth with different quay organizations

### ISSUE THREAD

**Issue by riegerben** [GoogleContainerTools/kaniko#3036]
In my quay private registry, i have multiple organizations, and a robot acount for every organization.
I need to pull from 1 organization and push to a different one.
It works with repositories but not for organizations.

```json
{
    "auths": {
        "example.com/organizationA": { 
            "username": "userA",
            "password": "passA"
        },
        "example.com/organizationB": { 
            "username": "userB",
            "password": "passB"
        }
    }
}
```

Kaniko Image: gcr.io/kaniko-project/executor:v1.14.0-debug

**Comment by JeromeJu** [comment]
Hi @riegerben would you mind elaborating more which feature are you using with kaniko and what's the expected behaviour out of the feature request?
