### ISSUE TITLE
Request custom /path on registry maps including fallback

### ISSUE THREAD

**Issue by prima101112** [GoogleContainerTools/kaniko#3046]
**Problem**

we have a problem when using --registry-mirror its limited the default to just /library
could we just make this option out to the config
--mirror-prefix

> we want to move the default docker hub with harbor proxy that actually go to dockerhub
> but the harbor is not in the library instead on another prefix
correlated with issue 
[#1618](https://github.com/GoogleContainerTools/kaniko/issues/1618) and [#2471](https://github.com/GoogleContainerTools/kaniko/issues/2471)

and changes the 
```
func normalizeReference(ref name.Reference, image string) (name.Reference, error) {
	if !strings.ContainsRune(image, '/') {
		return name.ParseReference("library/"+image, name.WeakValidation)
	}

	return ref, nil
}
```
https://github.com/GoogleContainerTools/kaniko/blob/main/pkg/image/remote/remote.go#L120

need feedback if its allowed we may pull request

**Comment by prima101112** [comment]
just adding PR also https://github.com/GoogleContainerTools/kaniko/pull/3048

**Comment by JeromeJu** [comment]
Hi @prima101112 , thanks for filing this and the PR, please feel free to assign me for the rebased PR once it's ready.

**Comment by prima101112** [comment]
@JeromeJu already fix on this PR https://github.com/GoogleContainerTools/kaniko/pull/3051 #3051

**Comment by JeromeJu** [comment]
Thanks will take a look

**Comment by prima101112** [comment]
PR already merged. thanks
