### ISSUE TITLE
COPY with glob is incompatible with Docker

### ISSUE THREAD

**Issue by jimsnab** [GoogleContainerTools/kaniko#3069]
**Actual behavior**

Given
`COPY file_that_might_not_exis[t] /dest`

Kaniko returns this error when the file does not exist

`failed to get files used from context: copy failed: no source files specified`

**Expected behavior**

Match current Docker behavior - when glob is used, COPY does not need to copy at least one file.

**To Reproduce**
1. Try simple dockerfile

**Additional Information**
 - Dockerfile 

```
FROM alpine
COPY known_host[s] /etc/ssh/ssh_known_hosts
```

 - Build Context

Don't  make the `known_hosts` file.

 - Kaniko Image (fully qualified with digest)
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [No] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [Yes] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [Yes] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [Yes] </li></ul>|

**Comment by prima101112** [comment]
Hi @jimsnab could you confirm, is this error only happen when there is no files, or even there is a file, is not detected the glob pattern? and if there is files is it copying all match pattern?

**Comment by yossicohn-hs** [comment]
@aaron-prindle @prima101112 any work around for this one?

**Comment by jimsnab** [comment]
> Hi @jimsnab could you confirm, is this error only happen when there is no files, or even there is a file, is not detected the glob pattern? and if there is files is it copying all match pattern?

Error is when there is no file (which is the reason to use this pattern).

**Comment by prima101112** [comment]
@yossicohn @jimsnab hope this will works we checked if using wildcard and file not found it will return error , change to warn instead

**Comment by yossicohn-hs** [comment]
@prima101112 Thanks, I don't think it is the same as [https://github.com/GoogleContainerTools/kaniko/issues/3092](https://github.com/GoogleContainerTools/kaniko/issues/3092).
Since there I show that the file exist but `COPY` will fail even though the files exist.
This failure occurs in the following cases of `COPY` usage

`COPY .  .`

`COPY ./* ./`
or
`COPY ./*.json  ./   `

**Comment by yossicohn** [comment]
@prima101112 Thanks, I don't think it is the same as #3092.
Since there I show that the file exist but COPY will fail even though the files exist.
This failure occurs in the following cases of COPY usage

COPY .  .

COPY ./* ./
or
COPY ./*.json  ./
