### ISSUE TITLE
Recipe for adding bash to Kaniko

### ISSUE THREAD

**Issue by BeyondEvil** [GoogleContainerTools/kaniko#3100]
```Dockerfile
FROM curlimages/curl:8.7.1 as base

RUN curl -sSLo "bash" "https://github.com/robxu9/bash-static/releases/download/5.2.015-1.2.3-2/bash-linux-x86_64" && \
    chmod +x bash

FROM gcr.io/kaniko-project/executor:v1.21.1-debug as final

COPY --from=base /bash /busybox/
RUN ln -s /busybox/bash /bin/bash
```

To maintainers: Is there a reason why you haven't enabled "Discussions" on this project?

**Comment by aaron-prindle** [comment]
@BeyondEvil thanks for the recipe here.  Currently i'm not sure it makes sense to have such recipes in our Github Issues, perhaps you can move this to Discussions (which I've now enabled thanks for flagging this) or submit a PR adding a RECIPES.md or something similar?  

> To maintainers: Is there a reason why you haven't enabled "Discussions" on this project?

There was no specific reason Discussions were previously not enabled on this project, I believe they did not exist when this repo was first created.  I have enabled Discussions now for this project.

I think I will close this issues as it stands as there is nothing actionable to do related to this for now.  Lmk and I can reopen this, thanks
