### ISSUE TITLE
Incorrect image creation date

### ISSUE THREAD

**Issue by lubo** [GoogleContainerTools/kaniko#312]
All my images built using Kaniko have creation date set two days before the actual build date.

**EDIT:** I've just found out Docker says that my layers were build 292 years ago and it's the base image that was build 2 days go.

**Comment by sjentzsch** [comment]
I can relate.
Just ported my GitLab CI pipeline from using dind to kaniko, and the GitLab registry claims the image was build on 6th July (1 month ago; probably using the timestamp from the base image etc.?).

**Comment by yuchunyu97** [comment]
For help, I used the v0.18.0 version of the executor to build my image, but I used `docker history` to see that the created image display layer was created 292 years ago, does anyone know how this happened?
