### ISSUE TITLE
Failed to create temporary file

### ISSUE THREAD

**Issue by Poswark** [GoogleContainerTools/kaniko#3234]
**Actual behavior**

DEBU[0000] Copying file /workspace/Dockerfile to /kaniko/Dockerfile 
assertion failed [!result.is_error]: Failed to create temporary file
(ThreadContextFcntl.cpp:84 create_tempfile)

**Expected behavior**
DEBU[0000] Copying file /workspace/Dockerfile to /kaniko/Dockerfile 
assertion failed [!result.is_error]: Failed to create temporary file
(ThreadContextFcntl.cpp:84 create_tempfile)

**To Reproduce**
Mac M1

**Additional Information**
 - Dockerfile 
   Please provide either the Dockerfile you're trying to build or one that can reproduce this error.
 - Build Context
   Please provide or clearly describe any files needed to build the Dockerfile (ADD/COPY commands)
 - Kaniko Image (fully qualified with digest)
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by Poswark** [comment]
Solution --kaniko-dir /tmp

**Comment by grahamcracker1234** [comment]
Can you give more information on your solution?

**Comment by Poswark** [comment]
Hello 

This flag 
--kaniko-dir /tmp
