### ISSUE TITLE
Cannot build an image with amazonlinux:1 image

### ISSUE THREAD

**Issue by mustafaakin** [GoogleContainerTools/kaniko#345]
**Actual behavior**

Build fails with message as chmod /etc/mtab not permitted and it seems to not use the credential provider. 

**Expected behavior**

I want my image to be built and use the IAM credentials of the EC2 instance, not need the keys directly as this is not the way people use AWS. The instance already have the permission and regular Docker instances can use ecr-login to get credentials.

**To Reproduce**

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-config
data:
  config.json: |-
    {
      "credHelpers": {
        "xxxxxx.dkr.ecr.us-west-2.amazonaws.com": "ecr-login"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-docker-file-test
data:
  Dockerfile: |
    FROM amazonlinux:1
    RUN ls -alh /
---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko-test
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=/app/Dockerfile",
            "--destination=xxxxx.dkr.ecr.us-west-2.amazonaws.com/mustafa-test:latest"]
    volumeMounts:
      - name: dockerfile
        mountPath: /app
      - name: docker-config
        mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
    - name: dockerfile
      configMap:
        name: my-docker-file-test
    - name: docker-config
      configMap:
        name: docker-config
```

```bash
$ kubectl apply -f kaniko-test.yaml
configmap/docker-config created
configmap/my-docker-file-test created
pod/kaniko-test created
$ kubectl logs kaniko-test
time="2018-09-10T14:07:38Z" level=info msg="appending to multi args xxxx.dkr.ecr.us-west-2.amazonaws.com/mustafa-test:latest"
INFO[0000] Downloading base image amazonlinux:1
2018/09/10 14:07:38 No matching credentials were found, falling back on anonymous
INFO[0000] Mounted directories: [/kaniko /var/run /proc /dev /dev/pts /sys /sys/fs/cgroup /sys/fs/cgroup/systemd /sys/fs/cgroup/cpuset /sys/fs/cgroup/cpu,cpuacct /sys/fs/cgroup/blkio /sys/fs/cgroup/memory /sys/fs/cgroup/devices /sys/fs/cgroup/freezer /sys/fs/cgroup/net_cls,net_prio /sys/fs/cgroup/perf_event /sys/fs/cgroup/pids /dev/mqueue /app /root/.docker /dev/termination-log /etc/resolv.conf /etc/hostname /etc/hosts /dev/shm /var/run/secrets/kubernetes.io/serviceaccount /proc/asound /proc/bus /proc/fs /proc/irq /proc/sys /proc/sysrq-trigger /proc/kcore /proc/timer_list /proc/timer_stats /proc/sched_debug /sys/firmware]
INFO[0001] Extracting layer 0
Error: error building image: chmod /etc/mtab: operation not permitted
Usage:
  executor [flags]

Flags:
```

**Additional Information**
 - Dockerfile : Provided above as configmap mounted to container
 - Build Context None
 - Kaniko Image (fully qualified with digest):  gcr.io/kaniko-project/executor@sha256:345d361c8a937f54f4751b8952b94710e0460247c0471594675cd2c2ad17c0c5

I tried changing the user to root for mount path /root/.docker but it did not work.
Also tried with minikube and it is the same.

**Comment by priyawadhwa** [comment]
@mustafaakin since the base image `amazonlinux:1` is a public image hosted on docker hub, kaniko doesn't need special credentials to pull it.

This looks like a bug in the filesystem extraction, probably occurring [here](https://github.com/GoogleContainerTools/kaniko/blob/master/pkg/util/fs_util.go#L188) when we try to set permissions on a file.

**Comment by mustafaakin** [comment]
Oh I see, that's the message for pulling the image. Is there anything that kaniko does or should do to prevent this? Why would we not be able to chmod inside a container? As I see the problem is that the container image has /etc/mtab but in the container it links to /proc/mounts which docker/container runtime needs specifically? But where does the kaniko extract the tar files?

**Comment by priyawadhwa** [comment]
So the issue was that `/etc/mtab` is provided by the runtime environment (Kubernetes/Docker) as a symlink which points to `/proc/mounts`. The file also exists in the `amazonlinux:1` image, so when we tried to extract it and run `chmod` kaniko actually was trying to change permissions on `/proc/mounts` which errored out.

I added `/etc/mtab` to the whitelist so that it won't be extracted from an image which should fix this problem -- you should be able to build the Dockerfile above with the latest image now!

Please let me know if I didn't completely answer your questions or if the fix doesn't work for you.

**Comment by dlorenc** [comment]
Any idea why the file detection didn't catch this? I thought it would automatically be whitelisted.

**Comment by priyawadhwa** [comment]
I thought so too, but it's not in `/proc/self/mountinfo`. Not sure why it isn't, but I figured it was a weird case like `/var/run`.

The only way I can think to have a 100% correct whitelist is to store all existing files in the whitelist before extracting the base image (but this would be slower so I don't love the idea)

**Comment by mustafaakin** [comment]
Yes, it works for me right now, thanks.

**Comment by mustafaakin** [comment]
Sorry, but with the newest image it happens again:


```
kubectl logs -f kaniko-test
time="2018-09-14T06:45:33Z" level=info msg="Unpacking filesystem of amazonlinux:1..."
2018/09/14 06:45:33 No matching credentials found for index.docker.io, falling back on anonymous
time="2018-09-14T06:45:34Z" level=info msg="Mounted directories: [/kaniko /var/run /proc /dev /dev/pts /sys /sys/fs/cgroup /sys/fs/cgroup/systemd /sys/fs/cgroup/cpuset /sys/fs/cgroup/cpu,cpuacct /sys/fs/cgroup/blkio /sys/fs/cgroup/memory /sys/fs/cgroup/devices /sys/fs/cgroup/freezer /sys/fs/cgroup/net_cls,net_prio /sys/fs/cgroup/perf_event /sys/fs/cgroup/pids /dev/mqueue /dev/termination-log /tmp/dockerfile /kaniko/.docker /etc/resolv.conf /etc/hostname /etc/hosts /dev/shm /var/run/secrets/kubernetes.io/serviceaccount /proc/asound /proc/bus /proc/fs /proc/irq /proc/sys /proc/sysrq-trigger /proc/kcore /proc/timer_list /proc/timer_stats /proc/sched_debug /sys/firmware]"
time="2018-09-14T06:45:34Z" level=info msg="Unpacking layer: 0"
time="2018-09-14T06:45:34Z" level=info msg="Not adding /dev because it is whitelisted"
time="2018-09-14T06:45:34Z" level=info msg="Not adding /dev/console because it is whitelisted"
time="2018-09-14T06:45:34Z" level=info msg="Not adding /dev/fd because it is whitelisted"
time="2018-09-14T06:45:34Z" level=info msg="Not adding /dev/null because it is whitelisted"
time="2018-09-14T06:45:34Z" level=info msg="Not adding /dev/random because it is whitelisted"
time="2018-09-14T06:45:34Z" level=info msg="Not adding /dev/urandom because it is whitelisted"
time="2018-09-14T06:45:34Z" level=info msg="Not adding /dev/zero because it is whitelisted"
time="2018-09-14T06:45:34Z" level=info msg="Not adding /etc/hosts because it is whitelisted"
time="2018-09-14T06:45:34Z" level=error msg="chmod /etc/mtab: operation not permitted"
```

With the image:

```
gcr.io/kaniko-project/executor@sha256:501056bf52f3a96f151ccbeb028715330d5d5aa6647e7572ce6c6c55f91ab374
```

**Comment by priyawadhwa** [comment]
Hey @mustafaakin , so we had a bug in our release process which I described [here](https://github.com/GoogleContainerTools/kaniko/issues/354#issuecomment-421441952), which should be fixed now.

If you could try again, I think it should work!

**Comment by mustafaakin** [comment]
Yeah it works right now @priyawadhwa thanks!
