### ISSUE TITLE
Latest kaniko release fails to find Dockerfile

### ISSUE THREAD

**Issue by ImJasonH** [GoogleContainerTools/kaniko#354]
**Actual behavior**

```
time="2018-09-14T14:48:36Z" level=error msg="open Dockerfile: no such file or directory"
```

**Expected behavior**

Build should succeed with the `:latest` release.

**To Reproduce**

Dockerfile:
```
FROM ubuntu
RUN echo hello
```

cloudbuild.yaml:
```
steps:
- name: gcr.io/kaniko-project/executor:latest
  args: ['--destination', 'gcr.io/$PROJECT_ID/built-with-kaniko'],
```

```
$ gcloud builds submit --config=cloudbuild.yaml
...
time="2018-09-14T14:48:36Z" level=error msg="open Dockerfile: no such file or directory"
```

(Using `:latest` which is currently `gcr.io/kaniko-project/executor@sha256:501056bf52f3a96f151ccbeb028715330d5d5aa6647e7572ce6c6c55f91ab374`)

If I pin to the image digest released yesterday, the build works:

```
steps:
- name: 'gcr.io/kaniko-project/executor@sha256:42b4dd2a4651a300005bcaf23a0af74aaf25046c212f9c9556b4baeeda8985e5'
  args: ['--destination', 'gcr.io/$PROJECT_ID/built-with-kaniko']
```

**Comment by pvdissel** [comment]
in the context of Gitlab CI (https://github.com/GoogleContainerTools/kaniko/issues/304), I had to use an absolute path for the `--dockerfile`, with the latest release of 16 hours ago

**Comment by priyawadhwa** [comment]
Hey @ImJasonH & @pvdissel, turns out we had a retagging process executing which was pinning `:latest` to an older version of the image.

I removed that process and rebuilt the images, the cloudbuild.yaml is building successfully for me now. Let me know if you're still running into trouble.

**Comment by dlorenc** [comment]
I think this should be fixed now.
