### ISSUE TITLE
More helpful message for pushing blobs 

### ISSUE THREAD

**Issue by mustafaakin** [GoogleContainerTools/kaniko#357]
Right now, I build a rather large image and push it in single snapshot and it takes some time to push it.

```
2018/09/15 18:31:00 existing blob: sha256:5b90a54fcf20cd7bbbfaaa43d29e91bc689ffbaac82ba9aa216a59be0532f6e1
2018/09/15 18:31:00 pushed blob sha256:ee96e8f949d63a53dec27a63881f24b9365e2cbc2fdd6c02bc3d7d626d78a459
2018/09/15 18:31:59 pushed blob sha256:b88668a215250fc0a47fcb47574e7db7032352811fe8d9e9d09f721d42b4cc82
2018/09/15 18:31:59 xxxxx.dkr.ecr.us-west-2.amazonaws.com/mustafa-test:latest: digest: sha256:a7f544e20f0397c2e17e027f2032fd6159f33208f3e431a81cbf649f1436abf0 size: 595
```

It says that it pushed the blob after 59 seconds and I have no indication of status. What do you think of a progress bar here or some info before starting to push a layer indicating the total size to be pushed?

**Comment by peter-evans** [comment]
@mustafaakin The code handling pushing the image and its individual layers is contained in the `github.com/google/go-containerregistry/pkg/v1/remote` package which Kaniko imports. So it might be best to create an issue at [go-containerregistry](https://github.com/google/go-containerregistry) and see if the maintainers would consider this enhancement.

**Comment by bobcatfish** [comment]
Closing since this is an issue with  [go-containerregistry](https://github.com/google/go-containerregistry)
