### ISSUE TITLE
Ability to use a TempFile instead of an in-memory buffer for tarball snapshots to build large Docker containers?

### ISSUE THREAD

**Issue by nelsonjchen** [GoogleContainerTools/kaniko#358]
https://github.com/GoogleContainerTools/kaniko/blob/13accbaf3243a5cf477c9e3d5116dc09dd80ae37/pkg/snapshot/snapshot.go#L57-L70

I'm interested in building multi-GB Docker images with Kaniko. Unfortunately, doing this immediately exhausts the RAM. I think this is because the snapshotting steps take a tarball snapshot of the whole filesystem in-memory. 

It would be nice to have an option to tell kaniko to use a Tempfile for the snapshot backing.

**Comment by priyawadhwa** [comment]
@nelsonjchen this should be fixed with #428. I'll go ahead and close this issue, please comment or open another if you run into any more problems!

**Comment by nelsonjchen** [comment]
Woah! I didn't expect this to be resolved. "Have a bit of faith." - Some game I'm currently playing. 

I look forward to trying this.

**Comment by lovetheguitar** [comment]
Hey,

sorry for the stupid question, but how do I enable this?
I'd like to build a 10+GB image from within Gitlab CI.
Thanks for any hints.

**Comment by nelsonjchen** [comment]
@lovetheguitar I would look at the code. Always look at the code. It's authoritative. Check out the PR. Apparently, you don't have to do anything except provide disk space.

**Comment by lovetheguitar** [comment]
> @lovetheguitar I would look at the code. Always look at the code. It's authoritative. Check out the PR that was merged and mentioned above. Apparently, you don't have to do anything except provide disk space.

Thanks for your answer. Yeah, I tried, but I don't know go at all. 
Either way it appears to be a different bug #909.
