### ISSUE TITLE
Please provide a valid path to a Dockerfile

### ISSUE THREAD

**Issue by olvlvl** [GoogleContainerTools/kaniko#359]
**Actual behavior**
I'm getting the error "please provide a valid path to a Dockerfile within the build context with --dockerfile" although I'm providing a correct absolute path to a Dockerfile. I tried replacing the absolute path with `Dockerfile`, `./Dockerfile`, and empty string. I'm running the image on MacOS using `Docker 18.06.1-ce-mac73 (26764)`.

**Expected behavior**
The command would just run.

**To Reproduce**

```
$ docker run gcr.io/kaniko-project/executor /kaniko/executor --dockerfile="/Volumes/hellofresh/webdev/src/menus-service/docker/images/cli-base/Dockerfile" "--destination=/Volumes/hellofresh:test" --context=/Volumes/hellofresh/webdev/src/menus-service/docker/images --tarPath=/Volumes/hellofresh/img.tar
```

**Additional Information**
This is the Dockerfile I'm trying to build:

```bash
$ cat /Volumes/hellofresh/webdev/src/menus-service/docker/images/cli-base/Dockerfile
```

```
FROM php:7.2.9-alpine3.8

RUN apk add --no-cache make openssl-dev && \
    apk add --no-cache --virtual .php-ext-deps autoconf g++ pcre-dev && \
    pecl channel-update pecl.php.net && \
    pecl install apcu mongodb redis && \
    docker-php-ext-install bcmath && \
    docker-php-ext-enable apcu mongodb opcache redis && \
    docker-php-source delete && \
    apk del .php-ext-deps && \
    rm -r /tmp/*

RUN echo "apc.enable_cli=On" >> /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini
```

Kaniko Image: `sha256:286f41d4ac5be8829c1d720a6afca4feabc880557b48575d5339577ad71455e7`

**Comment by priyawadhwa** [comment]
Hey @olvlvl, to run in Docker you'll need to mount the build context into the image with the `-v` flag so that it exists in the image, you could try something like :

```
docker run -v /Volumes/hellofresh/webdev/src/menus:/workspace \
gcr.io/kaniko-project/executor \
--dockerfile=/workspace/docker/images/cli-base/Dockerfile  \
--context=/workspace --tarPath=/Volumes/hellofresh/img.tar
```

**Comment by olvlvl** [comment]
Thanks for the help @priyawadhwa, I followed your advises and got something running with the following script:

```bash
CONTEXT=/Volumes/hellofresh/webdev/src/menus-service/docker/images/cli-base

docker run \
    -v ${CONTEXT}:/workspace \
    gcr.io/kaniko-project/executor  \
    --dockerfile=/workspace/Dockerfile \
    --no-push \
    --context=/workspace \
    --tarPath=/workspace/img.tar
```

Two problems:

1\. All `RUN` are failing, for instance `RUN ls` gives me this:

```
INFO[0000] Downloading base image php:7.2.9-alpine3.8
2018/09/18 13:15:34 No matching credentials were found, falling back on anonymous
INFO[0001] Executing 0 build triggers
INFO[0001] Mounted directories: [/kaniko /var/run /etc/mtab /proc /dev /dev/pts /sys /sys/fs/cgroup /sys/fs/cgroup/cpuset /sys/fs/cgroup/cpu /sys/fs/cgroup/cpuacct /sys/fs/cgroup/blkio /sys/fs/cgroup/memory /sys/fs/cgroup/devices /sys/fs/cgroup/freezer /sys/fs/cgroup/net_cls /sys/fs/cgroup/perf_event /sys/fs/cgroup/net_prio /sys/fs/cgroup/hugetlb /sys/fs/cgroup/pids /sys/fs/cgroup/systemd /dev/mqueue /workspace /etc/resolv.conf /etc/hostname /etc/hosts /dev/shm /proc/bus /proc/fs /proc/irq /proc/sys /proc/sysrq-trigger /proc/acpi /proc/kcore /proc/keys /proc/timer_list /proc/sched_debug /sys/firmware]
INFO[0001] Extracting layer 0
INFO[0002] Extracting layer 1
INFO[0002] Extracting layer 2
INFO[0002] Extracting layer 3
INFO[0002] Extracting layer 4
INFO[0003] Extracting layer 5
INFO[0003] Extracting layer 6
INFO[0005] Extracting layer 7
INFO[0005] Extracting layer 8
INFO[0005] Taking snapshot of full filesystem...
INFO[0007] RUN ls
INFO[0007] cmd: /bin/sh
INFO[0007] args: [-c ls]
sh: ls: Cannot stat: No such file or directory
sh: Exiting with failure status due to previous errors
error building image: error building stage: waiting for process to exit: exit status 2
```

2\. Whether I'm using `/workspace/img.tar` or `/Volumes/hellofresh/img.tar`, no archive is being created. Note that I'm using `--no-push` because omitting `--destination` was resulting in an error.

Would you have any more advise? 🙏

**Comment by skofgar** [comment]
Hello @olvlvl 
I had the same problem, where I am trying to build a tarball, but ran into the either `no-push` or `destination` issue. My script now runs without an error, but it does not create a tarball 😢 ...

I noticed in your script:
* where in the Dockerfile is the command `RUN ls` (I don't see it in the one listed above)
* could you try verifying that the folder you are trying to run `ls` in still exists? (example running `pwd` to see where you are)

**Comment by dlorenc** [comment]
> 2. Whether I'm using `/workspace/img.tar` or `/Volumes/hellofresh/img.tar`, no archive is being created. Note that I'm using `--no-push` because omitting `--destination` was resulting in an error.

If the image fails to build, I wouldn't expect a tar to be created. Do you mean that the tar is not being created even when your build succeeds?

Could you post the logs from one of those runs?

**Comment by dlorenc** [comment]
Also note that you do still need to provide an image name even if you want to save it in a tar, the docker image tar file format requires that images inside them have names.

**Comment by olvlvl** [comment]
@dlorenc, @skofgar Thanks for your messages.

The following command is working, and I get a tar file:

```
CONTEXT=/Volumes/hellofresh/webdev/src/menus-service/docker/images/cli-base

docker run \
    -v ${CONTEXT}:/workspace \
    gcr.io/kaniko-project/executor  \
    --dockerfile=/workspace/Dockerfile \
    --destination=hellofresh/menus-service:cli-base \
    --context=/workspace \
    --tarPath=/workspace/img.tar
```

But using any RUN command is failing:

```
FROM php:7.2.9-alpine3.8

RUN pwd
```

Gives me:

```
INFO[0006] RUN pwd
INFO[0006] cmd: /bin/sh
INFO[0006] args: [-c pwd]
sh: pwd: Cannot stat: No such file or directory
sh: Exiting with failure status due to previous errors
error building image: error building stage: waiting for process to exit: exit status 2
```

**Comment by xanonid** [comment]
The issue is that /bin/sh is overwritten by the GNU tar binary. Try
```
RUN ["/bin/sh","--version"]
``` 
to verify.  The issue is connected to a missing symlink check. First, tar is provided by busybox, but then GNU tar is installed. The unpack of the regular file does not remove the symlink, but overwrites its target file. Solution: Add a FilepathExists check in extractFile of pkg/util/fs_util.go also in the tar.TypeReg case. For the hard link case, this is done in #360.

**Comment by olvlvl** [comment]
Hi @xanonid, thanks for your message. So I'm getting this:

```
INFO[0007] RUN ["/bin/sh","--version"]
INFO[0007] cmd: /bin/sh
INFO[0007] args: [--version]
tar (GNU tar) 1.30
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Should I put [these changes](https://github.com/GoogleContainerTools/kaniko/pull/360/files#diff-d36eb675aa49a7b471e3a2be77005b18) in my setup?

**Comment by xanonid** [comment]
@olvlvl The changes from #360 does not help in your case. However, you can add the same lines after the  `case tar.TypeReg:` line ([line 176ff](https://github.com/GoogleContainerTools/kaniko/pull/360/files#diff-d36eb675aa49a7b471e3a2be77005b18L176)) which should help.

**Comment by olvlvl** [comment]
Yay! It works!

```
$ ll /Volumes/hellofresh/webdev/src/menus-service/docker/images/cli-base/img.tar
-rw-r--r--  1 olvlvl  staff    44M Sep 26 17:12 /Volumes/hellofresh/webdev/src/menus-service/docker/images/cli-base/img.tar
```
