### ISSUE TITLE
Cannot stat: No such file or directory

### ISSUE THREAD

**Issue by jozefkoscak** [GoogleContainerTools/kaniko#362]
I tried to build Dockerfile (similar to this one) with Gitlab CI, 
```
FROM composer:1.7.1 AS composer
FROM php:7.3.0RC1-cli-alpine3.8
COPY --from=composer /usr/bin/composer /usr/bin/composer

COPY ./ /app
WORKDIR /app

RUN ls -l
```
Actual result in current version 
`gcr.io/kaniko-project/executor:debug-8fb220b19b227bde9b7f4653da3b6b282be2fea4`
and
`gcr.io/kaniko-project/executor:debug-deda0ea04decceb8b758c764e6eeb9b8000e4095`
```
INFO[0094] cmd: /bin/sh                                 
INFO[0094] args: [-c ls -l]                             
sh: ls -l: Cannot stat: No such file or directory
sh: Exiting with failure status due to previous errors
```
Expected result as in version 
`gcr.io/kaniko-project/executor:debug-bb75c0461887034f40f5ba836cfd17647d2cf544`
```
INFO[0086] args: [-c ls -l]                             
total 12
-rw-rw-rw-    1 root     root           273 Sep 22 17:02 Dockerfile
```

**Comment by priyawadhwa** [comment]
Could be related to #359, comment [here](https://github.com/GoogleContainerTools/kaniko/issues/359#issuecomment-423576260)
