### ISSUE TITLE
Cannot COPY file to existing directory without trailing slash

### ISSUE THREAD

**Issue by Zetten** [GoogleContainerTools/kaniko#365]
**Actual behavior**
A Dockerfile with content
```dockerfile
RUN mkdir -p /path/to/foo
COPY sourcefile /path/to/foo
```
will fail to build in Kaniko, with the error:
`error building image: error building stage: open /path/to/foo: is a directory`

**Expected behavior**
`docker build` is rather more lenient with the target for COPY commands, and will create the file in the destination directory: `/path/to/foo/sourcefile`.

**Additional Information**
I've tried tracking down the problem through the `DestinationFilepath` function in `command_util.go`. This checks whether the destination is a directory using the `IsDestDir` function. However `IsDestDir` is quite naive and string-based, and only checks for the existence of a trailing slash or cwd marker - which are not present in the example above.

Changing `IsDestDir` seems like it may have side effects in other places, but I managed to test successfully with a new function, replacing the `IsDestDir` call in `DestinationFilepath`:

```go
func IsDirectory(path string) bool {
	fileInfo, err := os.Stat(path)
	if err != nil{
		return false
	}
	return fileInfo.IsDir()
}
```

It's not clear to me whether this is the best approach, nor how to properly test it. I'm happy to create a PR with some feedback!

**Comment by priyawadhwa** [comment]
@Zetten I agree that currently `IsDestDir` is naive and should be improved.  I think the string parsing is necessary in the case where we have something like

```
COPY file /maybe/a/dir
```

and `/maybe/a/dir` doesn't exist yet, so the trailing slash tells us if it's meant to be a directory or a file.

Perhaps we should check if the directory exists first, and if not then check the string? If you're still interested in opening a PR for this, that would be great!

**Comment by Zetten** [comment]
The PR tries to avoid any repercussions of changing IsDestDir, but it's used in a few places and not always to check real filesystems. I'm not so hot with go but I've tried to keep it as simple and defensive as I can. For the same reason, I've also missed out testing this - it hasn't broken the existing stuff, but with some guidance I can try adding a new test.
