### ISSUE TITLE
Kaniko panic when trying to use cache with --no-push

### ISSUE THREAD

**Issue by mathroc** [GoogleContainerTools/kaniko#373]
**Actual behavior**

Kaniko panic when trying to use cache with --no-push

> $ /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/config/docker/site/Dockerfile --cache --no-push
> INFO[0000] Downloading base image nginx:1-alpine        
> 2018/09/28 04:52:00 No matching credentials were found, falling back on anonymous
> INFO[0001] Executing 0 build triggers                   
> INFO[0001] Extracting layer 0                           
> INFO[0001] Extracting layer 1                           
> INFO[0002] Extracting layer 2                           
> INFO[0002] Extracting layer 3                           
> INFO[0002] Taking snapshot of full filesystem...        
> INFO[0002] RUN rm /usr/share/nginx/html/*               
> panic: runtime error: index out of range
> 
> goroutine 1 [running]:
> github.com/GoogleContainerTools/kaniko/pkg/cache.Destination(0x2488520, 0xc421185840, 0x40, 0xc4211ccff0, 0xc421185840, 0x40, 0x0)
> 	/go/src/github.com/GoogleContainerTools/kaniko/pkg/cache/cache.go:62 +0x43f
> github.com/GoogleContainerTools/kaniko/pkg/cache.RetrieveLayer(0x2488520, 0xc421185840, 0x40, 0xc421185840, 0x40, 0x0, 0x0)
> 	/go/src/github.com/GoogleContainerTools/kaniko/pkg/cache/cache.go:34 +0x5d
> github.com/GoogleContainerTools/kaniko/pkg/executor.(*stageBuilder).build(0xc4201c46e0, 0x2488520, 0xe, 0xc4202d4b40)
> 	/go/src/github.com/GoogleContainerTools/kaniko/pkg/executor/build.go:157 +0xb3d
> github.com/GoogleContainerTools/kaniko/pkg/executor.DoBuild(0x2488520, 0x1, 0x0, 0x0, 0x0)
> 	/go/src/github.com/GoogleContainerTools/kaniko/pkg/executor/build.go:248 +0x1c3
> github.com/GoogleContainerTools/kaniko/cmd/executor/cmd.glob..func2(0x2479260, 0xc4201bc540, 0x0, 0x6)
> 	/go/src/github.com/GoogleContainerTools/kaniko/cmd/executor/cmd/root.go:73 +0x6e
> github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra.(*Command).execute(0x2479260, 0xc420038080, 0x6, 0x6, 0x2479260, 0xc420038080)
> 	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
> github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2479260, 0x0, 0x18359ce, 0x25)
> 	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:852 +0x30a
> github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra.(*Command).Execute(0x2479260, 0xc420561f78, 0xc4200440b8)
> 	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:800 +0x2b
> main.main()
> 	/go/src/github.com/GoogleContainerTools/kaniko/cmd/executor/main.go:26 +0x2d

**Expected behavior**
I expect Kaniko to show an error explaining that maybe with `--no-push`, `--cache-repo` is required

**To Reproduce**

1. run `/kaniko/executor --context /path/to/context --dockerfile /path/to/Dockerfile --cache --no-push`

**Additional Information**
 - Dockerfile 

```Dockerfile
FROM nginx:1-alpine

RUN rm /usr/share/nginx/html/*

ADD config/nginx/conf.d /etc/nginx/conf.d

COPY src/ /usr/share/nginx/html/
```
 - Build Context
only static html, js, css, etc., but not relevant as Kaniko crash before getting to a command using the build context
 - Kaniko Image : sha256:e0ffe1d20087d89bf7a0f89ef4beb9a0ec18ee5ce1da19c5f39df426db8fa85f (  debug-49184c2114f71730583b4625308d4bbdce55f266  )

**Comment by priyawadhwa** [comment]
Hey @mathroc thanks for opening this bug, I'll open a PR to fix it. Would be interested to know how the cache is working out for you as well :)

**Comment by mathroc** [comment]
Well, I've just been trying this out on some non-critical image build but those build were quite fast already so the gain is not very significant but it's noticeable. I'll report again when I'll migrate more time-consuming build to kaniko
