### ISSUE TITLE
Image build failed in Openshift

### ISSUE THREAD

**Issue by fsc12** [GoogleContainerTools/kaniko#379]
**Actual behavior**
Trying to build images in Openshift results in an error:

....
INFO[0004] Extracting layer 0
DEBU[0005] creating dir /
error building image: error building stage: chmod  /: operation not permitted

**Expected behavior**
The build successfully executes.

**To Reproduce**

1. Create a secret in Openshift
oc create secret generic kaniko-secret --from-file=kaniko-secret.json

2. Create a ConfigMap which contains the Dockerfile
oc create configmap config-docker --from-file=Dockerfile

3. Create a ConfigMap which contains x.509-certificates
oc create configmap ca-certificates --from-file=cert.crt

4.) Create the Pod 
oc create -f pod.yaml

[pod.yaml](https://github.com/GoogleContainerTools/kaniko/files/2437626/podx.txt)

5.) Dockerfile 

[Dockerfile](https://github.com/GoogleContainerTools/kaniko/files/2437646/Dockerfile.txt)

The error occurred for all base-Images I've testet (RHEL7, Debian9, Centos7).

**Comment by xanonid** [comment]
Probably, the issue is that in OpenShift per-default only non-root containers are allowed. See #105 .

**Comment by bobcatfish** [comment]
Going to assume those docs resolved the issue, plz reopen if not @fsc12 !

**Comment by chauffer** [comment]
I have made an openshift-compatible version of the executor image here which seems to work for me: https://github.com/ContainerSolutions/dockerfiles/tree/master/kaniko-openshift

I have also based it on alpine to make it work with Jenkins and to easily add CA certificates (or anything else you might need.)
It is not maintained so if you intend to use it please copy & paste the files and maintain it.
