### ISSUE TITLE
Issue with symlink during layer extraction

### ISSUE THREAD

**Issue by devderek** [GoogleContainerTools/kaniko#380]
**Actual behavior**
I'm experiencing an issue when downloading and extracting layers during a build. I see the following error:
> error building image: error building stage: error removing opt/eap/standalone/deployments to make way for new symlink: remove /opt/eap/standalone/deployments: directory not empty

This occurs when I'm downloading this image:
> registry.access.redhat.com/jboss-eap-7/eap71-openshift:1.3-10

This behavior is not experienced when performing _docker pull_ then _docker run_.

**Expected behavior**
The image downloads and extracts without symlink errors.

**To Reproduce**
In a fresh folder run the following commands:

> echo "FROM registry.access.redhat.com/jboss-eap-7/eap71-openshift:1.3-10" > Dockerfile

> docker run -it -v "$(pwd):/workspace" --entrypoint "/kaniko/executor" gcr.io/kaniko-project/executor@sha256:f22531406dfd38b6f84d9310cd713d26c623ae152ced8e4ac490734c3fdb66b5 --no-push

You should see output similar to the following:

> Unable to find image 'gcr.io/kaniko-project/executor@sha256:f22531406dfd38b6f84d9310cd713d26c623ae152ced8e4ac490734c3fdb66b5' locally
sha256:f22531406dfd38b6f84d9310cd713d26c623ae152ced8e4ac490734c3fdb66b5: Pulling from kaniko-project/executor
3f7027d6fbd3: Pull complete
b8ca5337ef48: Pull complete
7db8e39884c2: Pull complete
a4562b062142: Pull complete
717aa8849da8: Pull complete
1e5beb4c8e0d: Pull complete
afe73cead066: Pull complete
Digest: sha256:f22531406dfd38b6f84d9310cd713d26c623ae152ced8e4ac490734c3fdb66b5
Status: Downloaded newer image for gcr.io/kaniko-project/executor@sha256:f22531406dfd38b6f84d9310cd713d26c623ae152ced8e4ac490734c3fdb66b5
INFO[0000] Downloading base image registry.access.redhat.com/jboss-eap-7/eap71-openshift:1.3-10
2018/10/02 21:14:07 No matching credentials were found, falling back on anonymous
INFO[0001] Executing 0 build triggers
INFO[0001] Extracting layer 0
INFO[0012] Extracting layer 1
INFO[0012] Extracting layer 2
INFO[0013] Extracting layer 3
INFO[0021] Extracting layer 4
INFO[0040] Extracting layer 5
error building image: error building stage: error removing opt/eap/standalone/deployments to make way for new symlink: remove /opt/eap/standalone/deployments: directory not empty

**Additional Information**
You should have everything you need to reproduce the issue above.

The JBoss image, unfortunately, does not describe the commands ran between the layers. I'm not sure if that makes it reproducible but it certainly doesn't hurt to open an issue for this.

**Comment by josephndenton** [comment]
This is biting me as well. Any way we can get some eyes on it?
