### ISSUE TITLE
Ignore files in .dockerignore

### ISSUE THREAD

**Issue by hkrutzer** [GoogleContainerTools/kaniko#384]
I am using [Kaniko in Gitlab](https://docs.gitlab.com/ee/ci/docker/using_kaniko.html) and Kaniko does not seem to use my `.dockerignore.` file. This means it's adding my Git repository to the image. Is it possible to make Kaniko ignore certain files?

**Comment by priyawadhwa** [comment]
Hey @hkrutzer , the `:latest` version of the kaniko image should support .dockerignore files now!

**Comment by hkrutzer** [comment]
Amazing thank you!
