### ISSUE TITLE
Error while building stage

### ISSUE THREAD

**Issue by binarious** [GoogleContainerTools/kaniko#391]
**Actual behavior**
When building a Docker image in GitLab CI I get the following error with a specific Dockerfile:

> error building image: error building stage: lstat /tmp/tmp.JRcH0P9qiZ/trustdb.gpg: no such file or directory

**Expected behavior**
Successful build.

**To Reproduce**
1. Use [this](https://gitlab.com/binarious/kaniko-test/blob/master/Dockerfile) Dockerfile
2. Run kaniko [in GitLab CI](https://docs.gitlab.com/ee/ci/docker/using_kaniko.html)

**Additional Information**
 - Dockerfile: https://gitlab.com/binarious/kaniko-test/blob/master/Dockerfile
 - Build Context: (GitLab CI config) https://gitlab.com/binarious/kaniko-test/blob/master/.gitlab-ci.yml
 - Kaniko Image (fully qualified with digest): `sha256:1c51cd259b155c27a9fa6915ce0a13908552b6eb8c4b90192742e1a6792ff82d`
- Failing build: https://gitlab.com/binarious/kaniko-test/-/jobs/107018269

**Comment by priyawadhwa** [comment]
Hey @binarious , I tried to build this with the `:latest` image and it built successfully. Could you try with that image as well?

**Comment by priyawadhwa** [comment]
Ah I see, I was able to build it with the latest version of the `:debug` image as well. 

I also wasn't able to reproduce this with the image you provided since `gcr.io/kaniko-project/executor@sha256:1c51cd259b155c27a9fa6915ce0a13908552b6eb8c4b90192742e1a6792ff82d` doesn't seem to exist. Could you try with the latest `:debug` image?

**Comment by binarious** [comment]
It seems to work now with `:debug`. I don't know what has changed. Thank you for your time.

**Comment by ViceIce** [comment]
I have the same error with `gcr.io/kaniko-project/executor:debug@sha256:62bc2acb47775f717cd5e81076e46f2c552d0ae958cd6d300d42ff73892c19da`

```
error building image: error building stage: Unable to add file /tmp/clr-debug-pipe-149-16587078-out to layered map: Error creating hash for /tmp/clr-debug-pipe-149-16587078-out: lstat /tmp/clr-debug-pipe-149-16587078-out: no such file or directory
```

```Dockerfile
FROM microsoft/dotnet:2.2-sdk@sha256:7d8256eead49252ac2de7079268659102f44a6e40e7890fec2a7633d0b374470
```

**Comment by ViceIce** [comment]
I've added a workaround

``` Dockerfile
FROM microsoft/dotnet:2.2-sdk
ENV COMPlus_EnableDiagnostics=0
```

See https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md#disabling-managed-attachdebugging

**Comment by zmeggyesi** [comment]
I seem to be running into this _randomly_. I'll try to trace the issue, but it doesn't look like there's any rhyme or reason when a given build fails with an `lstat` error on a `/tmp/`-based directory or file...
