### ISSUE TITLE
Can not pull from 10.x.x.x:5000/... insecure registry

### ISSUE THREAD

**Issue by berndtj** [GoogleContainerTools/kaniko#405]
**Actual behavior**

When building a container from a Dockerfile if the source is an insecure registry with an internal IP (cluster IP) the registry is treated as though it's secure (i.e. https).  The --insecure flag applies to the destination (push) but not source.

**Expected behavior**
A 10.x address should be treated as insecure just like localhost and .local registries.

**To Reproduce**

Build any Dockerfile with a `FROM 10.x.x.x:5000/xxxx:xxx`

**Additional Information**
 - Dockerfile 
   Please provide either the Dockerfile you're trying to build or one that can reproduce this error.
 - Build Context
   Please provide or clearly describe any files needed to build the Dockerfile (ADD/COPY commands)
 - Kaniko Image (fully qualified with digest)

**Comment by gimler** [comment]
I think it is fixed with #401

**Comment by berndtj** [comment]
Great. I’ll give it a shot later today.

Sent from my iPhone

On Oct 24, 2018, at 03:42, Gordon Franke <notifications@github.com<mailto:notifications@github.com>> wrote:


I think it is fixed with #401<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGoogleContainerTools%2Fkaniko%2Fpull%2F401&data=02%7C01%7Cbjung%40vmware.com%7C9bd83a5046c243cfa33708d639843a14%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C1%7C0%7C636759637409157494&sdata=7oPs0tCDxjZBaUmNrA8S4%2FvLVuQcSnVsZt8KkRtxJs0%3D&reserved=0>

**Comment by berndtj** [comment]
Confirmed, this is fixed.
