### ISSUE TITLE
COPY --from=dockerimage fails

### ISSUE THREAD

**Issue by bgokden** [GoogleContainerTools/kaniko#417]
**Actual behavior**

This line fails while building with kaniko but it is actually works with docker engine
`COPY --from=gcr.io/kaniko-project/executor:latest /kaniko /kaniko`

Error:
`INFO[0012] Taking snapshot of full filesystem...
INFO[0013] COPY --from=gcr.io/kaniko-project/executor:latest /kaniko /kaniko
error building image: error building stage: lstat /kaniko/gcr.io/kaniko-project/executor:latest/kaniko: no such file or directory`

Kaniko behaves like it is a folder.

**Expected behavior**
Copy the file from remote docker image

**To Reproduce**
Use any COPY --from=dockerimage in Dockerfile

**Comment by priyawadhwa** [comment]
Hey @bgokden, thanks for opening this issue. Until this is fixed, you can use a placeholder stage in your Dockerfile which kaniko should be able to build:

```
FROM gcr.io/kaniko-project/executor:latest

FROM some/other/image
COPY --from=0 /kaniko /kaniko
```
