### ISSUE TITLE
Removing ignored files also removes the Dockerfile

### ISSUE THREAD

**Issue by jeff-knurek** [GoogleContainerTools/kaniko#422]
**Actual behavior**
After this change: https://github.com/GoogleContainerTools/kaniko/commit/6ef616b8b278ef014ca1639765515837adf38b43
there is the potential to delete the Dockerfile that in the next step of building is no longer in the context

**To Reproduce**
in the .dockerignore, add something like:
```
*
!bin
!scripts/*.sh
```
this results in:
```
INFO[0000] Removing ignored files from build context: [* !bin !scripts/*.sh] 
Error: please provide a valid path to a Dockerfile within the build context with --dockerfile
```

**Comment by priyawadhwa** [comment]
Hey @jeff-knurek , this issue should be fixed with #424, please comment on this thread or open another issue if you run into any more bugs. Thanks!
