### ISSUE TITLE
Hide --azure-container-registry-config flag from kaniko help text

### ISSUE THREAD

**Issue by priyawadhwa** [GoogleContainerTools/kaniko#427]
This flag is added by a vendored dependency, and is displayed in the kaniko help text. I tried to mark it as hidden [here](https://github.com/GoogleContainerTools/kaniko/blob/7afb11cdf7a9315c05709bdb6ea94025d086ba41/cmd/executor/cmd/root.go#L117), but it looks like that isn't working. We should probably figure out a way to hide it, as the flag makes it unclear how to push to Azure (#425)

**Comment by anjakammer** [comment]
I would rather like to have these options instead of doing a  VolumeMount for the config.json.
