### ISSUE TITLE
Kaniko usage for Private Registry 

### ISSUE THREAD

**Issue by WoodProgrammer** [GoogleContainerTools/kaniko#429]
Hi everyone , I'm running kaniko on-prem machine so we have a private registry for storing our built images . 

But I've some trouble when I wanna push the images via kaniko . 
This is my command I've runned on my shell : 

 `/kaniko/executor --context testimtest/ --dockerfile testimtest/Dockerfile --insecure --destination $IP_OF_REGISTRY/project/project:latest `

After I've runned this command I've an error . 
`
error pushing image: failed to push to destination $IP_OF_REGISTRY/project/project:latest: TAG_INVALID: "manifest tag did not match URI"`

How can I handle this problem  ?

**Comment by WoodProgrammer** [comment]
I've handled issue, problem was about image . Thanks .

**Comment by priyawadhwa** [comment]
Cool, I'll go ahead and close this issue then.
