### ISSUE TITLE
ADD does not support ENV/ADD variables

### ISSUE THREAD

**Issue by morsik** [GoogleContainerTools/kaniko#431]
**Actual behavior**
`ADD` should support variables defined in `ENV`/`ADD` like `RUN` does, and like Docker does.

Example that works in `docker build` but doesn't work with kaniko:
```Dockerfile
ARG OC_VERSION=v3.11.0
ARG OC_RELEASE=openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit

ADD https://github.com/openshift/origin/releases/download/$OC_VERSION/$OC_RELEASE.tar.gz /tmp/release.tar.gz
```

But this works:
```Dockerfile
ARG OC_VERSION=v3.11.0
ARG OC_RELEASE=openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit

RUN wget https://github.com/openshift/origin/releases/download/$OC_VERSION/$OC_RELEASE.tar.gz -O /tmp/release.tar.gz
```

**Expected behavior**
Kaniko should build this like Docker does.

**To Reproduce**
Use examples above ;)

**Additional Information**
 - Kaniko Image: `gcr.io/kaniko-project/executor:debug@f1c17ecce552018e5acb88591c9c17ad606af12473f2837d25cbb815c1308880`

**Comment by cvgw** [comment]
@morsik I am unable to repro this issue. Looks like it may have since been fixed. Can you please confirm whether it is still happening on your end. Thanks!

**Comment by morsik** [comment]
@cvgw yes, it was fixed somewhere along the way! Thanks :D

(sorry, I had to reply on this old one since you replied 1 year later too and it's just funny :P)
