### ISSUE TITLE
multi-stage copy of symlinks 

### ISSUE THREAD

**Issue by mtsyganov** [GoogleContainerTools/kaniko#437]
**Actual behavior**
In the multistage build process when a directory with symlinks is copied, the symlinks are badly created in the target image. Too many levels of symbolic links are generated.

**Expected behavior**
Symlinks are copied from source image into the target image as they are created in the source image

**To Reproduce**
1. create an image with symbolic link. For example `/usr/local/psql/bin/postmaster -> postgres` (you can check `registry.gitlab.com/gitlab-org/build/cng/postgresql:9.6.8`)
2. build a multistage image where directory with symlinks is copied to target image `COPY --from=pg_image /usr/local/psql/bin/ /usr/bin/`
3. run created image and check the copied symlinks. In the source image they are defined as `/usr/local/psql/bin/postmaster -> postgres`, but in the target image as `/usr/bin/postmaster -> /usr/bin/postmaster/postgres`. Correct symlink should be in the target image `/usr/bin/postmaster -> postgres`

**Additional Information**
 - Dockerfile 
```
FROM registry.gitlab.com/gitlab-org/build/cng/postgresql:9.6.8 as pg_image
FROM ubuntu
COPY --from=pg_image /usr/local/psql/bin/ /usr/bin/
```

**Comment by mtsyganov** [comment]
@priyawadhwa retested with latest debug image. problem is still reproducable

**Comment by andrewrynhard** [comment]
@priyawadhwa Where is this on the list of priorities? This is a major blocker for my particular use case. If low on your list I'd consider picking this up.

**Comment by miguelitoq76** [comment]
Dear @priyawadhwa we had the same error during the use of kaniko in a custom image,
this a for us a problem, until we started to create a (Dummy build via executor --no_push), to force a filesystem cleanup. See my post in https://github.com/GoogleContainerTools/kaniko/issues/434

I assume, it would be a good idea, to start the build with a "delete FS"

**Comment by priyawadhwa** [comment]
@miguelitoq76 sorry, I'm a bit confused -- do you want kaniko to delete the filesystem before starting the image build? Wouldn't that essentially be the same as directly using the kaniko image (which is built from scratch)?

**Comment by tequilarista** [comment]
Triage - collapsing 'waiting for response' category into 'blocked'

**Comment by cvgw** [comment]
I am unable to repro this issue; leading me to think that it has since been fixed. If this issue can still be repro'd please share the appropriate steps to do so.

**Comment by Kami-no** [comment]
Still got this with fresh gcr.io/kaniko-project/executor:debug

GitLab CI + Kaniko

**Comment by cvgw** [comment]
@Kami-no would you mind sharing an example Dockerfile and the options you are passing to kaniko?

**Comment by raijinsetsu** [comment]
Is this related to #1036 ?
