### ISSUE TITLE
FROM command does not honor ENV variables

### ISSUE THREAD

**Issue by mtsyganov** [GoogleContainerTools/kaniko#439]
**Actual behavior**
When I create a new image from the base image `registry.gitlab.com/gitlab-org/gitlab-ee/gitlab-assets-ee:11-5-stable-ee`, I get an error

**Expected behavior**
Image is downloaded and parsed successfully same as docker do.

**To Reproduce**
1. build an image from base image `registry.gitlab.com/gitlab-org/gitlab-ee/gitlab-assets-ee:11-5-stable-ee` 
2. receive error message
```
INFO[0000] Downloading base image "registry.gitlab.com/gitlab-org/gitlab-ee/gitlab-assets-ee:11-5-stable-ee" 
error building image: getting stage builder for stage 0: could not parse reference
```

**Additional Information**
 - Dockerfile 
`FROM registry.gitlab.com/gitlab-org/gitlab-ee/gitlab-assets-ee:11-5-stable-ee as assets`

**Comment by priyawadhwa** [comment]
Hey @mtsyganov what version of the kaniko image are you using? I tried with `gcr.io/kaniko-project/executor:v0.6.0` and `gcr.io/kaniko-project/debug-v0.6.0` and they both build the image successfully.

**Comment by mtsyganov** [comment]
@priyawadhwa you are right. 
I am sorry, I misunderstood the bug. The real problem is that kaniko dont handle correct the `"` in the FROM command when I use variables. 

following Dockerfile will fail
```
ARG ASSETS_IMAGE="registry.gitlab.com/gitlab-org/gitlab-ee/gitlab-assets-ee:11-5-stable-ee"
FROM ${ASSETS_IMAGE} as assets
```

but this Dockerfile will succeed
```
ARG ASSETS_IMAGE=registry.gitlab.com/gitlab-org/gitlab-ee/gitlab-assets-ee:11-5-stable-ee
FROM ${ASSETS_IMAGE} as assets
```

In `docker build` both cases works fine
