### ISSUE TITLE
Bug: Caching for intermediate stages is broken

### ISSUE THREAD

**Issue by MMeent** [GoogleContainerTools/kaniko#458]
**Actual behavior**
There are no snapshots being made for individual 'layers' in intermediate stages, resulting in severely degraded performance for docker-images which use intermediate stages as a way to cache multiple components.

**Expected behavior**
When I specify `--cache=true`, it should push every intermediate layer to the cache registry.

**To Reproduce**
```Dockerfile
## ./Dockerfile

## First stage, this does not get sliced into cached layers
FROM debian:stretch AS stageone

RUN touch cacheable_operation
RUN touch stageone_file

## Second stage, this does not get sliced into cached layers
FROM debian:stretch AS stagetwo

RUN touch cacheable_operation
RUN touch stagetwo_file

## Third stage, this does not get sliced into cached layers
FROM debian:stretch AS stagethree

RUN touch cacheable_operation
RUN touch stagethree_file

## Final stage, this one does get sliced into cached layers
FROM debian:stretch

RUN mkdir files
COPY --from=stageone stageone_file files/
COPY --from=stagetwo stagetwo_file files/
COPY --from=stagethree stagethree_file files/
```
```sh
/kaniko/executor --cache=true --context . --dockerfile ./Dockerfile
```

**Additional Information**
This specifically happens [here](https://github.com/GoogleContainerTools/kaniko/blob/0c294138b891f0dc05f495d60b274889894e10fc/pkg/executor/build.go#L220). Kaniko iterates over the steps in the build process and `continue`s (and therefore skips the later cache upload step) if [`stage.shouldTakeSnapshot(index, ...)`](https://github.com/GoogleContainerTools/kaniko/blob/0c294138b891f0dc05f495d60b274889894e10fc/pkg/executor/build.go#L261) is false, which it always is for intermediate commands in a non-final stage.

**Comment by andrewrynhard** [comment]
@MMeent This is hitting me right now. You happen to be working on a PR? I can get one going if not. This is pretty painful to live with.

**Comment by MMeent** [comment]
I am not woking on any PR, so feel free to do so yourself.

**Comment by bobcatfish** [comment]
If you can take this on @andrewrynhard that's awesome!! :heart:
