### ISSUE TITLE
Add support for runtime labels in kaniko executor

### ISSUE THREAD

**Issue by tblaisot** [GoogleContainerTools/kaniko#465]
Hello,

We are missing a "docker build" feature in kaniko : the ability to pass label to add into the command line dynamically at runtime like this
`docker build . --label "version=1.0" --label "org.label-schema.vcs-ref = "279FA63""`

We used this to be able to add label containning build-time information (vcs informations, build date, etc...) using http://label-schema.org/rc1/.
This add a lot a boilerplate actually in kaniko because you must add all thoses label to all Dockerfiles using build args and passing build args to the cli...

Would be nice to have this, Thanks for your hard work !

**Comment by dgageot** [comment]
Thank you @tblaisot for submitting this issue!
Will you be able to create tickets for the compatibility issues that you faced too?

**Comment by tblaisot** [comment]
Hi @dgageot 
After a little analyse this morning i found that the bugs we have are already in the issue list:
we encounter #453 when using npm because the cache is on /root/.npm ...
BTW the node image is the one we encounter the more problem with (because of cache folder and global folder), I think it is a very good candidate to test kaniko :)
and i think we encouter #331 but not so sure about this one ...
I subscribe to thoses issues to be able to test it when corrected

**Comment by dgageot** [comment]
👍

**Comment by l2dy** [comment]
Fixed in #1075?

**Comment by tblaisot** [comment]
In fact it is now fixed I just use this new feature.
Thanks a lot.
