### ISSUE TITLE
Flaky integration test

### ISSUE THREAD

**Issue by priyawadhwa** [GoogleContainerTools/kaniko#472]
We should look into this flaky integration test:

>    --- FAIL: TestLayers/test_layer_Dockerfile_test_meta_arg (8.38s)
    	integration_test.go:241: Difference in number of layers in each image is 1 but should be 0. Image 1: Image: [gcr.io/kaniko-test/docker-dockerfile_test_meta_arg] Digest: [b14452bdb444ddad9ab2c2d85cc4d9114abb91e4d43d815de5d6b4bbccb5e4b9] Number of Layers: [3], Image 2: Image: [gcr.io/kaniko-test/kaniko-dockerfile_test_meta_arg] Digest: [3bde6500d9a626e06fc7abb126dfc2ff77175aaa037b72ea76ff39eaa7aa87e0] Number of Layers: [2]

**Comment by bobcatfish** [comment]
oh noes, not again!!

Did this just start flaking recently @priyawadhwa or has it been going for a while?

**Comment by priyawadhwa** [comment]
I noticed it a couple days ago with #459, seems like the number of layers is sometimes what we expect and sometimes off by one!

**Comment by sharifelgamal** [comment]
This is related to how we treat empty layers, I'm not sure why we sometimes build the extra layer and sometimes not.

**Comment by dlorenc** [comment]
I think I sent a fix for this in #498
