### ISSUE TITLE
Container structure test fail on symlink when building with Kaniko (ok using Docker build)

### ISSUE THREAD

**Issue by bgauduch** [GoogleContainerTools/kaniko#481]
Hello there 👋 

Ping @nkubala and @priyawadhwa 😉 

**Actual behavior**
Basically, when building an image using Kaniko (Apache on Alpine), symlinks created by Apache for modules under `/var/www/modules/` are KO when building with Kaniko, but OK when building with Docker.

Running tests with Container Structure Test throw errors when testing symlinked files presence.
See original issue on Container Structure Test describing the process : [issue 182](https://github.com/GoogleContainerTools/container-structure-test/issues/182#issuecomment-444616626)

**Expected behavior**
When building with Kaniko, Symlinks are expected to be present in the produced image.

**To Reproduce**
1. Use a simple Dockerfile installing Apache in Alpine:
```dockerfile
FROM alpine:3.8
RUN apk add --no-cache apache2=2.4.35-r0
```
2. Build with Kaniko
3. Run Container structure test on it (as specified in [issue 182](https://github.com/GoogleContainerTools/container-structure-test/issues/182#issuecomment-444616626))
4. Tests on symlinked files fails.
5. Tests on original files location succeeds.

**Additional Information**
 - Dockerfile: see previous steps to reproduce.
 - Build Context: just the local directory (Only Dockerfile is needed)
 - Kaniko Image: cannot be provided as-is (private image)

I know there is a lot of other issues / PR already related to symlinks, so hopefully this is not a duplicate.

**Comment by cvgw** [comment]
Hello, I am unable to repro this issue against the latest version of kaniko. I'm going to close this issue as it has most likely been fixed. If this issue is still present or this has been closed in error please re-open.
