### ISSUE TITLE
Allow overriding CMD and ENTRYPOINT

### ISSUE THREAD

**Issue by FranklinYu** [GoogleContainerTools/kaniko#484]
This is a feature request.

Docker Compose allow us to override `CMD` with [`command` key](https://docs.docker.com/compose/compose-file/#command), or `ENTRYPOINT` with [`entrypoint` key](https://docs.docker.com/compose/compose-file/#entrypoint). This is useful if we want to build multiple images in same context, with command or entrypoint as the only difference.

Somewhat related to #309.

**Comment by priyawadhwa** [comment]
@FranklinYu just to clarify, do you want to be able to override the command and entrypoint of the kaniko image?

**Comment by FranklinYu** [comment]
I think I misunderstood something about Docker image. Sorry.
