### ISSUE TITLE
An example of running kaniko in minikube

### ISSUE THREAD

**Issue by debuggy** [GoogleContainerTools/kaniko#494]
Hi, 

I write a detailed example for kaniko usage in minikube, to demo the simple usage of local build context and secret.  https://github.com/debuggy/kaniko-example

I had the same confusions with some issues (like #489 #109 ) before. Maybe this example will explain some.

**Comment by priyawadhwa** [comment]
@debuggy this is great! I think this would be really useful for a lot of users, would you be willing to add a section to our README with some of the key information?

**Comment by debuggy** [comment]
@priyawadhwa hi, sorry for the late reply.

I wrote this tutorial as a test case cause we had used kaniko in an image building and caching service. Since several months passed I need to go through this process again to ensure the correctness.

And I'm happy to contribute to the docs if it is ready. It is more like a get-started tutorial for new comers. So in which section do you prefer to put it in?

**Comment by priyawadhwa** [comment]
@debuggy no worries and thank you! I was thinking we could have a `docs/tutorial.md` file, and in the README we could have a `Tutorial` section that would point to it. Does that sound good?

**Comment by debuggy** [comment]
@priyawadhwa sounds reasonable, I will refine the tutorial and send a PR soon.
