### ISSUE TITLE
Local cache

### ISSUE THREAD

**Issue by andrewrynhard** [GoogleContainerTools/kaniko#496]
Using kaniko locally via `docker run` could be a better experience if local caching was allowed. At first I expected `--cache-dir` to do this, but that is only for the base images. Without this functionality, I have to run through my entire build every time while I develop, and that could take upwards of 30 minutes on some projects. Local caching would be great.

**Comment by dlorenc** [comment]
Hey,

This should be doable! We could store the intermediate layers on disk as well as the base image layers. We haven't enabled this ourselves yet because we mostly use kaniko stateless environments, but we'd welcome a PR here.

**Comment by dylanpiergies** [comment]
This would be an extremely useful feature. It's not hard to attach NFS storage to stateless pods. I'm already doing precisely this to allow Gradle to cache.

**Comment by cvgw** [comment]
I've created a proposal for this feature https://github.com/GoogleContainerTools/kaniko/issues/923

Closing this issue to continue discussion there.
