### ISSUE TITLE
Host Destination (Build & Run Locally)

### ISSUE THREAD

**Issue by davidbarratt** [GoogleContainerTools/kaniko#502]
Docker Compose has a `build` option:
https://docs.docker.com/compose/compose-file/#build
that option allows the user to use a `Dockerfile` instead of a remote image.

When the user does `docker-compose up` Compose will build the image and then run it (or you can do `docker-compose build` to build the image and then `docker-compose up` to use that image).

Would it be possible to use kaniko in this way? I'm looking to replace Docker Compose with k8s, but this missing feature is critical. Basically I'd like a `host` destination that would push (and optionally tag) the container

**Comment by davidbarratt** [comment]
I guess I could run a docker registry locally and push to that? or is there a more elegent solution?

**Comment by tejal29** [comment]
@davidbarratt I am not sure what the ask is here. 
Kaniko is used to build images from a Dockerfile, inside a container or Kubernetes cluster.
For locally building and running an app, you sould our other initiative Skaffold.
Skaffold also supports docker compose. 
https://github.com/GoogleContainerTools/skaffold/tree/master/examples/compose

**Comment by davidbarratt** [comment]
I think Skaffold is exactly what I'm looking for! thanks!
