### ISSUE TITLE
Warmer does not work with private images

### ISSUE THREAD

**Issue by jamesatha** [GoogleContainerTools/kaniko#503]
**Actual behavior**
I have a pod running the cache warmer. It has multiple --image arguments. The public images download just fine but the rest silently fail. I have made sure the docker config is mounted at /kaniko/.docker/config.json and the DOCKER_CONFIG environment variable is set to /kaniko/.docker/

**Expected behavior**
Should use the credentials specified to download the private image.

**To Reproduce**
1. Create a pod with for the cache warmer. Make sure there are some private images. In the list of images. Make sure that the docker config is properly mounted. 
2. See that the private image was not downloaded

**Additional Information**
Using gcr.io/kaniko-project/warmer:latest

**Comment by mamoit** [comment]
I'm using gitlab ci and in order to configure docker it actually [requires a shell](https://docs.gitlab.com/ee/ci/docker/using_kaniko.html).
Having a debug image for the warmer would give a lot of flexibility for this kind of use cases where some pre-configuring is needed.

**Comment by mamoit** [comment]
#497 should allow to setup the credentials prior to warming up the cache.

**Comment by mamoit** [comment]
I have built a debug kaniko image with the warmer inside of it, and I can verify what @jamesatha said, I try to pull the images with the docker config setup (that works with kaniko), but it silently fails when trying to pull a image from a private repo.

**Comment by pdemagny** [comment]
I also confirm that even when using #497, it still does not work with gitlab ci private registry :(
It would be awesome if it did !

**Comment by efenex** [comment]
same issue here, using debug image in combination with gitlab and warmer fails to pull private images, even though GOOGLE_APPLICATION_CREDENTIALS environment variable is configured and exported:

```
$ /kaniko/warmer --cache-dir=/cache --image=$CI_REGISTRY/private/base:1.4.3.1 --image=node:8-alpine
Failed warming cache: Failed to retrieve image: gitlab:4567/private/base:1.4.3.1: DENIED: access forbidden
```

**Comment by bflorat** [comment]
FYI, I had the same issue and with kaniko 0.11 executor and warmer, everything's fine now (layers and FROM private images now cached locally as expected). Thanks.

Note : I don't use the official Kaniko image but an in-house image using the same executor and warmer binary. Didn't tested with the official image.

**Comment by Enelar** [comment]
Confirmed. My workaround:

```
echo "FROM $SOURCE" > Dockerfile.try-pull
export WARM_RESULT=$(executor --dockerfile Dockerfile.try-pull --no-push -v panic )
if [[ $WARM_RESULT ]]
then
  # ...
fi
```

**Comment by Enelar** [comment]
@priyawadhwa please tag as issue. This isn't documented behavior.
Lost several hours debugging build scripts because it wasn't mentioned that warmer is not using docker login configs.

Our build pipeline have several layers of caching partial images, because building from scratch taking tens of minutes. After migrating from dind to kaniko, for some modules build process broke out.
