### ISSUE TITLE
'could not parse reference' for cached builds with UPPERCASE stage names

### ISSUE THREAD

**Issue by dinvlad** [GoogleContainerTools/kaniko#519]
**Actual behavior**
Multi-stage builds fail with
```
error building image: getting stage builder for stage 2: could not parse reference
```
if `--cache=true` and stage names contain UPPERCASE letters.

**Expected behavior**
Cached builds should succeed irregardless of character case in stage names.

**To Reproduce**
1. Set up CloudBuild builds based on https://github.com/broadinstitute/kaniko-stage-naming-bug
    (the builds are trigged with `--cache=true`).
2. The build should fail with
    ```
    WARN[0011] Error while retrieving image from cache: could not parse reference 
    error building image: getting stage builder for stage 2: could not parse reference
    ```
Stage 2 is the one trying to use the previous stage named with uppercase letters (see below). The build succeeds for stage 1, which refers to stage 0 with only lowercase letters and _.

**Additional Information**
 - Dockerfile
    ```Dockerfile
    FROM alpine as base_stage

    RUN echo base_stage


    FROM base_stage as BUG_stage

    RUN echo BUG_stage


    FROM BUG_stage as final_stage

    RUN echo final_stage
    ```
 - Build Context
    Does not apply.
 - Kaniko Image (fully qualified with digest)
    `gcr.io/kaniko-project/executor@sha256:a3e1a4ac0fc9625ce0eb2f74094e4e801cb1164c93a1dd6b8d2306f6efee7d9a`

**Comment by faiq** [comment]
I've experienced this issue not only with stage build names but building docker images that start with an all caps from image.

ie:

```
FROM CENTOS
RUN ls 
```

fails for me.

**Comment by cvgw** [comment]
> FROM CENTOS
> RUN ls

I don't believe `CENTOS` is a valid image name. AFAIK only lowercase letters, `_`, and `-` are allowed.

Looking into the issue with stage aliases

**Comment by cvgw** [comment]
I believe the issue is with this line
https://github.com/GoogleContainerTools/kaniko/blob/00a01f9f290b8df7620adbc199d03954eed312ba/pkg/dockerfile/dockerfile.go#L97

as `stage.Name` will be all lowercase while `stages[currentStage].BaseName` will be the original case

like such
```
stage name bug_stage current stage idx 2 current stage base name BUG_stage
```

**Comment by cvgw** [comment]
also here https://github.com/GoogleContainerTools/kaniko/blob/00a01f9f290b8df7620adbc199d03954eed312ba/pkg/dockerfile/dockerfile.go#L252

**Comment by cvgw** [comment]
I wonder if this line also should be updated https://github.com/GoogleContainerTools/kaniko/blob/00a01f9f290b8df7620adbc199d03954eed312ba/pkg/dockerfile/dockerfile.go#L197
