### ISSUE TITLE
"lstat /root/.config: no such file or directory" when using caching with google/cloud-sdk:alpine

### ISSUE THREAD

**Issue by dinvlad** [GoogleContainerTools/kaniko#520]
**Actual behavior**
While re-building an image based on `google/cloud-sdk:alpine` with `--cache=true`, the build process fails with
```
error building stage: Unable to add file /root/.config to layered map: Error creating hash for /root/.config: lstat /root/.config: no such file or directory
```

**Expected behavior**
The build should succeed.

**To Reproduce**
1. Try to build an image based on `google/cloud-sdk:alpine`
2. Observe the build log.

**Additional Information**
 - Dockerfile 
   ```Dockerfile
    FROM google/cloud-sdk:alpine
    ```
 - Build Context
   Not needed.
 - Kaniko Image (fully qualified with digest)
    `gcr.io/kaniko-project/executor@sha256:a3e1a4ac0fc9625ce0eb2f74094e4e801cb1164c93a1dd6b8d2306f6efee7d9a`

**Comment by dinvlad** [comment]
Thanks - `--single-snapshot` helps, but caching still doesn't work properly then.

**Comment by cvgw** [comment]
I am unable to repro this issue with or without the `--cache` flag enabled. If this is still an issue please share updated repo instructions. Thanks!

**Comment by cvgw** [comment]
Closing this issue; feel free to reopen if this bug still exists or re-surfaces

**Comment by thavlik** [comment]
FYI I am experiencing this issue. Multi-stage docker file, golang base image:

```
FROM golang:latest AS builder
WORKDIR /go/src/github.com/thavlik/my-app
COPY src .
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o my-app

FROM alpine:3.9.4
WORKDIR /app
COPY --from=builder /go/src/github.com/thavlik/my-app/my-app .
ENTRYPOINT [ "./my-app" ]
```

```
INFO[0049] COPY --from=builder /go/src/github.com/thavlik/my-app/my-app . 
INFO[0049] Found cached layer, extracting to filesystem 
error building image: error building stage: failed to take snapshot: unable to add file /app/my-app to layered map: error creating hash for /app/my-app: lstat /app/my-app: no such file or directory
INFO[0049] Taking snapshot of files... 
```

It fails every time with `--cache=true` and works every time without it.

EDIT: I just inserted a `RUN ls` layer for debugging purposes and it was able to build:
```
FROM alpine:3.9.4
WORKDIR /app
RUN ls
COPY --from=builder /go/src/github.com/thavlik/my-app/my-app .
ENTRYPOINT [ "./my-app" ]
```
Yikes.

**Comment by dinvlad** [comment]
@thavlik have you tried `:debug-a1af057f997316bfb1c4d2d82719d78481a02a79` yet? It addresses issues linked via https://github.com/GoogleContainerTools/kaniko/pull/1069, which I believe includes this one. You may have to delete Kaniko cache prior to re-running it though.

(BTW, can't wait until this image tag gets re-tagged as `:debug`)

**Comment by StarkillerObl** [comment]
@dinvlad We have similar issue and we have tried it, but it fails in the same way.

Our last successful dockerization was yesterday and it used:
docker image sha256:025bd79d3e0699b5f59142b03f7e66916980bd0e32653b9c7e21b561d4e538c3 for gcr.io/kaniko-project/executor:debug

We have tried to locate this particular image in https://console.cloud.google.com/gcr/images/kaniko-project/GLOBAL, but with no results unfortunately.

**Comment by thavlik** [comment]
> @thavlik have you tried `:debug-a1af057f997316bfb1c4d2d82719d78481a02a79` yet? It addresses issues linked via #1069, which I believe includes this one. You may have to delete Kaniko cache prior to re-running it though.
> 
> (BTW, can't wait until this image tag gets re-tagged as `:debug`)

I have not been able to reproduce the bug after changing the Dockerfile so the cache wasn't utilized. Fingers crossed it doesn't happen again lol
