### ISSUE TITLE
Stages with WORKDIR/only mkdir break caching

### ISSUE THREAD

**Issue by dinvlad** [GoogleContainerTools/kaniko#521]
**Actual behavior**
In a multi-stage build, if there's a step that only creates a folder (using `mkdir` or `WORKDIR`), then the downstream stages won't be cached.

**Expected behavior**
All stages cached if Dockerfile and context are unchanged.

**To Reproduce**
1. Create a Dockerfile with mkdir (example below)
2. Build once  with `--cache=true`
3. Build again with `--cache=true`
4. Observe the logs for both builds.
    Example from the 1st build:
    ```
    INFO[0003] RUN mkdir /cached_folder 
    INFO[0003] Found cached layer, extracting to filesystem 
    INFO[0004] Taking snapshot of files... 
    INFO[0004] Storing source image from stage 1 at path /kaniko/stages/1 
    INFO[0004] Deleting filesystem... 
    INFO[0004] Base image from previous stage 1 found, using saved tar at path /kaniko/stages/1 
    INFO[0004] Checking for cached layer gcr.io/project/kaniko-stage-caching-bug/cache:0116a345bc87ada9dc8811779ae7fe241a4c9e4fe45b55576dadd56adf2fa807
    INFO[0004] No cached layer found for cmd RUN echo bug_stage 
    ```
    Example from the 2nd build:
    ```
    INFO[0002] RUN mkdir /cached_folder 
    INFO[0002] Found cached layer, extracting to filesystem 
    INFO[0002] Taking snapshot of files... 
    INFO[0002] Storing source image from stage 1 at path /kaniko/stages/1 
    INFO[0003] Deleting filesystem... 
    INFO[0003] Base image from previous stage 1 found, using saved tar at path /kaniko/stages/1 
    INFO[0003] Checking for cached layer gcr.io/project/kaniko-stage-caching-bug/cache:7cdf15b929af18bcb142fdb9647f6d3b07a3d2cad3a056950792b0afbcb2b562
    INFO[0003] No cached layer found for cmd RUN echo bug_stage
    ```
5. Observe that hashes for the `RUN mkdir /cached_folder` layer *differ* in both cases, hence breaking caching of subsequent layers.
6. The same issue occurs if one uses `WORKDIR /cached_folder` instruction instead of `RUN mkdir /cached_folder`.

**Additional Information**
 - Dockerfile
    ```Dockerfile
    FROM alpine as base_stage

    RUN echo base_stage


    FROM base_stage as cached_stage

    RUN mkdir /cached_folder


    FROM cached_stage as bug_stage

    RUN echo bug_stage
    ```
 - Build Context
   None.
 - Kaniko Image (fully qualified with digest)
    `gcr.io/kaniko-project/executor@sha256:a3e1a4ac0fc9625ce0eb2f74094e4e801cb1164c93a1dd6b8d2306f6efee7d9a`
- Full example with this repro: https://github.com/broadinstitute/kaniko-stage-caching-bug

**Comment by dlorenc** [comment]
I have a theory here - I think the issue is actually with multiple steps rather than mkdir. The cache key we use is based on the digest of the base image for each stage.

In your 3 part dockerfile, I added some debugging and here's what I'm seeing for the misses:

```
Key missing was: sha256:51ebab957bac82fccfed2e00f66f4cd817ca08882f73b70850248e646192c460-RUN echo bug_stage 
```

and
```
Key missing was: sha256:92bd9ab06fee00b82065c71314c25f5d32d0fa70d3faad014ba015e866834427-RUN echo bug_stage 
```

So the difference is actually the digest of `FROM base_stage as cached_stage`.

I think that sort of makes sense actually - even though the files are the same the image will have a different digest because the timestamp has changed.

* the base image for stage one, alpine, will always have the same digest so we see the first cache hit.
* the base image for stage two, is just alpine. The echo command in stage one never changed anything so we never added a new layer.
* stage three is now the alpine image + a layer. This means we get a new image digest each time because of timestamps.

I need to think this through some more to figure out what the right behavior should actually be.

**Comment by dlorenc** [comment]
I can confirm that with another Dockerfile:

```shell
FROM alpine as base_stage

RUN echo base_stage > base


FROM base_stage as cached_stage

RUN echo cached_stage > cache

FROM cached_stage as bug_stage

RUN echo bug_stage > bug
```

The same caching issue happens here.

**Comment by dinvlad** [comment]
Thank you for looking into this! I also saw similar behavior without mkdir, although couldn't pinpoint it.

**Comment by tarr11** [comment]
This bug seems to still exist in latest master.  Using multi-stage builds with COPY causes different hashes each time.  If I remove the multi stages, it works.

**Comment by michaelfindlater** [comment]
I am also running into this bug in a multistage build.

**Comment by soapwong703** [comment]
I found this issue still exists in v1.23.1

**Comment by lovitt** [comment]
I've been pulling my hair out for months over inexplicable kaniko cache misses on Google Cloud Build.

My Dockerfile is actually pretty close to the default Rails Dockerfile, which is multi-stage. Multi-stage builds are not uncommon and it's pretty frustrating that kaniko can't handle them properly.
