### ISSUE TITLE
Are there tagged debug images available?

### ISSUE THREAD

**Issue by nelsonjchen** [GoogleContainerTools/kaniko#528]
Pretend I wanted to pin my build on GitLab CI to using Kaniko `v0.7.0`. [I would need to use the `debug` variant of Kaniko to build there](https://docs.gitlab.com/ee/ci/docker/using_kaniko.html#building-a-docker-image-with-kaniko).

`gcr.io/kaniko-project/executor:v0.7.0` exists, but it's non-debug and does not have busybox. 

`gcr.io/kaniko-project/executor:debug` exists but it's pretty much `latest` with busybox.

Are there releases where it is tagged for a released version of Kaniko and is like debug which has busybox? Something like `gcr.io/kaniko-project/executor:v0.7.0-debug`?

If this already exists, it would be nice to document in the README.

**Comment by nelsonjchen** [comment]
If I go to https://gcr.io/kaniko-project/executor , I get a list of images, and `debug-v0.7.0` would be the tag. Sorry for the bother.

**Comment by dlorenc** [comment]
Yup! No worries. We provide them for both tags and commits:
debug-${COMMIT_SHA}
debug-${TAG_NAME}
