### ISSUE TITLE
Provide image for arm64

### ISSUE THREAD

**Issue by everflux** [GoogleContainerTools/kaniko#530]
**Actual behavior**
Currently only amd64 architecture is supported

**Expected behavior**
Multi-arch images of the kaniko executor for amd64 and arm/arm64 are provided.

**Comment by MansM** [comment]
It actually builds on arm and arm64:
Arm64: https://www.trion.de/news/2019/02/01/kaniko-arm-image.html
Arm32: https://gist.github.com/MansM/d72295cc7214fc11f258ba7a22605d2e

On arm32 I have some weird issues:
- need to specify arch in Dockerfile
- arm32v7/fedora pulls
- arm32v7/golang:1.10 doesn’t get pulled by Kaniko, docker itself pulls fine

**Comment by lisa** [comment]
@MansM I believe https://github.com/GoogleContainerTools/kaniko/pull/646 addresses the need to specify arch in the Dockerfile.

**Comment by njgraham** [comment]
I would love to see an aarch64 image provided.  Meanwhile, I may try out the instructions linked by @MansM (with help from Google translate) - maybe it's not too difficult.

**Comment by qbasicer** [comment]
It would be great to have this officially supported as the solution linked by @MansM no longer works out of the box.

**Comment by mickkael** [comment]
> 
> 
> It would be great to have this officially supported as the solution linked by @MansM no longer works out of the box.

It seems to be available now.
https://github.com/GoogleContainerTools/kaniko/releases/tag/v1.3.0

**Comment by effitient** [comment]
> > It would be great to have this officially supported as the solution linked by @MansM no longer works out of the box.
> 
> It seems to be available now.
> https://github.com/GoogleContainerTools/kaniko/releases/tag/v1.3.0

I think this issue can be closed. But still missing debug images for arm64: #1488

**Comment by gabrielfreire** [comment]
Help please! 

I have a cluster deployed in a couple of Raspberry PIs and am trying to build a Tekton pipeline for my project but it became an incredibly frustrating experience as i'm getting the following error from `gcr.io/kaniko-project/executor@sha256:b44b0744b450e731b5a5213058792cd8d3a6a14c119cf6b1f143704f22a7c650`

```
could not find command for platform "linux/arm64/v8"
```

According to Kaniko this image supports multiple architectures including **arm64** 

My K8s cluster is version **v1.20.6** so I had to install **Tekton v0.32.4**

What should I do ? Is there any more specific image I could try ? I have already tried  
- gcr.io/kaniko-project/executor:1.5.1
- gcr.io/kaniko-project/executor:1.6.0
- gcr.io/kaniko-project/executor:1.7.1
- gcr.io/kaniko-project/executor:1.8.1
- gcr.io/kaniko-project/executor:latest

**Comment by imjasonh** [comment]
arm64 images are provided, so this can be closed.

As for https://github.com/GoogleContainerTools/kaniko/issues/530#issuecomment-1113027801, a similar platform selection bug was fixed in Kaniko by https://github.com/GoogleContainerTools/kaniko/pull/2025 which I believe is available in 1.8.1.

But the `could not find command for platform "linux/arm64/v8"` sounds like a Tekton bug, specifically https://github.com/tektoncd/pipeline/issues/4548, which may be fixed in a later Tekton version than v0.32.4.

If you get a chance to try a later Tekton release, and this still happens, let me know.

**Comment by gabrielfreire** [comment]
Thanks for your response, I've updated my cluster to v1.22+ and installed latest **Tekton** and it worked fine, not out of the box though
- i had to create a custom kaniko task that pulls `docker.io/library/bash:latest` for step `step-write-url` as the default one didn't work for `arm64`

**Comment by imjasonh** [comment]
That sounds like a bug in the kaniko task, the bash image should support arm64, I'm not sure what tag that digest points to but it looks wrong.

Anyway I'm glad you were able to get this working with the latest Tekton! 👍
