### ISSUE TITLE
Support for private object storage (minio)

### ISSUE THREAD

**Issue by akranga** [GoogleContainerTools/kaniko#531]
As a user I want to use Kaniko with my private object storage (like minio). At present kaniko supports `s3://...` prefix however it goes into aws s3 location. 

Kaniko can use shared credentials file [code here](https://github.com/GoogleContainerTools/kaniko/blob/master/pkg/buildcontext/s3.go#L40) that does not allow to set custom endpoint URL. 

Custom endpoint URL is an important prerequisite for private object storage. I would like to suggest to add a configuration parameter (`config.json`?) to allow user defined s3 endpoint url (`endpoint-url`)

**Comment by akranga** [comment]
Happy to make a PR if this issue will be supported

**Comment by nareshganesan** [comment]
would love to get this feature. +1

**Comment by davinkevin** [comment]
Very interested by this one to use minio and all S3 alternative out there (Cellar from Clever cloud by example...)
