### ISSUE TITLE
Building a stage using image with both tag and SHA digest fails

### ISSUE THREAD

**Issue by martin-sucha** [GoogleContainerTools/kaniko#535]
**Actual behavior**
With a Dockerfile containing a stage like this:
```
FROM ubuntu:latest@sha256:868fd30a0e47b8d8ac485df174795b5e2fe8a6c8f056cc707b232d65b8a1ab68
```

Kaniko fails with the following message:
```
Downloading base image ubuntu:latest@sha256:868fd30a0e47b8d8ac485df174795b5e2fe8a6c8f056cc707b232d65b8a1ab68 
error building image: getting stage builder for stage 0: could not parse reference
```

**Expected behavior**
Since Docker itself can build the image from the Dockerfile, I expect kaniko to be able to do the same.

**To Reproduce**
1. `echo "FROM ubuntu:latest@sha256:868fd30a0e47b8d8ac485df174795b5e2fe8a6c8f056cc707b232d65b8a1ab68" >Dockerfile`
2. `docker run -v "$(pwd):/workspace" gcr.io/kaniko-project/executor:debug@sha256:901f53b350d0681d1fcde2654bdab048610428e1150beda51acb76fedd62ad85 --dockerfile Dockerfile --destination test`

**Comment by martin-sucha** [comment]
The error comes from [ParseReference](https://github.com/GoogleContainerTools/kaniko/blob/b0e7c0e8cd07ef3ad2b7181e0779af9fcb312f0b/vendor/github.com/google/go-containerregistry/pkg/name/ref.go#L49) in `go-containerregistry`. The function can't parse image references with both tag and SHA.

**Comment by everflux** [comment]
Could this be related to the failure with multi-arch images when the manifest points to tag-hash-image?
I resolved the nginx:alpine arm image to docker.io/library/nginx:alpine@sha256:88f143e0196aad3eb20c56a4c78f55881de72c2e688ebc87eacfacaa734bc8db and the build failes with

```
INFO[1461] Error while retrieving image from cache: could not parse reference 
INFO[1461] Downloading base image docker.io/library/nginx:alpine@sha256:88f143e0196aad3eb20c56a4c78f55881de72c2e688ebc87eacfacaa734bc8db 
error building image: getting stage builder for stage 1: could not parse reference
```

**Comment by ViceIce** [comment]
Any chances to get this working soon? This is a blocker for me.

**Comment by priyawadhwa** [comment]
Hey @ViceIce , based on this [comment](https://github.com/GoogleContainerTools/skaffold/pull/1709#issuecomment-468762497) I think somebody will have to open a PR in go-containerregistry with the fix for this to work.

**Comment by ViceIce** [comment]
Looks like I have to learn go to get this fixed. 😁

**Comment by ViceIce** [comment]
Done 😁 

https://github.com/google/go-containerregistry/pull/391

**Comment by ViceIce** [comment]
Merged 😁
