### ISSUE TITLE
The images do not appear in Harbor, when they are pushed by kaniko on the registry.

### ISSUE THREAD

**Issue by gauthierc** [GoogleContainerTools/kaniko#539]
When i create a new image in empty folder in Harbor registry, this image do not appear.
I can make a 'docker pull' of this new image with no problem in my computer.
When I push this image with 'docker push' command from my computer, it's appear well in the registry.
I think so that the problem become from kaniko.
I use latest docker image of kaniko  gcr.io/kaniko-project/executor:debug in kubernetes.

Thanks

**Comment by vaxinate** [comment]
I'm also having this exact same problem. My kaniko pod shows "COMPLETED" and the logs indicate that the image was successfully published. I can use `docker pull` to download it locally, but it doesn't appear in the web ui for Harbor.

**Comment by vaxinate** [comment]
On further investigation, it seems like this could be a Harbor bug https://github.com/goharbor/harbor/issues/3348

**Comment by donmccasland** [comment]
I'm closing this bug based on the last comments.  If folks think it should still be open, please reopen with steps to reproduce.
