### ISSUE TITLE
FR: Before push to register, call clair to scan image.

### ISSUE THREAD

**Issue by Renz2018** [GoogleContainerTools/kaniko#563]
between build and push, call [clair ](https://github.com/coreos/clair)to scan image.
Vulnerability Static Analysis for Containers

**Comment by donmccasland** [comment]
This is something that should be handled in your CI flow, not kaniko.

**Comment by travisghansen** [comment]
@donmccasland what if someone wants to scan before push?

**Comment by GaetanJaminon** [comment]
@donmccasland  It is actually a best practice (requirement) to scan your image before pushing it to the Registry. Security tools like StackRox will prevent to push a image that is not scanned.
