### ISSUE TITLE
Odd behaviour with EPERM on whiteout file in unprivileged container

### ISSUE THREAD

**Issue by glenjamin** [GoogleContainerTools/kaniko#566]
I've been experimenting with building containers on CircleCI using kaniko, and it's mostly working well. However i'm getting some behaviour I can't explain when trying to build an image based on the kaniko executor - i'm able to build this same image fine with docker.

**Actual behavior**
Building fails with the error
```
error building image: removing whiteout kaniko/ssl/.wh..wh..opq: lstat /kaniko/0/kaniko/ssl/.wh..opq: operation not permitted
```

**Expected behavior**
The build should have completed successfully.

**To Reproduce**
1. This CircleCI job demonstrates the issue, with debug logging enabled: https://circleci.com/gh/glenjamin/kaniko-publish-orb/58

**Additional Information**

This is the github repo: https://github.com/glenjamin/kaniko-publish-orb/tree/build-with-itself

It effectively runs this dockerfile
```
FROM gcr.io/kaniko-project/executor:latest as builder

FROM alpine

COPY --from=builder /kaniko /kaniko
RUN echo "{}" > /kaniko/.docker/config.json

ENV PATH="$PATH:/kaniko"
ENV SSL_CERT_DIR=/kaniko/ssl/certs
ENV DOCKER_CONFIG /kaniko/.docker/

WORKDIR /workspace

ENTRYPOINT ["/kaniko/executor"]
```

with this command
```
/kaniko/executor --dockerfile Dockerfile --context /workspace --destination docker.io/glenathan/circleci-kaniko:build-58 --no-push -v debug
```

I've executed the same command on my local docker-for-mac environment, where it worked. And also on an ubuntu VM where I enabled userns-remap and that worked too:

```
docker run -it -v $(pwd):/workspace glenathan/circleci-kaniko:build-51 --dockerfile Dockerfile --context /workspace --destination docker.io/glenathan/circleci-kaniko:build-58 --no-push
```

I also re-ran the job with SSH enabled, and poked around a bit more, and got these rather surprising results. 

```
~ # ls -al /kaniko/0/kaniko/ssl/
total 8
drwxr-xr-x    2 root     root          4096 Feb 16 21:56 .
drwxr-xr-x    3 root     root          4096 Feb 16 22:03 ..
~ # stat /kaniko/0/kaniko/ssl/.wh
stat: can't stat '/kaniko/0/kaniko/ssl/.wh': No such file or directory
~ # stat /kaniko/0/kaniko/ssl/.wh.
stat: can't stat '/kaniko/0/kaniko/ssl/.wh.': Operation not permitted
```

I've seen one other mention of this in https://github.com/GoogleContainerTools/kaniko/issues/368#issue-364382457 - which was running in a gitlab pipeline, so possibly similarly constrained.

Kaniko Image (fully qualified with digest)
Digest: sha256:d9fe474f80b73808dc12b54f45f5fc90f7856d9fc699d4a5e79d968a1aef1a72
Bundle into an alpine container here: https://circleci.com/gh/glenjamin/kaniko-publish-orb/51

I fully expect this is a problem with the containerisation limits that CircleCI applies, I can get hold of details about what exactly is applied if needed - but if you can point me in the right direction for how to debug further, that would be great.

I'm also not really clear what whiteout files are, or why this one appears to be double-prefixed

**Comment by glenjamin** [comment]
Having looked into this a bit more and reading up on docker storage drivers, I suspect this is related to using an older version of docker and ubuntu that uses the `aufs` driver.

**Comment by glenjamin** [comment]
I've now tried this out on a clean Ubuntu VM that I own, it does seem to be a problem that only exists when using the `aufs` storage driver.

**Comment by fyuan1316** [comment]
Thank you so much, I was troubled by this problem for a few days.

**Comment by jsravn** [comment]
I'm running into this same issue, also with aufs. I can't see the .wh files with `ls` but they seem to be there - if I stat directly, I get the EPERM. I wonder if anyone has any further insight into why this is happening. Is the only solution to move away from aufs?
