### ISSUE TITLE
Allow .tgz for local context

### ISSUE THREAD

**Issue by snelson3** [GoogleContainerTools/kaniko#567]
According to the documentation you can either import the context from a tarball on S3/GC, or by providing a path to a directory inside the kaniko container.

It would be nice if you could instead provide a path to a tarball in the kaniko container, because it makes providing a build context via a K8s ConfigMap much easier (right now I am running an init container to unzip the tarball into a volume for kaniko to work with).

**Comment by praveensastry** [comment]
@tequilarista I would like to give it a go

**Comment by JordanGoasdoue** [comment]
Hello, for my first open source PR, I want to take this issue as it's not updated since August 2019 and it's with the `good first issue` label.
