### ISSUE TITLE
Support for --chown flag in ADD command

### ISSUE THREAD

**Issue by priyawadhwa** [GoogleContainerTools/kaniko#57]

**Comment by bobcatfish** [comment]
Implementation should be similar to #250

**Comment by stijndehaes** [comment]
Is it ok if I give this a shot?

**Comment by cvgw** [comment]
> Is it ok if I give this a shot?

@stijndehaes definitely! Contributions are always welcome and appreciated

**Comment by anton-johansson** [comment]
@stijndehaes, any news on this one? :)
