### ISSUE TITLE
Kaniko in unpriviliged mode

### ISSUE THREAD

**Issue by 2020testuser** [GoogleContainerTools/kaniko#587]
Could you please provide more details on what it means to say " Kaniko execute `RUN` instructions within Kaniko's rootfs and namespaces. i.e. `RUN` instructions are executed without creating containers" ?

Does that mean RUN instructions require light priviliged access?

Thanks in advance!

**Comment by donmccasland** [comment]
RUN commands will be run as the root user inside the kaniko executor container.
