### ISSUE TITLE
BLOB_UPLOAD_INVALID when pushing to ECR

### ISSUE THREAD

**Issue by tbarrella** [GoogleContainerTools/kaniko#607]
**Actual behavior**
When pushing blobs at the end of the build, after several successful "pushed blob sha256," I ran into the error

>error pushing image: failed to push to destination account.dkr.ecr.region.amazonaws.com/repo:tag: BLOB_UPLOAD_INVALID: “First byte of the layer part is 10485760 instead of 20971520”

Not sure if this is an issue with Kaniko or ECR, but I hadn't experienced this before when pushing to ECR from Docker

**Expected behavior**
All blobs being pushed successfully and an image digest being produced

**To Reproduce**
Not sure how; when I retried it worked (I know this isn't helpful, but I also can't share the Dockerfile or build context)

**Additional Information**
 - Kaniko Image (fully qualified with digest): gcr.io/kaniko-project/executor:v0.8.0@sha256:32ed8afc3c808d7159a7c1789d46c2abe95c1cb5b7afdd6867e360f0ed952c13

I'm sorry this isn't the most useful bug report, but am hoping it helps for tracking, and maybe someone already has an understanding for why this might happen

**References**
- https://github.com/docker/distribution/blob/master/docs/spec/api.md#errors-2
- https://github.com/docker/distribution/issues/2867

**Comment by NickolasHKraus** [comment]
I was hitting this issue as well. Our Docker registry was returning the following:

```
{"errors":[{"code":"BLOB_UPLOAD_INVALID","message":"blob upload invalid"}]}
```

Using the [`--single-snapshot`](https://github.com/GoogleContainerTools/kaniko#--single-snapshot) flag fixed this issue. However, I do not know what the performance or image size impacts this may have:

> This flag takes a single snapshot of the filesystem at the end of the build, so only one layer will be appended to the base image.
