### ISSUE TITLE
Rename to kaniko

### ISSUE THREAD

**Issue by priyawadhwa** [GoogleContainerTools/kaniko#61]

**Comment by wktk** [comment]
I'm just another guy curious about this. One of the authors says that `kaniko is a combo of the Greek words for "make" and "image"` here (https://github.com/GoogleContainerTools/kaniko/issues/101#issuecomment-382816179).  While I'm not familiar with Greek, these words could be "κάνω/κάνει" for "make/makes" and "εἰκών" for "image."
