### ISSUE TITLE
The container base on kaniko/executor image hangs when use knative to build image

### ISSUE THREAD

**Issue by zxDiscovery** [GoogleContainerTools/kaniko#611]
I run the case of  [Orchestrating a source-to-URL deployment on Kubernetes](https://github.com/knative/docs/tree/master/serving/samples/source-to-url-go), but the container hangs. 

image version: gcr.io/kaniko-project/executor:v0.9.0

The image need kaniko build is https://github.com/mchmarny/simple-app.git

The hangs information as follows, do we have any method to debug this?
```
root@boxers1:~# docker ps
CONTAINER ID        IMAGE                                                                                             COMMAND                  CREATED             STATUS              PORTS               NAMES
914756b9ffb3        aa7503991ccc                                                                                      "/kaniko/executor --…"   8 seconds ago       Up 7 seconds                            k8s_build-step-build-and-push_app-from-source-tlxcq-pod-32facd_default_0b6dfa5e-44c7-11e9-a717-0016ac101b0f_0

root@boxers1:~# docker logs -f 914756b9ffb3
INFO[0000] Downloading base image golang:latest
INFO[0002] Unpacking rootfs as cmd RUN CGO_ENABLED=0 go build -v -o app requires it.
```

**Comment by zxDiscovery** [comment]
The more information https://github.com/knative/serving/issues/3310

**Comment by dlorenc** [comment]
Could you run with --verbosity=debug?

**Comment by zxDiscovery** [comment]
I found It doesn't hang when I run with --verbosity=debug. It just very slow, I build a simple image use about one more hour. No error found. But why it so slow? @dlorenc

**Comment by zxDiscovery** [comment]
The I/O on my cluster is slow so lead this issue.  Close this issue.
