### ISSUE TITLE
pull gcr image failed

### ISSUE THREAD

**Issue by jovizhangwei** [GoogleContainerTools/kaniko#613]
I use latest image(gcr.io/kaniko-project/executor:latest), it cannot pull gcr images.

INFO[0000] Downloading base image gcr.io/google_containers/busybox:test
error building image: getting stage builder for stage 0: Get https://gcr.io/v2/token?scope=repository%3Agoogle_containers%2Fbusybox%3Apull&service=gcr.io: exit status 1

**Comment by sebgoa** [comment]
yes, I see the same thing

**Comment by dlorenc** [comment]
Are you seeing this with all gcr containers? Or just some?

**Comment by donmccasland** [comment]
Not reproducible.
