### ISSUE TITLE
Relationship to CBI?

### ISSUE THREAD

**Issue by cyphar** [GoogleContainerTools/kaniko#63]
A similar project called the "Container Builder Interface" (with more of a slant on defining an interface) was started a while ago. Have you looked a this, and is there any overlap that could result in a collaboration between the two projects?

https://github.com/containerbuilding/cbi

**Comment by AkihiroSuda** [comment]
Hi, I'm the author of CBI, and I'm definitely desiring adding kaniko. 😃 

Current CBI implementation only supports git as a build context, but I'll soon implement configmap context and GCS/S3/Swift/... as well.

**Comment by dlorenc** [comment]
CBI now supports Kaniko! Closing this.
