### ISSUE TITLE
Build image into local

### ISSUE THREAD

**Issue by axot** [GoogleContainerTools/kaniko#636]
Is it possible to build an image like `docker build -t`, there is `--no-push` without pushing to remote, it also need a way to save it to local.

**Comment by gabrielcalderon** [comment]
I was wondering the same thing. I want to run Kaniko inside Docker but the documentation states it requires gcloud?

**Comment by Aisuko** [comment]
@axot   `--tarPath=/your_workspace/image.tar` can save the image to the local directory.  And you need to manually load it to docker daemon.

**Comment by kwladyka** [comment]
https://github.com/GoogleContainerTools/kaniko/issues/675
you can do it like I described here, but be warn: at that moment relative path doesn't work, so use full one like in description.

**Comment by kwladyka** [comment]
I think the issue can be closed @axot ?

**Comment by axot** [comment]
> docker run --rm -w /workspace -v (pwd):/workspace gcr.io/kaniko-project/executor --tarPath=/path/to/image.tar --context=auth-provider --no-push

Yes, it makes sense to me. Thank you.

**Comment by Matts966** [comment]
Could it be possible to load image and locally and pushing it to the destination parallelly?

In my use case on Google Cloud Build, I always use the built image after the build finished, and always loading image takes long time.

The interface like below is desirable for me

```bash
/kaniko/executor --destination local:project/image
```

**Comment by mhvelplund** [comment]
> @axot `--destination=image --tarPath=/your_workspace/image.tar` can save the image to the local directory. And you need to manually load it to docker daemon.

If you come here after this message, the commandline that worked for me was:

```shell
docker run \
	-v $PWD:/build \
	gcr.io/kaniko-project/executor:latest \
	--dockerfile=Dockerfile \
	--tar-path image.tar \
	--no-push \
	--context /build
```
