### ISSUE TITLE
DNS timeout when checking for push permissions

### ISSUE THREAD

**Issue by Dopingus** [GoogleContainerTools/kaniko#645]
**Actual behavior**
When using the current Kaniko image (based on golang:1.10) Kaniko throws an error during push permission check. This can happen when the DNS server sends responses which cannot be unmarshalled correctly by the Golang DNS resolver implementation (see https://github.com/golang/go/issues/28419 and https://github.com/golang/go/issues/21160).
The error looks like this:
```
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "<redacted image name>": Get <redacted image repository>: dial tcp: lookup <redacted image repository hostname> on <K8s Cluster DNS IP>:53: read udp <Pod IP>:60645-> <K8s Cluster DNS IP>:53: i/o timeout
```

After building a Kaniko image based on golang 1.12, Kaniko was able to execute past push permission check.
-> Proposed solution: Update the golang version of Kaniko to 1.12

**Expected behavior**
The push permission check should work successfully if the DNS server is reachable and sending a valid response.

**To Reproduce**
1. Use gcr.io/kaniko-project/executor(:debug) (must be golang 1.10 based)
2. Setup a DNS server which sends slightly larger DNS responses
3. Run any build which uses the DNS server setup in 2.

**Additional Information**
 - Kaniko Image (fully qualified with digest): "gcr.io/kaniko-project/executor@sha256:62bc2acb47775f717cd5e81076e46f2c552d0ae958cd6d300d42ff73892c19da"

**Comment by cvgw** [comment]
kaniko is now using golang 1.12
