### ISSUE TITLE
Google cloud build fails when using image from the marketplace

### ISSUE THREAD

**Issue by jpambrun** [GoogleContainerTools/kaniko#659]
**Actual behavior**
Following instructions from [cloud build documentation](https://cloud.google.com/cloud-build/docs/kaniko-cache#configuring_the_cache_expiration_time), the build fails with 
```
INFO[0000] Resolved base name marketplace.gcr.io/google/ubuntu1804:latest to marketplace.gcr.io/google/ubuntu1804:latest 
INFO[0000] Downloading base image marketplace.gcr.io/google/ubuntu1804:latest 
2019/05/10 14:11:02 No matching credentials were found, falling back on anonymous
INFO[0000] Error while retrieving image from cache: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication 
```

Using image from docker hub works fine. I am not sure if #551 is related and was supposed to fix this. I tried with v0.9.0 and `404af20f7c041264282a4ca09b79660da6f9d616`

**Expected behavior**
I expect the downloads from marketplace.gcr.io to work since I am working from Google Cloud Build from my account.

**To Reproduce**
1. Build a docker image on Google Cloud Build with a FROM from `marketplace.gcr.io`

**Additional Information**
 - Dockerfile 
```
FROM marketplace.gcr.io/google/ubuntu1804:latest
# FROM ubuntu:18.04   <-- that works
```

 - CloudBuild.yaml
```
steps:
- name: 'gcr.io/kaniko-project/executor:404af20f7c041264282a4ca09b79660da6f9d616'
  args:
  - --dockerfile=Dockerfile
  - --destination=gcr.io/$PROJECT_ID/base/ubuntu:latest
  - --cache=true
  - --cache-ttl=6h
```
 - Kaniko Image (fully qualified with digest)
gcr.io/kaniko-project/executor:404af20f7c041264282a4ca09b79660da6f9d616

**Comment by donmccasland** [comment]
The marketplace.gcr.io interface has recently changed to require Google authentication for access.  You can either configure credentials in kaniko or use the public source of that same image:
gcr.io/gcp-runtimes/ubuntu_18_0_4:latest

**Comment by aronchick** [comment]
This is really valuable @donmccasland - I couldn't find docs on how to get kaniko to authenticate though. Can you point at it?

(this was the first result in google, so it'd be nice for anyone looking for it in the future)

**Comment by martijneken** [comment]
For future readers: launcher.gcr.io/google has the public images not requiring auth
