### ISSUE TITLE
Cannot build with company CA

### ISSUE THREAD

**Issue by abergmeier** [GoogleContainerTools/kaniko#660]
**Actual behavior**
When executing _Bazel_ as part of `make images` it fails to download skylibs.
In our network https is being changed to report a company (non-rooted) CA.

**Expected behavior**
This should download just fine.

**To Reproduce**
1. Have your company change the CA to a self-signed.
2. `make images`

**Additional Information**
I think this could be worked around by copying the Java trust store from host to container.
The long-term fix might be to use TLS 1.3!?

**Comment by donmccasland** [comment]
Do not use self-signed CA.
