### ISSUE TITLE
Shell doesn't seem available in debug image

### ISSUE THREAD

**Issue by neoel** [GoogleContainerTools/kaniko#661]
**Actual behavior**
Running kaniko in gitlab runners fails, possibly due to no shell available.

**Expected behavior**
Gitlab runners require a shell to be available, therefore the debug image was adviced

**To Reproduce**
Open a shell in a kaniko image.

**Comment by davidarcher** [comment]
Looking at the current debug image, the shell is located at /busybox/sh but gitlab-runner is going to be looking for /bin/sh, /usr/local/bin/sh, etc.

Setting the entrypoint explicitly seems to work for me with local testing.

> λ docker run -it --rm --entrypoint /busybox/sh gcr.io/kaniko-project/executor:debug

**Comment by neoel** [comment]
I've found out it seems to be an issue with running the debug image on containerd (specifically in a google kubernetes cluster). and failing to start with a permission denied error somewhere.
