### ISSUE TITLE
kaniko doesn't work with an HTTP registry build on Nexus OSS

### ISSUE THREAD

**Issue by al3xisb** [GoogleContainerTools/kaniko#667]
**Actual behavior**
kaniko doesn't work with HTTP registry build on Nexus OSS 3
- without flags : certificate signed by unknown authority
- with --insecure : does not allow http request
- with --skip-tls-verify : return no token in bearer response: {"title":"Unauthorized","description":"Authorize user failed"}.

**To Reproduce**
Nexus OSS is configure to be used as a private Docker repo with HTTP connector
The registry work well with the docker standard commands (login/push) and the tag insecure-registry into daemon.json

I'm using the gcr.io/kaniko-project/executor:debug and the following commands :
- echo "{\"auths\":{\"http://my-insecure-registry:8082\":{\"username\":\"admin\",\"password\":\"admin123\"}}}" > /kaniko/.docker/config.json
- /kaniko/executor --dockerfile=web-api1/Dockerfile --destination=my-insecure-registry:8082/web-api1:latest -insecure --skip-tls-verify

**Comment by himao** [comment]
same issue,any update?

**Comment by himao** [comment]
it seems like the `--insecure` no effect with the special registry port.
it's not work:
```bash
/kaniko/executor -f /myproj/Dockerfile -c /myproj --insecure --skip-tls-verify --destination="docker.abc.com:5000/temp/myimage" --verbosity debug 
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "docker.abc.com:5000/temp/myimage:latest": Get https://docker.abc.com:5000/v2/: http: server gave HTTP response to HTTPS client
```

but this is work:
```bash
/kaniko/executor -f /myproj/Dockerfile -c /myproj --insecure --skip-tls-verify --destination="docker.abc.com/temp/myimage" --verbosity debug 
```

**Comment by ccaballero646** [comment]
Facing same issue, can't test workaround suggested above because the registry image comes in via environment variables from Gitlab CI.
Gitlab Runner can pull images from the registry without issues, but when running executor:

```
$ /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --insecure --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for $CI_REGISTRY_IMAGE: creating push check transport for $CI_REGISTRY failed: Get https://$CI_REGISTRY/v2/: http: server gave HTTP response to HTTPS client
```

**Comment by tralexa** [comment]
#685 should fix this when using the Insecure or InsecureRegistries flag

**Comment by donmccasland** [comment]
Merged #685, closing...

**Comment by adwaitpawar** [comment]
i have the same issue

**Comment by JanHuege** [comment]
Using HTTPS we are facing the same issue. We cannot push the image to a nexus OSS Version(OSS 3.49.0-02) using gcr.io/kaniko-project/executor:v1.14.0-debug

Using username password auth we are facing:

`error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "private.registry.com/repository/imagename:tag": creating push check transport for nexus.istec.de failed: GET https://private.registry.com/v2/: unexpected status code 404 Not Found: `
