### ISSUE TITLE
[bug] tarPath is not relative path, but it should be

### ISSUE THREAD

**Issue by kwladyka** [GoogleContainerTools/kaniko#675]
**Actual behavior**
`docker run --rm -w /workspace -v (pwd):/workspace gcr.io/kaniko-project/executor --tarPath=image.tar --context=auth-provider --no-push`

`image.tar` is saved who know where. If I change it to ` --tarPath=/workspace/image.tar` then it works.

**Expected behavior**
Save it in right relative path. In case about in `/workspace/image.tar`.

**Additional Information**
I need it to produce tar in relative path in Concourse (cicd). It is random path so it not constant.

**Comment by Jukie** [comment]
Relative path to what? In this case image.tar is being saved at `/image.tar` because you aren't providing a path to save to, so the root `/...` is assumed.

**Comment by kwladyka** [comment]
It should be saved in `/workspace/image.tar` because I am running command from `/workspace` and I use relative path `image.tar`.

**Comment by kwladyka** [comment]
In practice I run it from `/tmp/fooX/barY` in Concourse (cicd) and I need to save it in artefact directory `/tmp/fooX/barY/artefact` by Concourse instead `docker run`.

But example with `docker run` is simple to recreate and easy to understand the issue.

**Comment by tejal29** [comment]
this should be fixed by https://github.com/GoogleContainerTools/kaniko/pull/736
