### ISSUE TITLE
Warmer crash

### ISSUE THREAD

**Issue by bflorat** [GoogleContainerTools/kaniko#678]
**Actual behavior**
Warmer crashes :
```
docker run -v $(pwd):/workspace gcr.io/kaniko-project/warmer:latest --cache-dir=/workspace/cache --image=gitlab-registry.company/myproject/myimage:0.1.0:latest 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xf13712]

goroutine 1 [running]:
github.com/GoogleContainerTools/kaniko/pkg/cache.WarmCache(0x1977fe0, 0xf25480, 0xc420369cd8)
	/go/src/github.com/GoogleContainerTools/kaniko/pkg/cache/warm.go:47 +0x372
github.com/GoogleContainerTools/kaniko/cmd/warmer/cmd.glob..func2(0x196f140, 0xc42015e220, 0x0, 0x2)
	/go/src/github.com/GoogleContainerTools/kaniko/cmd/warmer/cmd/root.go:54 +0x2d
github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra.(*Command).execute(0x196f140, 0xc4200a0070, 0x2, 0x2, 0x196f140, 0xc4200a0070)
	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x196f140, 0x0, 0x4, 0x116cca9)
	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra.(*Command).Execute(0x196f140, 0xc420369f78, 0xc42009a058)
	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/go/src/github.com/GoogleContainerTools/kaniko/cmd/warmer/main.go:26 +0x2d
```

**Expected behavior**
Pull the image and cache it in a bind mounted directory.

**To Reproduce**
- Setup a private repository (we use a Gitlab on premise)
- Run `docker run -v $(pwd):/workspace gcr.io/kaniko-project/warmer:latest --cache-dir=/workspace/cache --image=gitlab-registry.company/myproject/myimage:0.1.0:latest 

**Additional Information**
 - Detail of warmer image : `gcr.io/kaniko-project/warmer  latest                b454d1cbac22        3 months ago        22.8MB`
- I get the same error with `docker run -v $(pwd):/workspace gcr.io/kaniko-project/warmer:latest --cache-dir=/workspace/cache --image=httpd:latest` and I HAVE NO ACCESS TO INTERNET (hence no access to DockerHub)

**Comment by sxcoll2** [comment]
I'm encounter the same issue.  Is there are another way to warm the cache ?  thanks!

[root@slcifdi docker]# docker run -v $(pwd):/workspace gcr.io/kaniko-project/warmer:latest --cache-dir=/workspace/cache --image=oracleinux:7.5
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xf13712]

goroutine 1 [running]:
github.com/GoogleContainerTools/kaniko/pkg/cache.WarmCache(0x1977fe0, 0xf25480, 0xc420381cd8)
	/go/src/github.com/GoogleContainerTools/kaniko/pkg/cache/warm.go:47 +0x372
github.com/GoogleContainerTools/kaniko/cmd/warmer/cmd.glob..func2(0x196f140, 0xc4203053c0, 0x0, 0x2)
	/go/src/github.com/GoogleContainerTools/kaniko/cmd/warmer/cmd/root.go:54 +0x2d
github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra.(*Command).execute(0x196f140, 0xc420038040, 0x2, 0x2, 0x196f140, 0xc420038040)
	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x196f140, 0x0, 0x4, 0x116cca9)
	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra.(*Command).Execute(0x196f140, 0xc420381f78, 0xc4200c8058)
	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/go/src/github.com/GoogleContainerTools/kaniko/cmd/warmer/main.go:26 +0x2d

**Comment by bflorat** [comment]
Update : no more issue with Kaniko 0.11, the cache works as expected (layers and FROM images)
