### ISSUE TITLE
Redirect logs to file?

### ISSUE THREAD

**Issue by daldridge-cs** [GoogleContainerTools/kaniko#695]
(Yes, this may end up being a Kubernetes question, but the k8s examples of this approach work fine.  I'm just having difficulty doing the same with the kaniko image...)

I have a Kubernetes use-case where I need to redirect the kaniko build log/stdout to a file in a sidecar (basic approach: https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/admin/logging/two-files-counter-pod-streaming-sidecar.yaml).

`/kaniko/executor` doesn't have any command-line argument to specify writing logs/stdout to a file, so the only thing I can think to do is create a k8s job pod spec that with a `command` which executes `sh -c '/kaniko/executor ...args >> /var/log/build.log 2>&1'`.

See the k8s docs here (https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#notes) which describe how to have k8s ignore the default ENTRYPOINT.

For point of reference, here's what kubectl describe shows for my job and pod spec therein:
```
Name:           builder-job-738b486d-e233-411f-8bb6-fef24a5ceb2d
Namespace:      jhub
Selector:       controller-uid=a72b37a9-87d0-11e9-84e0-025000000001
Labels:         controller-uid=a72b37a9-87d0-11e9-84e0-025000000001
                job-name=builder-job-738b486d-e233-411f-8bb6-fef24a5ceb2d
Annotations:    <none>
Parallelism:    1
Completions:    1
Start Time:     Wed, 05 Jun 2019 15:29:43 -0500
Pods Statuses:  0 Running / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  controller-uid=a72b37a9-87d0-11e9-84e0-025000000001
           job-name=builder-job-738b486d-e233-411f-8bb6-fef24a5ceb2d
  Containers:
   kaniko-builder:
    Image:      gcr.io/kaniko-project/executor:latest
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
      -c
      /kaniko/executor --context=/tmp/build-context/ --destination=private-registry.cortex-dev.insights.ai/daldridge/myimage:mytag >> /var/log/build.log 2>&1
    Environment:
      DOCKER_CONFIG:  /kaniko/secrets
    Mounts:
      /kaniko/secrets from kaniko-secrets (rw)
      /tmp/build-context/ from build-context (rw)
      /var/log from varlog (rw)
   logs:
    Image:      busybox
    Port:       <none>
    Host Port:  <none>
    Args:
      /bin/sh
      -c
      tail -n+1 -f /var/log/build.log
    Environment:  <none>
    Mounts:
      /var/log from varlog (rw)
  Volumes:
   build-context:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  claim-daldridge-2ddaldridge-2d1
    ReadOnly:   false
   kaniko-secrets:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  daldridge-daldridge-a18256bee1a87978ad2fc04b95709e54
    Optional:    false
   varlog:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
Events:
  Type     Reason                Age                From            Message
  ----     ------                ----               ----            -------
  Normal   SuccessfulCreate      58s                job-controller  Created pod: builder-job-738b486d-e233-411f-8bb6-fef24a5ceb2d-mzqm4
  Normal   SuccessfulDelete      13s                job-controller  Deleted pod: builder-job-738b486d-e233-411f-8bb6-fef24a5ceb2d-mzqm4
  Warning  BackoffLimitExceeded  13s (x2 over 13s)  job-controller  Job has reached the specified backoff limit
```

I can't tell what's wrong with the kaniko pod at runtime, as it immediately terminates and has no logs available.  Examining the sidecar indicates that no logs were created.

Interestingly, if I change the pod spec command to simply echo and redirect instead of running the executor (keeping everything else the same), it works fine and the sidecar sees the logs.  E.g. `sh -c 'echo hello >> /var/log/build.log 2>&1'`.  It's feels like the container is not finding sh or /kaniko/executor...

Any ideas?

**Comment by daldridge-cs** [comment]
Turns out the kaniko image doesn't have a shell, as FROM golang is followed by FROM scratch to create a minimal size image.

I'm going the route of creating my own image from the combination of the executor and busybox images.

I'd prefer there be a way to redirect stdout/stderr to a file as an executor option.  Can this be labelled as a feature request?

**Comment by tejal29** [comment]
@daldridge-cs, the kaniko-executor:debug image has shell https://github.com/GoogleContainerTools/kaniko/blob/master/README.md#debug-image
