### ISSUE TITLE
error resolving dockerfile path using kaniko-project/executor:latest

### ISSUE THREAD

**Issue by d4nyll** [GoogleContainerTools/kaniko#727]
**Actual behavior**

When applying the following `kaniko` Pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=Dockerfile",
            "--context=git://github.com/d4nyll/docker-demo-frontend.git#refs/heads/docker/basic",
            "--destination=<account-id>.dkr.ecr.<region>.amazonaws.com/<repo>:<tag>",
            "--cache=false",
            "--verbosity=debug"]
    volumeMounts:
      - name: aws-credentials
        mountPath: /root/.aws/
      - name: docker-config
        mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
    - name: aws-credentials
      secret:
        secretName: aws-credentials
    - name: docker-config
      configMap:
        name: docker-config
```

When using the `kaniko-project/executor:latest` image, it errors with:

```
$ kubectl logs -f kaniko
DEBU[0000] Getting source context from git://github.com/d4nyll/docker-demo-frontend.git#refs/heads/docker/basic 
Enumerating objects: 29, done.
Counting objects: 100% (29/29), done.
Compressing objects: 100% (17/17), done.
Total 62 (delta 25), reused 12 (delta 12), pack-reused 33
DEBU[0001] Build context located at /kaniko/buildcontext/ 
Error: error resolving dockerfile path: please provide a valid path to a Dockerfile within the build context with --dockerfile
```

Although the `--dockerfile` argument _is_ passed in.

However, if I change the image to `gcr.io/kaniko-project/executor:debug`, `kaniko` runs perfectly fine and the image is uploaded to ECR. There are no other changes apart from this.

**Expected behavior**
Both the `gcr.io/kaniko-project/executor:latest` and `gcr.io/kaniko-project/executor:debug` images both to execute correctly.

**To Reproduce**
1. Apply Pod definition above, swapping in correct ECR ARN. `kubectl apply -f pod.yaml`

**Additional Information**
 - Dockerfile
   ```Dockerfile
   FROM node
   WORKDIR /root/
   COPY . .
   RUN npm install
   RUN npm run build
   CMD npm run serve
   ```
   https://raw.githubusercontent.com/d4nyll/docker-demo-frontend/docker/basic/Dockerfile
 - Build Context
   git://github.com/d4nyll/docker-demo-frontend.git#refs/heads/docker/basic
 - Kaniko Image (fully qualified with digest)
   `latest` - `gcr.io/kaniko-project/executor@sha256:78d44ec4e9cb5545d7f85c1924695c89503ded86a59f92c7ae658afa3cff5400` (errors)
   `debug` - `gcr.io/kaniko-project/executor@sha256:f946b28dde301409aaefb6315eb8e7dba1946a4bf2e8d8281e85b1c975fada79` (working)

**Comment by priyawadhwa** [comment]
Hi @d4nyll so `gcr.io/kaniko-project/executor:latest` points to the latest release, could you try ` gcr.io/kaniko-project/executor:80421f2a73d49057ab0aea8170afbf867475855c` which is based off the latest commit?

**Comment by tejal29** [comment]
I verified, this is not true anymore. 
maybe we had a bad release.
