### ISSUE TITLE
Relative paths don't work with `--context`, `--tarPath`, and others...

### ISSUE THREAD

**Issue by huguesalary** [GoogleContainerTools/kaniko#732]
# Actual behavior
Upon executing, the `executor` binary changes its root directory to `/` as seen here https://github.com/GoogleContainerTools/kaniko/blob/master/cmd/executor/cmd/root.go#L84

This prevents the use of relative directories in the `executor` command line arguments.

For example:
- Imagine a directory `/tmp/build` 
- with a subdirectory `myworkspace/` containing the `Dockerfile` (i.e. `/tmp/build/myworkspace/Dockerfile`)
- Running the following will fail:
```
cd /tmp/build
/kaniko/executor --dockerfile=Dockerfile --context=myworkspace/ --destination=image --tarPath=image.tar --cache=true --cache-dir=./cache/ --no-push
```
- With the error:
```
Error: error resolving dockerfile path: please provide a valid path to a Dockerfile within the build context with --dockerfile
```

# Expected behavior
Kaniko should allow the use of **relative paths** in its command line and honor them.

# Additional Information
The current behavior is also confusing because the `--dockerfile` argument **does** allow a relative path. 

That is, the following command line works: 
```
cd /tmp/build
/kaniko/executor --dockerfile=myworkspace/Dockerfile --destination=image --tarPath=image.tar --cache=true --cache-dir=./cache/ --no-push
```

But fails as soon as the Dockerfile tries to use a "workspace" file
```
error building image: error building stage: lstat /myworkspace/entrypoint.sh: no such file or directory
```

# Related issues
https://github.com/GoogleContainerTools/kaniko/issues/731
https://github.com/GoogleContainerTools/kaniko/issues/675

**Comment by tejal29** [comment]
This should be fixed by #736
