### ISSUE TITLE
can you specify multiple destinations ?

### ISSUE THREAD

**Issue by maurorappa** [GoogleContainerTools/kaniko#733]
It seems I cannot make kaniko to push an image to multiple places repeating the destination option. is it possible in any way?

**Comment by priyawadhwa** [comment]
Hey @maurorappa setting the `--destination` flag multiple times should work -- could you provide some logs?

**Comment by maurorappa** [comment]
my bad, I managed to push to jfrog.io and AWS ECR in one go!
Kaniko rocks!

**Comment by marekaf** [comment]
this doesn't seem to be document well though :(

**Comment by gstolz** [comment]
If multiple pushes to registries are ok, how about a combination of tar-export and push, would that be possible?

**Comment by felixdivo** [comment]
Couldn't this be documented in the flags listing in the repo README?

**Comment by yugi-t2s** [comment]
Adding this to the documentation would be helpful...

**Comment by mmurasawa** [comment]
thanks

**Comment by sinhasonalkumar** [comment]
> my bad, I managed to push to jfrog.io and AWS ECR in one go!
> Kaniko rocks!

Can plz share snippet. How did you managed creds for both ecr and jfrog artifactory.

**Comment by henricook** [comment]
@priyawadhwa Would you mind adding a definitive comment here please? To push my built image to two places I just need two `--destination` params, is that right? I've seen other posts saying I might also need `--cleanup` and it's still not in the docs as far as I can see

**Comment by henricook** [comment]
In the meantime, for any other readers, this **does** appear to work for me. The push messages can be a bit confusing because it always outputs a digest, but it is pushing to two places with two `--destination` tags

```
INFO[0145] Pushing image to registry.mycorp.com/myproject/project:abcdef
INFO[0148] Pushed registry.mycorp.com/myproject/project@sha256:98c377879e8d8e3d5ccca8b704c5c66fce4bd69095d8b36c7eb155c9e8265be5 
INFO[0149] Pushing image to registry.mycorp.com/myproject/project:latest-main
INFO[0152] Pushed registry.mycorp.com/myproject/project@sha256:98c377879e8d8e3d5ccca8b704c5c66fce4bd69095d8b36c7eb155c9e8265be5 
```
