### ISSUE TITLE
Does kaniko executor supports taking docker proxy settings as a runtime variable?

### ISSUE THREAD

**Issue by asifdxtreme** [GoogleContainerTools/kaniko#746]
I am running kaniko executor container behind proxy and wants to pass the proxy settings while bringing up the container, currently we need to pass the proxy json while building the executor image but that restricts me to use the same image in different env's.

Is there any way I can pass the docker proxy settings while bringing up executor container?

**Comment by tejal29** [comment]
Have you tried setting the proxy env varaibles mentioned [here](https://docs.docker.com/network/proxy/)  and add those in kaniko pod spec?

**Comment by asifdxtreme** [comment]
@tejal29 Thanks for giving the pointer, I tried now by passing the proxy configs in podspec and it works fine.
Thanks a lot for help
