### ISSUE TITLE
$PATH is not passed

### ISSUE THREAD

**Issue by prary** [GoogleContainerTools/kaniko#754]
**Actual behavior**
Dockerfile 
```
FROM something/lrh7
RUN env
```
Do a docker build, output shows 
```
Step 2/3 : RUN env
 ---> Running in a7ea3e88b5a6

HOSTNAME=a7ea3e88b5a6
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
SHLVL=1
HOME=/root
_=/usr/bin/env
```
Do skaffold build  -v=debug
```
INFO[0025] RUN env
INFO[0025] cmd: /bin/sh
INFO[0025] args: [-c env]
PWD=/
SHLVL=1
HOME=/root
_=/usr/bin/env
````
**Expected behavior**
Path variable should be retained

**Comment by prary** [comment]
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=34fbfd2c2006
TERM=xterm
HOME=/root

**Comment by prary** [comment]
If we do echo $PATH then
```
INFO[0021] RUN echo $PATH
INFO[0021] cmd: /bin/sh
INFO[0021] args: [-c echo $PATH]
/usr/local/bin:/usr/bin
```
Don't know from where this $PATH is coming

**Comment by fspaniol** [comment]
Related: #748

**Comment by prary** [comment]
We should set the default path if $PATH isnt defined in base image
https://github.com/GoogleContainerTools/kaniko/blob/1d3cf8a67dda19deecf6c754696e52f4f24a1198/pkg/executor/build.go#L127

Should remove this condition
