### ISSUE TITLE
Not valid link to config.json in the "Pushing to Amazon ECR" readme section

### ISSUE THREAD

**Issue by nlewo** [GoogleContainerTools/kaniko#755]
The link to the `config.json` file in the README is no longer valid. It points to https://github.com/GoogleContainerTools/kaniko/blob/master/files/config.json

**Comment by tejal29** [comment]
@nlewo thanks for finding a bug in our docs. Do you want to raise a PR to fix it?
The config.json should point to this link https://github.com/awslabs/amazon-ecr-credential-helper#configuration

**Comment by dgzlopes** [comment]
This issue can be closed @tejal29. The link points to the correct place! See it [here](https://github.com/GoogleContainerTools/kaniko/blob/master/README.md#pushing-to-amazon-ecr).

**Comment by nlewo** [comment]
Thanks @dgzlopes
