### ISSUE TITLE
Can't copy config.json into kaniko container when running in an OpenShift POD. Non-root issue?

### ISSUE THREAD

**Issue by vguaglione** [GoogleContainerTools/kaniko#758]
**Actual behavior**
I am attempting to use a kaniko container in an OpenShift POD via the gitlab-runner kubernetes executor.  Runner spins up the pod to service a build job but a failure occurs on initialization of the container when attempting to copy gitlab registry credentials into kaniko's /kaniko/.docker/config.json file.  Error detailed below:

$ echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
/busybox/sh: eval: line 87: can't create /kaniko/.docker/config.json: Permission denied
ERROR: Job failed: command terminated with exit code 1

**Expected behavior**
Config file is written into the container and the build continues.

**To Reproduce**
1. Configure gitlab-runner kubernetes executor in a cluster
2. Deploy gitlab-runner to cluster
3. Run a pipeline through your CI

**Additional Information**
 - Dockerfile 
   Any dockerfile will do.

 - Build Context
   Your $CI_PROJECT_DIR

 - Kaniko Image:
   gcr.io/kaniko-project/executor:debug

OpenShift is running the pod with non-root permissions but the file is only accessible via the root user.  See below:

/kaniko/.docker # ls -la
total 12
drwxr-xr-x    2 0        0             4096 Aug 16 20:20 .
drwxr-xr-x    1 0        0             4096 Aug 16 20:20 ..
-rw-------    1 0        0              155 Aug 16 20:15 config.json

Reference: https://docs.gitlab.com/ee/ci/docker/using_kaniko.html

Any ideas or suggestions?

**Comment by tejal29** [comment]
@vguaglione Can you try commenting this on the tutorial page? Maybe there is a way to run a pod with non-root permissions in open shift?

**Comment by vguaglione** [comment]
> @vguaglione Can you try commenting this on the tutorial page? Maybe there is a way to run a pod with non-root permissions in open shift?

Can you send me a link to the tutorial page?  You aren't talking about the wiki page are you?  Sorry, I don't actually use GitHub that often so I'm not familiar with some of the terminology.

**Comment by tejal29** [comment]
yes. i was taking about the page you referenced docs.gitlab.com/ee/ci/docker/using_kaniko.html

**Comment by vguaglione** [comment]
Thanks.  Actually, after further research, I'm not sure this will work without root permissions in OpenShift.  I can pose the question on the GitLab thread but since this is an OpenShift issue, I suspect they will point me to RedHat for clarification.

**Comment by tejal29** [comment]
Thanks. Closing this issue for now. Please re-open if you need any more follow ups.

**Comment by MrAmbiG** [comment]
same issue as of 9/9/2020

**Comment by manuelnucci** [comment]
@vguaglione do you have the issue in OpenShift that relates to this problem?

**Comment by vguaglione** [comment]
@manuelnucci 

Actually, I do not.  We never opened this specific issue with OpenShift.  We did, however, ask for clarification regarding OpenShift security context constraints, and implemented our configuration based on the support provided by the platform, taking into account this limitation.

Based on these constraints, we configured two gitlab runners in our OpenShift cluster, one with elevated privileges for any job that requires a kaniko container to perform container builds, another with the default non-root privileges for anything non-container build related, such as running npm install's, manipulating files, running helm deployments, etc..  

Any build requirement that falls outside the scope of what we have provided for our organization requires the user/group to set up their own physical/virtual build machine and runner (such as for docker-in-docker builds).  This strategy has allowed us to cover about 95% of use cases.  We only have a small number of groups that are currently maintaining their own runners.

**Comment by wayop2000** [comment]
@vguaglione we are experiencing the same issue with Kaniko op OpenShift (executed through the Gitlab runner). Could you elaborate on the applied security configuration? How did you elevate the Gitlab runner privileges?

Would be great if you could describe the oc commands and steps to follow.

**Comment by vguaglione** [comment]
There should be comprehensive documentation in RedHat's OpenShift documentation repository that discusses elevated privileges for service accounts.  I'd review that documentation as a primer.  

For our specific implementation, here's what we've done:

1. Create a service account for the gitlab-runner in the namespace in which we will deploy (via kubectl apply of a file containing the new service account object).

2. Add a line to the CI/helm deploy (or set the gitlab-runner chart value) for runners.serviceAccountName to use the service account we just created:

**--set runners.serviceAccountName=<your service account name>**

3. Use the OC admin command to assign the service account the anyuid privilege (which elevates the privilege to run as root):

**oc adm policy add-scc-to-user anyuid -n <your runner namespace> -z <your service account>**

The runner should now be able to spin up a pod using the kaniko image to build in the cluster.

Here's a blog link that discusses OpenShift's service accounts and security context constraints (SCCs):

https://blog.openshift.com/understanding-service-accounts-sccs/

**Comment by manuelnucci** [comment]
@vguaglione did you have any difficulties in running **dind** with this setup?

I tried configuring the runner with this TOML...

```
[[runners]]
  ...
  [runners.kubernetes]
    ...
    privileged = true
    tls_verify = false
    cap_add = ["NET_ADMIN", "SYS_ADMIN"]
    ...
```
...but without any success. I had also executed beforehand the command you proposed earlier: `oc adm policy add-scc-to-user anyuid ...` ([here](https://docs.gitlab.com/runner/configuration/configuring_runner_openshift.html#run-as-anyuid-scc)'s more info about it).

Despite all that, the error in the `svc-0` container (the one that runs **dind**) was always the same:

```
mount: permission denied (are you root?)
Could not mount /sys/kernel/security.
AppArmor detection and --privileged mode might break.
mount: permission denied (are you root?)
```

I'm intrigued before you talked earlied about running docker-in-docker builds in an exclusive VM, and maybe that was the only approach in this case.

**Comment by manuelnucci** [comment]
My mistake for not being clear. The setup I was referencing was to use dind as a new container (but completely unrelated to kaniko). The documentation for my scenario is [here](https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-the-docker-executor-with-the-docker-image-docker-in-docker). As I said, it's strictly unrelated to kaniko but, due to the fact that you mentioned dind, I though maybe you had had a similar problem trying to run it.

Here's how a GitLab pipeline would look like using only dind:

```
stages:
  - image build

build image:
  stage: image build
  image: docker:20.10.8
  cache: []
  services:
    - name: registry.hub.docker.com/library/docker:20.10.8-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker info
```

The error I mentioned earlier shows once this pipeline tries to run, having configured the runner with the TOML and added the specific policy to the SA in use.

**Comment by manuelnucci** [comment]
It seems this goes down another road because the error I'm getting is related to the container inside the pod that tries to run dind, and fails because of a lack of permissions. Despite that, thanks for the info @vguaglione, I'll keep looking.

**Comment by vguaglione** [comment]
@manuelnucci  Sorry I couldn't be of more help here.  Like I said previously, we concluded that dind inside the container running in the cluster wasn't possible, so we had users set up their own runners on dedicated hardware or VMs if they needed to do dind.
