### ISSUE TITLE
Push to destination and create tar?

### ISSUE THREAD

**Issue by LP0101** [GoogleContainerTools/kaniko#759]
Is there any way to push an image to a repository, and end up with a tarball in the Kaniko container? Currently, it seems as if we have to go through the process of building the image twice, which wastes quite a bit of time in the pipeline.

**Comment by tejal29** [comment]
@LP0101 Thank you for opening this issue. Current there is now way to do this.

What do you mean by "building the image twice" ? Can you please elaborate?

**Comment by LP0101** [comment]
Sure.

Currently, our pipeline requires that we build an image, upload it to GCR, then send the .tar file to a vulnerability scanning tool.

Given this limitation on Kaniko, the only way we've found to accomplish this is by building the image once with the `--destination` flag, then bringing up a whole new Kaniko container, where the image is built a second time, this time with `--no-push` and `--tarPath`, which is then sent to the scanning tool. Attempting to build the same image twice in the same Kaniko container results the pipeline breaking, as any `mkdir` operation returns a `Directory already exists` error.

**Comment by mhio** [comment]
Why does kaniko need to do this? It might be easier to export the built image from the repo as a tar. To be honest the image scanning tool should have the repo pull ability.

**Comment by tejal29** [comment]
@LP0101 I agree with @mhio. The scanning tool should be responsible for pulling the image.
Alternate approach would be have a script to pull the image and save it as tar.

closing this as wont-fix.
Thanks
Tejal

**Comment by MichaelSp** [comment]
> Alternate approach would be have a script to pull the image and save it as tar.
Anyone has experience with this?

**Comment by mhio** [comment]
Moby also provide a [`download-frozen-image-v2.sh`](https://github.com/moby/moby/blob/c7ad2b866182325b49bc7addb7042e16afbb60b6/contrib/download-frozen-image-v2.sh) script if you don't have docker available.
