### ISSUE TITLE
function SetEnvironmentVariable not used anywhere.

### ISSUE THREAD

**Issue by prary** [GoogleContainerTools/kaniko#762]
Function defined in pkg/image/image.go but not referenced anywhere, possible reason for #754 #748 and few others

https://github.com/GoogleContainerTools/kaniko/blob/1d3cf8a67dda19deecf6c754696e52f4f24a1198/pkg/image/image.go#L29

If this is dead code then it should be removed.

**Comment by tejal29** [comment]
Thanks @prary feel free to create a PR :)

**Comment by prary** [comment]
PR containing deletion of the image.go file?

**Comment by dgzlopes** [comment]
This issue is outdated, and  I think it can safely be closed. The `/pkg/image` folder is different now, and this code-block doesn't exist.
