### ISSUE TITLE
Support Dockerfile.dockerignore

### ISSUE THREAD

**Issue by victornoel** [GoogleContainerTools/kaniko#776]
Currently kaniko only looks for a `.dockerignore` file but a uselful feature of `docker build` is to take `<path/to/Dockerfile>.dockerignore` into account if it exists.

See https://github.com/moby/buildkit/pull/901

**Comment by tejal29** [comment]
Thanks @victornoel would you be up for submitting an PR for this?
You would need  to consider the `opts.DockerfilePath` here along with the `opts.SrcContext` if DockerfilePath is not a remote file.

https://github.com/GoogleContainerTools/kaniko/blob/master/pkg/executor/build.go#L430

**Comment by victornoel** [comment]
@tejal29 thx, I'm trying but I'm blocked by #798 :)

**Comment by victornoel** [comment]
@tejal29 I've made a PR, I will leave the integration tests execution to the CI :)

**Comment by tejal29** [comment]
Thanks @victornoel. Please try reverting go to v12, and try running `make integration`
