### ISSUE TITLE
Ability to use local cached layers

### ISSUE THREAD

**Issue by evheny0** [GoogleContainerTools/kaniko#777]
Hi!
Is there a way to use local cached layers instead of remote from `--cache-repo`?

**Comment by tejal29** [comment]
@evheny0 Please refer to the caching docs mentioned here https://github.com/GoogleContainerTools/kaniko#caching to learn more about how to use local cache.

**Comment by tejal29** [comment]
Feel free to re-open if you have follow up questions!
