### ISSUE TITLE
Dockerfile path can no longer be an HTTP(S) address

### ISSUE THREAD

**Issue by willcro** [GoogleContainerTools/kaniko#803]
**Actual behavior**
Kaniko attempts to resolve any URL as a relative path. This causes an error since the directory doesn't exist.

**Expected behavior**
If a URL is passed as the `--dockerfile` argument, it should make a GET request to fetch the Dockerfile. The downloaded Dockerfile should then be used for the build.

**To Reproduce**
1. `kaniko --context . --dockerfile https://example.com/dockerfile --no-push`
2. `error building image: reading dockerfile at path /https:/example.com/dockerfile: open /https:/example.com/dockerfile: no such file or directory`

**Additional Information**
 - This appears to have been broken by https://github.com/GoogleContainerTools/kaniko/pull/736
 - Tested with gcr.io/kaniko-project/executor:de093f9e05c5ddd11aee185cabecc3249bd090ec
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by tejal29** [comment]
@willcro Looks like a bug here
https://github.com/GoogleContainerTools/kaniko/blob/master/cmd/executor/cmd/root.go#L249,
Fixed in #804
