### ISSUE TITLE
The /kaniko/executor --digest-file option should create parent directories

### ISSUE THREAD

**Issue by Ark-kun** [GoogleContainerTools/kaniko#813]
**Actual behavior**
I run Kaniko Docker container with the --digest-file option:
```
/kaniko/executor ... --digest-file /tmp/outputs/Image_name_with_digest/data
```
The execution fails due to the lack of parent directories:
```
[33mWARN[0m[0055] error uploading layer to cache: writing digest to file failed: open /tmp/outputs/Image_name_with_digest/data: no such file or directory 
error pushing image: writing digest to file failed: open /tmp/outputs/Image_name_with_digest/data: no such file or directory
```

I cannot add a script to pre-create the parent directories, because Kaniko image is distroless and lacks `sh`.

**Expected behavior**
I expect Kaniko to create the parent directories for any output file it writes.

 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by prary** [comment]
@priyawadhwa you can assign this to me.

**Comment by priyawadhwa** [comment]
@prary sounds good!

**Comment by vivek-26** [comment]
@priyawadhwa Can I work on this issue?

**Comment by priyawadhwa** [comment]
@vivek-26 sure, looks like #884 has been quiet for a few months.

**Comment by vivek-26** [comment]
@priyawadhwa PR opened, please review.
