### ISSUE TITLE
Add --image-name-with-digest-file

### ISSUE THREAD

**Issue by Ark-kun** [GoogleContainerTools/kaniko#814]
I request a small new feature very similar to the existing `--digest-file` option.
The `--digest-file` option only outputs the image digest (`sha256:bc45...67e1`) and needs to be combined with image name to make a working image reference.

The `--image-name-with-digest-file` should output the full image name including the digest: `my-org/my-image@sha256:bc45...67e1`

**Comment by tejal29** [comment]
@Ark-kun, since the user specifies the image name in the `--destination` flag, can you write a script to append the image name?

**Comment by Ark-kun** [comment]
> can you write a script to append the image name?

I tried that, but the Kaniko container image is distroless and does not have `sh`.

Generally, I think that the full image name is more useful than just digest alone.
