### ISSUE TITLE
Change Filesystem Extraction debug log to trace log

### ISSUE THREAD

**Issue by prary** [GoogleContainerTools/kaniko#818]
**Actual behavior**
Too many debug logs while building. Can we change following log level to trace instead of debug. 
https://github.com/GoogleContainerTools/kaniko/blob/602657930f800d3fd7871ff647206a39e94bcd81/pkg/util/fs_util.go#L268

https://github.com/GoogleContainerTools/kaniko/blob/602657930f800d3fd7871ff647206a39e94bcd81/pkg/util/fs_util.go#L242

https://github.com/GoogleContainerTools/kaniko/blob/602657930f800d3fd7871ff647206a39e94bcd81/pkg/util/fs_util.go#L236

https://github.com/GoogleContainerTools/kaniko/blob/602657930f800d3fd7871ff647206a39e94bcd81/pkg/util/fs_util.go#L209

**Use Case**
Run a skaffold in debug mode, skaffold passes the debug mode to kaniko and then kaniko populate entire screen with logs like

```
symlink from libkeyutils.so.1.5 to /usr/lib64/libkeyutils.so.1
DEBU[0002] creating file /usr/lib64/libm-2.17.so
DEBU[0002] symlink from libm-2.17.so to /usr/lib64/libm.so.6
DEBU[0002] symlink from libmagic.so.1.0.0 to /usr/lib64/libmagic.so.1
DEBU[0002] creating file /usr/lib64/libmagic.so.1.0.0
and million more
```
It would be extremely helpful to user if filesystem extraction logs are not shown in debug mode.
Skaffold has trace log level we can output filesystem extraction logs in trace level

**To Reproduce**
Run a skaffold build with kaniko with -v=debug mode

**Additional Information**
FROM golang:latest
RUN /bin/sleep  5
 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ **Yes**] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ **NA**] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ **NA**] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ **NA**] </li></ul>|

**Comment by priyawadhwa** [comment]
Hey @prary this seems reasonable to me. Would you be interested in opening a PR? Please cc me if you, or anyone else, opens PRs around this issue.

**Comment by prary** [comment]
hi @priyawadhwa I raise a PR for it thanks.

**Comment by priyawadhwa** [comment]
Great I've assigned you to the issue
