### ISSUE TITLE
make push in Makefile

### ISSUE THREAD

**Issue by prary** [GoogleContainerTools/kaniko#819]
**Feature requirement**
How about the idea of push phony in Makefile 

 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ **Yes** ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ **No** ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ **No** ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [  **No** ] </li></ul>|

**Comment by priyawadhwa** [comment]
Hey @prary what image would this be pushing?

**Comment by prary** [comment]
Image build in ```make images``` step

**Comment by tejal29** [comment]
sure. you add a `push` target to makefile and use it 👍

**Comment by prary** [comment]
Great i'll raise a PR for it
