### ISSUE TITLE
USER 'www-data' uses '/home/www-data' instead of '/var/www' as $HOME

### ISSUE THREAD

**Issue by JordanGoasdoue** [GoogleContainerTools/kaniko#822]
**Actual behavior**

Kaniko doesn't recognize $HOME of USER such as `www-data` which is : 
* `/var/www` in Docker
* `/home/www-data` in Kaniko

Example with Kaniko : 
```
INFO[0000] Downloading base image debian:stretch
...............
...............
INFO[0009] USER www-data                                
INFO[0009] cmd: USER                                    
INFO[0009] RUN echo $HOME                 
INFO[0009] cmd: /bin/sh                                 
INFO[0009] args: [-c echo $HOME]                        
/home/www-data
```

**Expected behavior**

```
Step 1/3 : FROM debian:stretch
 ---> 4f5edfdf153f
Step 2/3 : USER www-data
 ---> Running in 78e96c34bbb0
Removing intermediate container 78e96c34bbb0
 ---> 5894bff94ad9
Step 3/3 : RUN echo $HOME
 ---> Running in dac8ca307ed8
/var/www
```
**To Reproduce**
1. USE this Dockerfile as example : 
```
FROM debian:stretch
USER www-data
RUN echo $HOME
```
2. `tar -C <path to build context> -zcvf context.tar.gz <path to Dockerfile>`
3. `docker run --rm -w /workspace -v (pwd):/workspace gcr.io/kaniko-project/executor@sha256:fb27a2ca60b0943d124100abb66e937bfcf81821d2c79eb7813b7e74637958d0 --tarPath=/path/to/context.tar.gz --context=auth-provider --no-push`

**Additional Information**
 - Dockerfile 
   Please provide either the Dockerfile you're trying to build or one that can reproduce this error.
```
FROM debian:stretch
USER www-data
RUN echo $HOME
```
 - Build Context
   Only Dockerfile
 - Kaniko Image : gcr.io/kaniko-project/executor@sha256:fb27a2ca60b0943d124100abb66e937bfcf81821d2c79eb7813b7e74637958d0

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by tejal29** [comment]
This issue was fixed in #824 and #995

I verified your dockerfile and the home dir is set correctly
```
/ # /kaniko/executor -f dockerfiles/Dockerfile_test1 --context=dir:///workspace --destination=gcr.io/tejal-test/test --tarPath=image.tar
INFO[0000] Resolved base name debian:stretch to debian:stretch 
INFO[0000] Using dockerignore file: /workspace/.dockerignore 
INFO[0000] Resolved base name debian:stretch to debian:stretch 
INFO[0000] Retrieving image manifest debian:stretch     
INFO[0001] Retrieving image manifest debian:stretch     
INFO[0002] Built cross stage deps: map[]                
INFO[0002] Retrieving image manifest debian:stretch     
INFO[0002] Retrieving image manifest debian:stretch     
INFO[0003] Unpacking rootfs as cmd RUN echo $HOME requires it. 
INFO[0005] Taking snapshot of full filesystem...        
INFO[0006] USER www-data                                
INFO[0006] cmd: USER                                    
INFO[0006] RUN echo $HOME                               
INFO[0006] cmd: /bin/sh                                 
INFO[0006] args: [-c echo $HOME]                        
/var/www
INFO[0006] Taking snapshot of full filesystem...        
INFO[0006] No files were changed, appending empty layer to config. No layer added to image. 

```
