### ISSUE TITLE
Feature Req: Update AWS Go sdk to use iam for pods (oidc)

### ISSUE THREAD

**Issue by ffahri** [GoogleContainerTools/kaniko#826]
https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

`supported go version : Go — 1.23.13`

**Comment by tejal29** [comment]
Hi @ffahri Would like to submit a PR for this? Happy to get this in!

**Comment by ffahri** [comment]
Hey @tejal29 i created a pr to upgrade aws sdk
https://github.com/GoogleContainerTools/kaniko/pull/832
