### ISSUE TITLE
kaniko fails without error after logging final Dockerfile step

### ISSUE THREAD

**Issue by silverlyra** [GoogleContainerTools/kaniko#842]
**Actual behavior**
Kaniko logs the `CMD` step near the end of the `Dockerfile` it's been building, pauses for a few seconds, then silently exits with status `0`.

**Expected behavior**
The `CMD` should correctly generate a new image layer, or if there is an error, kaniko should exit with nonzero status to signal failure to our CI system (and preferably also log something explaining why).

**To Reproduce**
This is an internal app built with an internal CI system that uses kaniko with in-cluster Knative Builds. Rolling back to the previous kaniko tag (`v0.12.0`) made `CMD` execute correctly again; hope that's a clue as I can't share full repro steps.

**Additional Information**
We're building a Python app based on miniconda.
```Dockerfile
FROM continuumio/miniconda3:4.6.14

COPY ./image/envs/ /opt/conda/envs/

CMD ["/opt/conda/envs/app_name/bin/python", "-m", "app_name"]
```

The `CMD` is the last Dockerfile statement; might not have to do with that at all.
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by silverlyra** [comment]
We’re seeing this now with `v0.12.0`; so much for the idea this was a regression.

Do any maintainers have a hunch how Kaniko could fail to complete a build and silently exit with status `0`?

**Comment by priyawadhwa** [comment]
Hey @silverlyra -- could you confirm that the image isn't pushed? I'm wondering if kaniko was successful but just didn't properly log that it was.

**Comment by silverlyra** [comment]
After digging in more today, it does seem like the problem is with our Docker registry 😅and metadata not being written successfully. I’m gonna close this as I’m now fairly certain it’s not a problem with Kaniko.
