### ISSUE TITLE
Can't copy with multistage Dockerfile

### ISSUE THREAD

**Issue by Woap** [GoogleContainerTools/kaniko#843]
**Actual behavior**
I recently migrated from dind method with docker daemon to Kaniko to build my applications.
Kaniko is working fine with classical Dockerfile, but I have a problem when I try to run a job with a multistage Dockerfile.

Here my Dockerfile : 
First, it copy my git project and then build it.

```
FROM maven:3.6-jdk-11-slim as BUILD
WORKDIR /home/java
COPY . .
RUN mvn clean package -Dmaven.test.skip=true

FROM openjdk:11-jre-slim as BASE
WORKDIR /home/java
COPY --from=BUILD /home/java/target/xxx-0.0.1-SNAPSHOT.jar /home/java
CMD ["java", "-jar","-Xmx512m", "xxx-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080
```

**Expected behavior**

Build has to be successful. When the job run, it fail at the COPY directive. 

```
COPY --from=BUILD /home/java/target/xxx-0.0.1-SNAPSHOT.jar /home/java 
error building image: error building stage: lstat /kaniko/BUILD/home/java/target/xxx-0.0.1-SNAPSHOT.jar: no such file or directory
```

The BUILD directory doesn't seem to exist.

**Additional Information**
 
 - Build Context :
The build is started by Jenkins which start a pod in Kubernetes. 
```/kaniko/executor --insecure --dockerfile `pwd`/Dockerfile --context `pwd` --destination=xxx.registry```

 - Kaniko Image  : 
gcr.io/kaniko-project/executor:debug-539ddefcae3fd6b411a95982a830d987f4214251
 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [x] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [x] </li></ul>|

**Comment by fredr** [comment]
It seems the stage names needs to be lowercase. Try changing from `BUILD` to `build`

**Comment by Woap** [comment]
Working now, why allowing only lowercase label ?

**Comment by fredr** [comment]
I would guess that is a bug

**Comment by Woap** [comment]
Closing this issue, resolved with lowercase label
