### ISSUE TITLE
error building image: unsupported MediaType when downloading from quay.io

### ISSUE THREAD

**Issue by jeunii** [GoogleContainerTools/kaniko#856]
**Actual behavior**
I am trying to download `quay.io/roboll/helmfile:v0.79.1` using kankio. Ive used
```
gcr.io/kaniko-project/executor:debug
gcr.io/kaniko-project/executor:debug-v0.12.0
```
But when it tries to download images like `quay.io/roboll/helmfile:v0.79.1`, I get the error message
```
[36mINFO[0m[0001] Error while retrieving image from cache: unsupported MediaType: "application/vnd.docker.distribution.manifest.v1+prettyjws"
```

**Expected behavior**
Kaniko should be able to download images like `quay.io/roboll/helmfile:v0.79.1`

Is there a reason why this happens ?

**Comment by prary** [comment]
Quay is v1 spec and I guess kaniko works with v2 spec that's the error you are seeing.

**Comment by cvgw** [comment]
Yes, Kaniko only supports the v2 spec. I'm not very familiar with Quay, but that is the error I have previously seen when the v1 spec is being used.

**Comment by cvgw** [comment]
Closing this issue as there are no plans to support the v1 registry spec. Please re-open if this was closed in error. Cheers
