### ISSUE TITLE
Kaniko fails on this multistage build since v0.9.0

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/kaniko#860]
**Actual behavior**

Multistage built broken for docker file  since v0.9.0 
https://github.com/AkihiroSuda/buildbench/blob/master/examples/ex01/Dockerfile

**Comment by simon991** [comment]
Hi @tejal29, I am facing the same issue using kaniko on google cloud build. Do you have any workaround so far?

**Comment by cvgw** [comment]
@tejal29 what error due you see with this build?  I'm able to build the linked dockerfile successfully and I don't see any differences between the kaniko version and docker version using `container-diff`

**Comment by tejal29** [comment]
Sorry @cvgw this was very poorly written bug description. I was trying to use the v0.11.0 version for the dockerfile. 
```
FROM alpine AS buildc
RUN apk add --no-cache build-base
RUN echo -e "#include <stdio.h>\nint main(int ac, char *av[]){printf(\"hello c\\\\n\");return 0;}" | tee /hello.c
COPY . /foo
RUN gcc -o /a.out /hello.c

# the COPY above SHOULD NOT invalidate the cache for the buildgo stage.

FROM alpine AS buildgo
RUN apk add --no-cache build-base
RUN apk add --no-cache go
RUN echo -e "package main\nfunc main(){println(\"hello go\")}" | tee /hello.go
RUN go build -o /a.out /hello.go

FROM alpine
COPY --from=buildc /a.out /hello1
COPY --from=buildgo /a.out /hello2
```

However, i tried this on latest executor image and it works.
