### ISSUE TITLE
Please make ecr login from eks with sts:AssumeRoleWithWebIdentity possible (update aws-sdk/ecr-credential-helper)

### ISSUE THREAD

**Issue by markussiebert** [GoogleContainerTools/kaniko#889]
**Actual behavior**
At the moment it is not possible to use the iam role connected to an serviceaccount within eks. The credential helper ignores this new method of getting iam credentials.

More info: https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

**Expected behavior**
It should be possible to get credentials this way.

**To Reproduce**
1. Try to push an image from your pod with iam role assigned like described here:
https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

**Additional Information**
This issue was already solved in the amazon-credential-helper two months ago.
https://github.com/awslabs/amazon-ecr-credential-helper/commit/73edd05845f26010e205cab9709a5a45406bffd5

In order to support native AWS IAM integration with Kubernetes,
the AWS SDK needs to be bumped to v1.23.13 at least.

**Comment by Teddy-Schmitz** [comment]
I ran into this same issue and did some digging, kaniko just gets the latest released version of the ecr-credentials helper and builds it in the docker file.  Unfortunately the latest version of the helper does not have awslabs/amazon-ecr-credential-helper@73edd05 .  I have asked them to release a new version awslabs/amazon-ecr-credential-helper#192 which then would allow kaniko to push an updated docker image.

**Comment by markus7811** [comment]
Yes, after recompiling the credential helper and kaniko and building my of kaniko image i still had trouble that the credential helper won't use my servicerole iam role. So i contacted AWS and the told me this solution.
env:
AWS_SDK_LOAD_CONFIG=true

=> and it is working. With the released kaniko image. Please test this solution if it works for you.

**Comment by Teddy-Schmitz** [comment]
yep that worked, thanks!

**Comment by ivankatliarchuk** [comment]
Latest kaniko image `gcr.io/kaniko-project/executor:debug-d72a960600f388655171eec0bf797cd5fbece666` works with AWS EKS WebIdentity and IAM orles over a  service account. Thanks for a tip. The environment variable `AWS_SDK_LOAD_CONFIG=true` shold be set.

**Comment by prasunsultania** [comment]
Thanks @markussiebert and @ivankatliarchuk 
adding AWS_SDK_LOAD_CONFIG = true worked for me.
