### ISSUE TITLE
COPY commands log too much info

### ISSUE THREAD

**Issue by unalterable** [GoogleContainerTools/kaniko#901]
**Actual behavior**
When my Dockerfile has a COPY command - kaniko logs out all the files that were copied.

For multi-stage builds, or copying dependencies, or any massive collection of files that aren't bundled or compiled, this is extremely impractical.

My build logs have gone from 10kb to over 1000kb per build.

**Expected behavior**
For me to only see such detailed logs when in a higher log-level than simply INFO

**To Reproduce**
1. put a COPY command on a node_modules/ folder
2. build with kaniko

 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [X] </li></ul>|

**Comment by Andor** [comment]
For me, it works well for first run, without usage of caching layers.
But when the layer used by `COPY` is extracted from cache then it generate tons of noise:
```
COPY --from=gcloud /usr/lib/google-cloud-sdk /usr/lib/google-cloud-sdk 
Found cached layer, extracting to filesystem 
extractedFiles: [/usr/lib/google-cloud-sdk/lib/third_party/kubernetes/client/models/v1beta2_replica_set_list.py /usr/lib/google-cloud-sdk/platform/google_appengine/lib/django-1.3/django/contrib/gis/db/models/query.py /usr/lib/google-cloud-sdk/platform/google_appengine/lib/django-1.5/django/contrib/gis/locale/sl/LC_MESSAGES/django.po...
```
Literally listing all the files in the copyed directory.

**Comment by ejose19** [comment]
Current workaround is adding --verbosity=warn flag to keep logs clean, but agree on this needs fixing.

**Comment by Andor** [comment]
@ejose19 It's not a workaround, because I will lose all the logs, not only unneeded.

Also, `COPY --from=...` works fine when the cache is not used, so it's definitely some difference between cached and non-cached copying.

**Comment by ejose19** [comment]
@Andor of course if you only use Kaniko in all steps of your CI the workaround is "useless", however when doing multi steps build it's better to have the others at least (google cloud build truncates logs over a certain size)

Yes, I noticed that too, the issue is related to cache.

**Comment by wmuizelaar** [comment]
Maybe related to https://github.com/GoogleContainerTools/kaniko/issues/303 ?

**Comment by Andor** [comment]
@wmuizelaar doesn't look like. It logs different data for cached and not-cached COPY command.
