### ISSUE TITLE
Adding linting of Docker image to Kaniko container

### ISSUE THREAD

**Issue by webmutation** [GoogleContainerTools/kaniko#902]
Feature Request
One of the main issues we have is improper Dockerfiles. So as a first step I run hadolint to avoid failed Kaniko builds. However I have to use a different Docker image for this. It would be more efficient to run it in the same container or for kaniko to have a linting option.

**Comment by cvgw** [comment]
Interesting, just want to make sure I'm understanding this correctly.

You're proposing adding a feature to kaniko where it could lint the supplied dockerfile and then exit early if that linting fails?

**Comment by webmutation** [comment]
Yes indeed. It would prevent having needless build done. unfortunately it has happened in our CI pipelines quite often, improperly formatted Dockerfiles

**Comment by cvgw** [comment]
@webmutation that seems like a reasonable and useful feature to me.

@tejal29 or @priyawadhwa any opinions?

**Comment by priyawadhwa** [comment]
I think this could be cool! We could put the feature behind a flag.

**Comment by tejal29** [comment]
@webmutation nice idea. Do you want to open a PR and implementing this?

**Comment by JordanGoasdoue** [comment]
@tejal29 , I want to give this cool feature request a shot :) as no one did before.

**Comment by tejal29** [comment]
closed as we discussed in #1152

**Comment by tejal29** [comment]
as discussed in #1152 this is not something that fits in kaniko's goals. Closing this.
