### ISSUE TITLE
Kaniko + Nexus

### ISSUE THREAD

**Issue by danilorsilva** [GoogleContainerTools/kaniko#916]
Hello all,

Is there a way to use kaniko + nexus private registry?

I tried to use a config.json without success.

Thanks!

**Comment by tejal29** [comment]
Hey @danilorsilva thank you for your question. 

Looking into using nexus private registry docs, 
you need to set up auth like this.
https://blog.sonatype.com/using-nexus-3-as-your-repository-part-3-docker-images

```
 ~/.docker/config.json:

{
	"auths": {
		"your-repo:8082": {
			"auth": "YWRtaW46YWRtaW4xMjM="
		},
		"your-repo:8083": {
			"auth": "YWRtaW46YWRtaW4xMjM="
		}
}
```

Can you follow the instructions here 
https://github.com/GoogleContainerTools/kaniko#pushing-to-docker-hub
to create a `/kaniko/.docker/config.json` and try?

**Comment by Elgarni** [comment]
@tejal29 We have a Nexus repository, and it's working with this setting.
@danilorsilva Make sure the authenticated user has the necessary permissions.

**Comment by danilorsilva** [comment]
Thanks!!!
