### ISSUE TITLE
QUESTION: Correct Build Parameters/Args For Opting Into Caching?

### ISSUE THREAD

**Issue by vguaglione** [GoogleContainerTools/kaniko#919]
I am attempting to make use of the built-in caching mechanism when building images.  I have set the following build parameters:

--cache=true
--cache-dir=/images  (mapped to a local volume via standard docker run -v)

I am testing using the debug version of the executor via docker run:  

docker run -it -v $(pwd):/workspace -v $(pwd)/mywkdir:/images --entrypoint=/busybox/sh gcr.io/kaniko-project/executor:debug

My builds run to completion but upon checking my /images folder, it is always empty.  I may be misunderstanding the role of caching here but I assumed that the cache option will allow me to store up to date images locally so I will not need to pull them from their source repos each time I run a build, unless they have been changed?

Can you provide clarification and guidance, please?

**Comment by vguaglione** [comment]
Pasting full command and selected output revealing the errors below:

/kaniko/executor --dockerfile /workspace/Dockerfile --no-push --context /workspace --cache=true --cache-dir=/image-cache --cache-repo=<my private repo>

INFO[0025] Taking snapshot of full filesystem...        
INFO[0028] Pushing layer <private repo>:b9f16ab3e1f4f8639b80facf2d658f05cad2186188e4f17c8a3a62f4d64d84ef to cache now 
INFO[0028] RUN chgrp -R root /opt/bitnami               
INFO[0028] cmd: /bin/sh                                 
INFO[0028] args: [-c chgrp -R root /opt/bitnami]        
INFO[0028] Taking snapshot of full filesystem...        
INFO[0032] USER 10001                                   
INFO[0032] cmd: USER                                    
INFO[0032] No files changed in this command, skipping snapshotting. 
INFO[0032] WORKDIR ${APP_ROOT}                          
INFO[0032] cmd: workdir                                 
INFO[0032] Changed working directory to /app            
INFO[0032] No files changed in this command, skipping snapshotting. 
INFO[0032] RUN sed "s@${USER_NAME}:x:${USER_UID}:0@${USER_NAME}:x:\${USER_ID}:\${GROUP_ID}@g" /etc/passwd > ${APP_ROOT}/etc/passwd.template 
INFO[0032] cmd: /bin/sh                                 
INFO[0032] args: [-c sed "s@${USER_NAME}:x:${USER_UID}:0@${USER_NAME}:x:\${USER_ID}:\${GROUP_ID}@g" /etc/passwd > ${APP_ROOT}/etc/passwd.template] 
INFO[0032] Taking snapshot of full filesystem...        
INFO[0032] Pushing layer <private repo>:71d425cc656b24aa764fb1f7c93fd0838c60dc9b790b434edf925b39a32206c9 to cache now 
INFO[0033] ENTRYPOINT [ "entrypoint.sh" ]               
INFO[0033] No files changed in this command, skipping snapshotting. 
INFO[0033] CMD [ "php-fpm", "-F", "--pid", "/opt/bitnami/php/tmp/php-fpm.pid", "-y", "/opt/bitnami/php/etc/php-fpm.conf" ] 
INFO[0033] No files changed in this command, skipping snapshotting. 
INFO[0033] Pushing layer <private repo>:0823510cb7b52c8ae766d4e99e3aa7d09b84e01fc85534d0e1e7f93b7f6de9a8 to cache now 
WARN[0034] error uploading layer to cache: failed to push to destination index.docker.io/library/<private repo>:132818bc6803869f4d18b21cd9ab481028821a109fd0deef2ef2a00d2f07b279: unsupported status code 401; body:  
INFO[0034] Skipping push to container registry due to --no-push flag

**Comment by cvgw** [comment]
@vguaglione it looks like you're specifying a blank `cache-repo`. I would imagine that results in some weird, undefined behavior we could probably produce a better error message for.

I'm not sure if this was clear to you already, but `cache-dir` is only for base images and populated by the `cache-warmer`. `cache-repo` is used for the layers build by kaniko.

**Comment by vguaglione** [comment]
> @vguaglione it looks like you're specifying a blank `cache-repo`. I would imagine that results in some weird, undefined behavior we could probably produce a better error message for.
> 
> I'm not sure if this was clear to you already, but `cache-dir` is only for base images and populated by the `cache-warmer`. `cache-repo` is used for the layers built by kaniko.

Actually,  I have specified the cache repo but attempted to obfuscate it from the output.   Here's the command:

/kaniko/executor --dockerfile /workspace/Dockerfile --no-push --context /workspace --cache=true --cache-dir=/image-cache --cache-repo=gitlab.dhe.duke.edu 

I believe I misunderstood the functionality of the cache.  What we were trying to do was use cache=true and cache-dir=/image-cache to cache the layers on the machine in which the build is running, in the /image-cache folder.  Actually, our end goal is to be able to do this in our kubernetes cluster.  We have the kaniko container running via the gitlab-runner pod in our cluster, and wanted to cache image layers in a PVC that is mapped via the runner's volume mount.  The runner pods are transient so they will need to connect to the PVC upon initialization, which is no problem.  If we use pod local storage for this our layers will go away once the pod spins down.

Can cache-repo be pointing to a local directory (or a mapped volume from a PVC) because, if so, that might work.

**Comment by cvgw** [comment]
> Actually, I have specified the cache repo but attempted to obfuscate it from the output. Here's the command:

Whoops! Sorry, that makes sense :) In that case I'm not sure what the 401 is about but probably related to configuring auth in the container.

But to address your main point: afaik `cache-repo` can't point to a local directory (or a mapped volume). @tejal29 might correct me on that though.

I can definitely see the use case and advantage of that;  seems like a reasonable feature to consider adding imo

**Comment by vguaglione** [comment]
> > Actually, I have specified the cache repo but attempted to obfuscate it from the output. Here's the command:
> 
> Whoops! Sorry, that makes sense :) In that case I'm not sure what the 401 is about but probably related to configuring auth in the container.
> 
> But to address your main point: afaik `cache-repo` can't point to a local directory (or a mapped volume). @tejal29 might correct me on that though.
> 
> I can definitely see the use case and advantage of that; seems like a reasonable feature to consider adding imo

Ok so to sum up, we can't cache layers locally at this point, correct?

**Comment by cvgw** [comment]
> Ok so to sum up, we can't cache layers locally at this point, correct?
No, I do not believe that is possible at this time.

**Comment by vguaglione** [comment]
> > Ok so to sum up, we can't cache layers locally at this point, correct?
> 
> Correct, I do not believe that is possible at this time.

Can we add this?  I can go ahead and create a feature request or can you move this to the backlog?

**Comment by cvgw** [comment]
@vguaglione ya I think this is reasonable to add. I opened https://github.com/GoogleContainerTools/kaniko/issues/923 to track

**Comment by vguaglione** [comment]
Great, thanks so much!

**Comment by cvgw** [comment]
@vguaglione is it ok if I close this issue?

**Comment by vguaglione** [comment]
> @vguaglione is it ok if I close this issue?

Sure.  Thanks for looking into this for us.
