### ISSUE TITLE
cache warmer --cache-ttl option serves no apparent purpose

### ISSUE THREAD

**Issue by gawi** [GoogleContainerTools/kaniko#921]
**Actual behavior**
The cache warmer will always ensure that the requested image will be written to the base image cache. It will always validate against the registry (a given tag can point to different images over time, the best example of that is the `latest` tag).

If the base image was not present, the file will be written to the cache and the cache warmer will output some traces:
```
$ docker run -v ${PWD}:/cache gcr.io/kaniko-project/warmer:latest \
             --cache-dir=/cache -v debug -i ubuntu:latest --cache-ttl=10h
DEBU[0000] /cache                                       
DEBU[0000] [ubuntu:latest]                              
DEBU[0002] Wrote ubuntu:latest to cache
```

If the base image was already in the cache and is not expired according to the `--cache-ttl` option, nothing special happens beside a specific trace:
```
$ docker run -v ${PWD}:/cache gcr.io/kaniko-project/warmer:latest \
             --cache-dir=/cache -v debug -i ubuntu:latest --cache-ttl=10h
DEBU[0000] /cache                                       
DEBU[0000] [ubuntu:latest]                              
INFO[0000] Found sha256:2695d3e10e69cc500a16eae6d6629c803c43ab075fa5ce60813a0fc49c47e859 in local cache 
INFO[0000] Found manifest at /cache/sha256:2695d3e10e69cc500a16eae6d6629c803c43ab075fa5ce60813a0fc49c47e859.json 
```

If it's expired, nothing special happens but the trace is different:
```
$ docker run -v ${PWD}:/cache gcr.io/kaniko-project/warmer:latest --cache-dir=/cache -v debug -i ubuntu:latest --cache-ttl=1s
DEBU[0000] /cache                                       
DEBU[0000] [ubuntu:latest]                              
DEBU[0000] Cached image is too old: 2019-12-19 16:46:48.276102926 +0000 UTC
```

**Expected behavior**
There is nothing in the documentation telling what should be the expected behaviour. Possibly, the option could be removed as it doesn't have any significant effect. 

At the very least, the exit code should be different if the base image is expired (but frankly I don't know what it could be used for).

As I understand it, the cache warmer will always contact the registry to lookup the image before even looking at the cache.  So the `--cache-ttl` doesn't even prevent this network trip.

**To Reproduce**
See above

**Additional Information**
- none
  
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by cvgw** [comment]
I confirmed we don't have any documentation of what `cache-tll` does for either executor or warmer so I'll definitely create an issue to add that information to the docs.

As far as the warmer goes, looking at the src kaniko definitely ignores when the cached image is expired so I'm not sure what the point of passing `cache-ttl` to the warmer is.

I'll open a bug for the warmer and start a discussion about how to resolve it.

**Comment by cvgw** [comment]
opened https://github.com/GoogleContainerTools/kaniko/issues/928 and https://github.com/GoogleContainerTools/kaniko/issues/929

Please close this issue if you feel #928 and #929 sufficiently cover your concerns. If not let me know what else we should include!

**Comment by gawi** [comment]
Thanks. #928 and #929 accurately cover the issue.
