### ISSUE TITLE
Kaniko hangs in GKE cluster with Workload Identity enabled

### ISSUE THREAD

**Issue by martinraison** [GoogleContainerTools/kaniko#937]
**Actual behavior**

The kaniko executor hangs on startup when running inside our GKE cluster. After a bit of investigation, it seems the executor is stuck in a loop when trying to get the instance metadata (see reproduction below for details).

I suspect (not 100% sure) this might be due to Workload Identity being enabled in the cluster (which protects metadata by default).

What is metadata used for ? Is there a workaround to proceed without metadata ?

**Expected behavior**
Kaniko executor should not hang on startup

**To Reproduce**
1. `kubectl run -it  kaniko --rm=true --restart=Never --image=gcr.io/kaniko-project/executor:debug-v0.15.0 -- --help`
2. the command hangs

To understand the problem, I sshed into the pod and killed the process with `kill -ABRT 1`, here is the stack-trace that got printed:

```
goroutine 1 [sleep, locked to thread]:                                                               
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:307
time.Sleep(0x2faf0800)
        /usr/local/go/src/runtime/time.go:105 +0x159
github.com/GoogleContainerTools/kaniko/vendor/k8s.io/kubernetes/pkg/credentialprovider/gcp.runWithBackoff(0xc000435de0, 0xc000136440, 0x40, 0x40)
        /go/src/github.com/GoogleContainerTools/kaniko/vendor/k8s.io/kubernetes/pkg/credentialprovider/gcp/metadata.go:186 +0x32
github.com/GoogleContainerTools/kaniko/vendor/k8s.io/kubernetes/pkg/credentialprovider/gcp.(*containerRegistryProvider).Enabled(0xc00012a068, 0xc00012c760)
        /go/src/github.com/GoogleContainerTools/kaniko/vendor/k8s.io/kubernetes/pkg/credentialprovider/gcp/metadata.go:209 +0x7c
github.com/GoogleContainerTools/kaniko/vendor/k8s.io/kubernetes/pkg/credentialprovider.NewDockerKeyring(0xc000435f28, 0x11420ce)
        /go/src/github.com/GoogleContainerTools/kaniko/vendor/k8s.io/kubernetes/pkg/credentialprovider/plugins.go:55 +0x123
github.com/GoogleContainerTools/kaniko/vendor/github.com/google/go-containerregistry/pkg/authn/k8schain.init.ializers()
        /go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/google/go-containerregistry/pkg/authn/k8schain/k8schain.go:50 +0x22
```

**Additional Information**
 - Dockerfile 
   No Dockerfile needed
 - Build Context
   No context needed
 - Kaniko Image (fully qualified with digest): `gcr.io/kaniko-project/executor:debug-v0.15.0`
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by martinraison** [comment]
After further investigation, there seems to be an issue on the GKE side. I tried fetching the service account metadata manually from the kaniko container, with:

```
echo -e "GET /computeMetadata/v1/instance/service-accounts/ HTTP/1.1\nHost: metadata.google.internal.\nMetadata-Flavor: Google\n\n" | nc metadata.google.internal. 80
```

I'm getting a 500:

```
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Sun, 29 Dec 2019 18:19:46 GMT
Content-Length: 19

Could not list uri
```

Looks like the issue has more to do with Kubernetes than with Kaniko. I'll close (let me know if you know a workaround, though !)

**Comment by sbeaulie** [comment]
I get the same issue on the latest image `gcr.io/kaniko-project/executor:debug-v0.19.0` did you ever find a workaround or something to change on the GKE side for permissions or other settings?

**Comment by tejal29** [comment]
Looks like the @martinraison who reported the issue closed this because it not an issue with kaniko but GCE.

**Comment by nburns** [comment]
For anyone else who ends up here looking for a way to open a shell in a kaniko image, there's a debug image with a shell `sh`: https://github.com/GoogleContainerTools/kaniko?tab=readme-ov-file#debug-image so you can run `docker run --entrypoint sh -it gcr.io/kaniko-project/executor:debug`
