### ISSUE TITLE
Travis, Docker, and Kokoro all use different golang versions

### ISSUE THREAD

**Issue by cvgw** [GoogleContainerTools/kaniko#947]
**Actual behavior**
Kokoro, Travis, and the Kaniko Dockerfiles all use different Golang versions

Travis is 1.13
https://github.com/GoogleContainerTools/kaniko/blob/eafb80227b044b521f261b3883f094da0dd29950/.travis.yml#L5

Dockerfile is 1.12
https://github.com/GoogleContainerTools/kaniko/blob/eafb80227b044b521f261b3883f094da0dd29950/deploy/Dockerfile#L17

I have no idea what Kokoro is using but it's not 1.13 because `testing.Init` is not available and that was added in 1.13

**Expected behavior**
Kokoro, Travis, and the Kaniko docker files should all use the same golang version

**To Reproduce**
N/A

**Additional Information**
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by tejal29** [comment]
This is being tackled by @samos123

**Comment by tejal29** [comment]
@samos123 is this fixed now?

**Comment by samos123** [comment]
Yes, however I will still need to update the Dockerfile to use 1.13 as well. It's still using 1.12 in the dockerfile. Let me create a PR for that.

**Comment by samos123** [comment]
Actually seems the Dockerfiles have already been updated to use 1.13 in master. So this can be closed now.
