### ISSUE TITLE
Hash Bang on wrong line in bash script

### ISSUE THREAD

**Issue by amouat** [GoogleContainerTools/kaniko#953]
**Actual behavior**

Running the `run_in_docker.sh` script on non-bash shells results in an error:

```
echo $SHELL
/usr/bin/zsh

# amouat @ blagulon in ~/proj/kaniko on git:master x [11:54:24] 
$ ./run_in_docker.sh Dockerfile directory test
./run_in_docker.sh: 28: [[: not found
./run_in_docker.sh: 32: [[: not found
...
```

This is because hash bang lines in bash scripts (e.g. `#!/bin/bash`) must occur on the first line, but in this script the first line is a copyright statment.

**Expected behavior**

The error lines should not appear:

```
./run_in_docker.sh: 28: [[: not found
./run_in_docker.sh: 32: [[: not found
```

**To Reproduce**

Run the following:
```
$ sh
$ ./run_in_docker.sh test test test
```

**Additional Information**
I'll create a PR shortly.
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>n</li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>n</li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>n</li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>n</li></ul>|

**Comment by amouat** [comment]
I also found the same problem in two more scripts `integration-test.sh` and `benchmark.sh`

**Comment by cvgw** [comment]
I didn't realize this way a requirement :+1:

I am concerned that the tool we use https://github.com/google/addlicense will cause this problem to occur again.

**Comment by cvgw** [comment]
Re-opening this issue as it may happen again due to `addlicense` behavior

**Comment by aaron-prindle** [comment]
All scripts currently have `#!/bin/bash` or `#!/bin/sh` as the first line in the file.  Closing
