### ISSUE TITLE
Add option to only build if the image/tag does not yet exist

### ISSUE THREAD

**Issue by cmorty** [GoogleContainerTools/kaniko#958]
Depending on your CI-Environment it might be helpful to only build a certain image only if it it does not yet exist at the registry. (E.g. if the tag is derived from a version/ID or, as in our case, from the hash of the Git-Folder-Object containing the Docker-file.)

**Actual behavior**
The image is always built and uploaded.

**Expected behavior**
Only build the image if it does not yet exist.

**Implementation Idea**
This can be implemented analog to, or as part of `executor.CheckPushPermissions`.
The flag could be `--ifNecessary`.
Unfortunately my Go-Skills are non-existent, but I'm happy to support with testing, etc.

 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [x] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by xpepermint** [comment]
A year has passed. What is the status of this task?

**Comment by ChuckNoxis** [comment]
Any updates on this ?

**Comment by fshafiee** [comment]
If it helps, this is how I am currently handling it using `docker manifest`:

```bash
```

**Comment by fshafiee** [comment]
If it helps, this is my workaround usign [`docker manifest`](https://docs.docker.com/engine/reference/commandline/manifest/):

```bash
if docker manifest inspect alpine:invalid-tag
then
  echo "It exists. Skip the build..."
else
  echo "Building new image.."
fi
```
I don't know how to access docker daemon inside a kaniko container (or even if it's possible at all). So I had to use a separate job in the CI to check and set an environment variable and pass it to the next job.

This should be a flag for kaniko.

**Comment by thejan2009** [comment]
Another workaround using [crane](https://github.com/google/go-containerregistry/tree/main/cmd/crane) in a custom kaniko container image:

```Dockerfile
FROM gcr.io/go-containerregistry/crane:v0.8.0 as crane

FROM gcr.io/kaniko-project/executor:v1.8.0-debug

COPY --from=crane /ko-app/crane /usr/local/bin/
```

Call the following before `/kaniko/executor` but after setting up registry credentials:
```bash
if crane manifest $IMAGE; then echo "already exists, skipping build"; exit 1; fi
```

**Comment by imjasonh** [comment]
I don't consider this behavior that Kaniko should be responsible for. Similarly, `docker build` doesn't have any such flag with this behavior.

As mentioned throughout these comments, whatever workflow you're using to invoke Kaniko can also be used to conditionally _not_ invoke Kaniko based on whatever conditions you want.

**Comment by cmorty** [comment]
@imjasonh Docker has `docker inscpect`, which allows you to check. Also kaniko clearly targets CI, where a "Build if it does not exist` is a common scenario. But I don't have any stakes any more.

**Comment by imjasonh** [comment]
You can use existing tools to check whether an image exists in the registry, such as [`crane`](https://github.com/google/go-containerregistry/blob/main/cmd/crane/) or [Skopeo](https://github.com/containers/skopeo).

**Comment by blackliner** [comment]
The nice thing about this idea is that we would not have to do a separate docker login, and thus handle credentials in addition to the docker.config we have to write. kaniko also checks the repo for write access, so checking for an existing image would literally be one additional condition. Please reconsider

**Comment by imjasonh** [comment]
I'm not sure why you'd have to do a separate docker login, Kaniko and `crane` (and Skopeo, I think) all read the same auth config and use the same credential helpers.

Kaniko checks the repo for write access as an optimization to save time building if it knows it won't be able to push.

The "if this tag doesn't exist yet" check is race-y anyway (using Kaniko or crane or any tool), so there's no guarantee that the tag won't exist between the time that you checked and when you push to it.

**Comment by cmorty** [comment]
@imjasonh Yes, it's racy (that must be taken care of by the user). But all the code is already there. It just a matter of how to handle the result. And it saves the user the trouble of using an additional tool by adding a command line parameter.

**Comment by imjasonh** [comment]
If you'd like to send a PR I can review it. In general I'm against adding more flags (or more code) to Kaniko unless it's to improve Docker compatibility, or in some cases to improve performance to a level that's comparable with Docker.

**Comment by blackliner** [comment]
Thanks for being open to this.

One issue I encountered as well is that we can't even use `docker` to login or do any checks when running inside the kaniko container. I agree its 100% convenience.

**Comment by zdelagrange** [comment]
>Kaniko checks the repo for write access as an optimization to save time building if it knows it won't be able to push.

should this feature be removed since you can use other tools to perform the same action?

**Comment by Adamantish** [comment]
@imjasonh I would agree that kaniko shouldn't implement this if it were designed purely as an image builder. But it also has all kinds of functionality for writing to an image registry. Surely, any API with destructive write capabilities needs its counterpart of read capability. i.e. if I can't have eyes, I don't want hands.

**Comment by THEtheChad** [comment]
I agree with @Adamantish. Kaniko already has the ability to interact with the repository, so it makes sense to incorporate a minimal set of tooling to interact with it (outside of just publishing).

The race condition is a moot point. The idea is to free up resources as soon as possible if we know for a fact that the effort is going to be wasted. The race condition is an edge case and is no worse that what's happening now.

This is coming from the perspective of a person that just inherited a pipeline using Kaniko. I have no prior experience. My first instinct upon seeing that Kaniko publishes to the repository was to look for documentation on how to do a check with the same tool. I don't think it's crazy that end users expect this kind of functionality, especially in an enterprise CI pipeline where resources can be a little more scarce.

**Comment by danifv** [comment]
I'd also prefer including an options as the one suggested by @Adamantish.  
Having a custom image with both kaniko and crane is possible, but it increases the number of images we have to maintain.

**Comment by celorodovalho** [comment]
+1
