### ISSUE TITLE
Unprivileged & The usage of the root user

### ISSUE THREAD

**Issue by Quentin-M** [GoogleContainerTools/kaniko#96]
Congratulations on the launch, and thank you for investing in the direction of secure builds.

From the release's [blog post](https://cloudplatform.googleblog.com/2018/04/introducing-kaniko-Build-container-images-in-Kubernetes-and-Google-Container-Builder-even-without-root-access.html): 

> an open-source tool for building container images from a Dockerfile even without privileged root access. 

> Since it doesn’t require any special privileges or permissions, you can run kaniko in a standard Kubernetes cluster, Google Kubernetes Engine, or in any environment that can’t have access to privileges or a Docker daemon.

Unfortunately, running a container as `root` inside a Kubernetes cluster, does indeed mean giving special privileges/permissions (e.g. `PodSecurityPolicy`). Under certain definitions of security where state/resourceful actors are involved, running any process (e.g. `kaniko`) as the `root` user inside a Docker container, and executing arbitrary code inside that process (e.g. `kaniko` doing executing a `RUN` statement that involve 3rd party dependencies), can be considered equivalent to giving `root` access to the underlying nodes. At least, until [userns support](https://github.com/kubernetes/features/issues/127) is added to Kubernetes, or until alternative runtime become stable (e.g. `Kata containers`).

Therefore, I am saddened to notice that the previous statements are a bit misleading, and that `kaniko` will not help us get rid of the isolated nodes/VMs we must use for Gitlab/Jenkins CI.

As an actionable to this issue, I suggest adding relevant notes regarding the security aspects in the README.

**Comment by cyphar** [comment]
Using tools like [`umoci`](https://github.com/openSUSE/umoci) would allow for unprivileged builds to be done fairly easily (even within containers if that is a constraint -- though there are some `runc` bugs that are being worked on fixed to allow container-based builds inside containers).

> At least, until userns support is added to Kubernetes, or until alternative runtime become stable (e.g. Kata containers).

Or if you use [rootless containers](https://rootlesscontaine.rs/).

**Comment by dlorenc** [comment]
I think we've cleared this up in the readme now with #115 . Please open another issue or PR with more suggestions on documenting this clearly.
