### ISSUE TITLE
How to get imageSize using kaniko

### ISSUE THREAD

**Issue by gejunqiang** [GoogleContainerTools/kaniko#976]
I want to build a docker image using kaniko, and I want to know imageID and imageSize after build completion which can easily get by two docker commands: `docker inspect imageName:imageTag --format='{{.Id}}'`, `docker inspect imageName:imageTag --format='{{.Size}}'`. 

I tried the `--oci-layout-path` to save the  OCI image layout. Then I can get the imageID from the image manifest file. For imageSize，I decompress every layer that in gzipped tar format and then add the uncompressed layer's size together，but the result **isn't** equal to the result retrieved from `docker inspect` command.

So I want to know how to get the correct imageSize using kaniko

**Comment by jasondamour** [comment]
@gejunqiang Did you find a solution?
