### ISSUE TITLE
Connection refused for non-TLS registry URL

### ISSUE THREAD

**Issue by nonetheless** [GoogleContainerTools/kaniko#977]
**Actual behavior**
When I use kaniko to build image and push it to a local registry (xx.xx.xx.xx:5000/tag:version), it will refuse the connection.
We should upgrade go-containerregistry version to deal it.

https://github.com/google/go-containerregistry/commit/4711a5d6e6d8d5973f1cce4f680feff4fde91550

**Expected behavior**

**To Reproduce**
1. ...
2. ...

**Additional Information**
 - Dockerfile 
   Please provide either the Dockerfile you're trying to build or one that can reproduce this error.
 - Build Context
   Please provide or clearly describe any files needed to build the Dockerfile (ADD/COPY commands)
 - Kaniko Image (fully qualified with digest)
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by tejal29** [comment]
Thanks looks like you already have a pr in progress.
Thanks

**Comment by antechrestos** [comment]
@nonetheless @tejal29 I think that this issue is already fixed by #957 as I upgraded to the commit [34fb8ff](https://github.com/google/go-containerregistry/commit/34fb8ff33bed0fab41a607d21da5860b924ff694) which is more recent that [4711a5d](https://github.com/google/go-containerregistry/commit/4711a5d6e6d8d5973f1cce4f680feff4fde91550)

**Comment by tejal29** [comment]
Thanks @antechrestos for confirming!
