### ISSUE TITLE
COPY --from incorrectly uses .dockerignore

### ISSUE THREAD

**Issue by mykter** [GoogleContainerTools/kaniko#986]
**Actual behavior**
`COPY --from` appears to be applying `.dockerignore` filtering, which it shouldn't.
```
INFO[0006] COPY --from=prep /hi /hi
error building image: error building stage: failed to execute command: copy failed: no source files specified
```

**Expected behavior**
The source file is copied to the destination.

**To Reproduce**
With this Dockerfile in the current directory
```dockerfile
FROM alpine:latest as prep

RUN echo "hi" > /hi

FROM scratch
COPY --from=prep /hi /hi
```
and this .dockerignore:
`*`
Run ```docker run -v `pwd`:/workspace gcr.io/kaniko-project/executor:latest --no-push ```

Gives the above error.

**Additional Information**
 - Kaniko Image (fully qualified with digest)
f116560a308ead98708bd66b80fe06ab19a70355d590060aa4a01703d8b17203
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [x] </li></ul>|

**Comment by tejal29** [comment]
@mykter What is your `.dockerignore` file?

**Comment by mykter** [comment]
> **To Reproduce**
> With this Dockerfile in the current directory
> 
> ```dockerfile
> FROM alpine:latest as prep
> 
> RUN echo "hi" > /hi
> 
> FROM scratch
> COPY --from=prep /hi /hi
> ```
> 
> and this .dockerignore:
> `*`

**Comment by ejose19** [comment]
The problem is that .dockerignore is being applied to COPY between stages, like the one provided by @mykter. Current workaround is to use debug image to replace/rename .dockerignore before launching kaniko

**Comment by bootc** [comment]
It looks like this is a duplicate of #595.

**Comment by mykter** [comment]
Yup, sorry I missed that
