### ISSUE TITLE
run_in_docker.sh doesn't work (or gracefully not work) with non-glcoud registires

### ISSUE THREAD

**Issue by rhs** [GoogleContainerTools/kaniko#988]
**Actual behavior**
I'm trying to get run_in_docker.sh to work... I'm passing in quay.io/<username>/foo as the third argument, and I keep getting permission issues with pushing to that repo
how am I supposed to give the run_in_docker.sh script credentials?

**Expected behavior**
I would expect there to be some instructions for passing in docker credentials to work with a normal registry. Or alternatively it should be clear (perhaps via README or an error check in the shell script) that it only works with gcr.

**To Reproduce**
See above.

**Comment by tejal29** [comment]
@rhs is this insecure registry?

**Comment by samos123** [comment]
could you try this pull request the script from this pull request to confirm whether it fixes the issue? https://github.com/samos123/kaniko/blob/fix-988-run-in-docker-sh-non-gcr/run_in_docker.sh

**Comment by samos123** [comment]
@rhs kindly let me know if it fixed the issue for you
