### ISSUE TITLE
Should it crash with MAINTAINER command?

### ISSUE THREAD

**Issue by gitirabassi** [GoogleContainerTools/kaniko#99]
I know MAINTAINER is deprecated and all, but should the build really crash when MAINTAINER is found as command?

**Comment by dlorenc** [comment]
We should probably just warn and continue for this one.

**Comment by gitirabassi** [comment]
I can send a PR for this in a couple hours

**Comment by dmonakhov** [comment]
@dlorenc  +1.  Otherthise this prevent from transparent migration of old Dockerfiles  to kaniko
