### ISSUE TITLE
Kaniko doesn’t set image platform for FROM scratch images

### ISSUE THREAD

**Issue by andrewshadura** [GoogleContainerTools/kaniko#997]
**Actual behavior**
When trying to pull an image generated with kaniko `FROM scratch` with podman, podman complains:
```
Trying to pull registry.tld/package-builder...
  Image operating system mismatch: image uses "", expecting "linux"
Error: unable to pull registry.tld/package-builder: unable to pull image: Image operating system mismatch: image uses "", expecting "linux"
```
Apparently, the platform is set only for images derived from others:
```
$ skopeo inspect docker://registry.tld/debian-based-image-builder | grep Os
    "Os": "linux",
$ skopeo inspect docker://registry.tld/package-builder | grep Os
    "Os": "",
```
**Expected behavior**
Set the platform value to an actual one or provide a way to override.

**To Reproduce**
```
FROM scratch

ADD rootfs.tar.gz /
```
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [x] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by em-** [comment]
My naive observation is that kaniko may be creating an empty manifest that is too empty when building an image from scratch:
  https://github.com/GoogleContainerTools/kaniko/blob/master/pkg/executor/build.go#L444

`Os` and `Architecture` should probably be set if unset, just like it is done for `Env`:
https://github.com/GoogleContainerTools/kaniko/blob/a2aae627/pkg/executor/build.go#L139

Likely these values should be used by default (they don't seem to be used anywhere at the moment):
https://github.com/GoogleContainerTools/kaniko/blob/a2aae6274/pkg/util/util.go#L146

**Comment by tejal29** [comment]
Thanks @em for the details. 
@andrewshadura oe @em-  Would you any of you want to give it a try?

**Comment by sereinity** [comment]
Also, having `os=""` makes podman fail to run the container.

```bash
podman run …
Error: incompatible image OS "" on "linux" host
```
Do you prefer a separated issue ?
